export class ChatError extends Error{constructor(message,status=400,code='INVALID_INPUT'){super(message);this.status=status;this.code=code}}
export const rank={GUEST:0,MEMBER:1,MODERATOR:2,ADMIN:3}
export const durations={'1h':3600000,'24h':86400000,'7d':604800000,'30d':2592000000,permanent:null}
export function canModerate(actor,target){return !target.protected&&actor.key!==target.actorKey&&rank[actor.role]>=2&&(actor.manageRoles||rank[actor.role]>rank[target.role])}
function clean(v,max){if(typeof v!=='string'||v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v))throw new ChatError('Ungültiger Text.');const normalized=v.normalize('NFKC').replace(/\r\n?/g,'\n').trim();if(normalized.length>max)throw new ChatError('Normalisierter Text ist zu lang.');return normalized}
export function validateMessage(v,host){const text=clean(v,500);if(!text||text.split('\n').length>6)throw new ChatError('Nachricht: 1–500 Zeichen, höchstens sechs Zeilen.');const normalized=text.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[013457]/g,x=>({'0':'o','1':'i','3':'e','4':'a','5':'s','7':'t'}[x]));if(/\b(arschloch|hurensohn|idiot|bitch|fuck|nigger|faggot|wichser)\b/i.test(normalized))throw new ChatError('Bitte respektvoll formulieren.');if(/\b(mein|unser|my|our)\s+(shop|store|kanal|channel|angebot)|\b(ich verkaufe|we sell|for sale|dm me|pn mich)|\b(rabattcode|coupon|promo code)\b/i.test(text))throw new ChatError('Werbung ist im Chat nicht erlaubt.');if(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/i.test(text)||/\b\w+\s*(?:\[\.\]|\(\.\)|\s+dot\s+|\s+punkt\s+)\s*(com|de|net|shop|org)\b/i.test(text))throw new ChatError('Externe Kontakte und Links sind nicht erlaubt.');for(const value of text.match(/(?:https?:\/\/|www\.)[^\s]+|\b[a-z0-9-]+(?:\.[a-z0-9-]+)+\b(?:\/[^\s]*)?/gi)||[]){let url;try{url=new URL(/^https?:/i.test(value)?value:'https://'+value)}catch{throw new ChatError('Ungültiger Link.')}if(!host||url.hostname!==host||url.username||url.password)throw new ChatError('Nur Links zur eigenen ELYSERA-Website sind erlaubt.')}return text}
export function validateName(v){const name=clean(v,40).replace(/\s+/g,' ');if(name.length<2||/[<>\[\]{}\\/@:;]/.test(name)||/\b(admin|administrator|moderator|support|staff|team|elysera)\b/i.test(name))throw new ChatError('Bitte einen Namen mit 2–40 Zeichen ohne Rollen- oder Markennamen wählen.');return name}
export function chatInput(raw,host){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!['actorId','requestId','action','targetId','expectedVersion','body','displayName','reason','duration','role'].includes(k))||typeof raw.actorId!=='string'||!raw.actorId||!/^[0-9a-f-]{36}$/i.test(raw.requestId||''))throw new ChatError('Ungültige Anfragekennung.');const action=raw.action;if(!['SEND','REMOVE','BAN','UNBAN','ROLE'].includes(action))throw new ChatError('Unbekannte Aktion.');const out={actorId:raw.actorId,requestId:raw.requestId,action};if(action==='SEND'){out.body=validateMessage(raw.body,host);out.displayName=raw.displayName?validateName(raw.displayName):'';return out}if(typeof raw.targetId!=='string'||!raw.targetId||raw.targetId.length>100||!Number.isSafeInteger(raw.expectedVersion)||raw.expectedVersion<0)throw new ChatError('Ziel und Version prüfen.');Object.assign(out,{targetId:raw.targetId,expectedVersion:raw.expectedVersion});if(['REMOVE','BAN'].includes(action)){out.reason=clean(raw.reason,160);if(!out.reason)throw new ChatError('Bitte Grund angeben.')}if(action==='BAN'){if(typeof raw.duration!=='string'||!Object.hasOwn(durations,raw.duration))throw new ChatError('Ungültige Sperrdauer.');out.duration=raw.duration}if(action==='ROLE'){if(!['MEMBER','MODERATOR','ADMIN'].includes(raw.role))throw new ChatError('Ungültige Chatrolle.');out.role=raw.role}return out}
export function checkVersion(row,v){if(!row)throw new ChatError('Eintrag nicht verfügbar.',404,'NOT_FOUND');if(row.version!==v)throw new ChatError('Zwischenzeitlich geändert. Aktuellen Stand laden und Entwurf erneut prüfen.',409,'VERSION_CONFLICT')}
export function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));return value}
