'use client'
import {useEffect,useRef,useState} from 'react'
import {chatInput} from '@/lib/chat/policy.mjs'
import './chat-workspace.css'
const roles={GUEST:'Gast',MEMBER:'Mitglied',MODERATOR:'Moderation',ADMIN:'Chat-Admin'}
const actionNames={SEND:'Nachricht senden',REMOVE:'Nachricht entfernen',BAN:'Person sperren',UNBAN:'Sperre aufheben',ROLE:'Chatrolle ändern'}
const durationNames={'1h':'1 Stunde','24h':'24 Stunden','7d':'7 Tage','30d':'30 Tage',permanent:'Unbefristet'}
export default function ChatWorkspace({admin=false}){
 const endpoint=admin?'/api/admin/community-chat':'/api/community-chat',storageKey=admin?'elysera-chat-admin-pending':'elysera-chat-public-pending'
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[body,setBody]=useState(''),[guestName,setGuestName]=useState(''),[query,setQuery]=useState(''),[operation,setOperation]=useState(null),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[conflict,setConflict]=useState(false),[auth,setAuth]=useState(false)
 const attempt=useRef(null),cursor=useRef(null),loadingRef=useRef(false),editorRef=useRef(null),inputRef=useRef(null),activeRef=useRef(false),queryRef=useRef('');queryRef.current=query
 async function load(reset=false){if(loadingRef.current)return null;loadingRef.current=true;if(reset)setLoading(true);try{const url=endpoint+(admin?'?q='+encodeURIComponent(queryRef.current):!reset&&cursor.current!==null?'?cursor='+cursor.current:'');const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(!r.ok){if(r.status===401)setAuth(true);throw Error(d.error||'Chat nicht verfügbar.')}setAuth(Boolean(attempt.current&&d.viewer.actorId!==attempt.current.payload.actorId));cursor.current=d.cursor;setData(old=>{if(reset||admin||!old)return d;const map=new Map(old.messages.map(m=>[m.id,m]));for(const m of d.messages){if(m.deleted)map.delete(m.id);else map.set(m.id,m)}return {...d,messages:[...map.values()].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(-100)}});if(!activeRef.current)setError('');return d}catch(e){setError(e.message);return null}finally{loadingRef.current=false;setLoading(false)}}
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(storageKey));if(saved){attempt.current=saved;setOperation(saved.operation);setReview(true);setPending(true);activeRef.current=true;setBody(saved.payload.body||'');setGuestName(saved.payload.displayName||'')}}catch{setError('Gespeicherte Anfrage konnte nicht gelesen werden.')}load(true);let ticks=0;const timer=setInterval(()=>{if(!document.hidden){ticks++;load(!admin&&ticks%5===0)}},admin?10000:4000);return()=>clearInterval(timer)},[])
 function choose(action,target){if(pending||busy)return;activeRef.current=true;setOperation({action,targetId:target.id,expectedVersion:target.version,label:target.authorName||target.displayName||target.email||'Person',reason:'',duration:'24h',role:target.role||'MEMBER',previousRole:target.role||'MEMBER',source:target.body||target.reason||''});setReview(false);setConflict(false);setNotice('');setError('');requestAnimationFrame(()=>{editorRef.current?.scrollIntoView({block:'center'});inputRef.current?.focus()})}
 function requestPayload(){const op=operation||{action:'SEND'};return {actorId:data?.viewer.actorId,requestId:crypto.randomUUID(),action:op.action,...op.action==='SEND'?{body,displayName:data?.viewer.guest?guestName:''}:{targetId:op.targetId,expectedVersion:op.expectedVersion,...['REMOVE','BAN'].includes(op.action)?{reason:op.reason}:{},...op.action==='BAN'?{duration:op.duration}:{},...op.action==='ROLE'?{role:op.role}:{}}}}
 function prepare(){try{chatInput(requestPayload(),location.hostname);setOperation(op=>op||{action:'SEND',label:guestName||data?.viewer.name});setReview(true);activeRef.current=true;setError('')}catch(e){setError(e.message)}}
 async function save(){setBusy(true);setError('');try{let entry=attempt.current;if(!entry){const payload=chatInput(requestPayload(),location.hostname);entry={payload,operation:operation||{action:'SEND'}};sessionStorage.setItem(storageKey,JSON.stringify(entry));attempt.current=entry;setPending(true)}const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(entry.payload)}),d=await r.json();if(!r.ok){if(r.status===401||d.code==='ACTOR_CHANGED')setAuth(true);if(['INVALID_INPUT','VERSION_CONFLICT','FORBIDDEN','BANNED','RATE_LIMITED','DUPLICATE','GUEST_UNAVAILABLE','NOT_FOUND'].includes(d.code)){sessionStorage.removeItem(storageKey);attempt.current=null;setPending(false)}if(d.code==='VERSION_CONFLICT')setConflict(true);throw Error(d.error||'Speicherung nicht bestätigt.')}if(d.applied?.action!==entry.payload.action||typeof d.applied.id!=='string')throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut prüfen.');sessionStorage.removeItem(storageKey);attempt.current=null;setPending(false);setOperation(null);setReview(false);setConflict(false);activeRef.current=false;if(entry.payload.action==='SEND')setBody('');setNotice(d.replayed?'Frühere Anfrage bestätigt. Aktueller Chat wird geladen.':'Änderung gespeichert und geprüft.');await load(true)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function reloadDraft(){const d=await load(true);if(!d)return;const rows=operation?.action==='ROLE'?d.members:operation?.action==='UNBAN'?d.bans:d.messages;const target=rows?.find(x=>x.id===operation.targetId);if(!target){setError('Ziel nicht mehr im aktuellen Ausschnitt. Entwurf bleibt erhalten; eine neue Auswahl ist nötig.');return}setOperation(o=>({...o,expectedVersion:target.version,previousRole:target.role||o.previousRole}));setReview(false);setConflict(false);setError('');setNotice('Aktueller Stand geladen. Dein Entwurf bleibt zur erneuten Prüfung erhalten.')}
 function cancel(){if(pending||busy)return;setOperation(null);setReview(false);setConflict(false);activeRef.current=false;setError('')}
 const op=operation,canModerate=['MODERATOR','ADMIN'].includes(data?.viewer.role)
 return <section className={'ech-root '+(admin?'ech-admin':'ech-public')}><div className="ech-heading"><div><h1>{admin?'Community':'ELYSERA Community'}</h1><p>{admin?'Eigene Chatrollen, Sperren und Nachrichten verwalten.':'Austausch über deine Pflegeroutine. Respektvoll und ohne Werbung.'}</p></div><button onClick={()=>load(true)} disabled={loading||busy}>Aktualisieren</button></div>
 {admin&&<div className="ech-metrics">{[['Nachrichten · 24 Std.',data?.counts?.messages24h],['Aktive Sperren',data?.counts?.activeBans],['Eigene Chatrollen',data?.counts?.moderators]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div>}
 {notice&&<p className="ech-notice" role="status">{notice}</p>}{error&&!op&&<p className="ech-error" role="alert">{error}</p>}{auth&&!op&&<a className="ech-primary ech-link" href={admin?'/auth/admin':'/auth/signin'}>Zur Anmeldung</a>}
 <div className="ech-columns"><div className="ech-main"><section className="ech-panel"><div className="ech-panel-heading"><h2>Nachrichten</h2><span>{data?roles[data.viewer.role]:'Status unbekannt'}</span></div>{loading&&!data?<p role="status">Chat wird geladen …</p>:!data?<button onClick={()=>load(true)}>Erneut laden</button>:<><div className="ech-stream" aria-label="Chatnachrichten">{data.messages.length===0?<p className="ech-empty">Noch keine Nachrichten. Starte einen respektvollen Austausch.</p>:data.messages.map(m=><article key={m.id} className={m.isOwn?'ech-own':''}><header><strong>{m.authorName}</strong><span>{roles[m.authorRole]}</span><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})}</time></header><p>{m.body}</p>{m.canModerate&&canModerate&&<div className="ech-message-actions"><button disabled={pending||busy} onClick={()=>choose('REMOVE',m)}>Entfernen</button><button disabled={pending||busy} onClick={()=>choose('BAN',m)}>Person sperren</button></div>}</article>)}</div>{data.hasMore&&<button onClick={()=>load(false)}>Weitere neue Nachrichten laden</button>}<p className="ech-hint">Die neuesten Nachrichten werden automatisch aktualisiert.</p>
 {data.viewer.ban?<div className="ech-error" role="status"><strong>Chat gesperrt</strong><p>{data.viewer.ban.reason}</p><p>{data.viewer.ban.expiresAt?'Bis '+new Date(data.viewer.ban.expiresAt).toLocaleString('de-DE'):'Unbefristet'}</p></div>:data.viewer.unavailable?<p role="status">{data.viewer.unavailable} <a href="/auth/signin">Anmelden</a></p>:<div className="ech-compose"><h3>Deine Nachricht</h3>{data.viewer.guest&&<label>Gastname<input maxLength={40} value={guestName} disabled={pending||busy||!!op} onChange={e=>setGuestName(e.target.value)}/></label>}<label>Nachricht<textarea rows={3} maxLength={500} value={body} disabled={pending||busy||!!op} onChange={e=>setBody(e.target.value)}/></label><div className="ech-compose-footer"><small>{body.length}/500 · Nur Text, keine Werbung.</small><button className="ech-primary" disabled={!body.trim()||pending||busy||!!op||!data.viewer.canSend} onClick={prepare}>Nachricht prüfen</button></div></div>}</>}</section>
 {op&&<section className="ech-panel ech-editor" ref={editorRef} aria-label="Aktion prüfen"><h2>{actionNames[op.action]}</h2>{op.label&&<p><strong>{op.label}</strong></p>}{op.source&&<p className="ech-message-preview">{op.source}</p>}{op.action==='SEND'?<p className="ech-message-preview">{body}</p>:<>{['REMOVE','BAN'].includes(op.action)&&<label>Grund<textarea ref={inputRef} maxLength={160} rows={2} value={op.reason} disabled={review||pending||busy} onChange={e=>setOperation(o=>({...o,reason:e.target.value}))}/></label>}{op.action==='BAN'&&<label>Sperrdauer<select value={op.duration} disabled={review||pending||busy} onChange={e=>setOperation(o=>({...o,duration:e.target.value}))}>{Object.entries(durationNames).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}{op.action==='ROLE'&&<><label>Neue Chatrolle<select ref={inputRef} value={op.role} disabled={review||pending||busy} onChange={e=>setOperation(o=>({...o,role:e.target.value}))}>{['MEMBER','MODERATOR','ADMIN'].map(r=><option key={r} value={r}>{roles[r]}</option>)}</select></label><p>Aktuell: {roles[op.previousRole]} · Entwurf: {roles[op.role]}</p><p>Diese Rolle gilt ausschließlich im ELYSERA-Chat. Sie erteilt keinen Zugang zur Administration.</p></>}{op.action==='UNBAN'&&<p>Die Person darf nach Aufhebung wieder Nachrichten senden, sofern keine weitere aktive Sperre besteht.</p>}</>}
 {auth&&<div className="ech-error" role="alert"><strong>Anmeldung erforderlich</strong><p>Melde dich mit derselben Identität an. Die genaue Anfrage bleibt in diesem Tab erhalten.</p></div>}{pending&&<p className="ech-notice" role="status">Speicherung ungeklärt. Die unveränderte Anfrage erneut prüfen; ein Neuladen erhält sie.</p>}{conflict&&<p>Aktuellen Stand laden. Dein Entwurf bleibt erhalten und wird erneut geprüft.</p>}{error&&<p className="ech-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <footer><button disabled={pending||busy} onClick={review?()=>setReview(false):cancel}>{review?'Weiter bearbeiten':'Abbrechen'}</button>{auth?<a className="ech-primary ech-link" href={admin?'/auth/admin':'/auth/signin'}>Zur Anmeldung</a>:conflict?<button className="ech-primary" disabled={busy} onClick={reloadDraft}>Stand laden · Entwurf behalten</button>:review?<button className="ech-primary" disabled={busy} onClick={save}>{busy?'Wird geprüft …':pending?'Dieselbe Anfrage erneut prüfen':'Verbindlich bestätigen'}</button>:<button className="ech-primary" disabled={busy} onClick={prepare}>Änderung prüfen</button>}</footer>{auth&&pending&&<button disabled={busy} onClick={save}>Dieselbe Anfrage erneut prüfen</button>}</section>}
 </div>{admin&&<aside className="ech-sidebar"><section className="ech-panel"><h2>Chatrollen</h2><p>Nur eigene ELYSERA-Konten. Administrative Zugänge bleiben geschützt.</p><form className="ech-search" onSubmit={e=>{e.preventDefault();load(true)}}><label>Konto suchen<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name oder E-Mail"/></label><button type="submit" disabled={loading}>Suchen</button></form>{data?.membersLimited&&<p>Mehr als 100 Treffer. Bitte Suche eingrenzen.</p>}{data?.members?.length===0&&<p>Keine passenden ELYSERA-Konten.</p>}<div className="ech-people">{data?.members?.map(m=><article key={m.id}><strong>{[m.firstName,m.secondName].filter(Boolean).join(' ')||'Mitglied'}</strong><span>{m.email}</span><small>{m.protected?'ELYSERA-Administration':roles[m.role]}</small><button disabled={m.protected||pending||busy} onClick={()=>choose('ROLE',m)}>Chatrolle ändern</button></article>)}</div></section><section className="ech-panel"><h2>Aktive Sperren</h2>{data?.bansLimited&&<p>Die neuesten 100 Sperren werden angezeigt.</p>}{data?.bans?.length===0&&<p>Keine aktiven Sperren.</p>}<div className="ech-people">{data?.bans?.map(b=><article key={b.id}><strong>{b.displayName}</strong><p>{b.reason}</p><small>{b.expiresAt?'Bis '+new Date(b.expiresAt).toLocaleString('de-DE'):'Unbefristet'}</small><button disabled={pending||busy} onClick={()=>choose('UNBAN',b)}>Sperre aufheben</button></article>)}</div></section></aside>}</div></section>
}
