'use client'
import {useEffect,useRef,useState} from 'react'
import {eurosToCents} from '../../lib/admin/credits.mjs'
import './credits-workspace.css'
const money=c=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(c/100)
const name=r=>[r.firstName,r.secondName].filter(Boolean).join(' ')||'ELYSERA-Kunde'
const cell=v=>'"'+String(v??'').replace(/^\s*[=+@-]/,"'$&").replaceAll('"','""')+'"'
function exportRows(rows){const lines=[['Buchung','Datum UTC','Empfänger','E-Mail','Betrag EUR','Begründung','Administrator'],...rows.map(r=>[r.id,r.createdAt,r.userId,r.recipientEmail,(r.amountCents/100).toFixed(2),r.reason,r.actorEmail])];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='elysera-gutschriften.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function CreditsWorkspace({fixture}){
 const [data,setData]=useState(fixture||null),[loading,setLoading]=useState(!fixture),[error,setError]=useState(''),[retry,setRetry]=useState(0),[query,setQuery]=useState(''),[recipients,setRecipients]=useState([]),[searchState,setSearchState]=useState(''),[recipient,setRecipient]=useState(null),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[unresolved,setUnresolved]=useState(false),[saveError,setSaveError]=useState(''),[success,setSuccess]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(1),[balance,setBalance]=useState(null),[historyUser,setHistoryUser]=useState(null),[view,setView]=useState('grant'),[rejection,setRejection]=useState('')
 const dialog=useRef(null),reviewButton=useRef(null),pending=useRef(null),recipientSearch=useRef(null)
 useEffect(()=>{if(fixture){setData(fixture);return}const c=new AbortController();setLoading(true);setError('');fetch('/api/admin/credits'+(historyUser?'?userId='+encodeURIComponent(historyUser.id):''),{cache:'no-store',signal:c.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);setData(b)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[fixture,retry,historyUser])
 useEffect(()=>{if(query.trim().length<2){setRecipients([]);setSearchState('');return}const c=new AbortController();setSearchState('Suche läuft …');const timer=setTimeout(()=>{if(fixture){const matches=(fixture.recipients||[]).filter(r=>(name(r)+' '+r.email).toLowerCase().includes(query.toLowerCase()));setRecipients(matches);setSearchState(matches.length?'':'Keine passenden ELYSERA-Kunden.');return}fetch('/api/admin/credits?q='+encodeURIComponent(query),{signal:c.signal,cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);setRecipients(b.recipients);setSearchState(b.limited?'Weitere Treffer: Suche eingrenzen.':b.recipients.length?'':'Keine passenden ELYSERA-Kunden.')}).catch(e=>{if(e.name!=='AbortError'){setRecipients([]);setSearchState('Suche fehlgeschlagen. Suchbegriff ändern und erneut versuchen.')}})},250);return()=>{clearTimeout(timer);c.abort()}},[query,fixture])
 useEffect(()=>{setBalance(null);if(!recipient)return;if(fixture){setBalance(fixture.balanceCents??null);return}const c=new AbortController();fetch('/api/admin/credits?userId='+encodeURIComponent(recipient.id),{signal:c.signal,cache:'no-store'}).then(async r=>{const b=await r.json();if(r.ok)setBalance(b.balanceCents)}).catch(()=>{});return()=>c.abort()},[recipient,fixture])
 useEffect(()=>{if(review&&!dialog.current?.open)dialog.current?.showModal()},[review])
 function close(){if(busy||unresolved)return;dialog.current?.close();setReview(null);reviewButton.current?.focus()}
 function prepare(e){e.preventDefault();const amountCents=eurosToCents(amount);if(unresolved||!recipient||!amountCents||reason.trim().length<3)return;const body={userId:recipient.id,email:recipient.email,amountCents,reason:reason.trim()};const fingerprint=JSON.stringify(body);if(!pending.current||pending.current.fingerprint!==fingerprint)pending.current={fingerprint,body:{...body,idempotencyKey:crypto.randomUUID()}};setSaveError('');setRejection('');setReview({...pending.current.body,name:name(recipient)})}
 useEffect(()=>{if(fixture)return;try{const saved=JSON.parse(sessionStorage.getItem('elysera-credit-unresolved')||'null');if(saved?.idempotencyKey){setReview(saved);setUnresolved(true);setSaveError('Ein früherer Buchungsauftrag ist noch ungeklärt. Erneut bestätigen prüft denselben Auftrag.')}}catch{}},[fixture])
 function correct(){if(busy||unresolved)return;setView('grant');setAmount((review.amountCents/100).toFixed(2).replace('.',','));setReason(review.reason);if(rejection!=='INVALID'){setRecipient(null);setQuery('');setRecipients([])}pending.current=null;dialog.current?.close();setReview(null);setSaveError('');setRejection('');requestAnimationFrame(()=>recipientSearch.current?.focus())}
 async function grant(){if(fixture){setSaveError('Designvorschau: Es werden keine Gutschriften gebucht.');return}setBusy(true);setSaveError('');try{sessionStorage.setItem('elysera-credit-unresolved',JSON.stringify(review));setUnresolved(true);const {name:_,...body}=review;const r=await fetch('/api/admin/credits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok){if([400,404,409].includes(r.status)&&['INVALID','NOT_FOUND','RECIPIENT_CHANGED'].includes(b.code)){sessionStorage.removeItem('elysera-credit-unresolved');setUnresolved(false);setRejection(b.code)}throw Error(b.error)}sessionStorage.removeItem('elysera-credit-unresolved');setUnresolved(false);setBalance(b.balanceCents);setSuccess(`${money(b.grant.amountCents)} für ${b.grant.recipientEmail} bestätigt. ELYSERA-Buchungsbestand: ${money(b.balanceCents)}.`);pending.current=null;setAmount('');setReason('');dialog.current?.close();setReview(null);reviewButton.current?.focus();setRetry(x=>x+1)}catch(e){setSaveError(e.message||'Keine Buchung bestätigt. Bitte erneut versuchen.')}finally{setBusy(false)}}
 const rows=(data?.history||[]).filter(r=>(r.recipientEmail+' '+r.reason+' '+name(r)).toLowerCase().includes(filter.toLowerCase())),pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages)
 const groups=Object.values((data?.history||[]).reduce((a,r)=>{const g=a[r.userId]||{id:r.userId,email:r.recipientEmail,count:0,total:0,highest:0,latest:r.createdAt};g.count++;g.total+=r.amountCents;g.highest=Math.max(g.highest,r.amountCents);if(r.createdAt>g.latest)g.latest=r.createdAt;a[r.userId]=g;return a},{}))
 return <section className="crw-workspace"><div className="crw-heading"><div><span>Finanzen · Gutschriften</span><h1>Gutschriften verwalten</h1><p>ELYSERA-Gutschriften zuordnen und jede Buchung nachvollziehen.</p></div><button onClick={()=>setRetry(x=>x+1)} disabled={loading} aria-label="Gutschriften aktualisieren">↻</button></div>{fixture&&<p className="crw-notice">Designvorschau · Beispieldaten</p>}
 <nav className="crw-switch" aria-label="Gutschriftenansicht"><button aria-pressed={view==='grant'} onClick={()=>setView('grant')}>Neue Gutschrift</button><button aria-pressed={view==='history'} onClick={()=>setView('history')}>Buchungsverlauf</button></nav><div className="crw-layout" hidden={view!=='grant'}><article className="crw-panel"><header><h2>Neue Gutschrift</h2><p>Empfänger auswählen, Betrag eingeben und prüfen.</p></header><form onSubmit={prepare}><label>ELYSERA-Kunde suchen<input ref={recipientSearch} type="search" aria-describedby="crw-search-help" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name oder E-Mail"/></label><small id="crw-search-help">Mindestens 2 Zeichen eingeben.</small>{searchState&&<p role="status">{searchState}</p>}{recipients.length>0&&<div className="crw-results">{recipients.map(r=><button type="button" key={r.id} onClick={()=>{setRecipient(r);setQuery('');setRecipients([]);setSuccess('')}}><strong>{name(r)}</strong><span>{r.email}</span></button>)}</div>}
 {recipient?<div className="crw-recipient"><strong>{name(recipient)}</strong><span>{recipient.email}</span><small>Kundennummer: {recipient.id}</small><p>ELYSERA-Buchungsbestand <b>{balance===null?'Nicht verfügbar':money(balance)}</b></p><button type="button" onClick={()=>{setRecipient(null);setSuccess('')}}>Auswahl aufheben</button></div>:<p className="crw-hint">Noch kein Empfänger ausgewählt.</p>}
 <label>Betrag in EUR<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" required aria-describedby="crw-amount-help"/></label><div className="crw-quick" aria-label="Betrag auswählen">{[10,25,50,100].map(n=><button type="button" key={n} onClick={()=>setAmount(String(n))}>{n} €</button>)}</div><small id="crw-amount-help">0,01 bis 100.000,00 EUR · höchstens zwei Nachkommastellen</small><label>Begründung<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={240} required placeholder="Anlass der Gutschrift …"/></label><small>{reason.length}/240 Zeichen</small><button className="crw-primary" ref={reviewButton} disabled={!recipient||!eurosToCents(amount)||reason.trim().length<3}>Gutschrift prüfen →</button></form></article>
 <aside className="crw-panel crw-info"><details><summary>Hinweise zur Verwendung</summary><div><p>Jede Gutschrift wird mit Empfänger, Betrag, Datum und Administrator protokolliert.</p><p>Die Einlösung im ELYSERA-Checkout ist noch nicht verfügbar. Der Buchungsbestand ist kein auszahlbares Guthaben.</p><p>Admin-Gutschriften sind nicht provisionsberechtigt.</p></div></details></aside></div>
 {success&&<p className="crw-success" role="status">{success}</p>}<article className="crw-panel crw-history" hidden={view!=='history'}><header><div><h2>{historyUser?'Gutschriften für '+historyUser.email:'Buchungsverlauf'}</h2>{data?.limited&&<p>Die neuesten 500 Buchungen.</p>}</div><button aria-label="CSV exportieren" disabled={loading||!!error||!rows.length} onClick={()=>exportRows(rows)}>CSV ↓</button></header>{historyUser&&<div className="crw-drill"><button onClick={()=>{setHistoryUser(null);setPage(1)}}>← Alle Empfänger</button><span>ELYSERA-Buchungsbestand: {loading||!!error||data?.balanceCents===undefined?'Nicht verfügbar':money(data.balanceCents)}</span></div>}{!historyUser&&!loading&&!error&&groups.length>0&&<details className="crw-groups"><summary>Übersicht nach Empfänger · {groups.length}</summary><p>Summen aus den geladenen, höchstens 500 neuesten Buchungen.</p>{groups.map(g=><button key={g.id} onClick={()=>{setHistoryUser(g);setFilter('');setPage(1)}}><strong>{g.email}</strong><span>{g.count} Buchungen · Summe {money(g.total)} · Höchste {money(g.highest)}</span><small>Zuletzt: {new Date(g.latest).toLocaleDateString('de-DE',{timeZone:'UTC'})}</small></button>)}</details>}<label className="crw-filter"><span className="crw-sr">Verlauf durchsuchen</span><input type="search" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}} placeholder="Verlauf suchen"/></label>{loading?<div className="crw-state" role="status">Gutschriften werden geladen …</div>:error?<div className="crw-state" role="alert"><h3>Buchungsverlauf nicht verfügbar</h3><p>{error}</p><button onClick={()=>setRetry(x=>x+1)}>Erneut versuchen</button></div>:!rows.length?<div className="crw-state"><h3>{filter?'Keine passenden Buchungen':'Noch keine Gutschriften'}</h3><p>{filter?'Passe die Suche an.':'Bestätigte Gutschriften erscheinen hier mit Begründung und Administrator.'}</p></div>:<><div className="crw-row crw-th"><span>Empfänger / Datum</span><span>Begründung / Administrator</span><span>Betrag</span></div>{rows.slice((current-1)*8,current*8).map(r=><div className="crw-row" key={r.id}><div><strong>{name(r)}</strong><button className="crw-person" onClick={()=>{setHistoryUser({id:r.userId,email:r.recipientEmail});setPage(1);setFilter('')}}>{r.recipientEmail}</button><small>{new Date(r.createdAt).toLocaleString('de-DE',{timeZone:'UTC'})} · UTC</small></div><div><span>{r.reason}</span><small>{r.actorEmail}</small><small>Buchung: {r.id}</small></div><strong className="crw-amount">+{money(r.amountCents)}</strong></div>)}<footer><span>{rows.length} Buchungen · Seite {current}/{pages}</span><div><button aria-label="Vorherige Seite" disabled={current===1} onClick={()=>setPage(current-1)}>←</button><button aria-label="Nächste Seite" disabled={current===pages} onClick={()=>setPage(current+1)}>→</button></div></footer></>}</article>
 <dialog ref={dialog} aria-labelledby="crw-review-title" className="crw-dialog" onCancel={e=>{e.preventDefault();close()}}>{review&&<><h2 id="crw-review-title">Gutschrift bestätigen</h2><p>Prüfe den Empfänger und Betrag vor der Buchung.</p><dl><dt>Empfänger</dt><dd>{review.name}<br/>{review.email}<small>{review.userId}</small></dd><dt>Betrag</dt><dd className="crw-review-amount">{money(review.amountCents)}</dd><dt>Begründung</dt><dd>{review.reason}</dd></dl><p>{unresolved?'Dieser Auftrag ist noch ungeklärt. Erneut bestätigen prüft dieselbe Buchung. Empfänger und Betrag bleiben bis zur Klärung gesperrt.':'Die Buchung wird dauerhaft protokolliert.'}</p>{saveError&&<p role="alert" className="crw-error">{saveError}</p>}<div className="crw-actions"><button disabled={busy||unresolved} onClick={close}>Zurück</button><button className="crw-primary" disabled={busy} onClick={rejection?correct:grant}>{rejection?(rejection==='INVALID'?'Angaben korrigieren':'Empfänger korrigieren'):busy?'Wird gebucht …':saveError?'Erneut bestätigen':'Verbindlich gutschreiben'}</button></div></>}</dialog></section>
}
