'use client'
import {useEffect,useState} from 'react'
import {membershipLabels} from '../../lib/admin/membership-policy.mjs'
export default function CustomerMembership({customerId}){
 const [state,setState]=useState(null),[status,setStatus]=useState('NONE'),[reason,setReason]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reloadRequired,setReloadRequired]=useState(false)
 async function load(){setBusy(true);setError('');setReview(false);try{const r=await fetch('/api/admin/customers/membership?id='+encodeURIComponent(customerId),{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error);setState(b.membership);setStatus(b.membership.status);setReloadRequired(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[customerId])
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/admin/customers/membership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId,status,reason,expectedVersion:state.version})}),b=await r.json();if(!r.ok)throw Error(b.error);setState(b.membership);setStatus(b.membership.status);setReview(false);setReason('');setNotice('ELYSERA-Mitgliedschaft gespeichert: '+membershipLabels[b.membership.status])}catch(e){setReloadRequired(true);setError(e.message||'Ergebnis unklar. Status neu laden.')}finally{setBusy(false)}}
 return <section className="cw-membership"><h3>ELYSERA-Mitgliedschaft</h3><p>Mitgliedschaft für ELYSERA. Diese Auswahl vergibt keine Administratorrechte und löst keine Zahlung aus.</p>{state&&<><p>Aktuell: <strong>{membershipLabels[state.status]||state.status}</strong></p><label>Neue Mitgliedschaft<select aria-label="Neue Mitgliedschaft" value={status} disabled={busy||reloadRequired} onChange={e=>{setStatus(e.target.value);setReview(false);setNotice('')}}>{Object.entries(membershipLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Begründung<textarea aria-label="Begründung der Mitgliedschaftsänderung" value={reason} disabled={busy||reloadRequired} maxLength={500} onChange={e=>{setReason(e.target.value);setReview(false)}}/></label>{review&&<p className="cw-membership-review">{membershipLabels[state.status]} → <strong>{membershipLabels[status]}</strong><br/>{reason}</p>}<button className="cw-save-primary" disabled={busy||reloadRequired||status===state.status||!reason.trim()} onClick={()=>review?save():setReview(true)}>{busy?'Wird gespeichert …':review?'Mitgliedschaft speichern':'Mitgliedschaft ändern'}</button>{review&&<button disabled={busy} onClick={()=>setReview(false)}>Abbrechen</button>}</>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{(!state||reloadRequired)&&<button disabled={busy} onClick={load}>{busy?'Wird geladen …':'Aktuellen Status neu laden'}</button>}</section>
}
