'use client'
import {useEffect,useRef,useState} from 'react'
import './customers-workspace.css'
import CustomerMembership from './customer-membership'
import CustomerImpersonation from './customer-impersonation'
const name=c=>[c.firstName,c.secondName].filter(Boolean).join(' ')||'Name nicht erfasst'
const date=value=>value?new Date(value).toLocaleDateString('de-DE'):'Nicht erfasst'
const loginDate=value=>value?new Date(value).toLocaleString('de-DE',{timeZone:'Europe/Berlin',dateStyle:'medium',timeStyle:'short'})+' Uhr (Berlin)':'Noch kein Login erfasst'
const money=value=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(value)
const fields={street:'Straße',houseNumber:'Hausnummer',postalCode:'Postleitzahl',city:'Ort',country:'Land',phone:'Telefon (optional)'}
const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"'
const complete=c=>['street','houseNumber','postalCode','city','country'].every(k=>c.details?.[k])
export default function CustomersWorkspace({fixture}){
 const [customers,setCustomers]=useState(fixture?.customers??null),[loading,setLoading]=useState(!fixture),[error,setError]=useState(''),[limited,setLimited]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[activity,setActivity]=useState('all'),[page,setPage]=useState(1),[selected,setSelected]=useState(null)
 async function reload(){setLoading(true);setError('');try{const res=await fetch('/api/admin/customers',{cache:'no-store'}),data=await res.json();if(!res.ok)throw Error(data.error);setCustomers(data.customers);setLimited(data.limited)}catch(e){setError(e.message||'Laden fehlgeschlagen.')}finally{setLoading(false)}}
 useEffect(()=>{if(!fixture){setQuery(new URLSearchParams(window.location.search).get("q")||"");reload()}},[])
 const filtered=(customers||[]).filter(c=>(activity==='all'||(activity==='active'?!!c.firstLoginAt:!c.firstLoginAt))&&(filter==='all'||(filter==='complete'?complete(c):!complete(c)))&&[c.id,name(c),c.email,c.details?.phone,c.details?.city,c.details?.country].join(' ').toLowerCase().includes(query.trim().toLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pages)
 function exportCsv(){const rows=[['Kundennummer','Name','E-Mail','Telefon','Straße','Hausnummer','Postleitzahl','Ort','Land','Profil aktualisiert','Erster Login (UTC)'],...filtered.map(c=>[c.id,name(c),c.email,c.details?.phone,c.details?.street,c.details?.houseNumber,c.details?.postalCode,c.details?.city,c.details?.country,c.updatedAt,c.firstLoginAt])],url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='elysera-kunden.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="customers-workspace"><header className="cw-heading"><div><span className="cw-eyebrow">Kunden · ELYSERA-Profile</span><h1>Kunden</h1><p>Kontaktangaben und Bestellungen im Überblick.</p></div><button aria-label="Kunden aktualisieren" onClick={reload} disabled={loading}>↻ Aktualisieren</button></header>{fixture&&<p className="cw-note">Designvorschau · Beispieldaten</p>}
 <div className="cw-metrics">{[['Kundenprofile',customers?.length,'Geladene ELYSERA-Profile'],['Adresse vollständig',customers?.filter(complete).length,'Alle Adressfelder erfasst'],['Adresse unvollständig',customers?.filter(c=>!complete(c)).length,'Angaben fehlen'],['Mit Telefonnummer',customers?.filter(c=>c.details?.phone).length,'Telefon im ELYSERA-Profil']].map(([label,value,hint])=><div key={label}><span>{label}</span><strong>{loading||error?'—':value??'—'}</strong><small>{hint}</small></div>)}</div>
 <div className="cw-panel"><div className="cw-toolbar"><label><span className="cw-sr">Kunden suchen</span><input type="search" placeholder="Name, E-Mail, Telefon oder Ort" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><label><span className="cw-sr">Adressstatus filtern</span><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="all">Alle Profile</option><option value="complete">Adresse vollständig</option><option value="incomplete">Adresse unvollständig</option></select></label><label><span className="cw-sr">Login-Status filtern</span><select value={activity} onChange={e=>{setActivity(e.target.value);setPage(1)}}><option value="all">Alle Login-Status</option><option value="active">Bereits eingeloggt</option><option value="inactive">Noch kein Login erfasst</option></select></label><button disabled={loading||!!error||!filtered.length} onClick={exportCsv}>CSV exportieren</button></div>
 {loading?<div className="cw-state" role="status">Kunden werden geladen …</div>:error?<div className="cw-state" role="alert"><h2>Laden nicht möglich</h2><p>{error}</p><button onClick={reload}>Erneut versuchen</button></div>:!filtered.length?<div className="cw-state"><h2>{customers?.length?'Keine passenden Kunden':'Noch keine Kundenprofile'}</h2><p>{customers?.length?'Passe die Suche oder den Filter an.':'Neue ELYSERA-Kundenprofile erscheinen hier.'}</p></div>:<><div className="cw-table-head"><span>Kunde / E-Mail</span><span>Telefon / Ort</span><span>Profil</span><span/></div><div className="cw-list">{filtered.slice((current-1)*10,current*10).map(c=><article key={c.id} className="cw-row"><div className="cw-identity"><i className="cw-avatar" aria-hidden="true">{[c.firstName,c.secondName].filter(Boolean).map(v=>v[0]).slice(0,2).join('')||'E'}</i><strong>{name(c)}</strong><span>{c.email||'E-Mail nicht erfasst'}</span></div><div className="cw-contact-group"><span>{c.details?.phone||'Telefon nicht erfasst'}</span><small>{[c.details?.city,c.details?.country].filter(Boolean).join(' · ')||'Adresse nicht erfasst'}</small></div><div className="cw-status"><span className={complete(c)?'is-paid':''}>{complete(c)?'Adresse vollständig':'Adresse unvollständig'}</span><small>Aktualisiert {date(c.updatedAt)}</small><small className="cw-login-status">{c.firstLoginAt?`Erster Login: ${loginDate(c.firstLoginAt)}`:loginDate(null)}</small></div><button aria-label={'Kunde '+name(c)+' ansehen'} onClick={()=>setSelected(c)}>Details ↗</button></article>)}</div><footer className="cw-pagination"><span>{filtered.length} Treffer{limited?' · letzte 1.000 Profile':''}</span><div><button aria-label="Vorherige Seite" disabled={current===1} onClick={()=>setPage(current-1)}>←</button><span>{current} / {pages}</span><button aria-label="Nächste Seite" disabled={current===pages} onClick={()=>setPage(current+1)}>→</button></div></footer></>}
 </div><p className="cw-note">Nur Kunden mit ELYSERA-Profil. {limited?'Suche und Export umfassen die zuletzt aktualisierten 1.000 Profile.':'Die Profilzahlen beziehen sich auf die geladene Kundenliste.'}</p>{selected&&<CustomerDetail initial={selected} fixture={fixture} close={()=>setSelected(null)} saved={c=>setCustomers(rows=>rows.map(row=>row.id===c.id?c:row))}/>}</section>
}
function CustomerDetail({initial,fixture,close,saved}){
 const ref=useRef(null),[customer,setCustomer]=useState(initial),[orders,setOrders]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[limited,setLimited]=useState(false),[edit,setEdit]=useState(false),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[draft,setDraft]=useState({}),[conflict,setConflict]=useState(false)
 async function load(){setLoading(true);setError('');try{let data;if(fixture)data={customer:initial,orders:fixture.orders||[]};else{const res=await fetch('/api/admin/customers?id='+encodeURIComponent(initial.id),{cache:'no-store'});data=await res.json();if(!res.ok)throw Error(data.error)}setCustomer(data.customer);setOrders(data.orders);setLimited(data.limited)}catch(e){setError(e.message||'Laden fehlgeschlagen.')}finally{setLoading(false)}}
 useEffect(()=>{const previous=document.activeElement,dialog=ref.current;dialog.showModal();load();return()=>{dialog.close();previous?.focus()}},[])
 useEffect(()=>{if(edit&&ref.current)ref.current.scrollTop=0},[edit,review])
 async function save(){setBusy(true);setNotice('');try{if(fixture)throw Error('Speichern ist in der Designvorschau deaktiviert.');const res=await fetch('/api/admin/customers',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:customer.id,updatedAt:customer.updatedAt,contact:draft})}),data=await res.json();if(!res.ok){if(res.status===409)setConflict(true);throw Error(data.error)}const next={...customer,...data.profile};setCustomer(next);saved(next);setEdit(false);setReview(false);setNotice('ELYSERA-Kontaktangaben gespeichert.')}catch(e){setNotice(e.message||'Speichern fehlgeschlagen.')}finally{setBusy(false)}}
 return <dialog ref={ref} className="cw-dialog" aria-labelledby="cw-title" onCancel={e=>{e.preventDefault();if(!busy)close()}}><header><div><span className="cw-eyebrow">Kundenprofil</span><h2 id="cw-title">{name(customer)}</h2></div><button aria-label="Details schließen" disabled={busy} onClick={close}>×</button></header><p className="cw-detail-id">{customer.id}</p>{loading?<div role="status" className="cw-state">Profil wird geladen …</div>:error?<div role="alert"><p>{error}</p><button onClick={load}>Erneut versuchen</button></div>:<>{!edit&&<><div className="cw-detail-columns"><section className="cw-field-group"><h3>Kontakt</h3><dl><div><dt>E-Mail</dt><dd>{customer.email||'Nicht erfasst'}</dd></div><div><dt>Telefon</dt><dd>{customer.details?.phone||'Nicht erfasst'}</dd></div></dl></section><section className="cw-field-group"><h3>ELYSERA-Adresse</h3><dl><div><dt>Straße</dt><dd>{[customer.details?.street,customer.details?.houseNumber].filter(Boolean).join(' ')||'Nicht erfasst'}</dd></div><div><dt>Ort / Land</dt><dd>{[[customer.details?.postalCode,customer.details?.city].filter(Boolean).join(' '),customer.details?.country].filter(Boolean).join(' · ')||'Nicht erfasst'}</dd></div></dl></section></div><section className="cw-login"><h3>Account-Aktivität</h3><p>{customer.firstLoginAt?`Erster Login: ${loginDate(customer.firstLoginAt)}`:loginDate(null)}</p><p>Einmalige Erfassung eines bestätigten ELYSERA-Zugriffs ab Einführung der Login-Erfassung. Frühere Besuche sind nicht nachträglich erfasst.</p></section><p>Profil aktualisiert: {date(customer.updatedAt)}</p></>}
 {!edit&&<><CustomerImpersonation customerId={customer.id}/><CustomerMembership customerId={customer.id}/></>}
 {!edit?<button onClick={()=>{setDraft(Object.fromEntries(Object.keys(fields).map(k=>[k,customer.details?.[k]||''])));setEdit(true);setNotice('')}}>Kontaktangaben bearbeiten</button>:<form className="cw-edit" onSubmit={e=>{e.preventDefault();setReview(true)}}><h3>{review?'Änderungen prüfen':'ELYSERA-Kontaktangaben bearbeiten'}</h3>{review?<><p>Die folgenden Angaben werden im ELYSERA-Profil gespeichert.</p><dl>{Object.keys(fields).filter(k=>draft[k]!==String(customer.details?.[k]||'')).map(k=><div key={k}><dt>{fields[k]}</dt><dd><del>{customer.details?.[k]||'Nicht erfasst'}</del><strong>{draft[k]||'Nicht erfasst'}</strong></dd></div>)}</dl><div className="cw-edit-actions"><button type="button" disabled={busy} onClick={()=>setReview(false)}>Zurück</button><button className="cw-save-primary" type="button" disabled={busy||conflict} onClick={save}>{busy?'Wird gespeichert …':'Änderungen speichern'}</button></div></>:<><div className="cw-edit-grid">{Object.entries(fields).map(([key,label])=><label key={key}>{label}<input value={draft[key]} required={key!=='phone'} maxLength={{street:160,houseNumber:30,postalCode:24,city:100,country:100,phone:30}[key]} type={key==='phone'?'tel':'text'} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}</div><div className="cw-edit-actions"><button type="button" onClick={()=>setEdit(false)}>Abbrechen</button><button disabled={!Object.keys(fields).some(k=>draft[k]!==String(customer.details?.[k]||''))}>Änderungen prüfen</button></div></>}</form>}
 {notice&&<p role="status" className={'cw-save-notice '+(notice==='ELYSERA-Kontaktangaben gespeichert.'?'is-success':'is-error')}>{notice}</p>}{conflict&&<div className="cw-conflict-recovery"><p>Deine Eingaben bleiben erhalten, bis du neu lädst. Beim Neuladen werden sie verworfen.</p><button onClick={()=>{setEdit(false);setReview(false);setConflict(false);setNotice('');load()}}>Profil neu laden</button></div>}{!edit&&<><h3>ELYSERA-Bestellungen</h3><p>Bestellungen mit ausschließlich ELYSERA-Produkten.{limited?' Die letzten 100 Bestellungen.':''}</p>{orders?.length?orders.map(o=><div key={o.id} className="cw-customer-order"><div><strong>{date(o.createdAt)} · {money(o.total)}</strong><small>{o.id}</small><span>{({PAID:'Bezahlt',SHIPPED:'Versendet',DELIVERED:'Zugestellt',PENDING:'Ausstehend',AWAITING_BANK_TRANSFER:'Überweisung offen',CANCELLED:'Storniert'})[o.status]||o.status}</span></div><p>{o.items.map(i=>`${i.quantity} × ${i.name}`).join('\n')}</p></div>):<p className="cw-empty-orders">Keine ELYSERA-Bestellungen vorhanden.</p>}</>}</>}<footer><button disabled={busy} onClick={close}>Schließen</button></footer></dialog>
}
