'use client'
import {useRef,useState} from 'react'
import {EMAIL_GROUPS,EMAIL_TEMPLATES,EMAIL_VARIANTS,buildEmailPreview,isolatedEmailHtml} from '../../lib/admin/email-previews.mjs'
import './emails-workspace.css'
export default function EmailsWorkspace({initialTemplateId=null,initialLocale='de',initialVariant=''}){
 const [search,setSearch]=useState(''),[group,setGroup]=useState('all'),[selected,setSelected]=useState(()=>EMAIL_TEMPLATES.find(t=>t.id===initialTemplateId)||null),[locale,setLocale]=useState(initialLocale),[variant,setVariant]=useState(initialVariant),[mode,setMode]=useState('desktop'),[text,setText]=useState(false)
 const heading=useRef(null),opener=useRef(null)
 const templates=EMAIL_TEMPLATES.filter(t=>(group==='all'||t.group===group)&&`${t.title} ${EMAIL_GROUPS[t.group]}`.toLowerCase().includes(search.toLowerCase()))
 const preview=selected?buildEmailPreview(selected.id,locale,variant):null
 function open(t,e){opener.current=t.id;setSelected(t);setLocale('de');setVariant(t.variants?.[0]||'');setText(false);requestAnimationFrame(()=>{heading.current?.focus();heading.current?.scrollIntoView({block:'start'})})}
 function back(){setSelected(null);requestAnimationFrame(()=>document.getElementById(`emw-template-${opener.current}`)?.focus())}
 return <section className="emw-workspace" aria-label="E-Mail-Vorlagen">
 <header className="emw-header"><div><h2>E-Mail-Vorlagen</h2><p>Nachrichten prüfen, bevor sie Teil deiner Kundenkommunikation werden.</p></div><span className="emw-count">{EMAIL_TEMPLATES.length} Vorlagen</span></header>
 <p className="emw-notice">Alle Beispieldaten sind fiktiv. Drei Kontovorlagen stammen aus dem ELYSERA-Code; die übrigen sind Entwürfe ohne Versandanbindung.</p>
 {selected?<article className="emw-detail"><button className="emw-back" onClick={back}>← Alle Vorlagen</button><div className="emw-detail-title"><h3 tabIndex={-1} ref={heading}>{selected.title}</h3><span className="emw-badge" data-actual={selected.actual}>{selected.actual?'Originalvorlage':'Entwurf · nicht angebunden'}</span></div><p className="emw-origin">{selected.actual?'Originalinhalt der ELYSERA-Kontovorlage mit einem fiktiven Link. Diese Ansicht bestätigt keinen Versand.':'Vorgeschlagene ELYSERA-Nachricht. Texte und Abläufe müssen vor einer Versandanbindung freigegeben werden.'}</p>
 <div className="emw-controls"><label>Sprache<select value={locale} onChange={e=>setLocale(e.target.value)}>{selected.locales.map(l=><option key={l} value={l}>{l==='de'?'Deutsch':'English'}</option>)}</select></label>{selected.variants&&<label>Variante<select value={variant} onChange={e=>setVariant(e.target.value)}>{selected.variants.map(v=><option key={v} value={v}>{EMAIL_VARIANTS[v]}</option>)}</select></label>}<div className="emw-toggle" aria-label="Vorschauformat"><button aria-pressed={!text} onClick={()=>setText(false)}>HTML</button><button aria-pressed={text} onClick={()=>setText(true)}>Klartext</button></div>{!text&&<div className="emw-toggle" aria-label="Vorschaubreite"><button aria-pressed={mode==='desktop'} onClick={()=>setMode('desktop')}>Desktop</button><button aria-pressed={mode==='mobile'} onClick={()=>setMode('mobile')}>Mobil</button></div>}</div>
 <div className="emw-subject"><span>Betreff</span><strong>{preview.subject}</strong></div>{text?<pre className="emw-text">{preview.text}</pre>:<div className="emw-canvas" data-mode={mode}><iframe title={`${selected.title} – isolierte E-Mail-Vorschau`} sandbox="" referrerPolicy="no-referrer" srcDoc={isolatedEmailHtml(preview.html)}/></div>}<p className="emw-foot"><a href={`/admin/emails/${selected.id}?${new URLSearchParams({locale:preview.locale,...(preview.variant?{variant:preview.variant}:{})})}`}>Direktlink zu dieser Vorschau</a><br/>Fiktive Vorschau · Links deaktiviert · Kein Versand aus dieser Ansicht</p></article>:<>
 <div className="emw-filters"><label>Vorlage suchen<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name oder Bereich"/></label><label>Bereich<select value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Alle Bereiche</option>{Object.entries(EMAIL_GROUPS).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label></div>
 {!templates.length?<div className="emw-empty"><h3>Keine passende Vorlage</h3><p>Ändere den Suchbegriff oder wähle einen anderen Bereich.</p><button onClick={()=>{setSearch('');setGroup('all')}}>Filter zurücksetzen</button></div>:<div className="emw-grid">{templates.map(t=><button className="emw-card" id={`emw-template-${t.id}`} key={t.id} onClick={e=>open(t,e)}><span className="emw-card-top"><span>{EMAIL_GROUPS[t.group]}</span><span className="emw-envelope" aria-hidden="true">✉</span></span><strong>{t.title}</strong><span className="emw-badge" data-actual={t.actual}>{t.actual?'Originalvorlage':'Entwurf · nicht angebunden'}</span><span className="emw-card-bottom">{t.locales.join(' / ').toUpperCase()}{t.variants?` · ${t.variants.length} Varianten`:''}<span>Vorschau →</span></span></button>)}</div>}</>}
 </section>
}
