'use client'
import {useEffect,useRef,useState} from 'react'
import './faq-workspace.css'
const labels={PENDING:'Offen',APPROVED:'Freigegeben',REJECTED:'Abgelehnt'}
function Editor({entry:initialEntry,onClose,onSaved}){
 const alertRef=useRef(null);const ref=useRef(null);const [entry,setEntry]=useState(initialEntry);const [conflict,setConflict]=useState(false)
 const [value,setValue]=useState({question:entry.question,answer:entry.answer,locale:entry.locale,status:entry.status,sortOrder:entry.sortOrder});const [review,setReview]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{ref.current.showModal()},[]);useEffect(()=>{if(error)alertRef.current?.scrollIntoView({block:"nearest"})},[error])
 const update=(key,v)=>setValue(s=>({...s,[key]:v}))
 async function save(){setBusy(true);setError('');try{const r=await fetch(`/api/admin/faqs/${encodeURIComponent(entry.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({changes:value,expectedVersion:entry.version})});const body=await r.json();if(!r.ok){if(r.status===409)setConflict(true);throw Error(body.error)}onSaved(body.entry)}catch(e){setError(e.message||'Speichern nicht möglich.')}finally{setBusy(false)}}
 async function reload(){setBusy(true);try{const r=await fetch('/api/admin/faqs',{cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.error);const fresh=body.entries.find(e=>e.id===entry.id);if(!fresh)throw Error('Diese FAQ ist nicht mehr verfügbar.');setEntry(fresh);setValue({question:fresh.question,answer:fresh.answer,locale:fresh.locale,status:fresh.status,sortOrder:fresh.sortOrder});setReview(false);setConflict(false);setError('')}catch(e){setError(e.message||'Neu laden nicht möglich.')}finally{setBusy(false)}}
 return <dialog ref={ref} className="faq-dialog" onCancel={e=>{if(busy)e.preventDefault();else onClose()}}><header><div><small>FAQ bearbeiten</small><h2>{review?'Änderungen prüfen':'Frage & Antwort'}</h2></div><button disabled={busy} onClick={onClose} aria-label="Dialog schließen">×</button></header><form onSubmit={e=>{e.preventDefault();setReview(true)}}><div className="faq-dialog-body">{review?<div className="faq-review">{Object.keys(value).map(key=><section key={key}><strong>{{question:'Frage',answer:'Antwort',locale:'Sprache',status:'Status',sortOrder:'Reihenfolge'}[key]}</strong>{value[key]!==entry[key]&&<del>{labels[entry[key]]||String(entry[key]??'—')}</del>}<p>{labels[value[key]]||String(value[key]??'—')}</p></section>)}{value.status==='APPROVED'&&<p>Diese Frage und Antwort werden öffentlich angezeigt.</p>}</div>:<><label>Frage<textarea aria-label="Frage" required maxLength={2000} value={value.question} onChange={e=>update('question',e.target.value)}/></label><label>Antwort<textarea aria-label="Antwort" className="faq-answer" required={value.status==='APPROVED'} maxLength={6000} value={value.answer} onChange={e=>update('answer',e.target.value)}/></label><div className="faq-fields"><label>Sprache<select aria-label="Sprache" value={value.locale} onChange={e=>update('locale',e.target.value)}><option value="de">Deutsch</option><option value="en">Englisch</option>{!["de","en"].includes(value.locale)&&<option value={value.locale}>{value.locale}</option>}</select></label><label>Status<select aria-label="Status" value={value.status} onChange={e=>update('status',e.target.value)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Reihenfolge<input aria-label="Reihenfolge" type="number" min="-100000" max="100000" step="1" required value={value.sortOrder} onChange={e=>update('sortOrder',e.target.value===''?'':Number(e.target.value))}/></label></div></>}{error&&<div ref={alertRef} className="faq-save-error" role="alert"><strong>{conflict?"FAQ wurde zwischenzeitlich geändert":"Speichern nicht bestätigt"}</strong><p>{error}</p>{conflict&&<><p>Deine Eingaben bleiben erhalten. „FAQ neu laden“ verwirft sie und lädt den aktuellen Stand.</p><button type="button" disabled={busy} onClick={reload}>{busy?"Lädt …":"FAQ neu laden"}</button></>}</div>}</div><footer><button type="button" disabled={busy} onClick={review?()=>setReview(false):onClose}>{review?'Zurück':'Abbrechen'}</button>{review?<button type="button" className="primary" disabled={busy||conflict} onClick={save}>{busy?'Speichert …':'Änderungen speichern'}</button>:<button className="primary">Änderungen prüfen</button>}</footer></form></dialog>
}
export default function FaqWorkspace(){
 const [entries,setEntries]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState('PENDING'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[limited,setLimited]=useState(false),[notice,setNotice]=useState('');const opener=useRef(null)
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/admin/faqs',{cache:'no-store'}),body=await r.json();if(!r.ok)throw Error(body.error);setEntries(body.entries);setLimited(body.limited)}catch(e){setError(e.message||'Laden nicht möglich.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=(entries||[]).filter(e=>e.status===tab&&`${e.question} ${e.answer} ${e.locale}`.toLowerCase().includes(search.toLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/15)),current=Math.min(page,pages)
 function close(){setSelected(null);requestAnimationFrame(()=>opener.current?.focus())}
 return <section className="faq-workspace"><header className="faq-title"><div><h1>FAQ</h1><p>Fragen prüfen und Antworten für ELYSERA veröffentlichen.</p></div><button onClick={load} disabled={loading}>Aktualisieren</button></header><div className="faq-metrics">{[['Gesamt',entries?.length],...Object.entries(labels).map(([s,l])=>[l,entries?.filter(e=>e.status===s).length])].map(([label,count])=><article key={label}><span>{label}</span><strong>{loading||error?'—':count}</strong></article>)}</div><div className="faq-panel"><div className="faq-toolbar"><div className="faq-tabs" role="tablist" aria-label="FAQ-Status">{Object.entries(labels).map(([s,l])=><button key={s} role="tab" aria-selected={tab===s} onClick={()=>{setTab(s);setPage(1)}}>{l}</button>)}</div><input type="search" aria-label="FAQ suchen" placeholder="Frage oder Antwort suchen" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div>{notice&&<p role="status">{notice}</p>}{limited&&<p>Die Ansicht enthält maximal 2.000 Einträge. Zähler beziehen sich auf diese Auswahl.</p>}{loading?<div className="faq-state" role="status">FAQ werden geladen …</div>:error?<div className="faq-state" role="alert"><h2>Laden nicht möglich</h2><p>{error}</p><button onClick={load}>Erneut versuchen</button></div>:!filtered.length?<div className="faq-state"><h2>{search?'Keine passenden Fragen':'Keine Fragen in diesem Status'}</h2><p>{search?'Passe deinen Suchbegriff an.':'Wähle einen anderen Status, um weitere FAQ zu sehen.'}</p></div>:<><div className="faq-rows">{filtered.slice((current-1)*15,current*15).map(entry=><article key={entry.id}><div><div className="faq-meta"><span>{entry.locale.toUpperCase()}</span><span>Position {entry.sortOrder}</span><span>{labels[entry.status]}</span></div><h2>{entry.question}</h2><p>{entry.answer||'Noch keine Antwort hinterlegt.'}</p></div><button aria-label={`FAQ bearbeiten: ${entry.question}`} onClick={e=>{opener.current=e.currentTarget;setSelected(entry);setNotice('')}}>Bearbeiten</button></article>)}</div><footer className="faq-pagination"><span>{filtered.length} Fragen · Seite {current} von {pages}</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}>Zurück</button><button disabled={current===pages} onClick={()=>setPage(current+1)}>Weiter</button></div></footer></>}</div>{selected&&<Editor entry={selected} onClose={close} onSaved={entry=>{setEntries(s=>s.map(e=>e.id===entry.id?entry:e).sort((a,b)=>a.sortOrder-b.sortOrder));setNotice('Änderungen gespeichert und bestätigt.');close()}}/>}</section>
}
