'use client'
import {useEffect,useRef,useState} from 'react'
import './feedback-workspace.css'
const names={'elysera-renewal-serum-30ml':'Renewal Serum','elysera-balance-toner-100ml':'Balance Toner','elysera-contour-eye-cream-15ml':'Contour Eye Cream'}
const labels={OPEN:'Offen',ANSWERED:'Beantwortet',HIDDEN:'Ausgeblendet',PENDING:'Ausstehend',APPROVED:'Freigegeben',REJECTED:'Abgelehnt'}
export default function FeedbackWorkspace(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[kind,setKind]=useState('question'),[filter,setFilter]=useState(''),[product,setProduct]=useState(''),[selected,setSelected]=useState(null),[reply,setReply]=useState(''),[status,setStatus]=useState(''),[confirm,setConfirm]=useState(false),[notice,setNotice]=useState(''),[uncertain,setUncertain]=useState(false),[conflict,setConflict]=useState(false);const requestRef=useRef(null)
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/admin/product-feedback',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem('elysera-feedback-admin-attempt'));if(saved){requestRef.current=saved;setSelected(saved.snapshot);setKind(saved.snapshot.kind);setReply(saved.payload.reply);setStatus(saved.payload.status);setConfirm(true);setUncertain(true);setNotice('Vorherige Speicherung ungeklärt. Dieselbe Anfrage erneut prüfen.')}}catch{}load()},[])
 function select(row){if(uncertain)return;setConflict(false);setSelected(row);setReply(row.reply||'');setStatus(row.status);setConfirm(false);setNotice('');requestRef.current=null}
 async function save(){setBusy(true);setError('');try{const payload=requestRef.current?.payload||{actorId:data.actorId,id:selected.id,version:selected.version,status,reply};const key=JSON.stringify(payload);if(requestRef.current?.key!==key)requestRef.current={key,id:crypto.randomUUID(),payload,snapshot:selected};sessionStorage.setItem('elysera-feedback-admin-attempt',JSON.stringify(requestRef.current));setUncertain(true);const r=await fetch('/api/admin/product-feedback',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestId:requestRef.current.id})}),d=await r.json();if(!r.ok){if(['INVALID_INPUT','VERSION_CONFLICT'].includes(d.code)){sessionStorage.removeItem('elysera-feedback-admin-attempt');requestRef.current=null;setUncertain(false)}if(r.status===409)setConflict(true);throw Error(d.error)}sessionStorage.removeItem('elysera-feedback-admin-attempt');setUncertain(false);setData(old=>({...old,entries:old.entries.map(x=>x.id===d.entry.id?{...x,...d.entry}:x)}));setSelected(old=>({...old,...d.entry}));setConfirm(false);setNotice('Änderung gespeichert und geprüft.');requestRef.current=null}catch(e){setError(e.message)}finally{setBusy(false)}}
 const rows=data?.entries.filter(x=>x.kind===kind&&(!filter||x.status===filter)&&(!product||x.productId===product))
 return <section className={`fbw-root${selected?' fbw-has-selection':''}`}><div className="fbw-heading"><div><h1>Produktfeedback</h1><p>Fragen beantworten und Rezensionen prüfen.</p></div><button disabled={busy} onClick={load}>Neu laden</button></div>
 <div className="fbw-metrics">{[['Offene Fragen','OPEN'],['Antworten','ANSWERED'],['Zu prüfen','PENDING'],['Freigegeben','APPROVED']].map(([label,s])=><div key={s}><span>{label}</span><strong>{data?data.entries.filter(x=>x.status===s).length:'—'}</strong><small>{data?.limited?'im geladenen Ausschnitt':'Einträge'}</small></div>)}</div>
 {error&&<div className="fbw-error" role="alert">{error} Ein vorhandener Entwurf bleibt erhalten. Bei Versionskonflikten den aktuellen Stand unten laden und den Entwurf vergleichen.</div>}{notice&&<p role="status">{notice}</p>}
 <div className="fbw-toolbar"><div className="fbw-tabs" role="tablist" aria-label="Feedbacktyp">{[['question','Fragen'],['review','Rezensionen']].map(([k,label])=><button role="tab" aria-selected={kind===k} key={k} disabled={busy||uncertain} onClick={()=>{setKind(k);setFilter('');setSelected(null)}}>{label}</button>)}</div><label>Produkt<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Alle Produkte</option>{Object.entries(names).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Alle Status</option>{(kind==='question'?['OPEN','ANSWERED','HIDDEN']:['PENDING','APPROVED','REJECTED']).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label></div>
 {data?.limited&&<p>Die neuesten {data.limit} Einträge sind geladen. Kennzahlen beziehen sich auf diesen Ausschnitt.</p>}
 <div className="fbw-columns"><div className="fbw-list" aria-busy={busy}>{!data?<p>{busy?'Feedback wird geladen …':'Noch keine Daten verfügbar.'}</p>:rows.length===0?<p>Keine Einträge für diese Auswahl.</p>:rows.map(row=><button disabled={busy||uncertain} className={selected?.id===row.id?'fbw-selected':''} key={row.id} onClick={()=>select(row)}><span className="fbw-rowhead"><strong>{names[row.productId]}</strong><span>{labels[row.status]}</span></span><span className="fbw-copy">{row.body}</span><small>{row.firstName||'Kundenkonto'} · {new Date(row.createdAt).toLocaleDateString('de-DE')}{row.rating?` · ${row.rating}/5`:''}{row.verifiedPurchase?' · Kauf bestätigt':''}</small></button>)}</div>
 <div className="fbw-detail">{selected&&<button className="fbw-back" disabled={busy||uncertain} onClick={()=>{setSelected(null);setConfirm(false);setError('');setNotice('')}}>← Zur Liste</button>}{!selected?<><h2>Feedback im Detail</h2><p>Wähle einen Eintrag, um Text und Status zu prüfen.</p></>:<><h2>{names[selected.productId]}</h2><p>{selected.kind==='review'?'Rezension · '+selected.rating+'/5'+(selected.verifiedPurchase?' · Kauf bestätigt':''):'Kundenfrage'}</p><p className="fbw-body">{selected.body}</p><p>{selected.email||'Kundenkonto'} · Version {selected.version}</p><label>Öffentliche Antwort<textarea maxLength={8000} rows={7} value={reply} disabled={busy||uncertain} onChange={e=>{setReply(e.target.value);setConfirm(false)}}/></label><label>Status<select value={status} disabled={busy||uncertain} onChange={e=>{setStatus(e.target.value);setConfirm(false)}}>{(selected.kind==='question'?['OPEN','ANSWERED','HIDDEN']:['PENDING','APPROVED','REJECTED']).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><p>Freigegebene Rezensionen und beantwortete Fragen erscheinen am Produkt. Es wird keine E-Mail versendet.</p>{error&&<p role="status" className="fbw-error">{error}</p>}{conflict&&<button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/admin/product-feedback',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);const latest=d.entries.find(x=>x.id===selected.id);if(!latest)throw Error('Eintrag nicht mehr im geladenen Ausschnitt.');setData(d);setSelected(latest);setConflict(false);setConfirm(false);setError('');setNotice('Aktueller Stand: '+labels[latest.status]+' · Antwort: '+(latest.reply||'keine')+'. Dein Entwurf bleibt zur Prüfung erhalten.')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Aktuellen Stand laden, Entwurf behalten</button>}{confirm?<div className="fbw-confirm"><strong>Änderung prüfen</strong><p>Neuer Status: {labels[status]}</p><p className="fbw-body">{reply||'Ohne öffentliche Antwort'}</p><button disabled={busy||conflict} onClick={save}>{busy?'Wird gespeichert …':uncertain?'Dieselbe Anfrage erneut prüfen':'Verbindlich speichern'}</button><button disabled={busy||uncertain} onClick={()=>setConfirm(false)}>Zurück</button></div>:<button disabled={busy||status==='ANSWERED'&&!reply.trim()} onClick={()=>setConfirm(true)}>Änderung prüfen</button>}</>}</div></div></section>
}
