'use client'
import {useEffect,useState} from 'react'
import {PAID,PENDING,summarize,dailyValues,csvCell} from '../api/admin/finance/model.mjs'
import './finance-workspace.css'
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n)
const day=d=>new Intl.DateTimeFormat('de-DE',{timeZone:'UTC',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d))
const state=s=>PAID.includes(s)?'Bezahlt':PENDING.includes(s)?'Ausstehend':s==='CANCELLED'?'Storniert':s==='REFUNDED'?'Erstattungsstatus':s
function csv(rows,period){const text=[['Bestellung','Erstellt (UTC)','Status','Bestellwert EUR'],...rows.map(r=>[r.id,r.createdAt,r.status,r.total.toFixed(2)])].map(r=>r.map(csvCell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`elysera-bestellwerte-${period}-tage.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function FinanceWorkspace({fixture}){
 const [period,setPeriod]=useState('30'),[data,setData]=useState(fixture||null),[loading,setLoading]=useState(!fixture),[error,setError]=useState(''),[retry,setRetry]=useState(0),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[page,setPage]=useState(1)
 useEffect(()=>{setPage(1);if(fixture){setData(fixture);return}const controller=new AbortController();setLoading(true);setError('');setData(null);fetch('/api/admin/finance?period='+period,{cache:'no-store',signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.error);setData(body)}).catch(e=>{if(e.name!=='AbortError')setError(e.message||'Laden fehlgeschlagen.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[period,retry,fixture])
 const orders=data?.orders||[],summary=data?.summary|| (data?summarize(orders):null),visible=orders.filter(r=>(filter==='all'||(filter==='paid'?PAID:PENDING).includes(r.status))&&r.id.toLowerCase().includes(query.toLowerCase())),daily=dailyValues(orders),chartMax=Math.max(1,...daily.map(d=>d.paid+d.pending)),pages=Math.max(1,Math.ceil(visible.length/8)),current=Math.min(page,pages)
 return <section className="fw-workspace"><div className="fw-heading"><div><span className="fw-eyebrow">Finanzen · Bestellwerte</span><h1>Finanzübersicht</h1><p>ELYSERA-Bestellungen nachvollziehen und offene Zahlungen prüfen.</p></div><button aria-label="Finanzdaten aktualisieren" onClick={()=>setRetry(x=>x+1)} disabled={loading}>↻</button></div>
 {fixture&&<p className="fw-notice">Designvorschau · Beispieldaten</p>}
 <div className="fw-controls"><label>Zeitraum<select aria-label="Zeitraum" value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Letzte 7 Tage</option><option value="30">Letzte 30 Tage</option><option value="90">Letzte 90 Tage</option><option value="365">Letzte 365 Tage</option></select></label><p>Nach Bestelldatum · UTC{data?.start&&<span>{day(data.start)} – {day(data.end)}</span>}</p><button disabled={loading||!!error||!visible.length} onClick={()=>csv(visible,period)}>CSV exportieren ↓</button></div>
 <div className="fw-metrics"><article><span>Bezahlter Bestellwert</span><strong>{summary?money(summary.paid):'—'}</strong><small>{summary?summary.paidCount+' Bestellungen':error?'Nicht verfügbar':'Wird ermittelt'}</small></article><article><span>Ausstehender Bestellwert</span><strong>{summary?money(summary.pending):'—'}</strong><small>{summary?summary.pendingCount+' Bestellungen':error?'Nicht verfügbar':'Wird ermittelt'}</small></article><article><span>Erstattete Beträge</span><strong>—</strong><small>Kein zugeordneter Zahlungsnachweis</small></article><article><span>Netto-Zahlungseingang</span><strong>—</strong><small>Nicht aus Bestellwerten ableitbar</small></article></div>
 <div className="fw-layout"><article className="fw-orders"><header><div><h2>Beiträge je Bestellung</h2><p>Bestellwert und aktueller Zahlungsstatus</p></div><span className="fw-count">{data?orders.length:'—'}</span></header><div className="fw-filters"><label><span className="fw-sr">Bestellnummer suchen</span><input aria-label="Bestellnummer suchen" type="search" placeholder="Bestellnummer suchen …" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><label><span className="fw-sr">Zahlungsstatus</span><select aria-label="Zahlungsstatus" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="all">Alle Status</option><option value="paid">Bezahlt</option><option value="pending">Ausstehend</option></select></label></div>
 {loading?<div className="fw-state" role="status">Finanzdaten werden geladen …</div>:error?<div className="fw-state" role="alert"><h3>Finanzdaten nicht verfügbar</h3><p>{error}</p><button onClick={()=>setRetry(x=>x+1)}>Erneut versuchen</button></div>:!visible.length?<div className="fw-state"><h3>{orders.length?'Keine passenden Bestellungen':'Keine Bestellungen im Zeitraum'}</h3><p>{orders.length?'Passe Suche oder Zahlungsfilter an.':'Wähle einen größeren Zeitraum, um weitere ELYSERA-Bestellungen zu prüfen.'}</p></div>:<><div className="fw-table"><div className="fw-row fw-th"><span>Bestellung / Datum</span><span>Zahlungsstatus</span><span>Bestellwert</span></div>{visible.slice((current-1)*8,current*8).map(r=><div className="fw-row" key={r.id}><div className="fw-orderid"><strong>{r.id}</strong><small>{day(r.createdAt)} · UTC</small></div><span className={'fw-badge '+(PAID.includes(r.status)?'paid':PENDING.includes(r.status)?'pending':'')}>{state(r.status)}</span><strong className="fw-amount">{money(r.total)}</strong></div>)}</div><footer><span>{visible.length} Bestellungen · Seite {current} von {pages}</span><div><button disabled={current===1} onClick={()=>setPage(current-1)} aria-label="Vorherige Seite">←</button><button disabled={current===pages} onClick={()=>setPage(current+1)} aria-label="Nächste Seite">→</button></div></footer></>}
 </article><aside className="fw-evidence"><h2>Bestellwert nach Tag</h2><p className="fw-chart-intro">Bestelldatum · UTC</p><div className="fw-legend"><span><i/>Bezahlt</span><span><i/>Ausstehend</span></div>{loading?<p role="status">Verlauf wird geladen …</p>:error?<p>Verlauf nicht verfügbar.</p>:!daily.length?<p>Keine Bestellwerte für diesen Zeitraum.</p>:<div className="fw-chart" role="img" aria-label="Tageswerte bezahlter und ausstehender Bestellungen"><p className="fw-chart-ceiling">Skala bis {money(chartMax)}</p><div className="fw-bars">{daily.map(d=><div className="fw-day" key={d.date} title={day(d.date)+': bezahlt '+money(d.paid)+', ausstehend '+money(d.pending)}><div className="fw-stack"><span className="fw-bar-paid" style={{height:(d.paid/chartMax*100)+'%'}}/><span className="fw-bar-pending" style={{height:(d.pending/chartMax*100)+'%'}}/></div></div>)}</div><div className="fw-chart-axis"><span>{day(daily[0].date)}</span><span>{day(daily[daily.length-1].date)}</span></div></div>}{daily.length>0&&<details className="fw-day-details"><summary>Tageswerte</summary><div className="fw-day-table">{daily.map(d=><div key={d.date}><span>{day(d.date)}</span><span>{money(d.paid)} bezahlt</span><span>{money(d.pending)} ausstehend</span></div>)}</div></details>}<div className="fw-chart-scope"><h3>Eindeutig ELYSERA</h3><p>Nur reine ELYSERA-Bestellungen.</p></div><details className="fw-limitations"><summary>Datengrundlage</summary><p>Gemischte Warenkörbe sind ausgeschlossen. Bezahlt umfasst bezahlt, verpackt, versendet und zugestellt. Bestellwerte bestätigen keinen Bankeingang und sind kein buchhalterischer Umsatz.</p><p>Erstattungen, Gebühren, Provisionen, Auszahlungen und Gewinn benötigen gesondert zugeordnete Buchungen. Der Export enthält die gefilterten Bestellungen.</p></details></aside></div></section>
}
