'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {DashboardIcon as Icon} from '../dashboard/design-icons'
import './live-overview.css'

const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n)
const date=n=>new Date(n).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})
// Calendar boundaries use the same browser timezone as the displayed order dates.
function overviewWindow(days,now){
 const today=new Date(now);today.setHours(0,0,0,0)
 const start=new Date(today);start.setDate(start.getDate()-days+1)
 const end=new Date(today);end.setDate(end.getDate()+1)
 const buckets=Array.from({length:7},(_,i)=>{
  const from=new Date(start);from.setDate(from.getDate()+Math.floor(i*days/7))
  const to=new Date(start);to.setDate(to.getDate()+Math.floor((i+1)*days/7))
  const last=new Date(to);last.setDate(last.getDate()-1)
  return {start:from.getTime(),end:to.getTime(),label:days===7?date(from):date(from)+'–'+date(last)}
 })
 return {start:start.getTime(),end:end.getTime(),buckets}
}
const initial={status:'loading',rows:[],error:''}
function Status({children}){return <span className={'eo-status '+(['Bezahlt','Versendet','Zugestellt'].includes(children)?'is-good':String(children).toLowerCase().includes('ausstehend')?'is-pending':'')}>{children}</span>}
function DataState({status,error,emptyTitle,emptyText}){return <div className="eo-data-state" role={status==='error'?'alert':'status'}><span className="eo-state-icon"><Icon name={status==='error'?'help':'bag'} size={25}/></span><strong>{status==='loading'?'Daten werden geladen …':status==='error'?'Daten aktuell nicht verfügbar':emptyTitle}</strong><p>{status==='error'?error:status==='loading'?'Deine ELYSERA-Daten werden abgerufen.':emptyText}</p></div>}
export default function LiveOverview({period,onPeriodChange}){
 const [ordersState,setOrders]=useState(initial),[productsState,setProducts]=useState(initial),[revision,setRevision]=useState(0),[updated,setUpdated]=useState(null)
 useEffect(()=>{const controller=new AbortController();setUpdated(null);for(const [section,setter] of [['orders',setOrders],['products',setProducts]]){setter(initial);fetch('/api/admin/data/'+section,{signal:controller.signal,cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error||'Bitte erneut versuchen.');if(!Array.isArray(data.rows))throw Error('Die Antwort enthält keine gültigen Daten.');setter({status:'ready',rows:data.rows,error:''});setUpdated(new Date())}).catch(error=>{if(error.name!=='AbortError')setter({status:'error',rows:[],error:error.message})})}return()=>controller.abort()},[revision])
 const days=[7,30,90].includes(Number(period))?Number(period):7,window=overviewWindow(days,updated||new Date())
 const orders=ordersState.rows.filter(r=>r[7]&&new Date(r[7]).getTime()>=window.start&&new Date(r[7]).getTime()<window.end)
 const orderReady=ordersState.status==='ready',productReady=productsState.status==='ready',loading=ordersState.status==='loading'||productsState.status==='loading'
 const paid=orders.filter(r=>r[5]==='Bezahlt'),total=paid.reduce((sum,r)=>sum+(Number.parseFloat(r[4])||0),0),pending=orders.filter(r=>String(r[5]).toLowerCase().includes('ausstehend')).length
 const buckets=window.buckets.map(bucket=>({...bucket,value:paid.filter(r=>new Date(r[7]).getTime()>=bucket.start&&new Date(r[7]).getTime()<bucket.end).reduce((sum,r)=>sum+(Number.parseFloat(r[4])||0),0)}))
 const ceiling=Math.max(1,...buckets.map(b=>b.value)),amount=orderReady?euro(total):'—'
 function exportOrders(){const escape=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Bestellung','Kunde','Produkte','Menge','Betrag','Zahlung','Versand','Datum'],...orders];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`elysera-bestellungen-${days}-tage.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="eo-overview">
  <section className="eo-metrics" aria-label="ELYSERA-Kennzahlen">{[['Bezahlter Bestellwert',amount,days+' Tage','chart',ordersState],['Bestellungen',orderReady?orders.length:'—',days+' Tage','bag',ordersState],['Pflegeprodukte',productReady?productsState.rows.length:'—','Im Sortiment','leaf',productsState],['Offene Zahlungen',orderReady?pending:'—',days+' Tage','wallet',ordersState]].map(([title,value,sub,icon,state])=><article key={title}><span className="eo-metric-icon"><Icon name={icon} size={23}/></span><div><h2>{title}</h2><strong>{value}</strong><small>{state.status==='loading'?'Wird geladen …':state.status==='error'?'Nicht verfügbar':sub}</small></div></article>)}</section>
  <div className="eo-layout">
   <section className="eo-panel eo-chart-panel"><header><div><h2>Bestellwert im Verlauf</h2><p>Bezahlte Bestellungen · letzte {days} Tage</p></div><select className="eo-period" aria-label="Zeitraum" value={period} onChange={event=>onPeriodChange?.(event.target.value)}><option value="7">7 Tage</option><option value="30">30 Tage</option><option value="90">90 Tage</option></select></header>
    <div className="eo-chart-body"><div className="eo-chart-area">{!orderReady||!paid.length?<DataState status={ordersState.status} error={ordersState.error} emptyTitle="Noch kein bezahlter Bestellwert" emptyText="Sobald eine Bestellung bezahlt ist, erscheint sie hier im Verlauf."/>:<div className="eo-chart" role="img" aria-label={`${euro(total)} bezahlter Bestellwert in ${days} Tagen`}><div className="eo-axis"><span>{euro(ceiling)}</span><span>{euro(ceiling/2)}</span><span>0 €</span></div><div className="eo-plot"><svg viewBox="0 0 700 180" preserveAspectRatio="none"><g stroke="#e6edf4"><path d="M0 1H700M0 90H700M0 179H700"/></g>{buckets.map((b,i)=><rect key={i} x={22+i*100} y={180-b.value/ceiling*164} width="51" height={b.value/ceiling*164} rx="3" fill="#203f66"><title>{b.label}: {euro(b.value)}</title></rect>)}</svg><div className={'eo-xaxis'+(days>7?' eo-ranges':'')}>{buckets.map((b,i)=><span key={i}>{b.label}</span>)}</div></div></div>}</div><aside className="eo-chart-summary"><div><span>Bezahlter Bestellwert</span><strong>{amount}</strong><small>{orderReady?`${paid.length} bezahlte Bestellungen`:'Noch nicht verfügbar'}</small></div><div><span>Ø bezahlter Bestellwert</span><strong>{orderReady&&paid.length?euro(total/paid.length):'—'}</strong><small>{orderReady&&!paid.length?'Noch keine Grundlage':'Im gewählten Zeitraum'}</small></div></aside></div>
    <p className="eo-chart-note">Bestellwerte inklusive eingesetzter Zahlungsmittel.</p>
   </section>
   <section className="eo-panel eo-orders"><header><div><h2>Neueste Bestellungen</h2><p>ELYSERA · letzte {days} Tage</p></div><Link href="/admin/orders">Alle ansehen <Icon name="arrow" size={14}/></Link></header>{!orderReady||!orders.length?<DataState status={ordersState.status} error={ordersState.error} emptyTitle="Noch keine Bestellungen" emptyText="Neue ELYSERA-Bestellungen in diesem Zeitraum erscheinen hier automatisch."/>:<><div className="eo-table"><table><thead><tr>{['Bestellung','Kunde / Produkte','Betrag','Zahlung','Versand'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{orders.slice(0,5).map(r=><tr key={r[0]}><td><Link href="/admin/orders">#{r[0].slice(-8)}</Link><small>{date(r[7])}</small></td><td>{r[1]}<small>{r[2]}</small></td><td>{euro(Number.parseFloat(r[4])||0)}</td><td><Status>{r[5]}</Status></td><td><Status>{r[6]}</Status></td></tr>)}</tbody></table></div><div className="eo-order-cards">{orders.slice(0,5).map(r=><Link href="/admin/orders" key={r[0]}><span className="eo-order-icon"><Icon name="bag" size={23}/></span><div><div className="eo-order-line"><strong>#{r[0].slice(-8)}</strong><small>{date(r[7])}</small></div><div className="eo-order-line"><b>{r[1]}</b><strong>{euro(Number.parseFloat(r[4])||0)}</strong></div><p>{r[2]}</p><div className="eo-statuses"><Status>{r[5]}</Status><Status>{r[6]}</Status></div></div></Link>)}</div></>}</section>
   <aside className="eo-side"><section className="eo-panel eo-tasks"><header><h2>Deine nächsten Schritte</h2><Icon name="arrow" size={15}/></header>{[['orders','Bestellungen prüfen',orderReady?`${pending} ${pending===1?'offene Zahlung':'offene Zahlungen'} im Zeitraum`:ordersState.status==='loading'?'Zahlungen werden geladen …':'Zahlungsdaten nicht verfügbar','bag'],['products','Sortiment verwalten',productReady?`${productsState.rows.length} Pflegeprodukte`:productsState.status==='loading'?'Sortiment wird geladen …':'Sortimentsdaten nicht verfügbar','leaf'],['users','Kunden & Partner','ELYSERA-Konten aufrufen','team']].map(([id,title,sub,icon])=><Link href={'/admin/'+id} key={id}><span className="eo-task-icon"><Icon name={icon} size={21}/></span><span><strong>{title}</strong><small>{sub}</small></span><Icon name="arrow" size={14}/></Link>)}{productsState.status==='error'&&<p className="eo-product-error" role="alert">{productsState.error}</p>}</section><Link href="/admin/products" className="eo-brand"><div><h2>Schönheit<br/>schafft Chancen.</h2><p>Die ELYSERA<br/>Peptid-Routine.</p><span>Zum Sortiment <Icon name="arrow" size={14}/></span></div><div className="eo-montage">{['serum','toner','eye'].map(n=><img key={n} src={`/media/campaign-2026/${n}.webp`} alt={n==='serum'?'ELYSERA Serum':n==='toner'?'ELYSERA Toner':'ELYSERA Augenpflege'}/>)}</div></Link></aside>
  </div>
  <div className="eo-data-toolbar"><p>Bis zu 500 neueste ELYSERA-Bestellungen{updated&&orderReady&&productReady?` · Aktualisiert ${updated.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`:''}. {(ordersState.status==='error'||productsState.status==='error')?'Abruf teilweise fehlgeschlagen. ':''}{ordersState.rows.length>=500?'Die Auswertung kann unvollständig sein.':''}</p><div><button disabled={loading} onClick={()=>setRevision(v=>v+1)}>{loading?'Wird geladen …':'Aktualisieren'}</button><button disabled={!orderReady||!orders.length} onClick={exportOrders}>Bestellungen exportieren <Icon name="arrow" size={14}/></button></div></div>
 </div>
}
