export const groups=['Arbeitsplatz','Shop & Kunden','Partner & Finanzen','Inhalte & Kommunikation','System']
const definitions=[
 ['overview','Übersicht',0,'home','Dein Geschäft auf einen Blick.'],
 ['orders','Bestellungen',1,'bag','Zahlungen prüfen, Bestellungen bearbeiten und Versand verfolgen.','Bestellung,Kunde,Produkt,Menge,Betrag,Zahlung,Versand'],
 ['users','Nutzer',1,'team','Kunden, Partner und Zugriffsrechte verwalten.','Name,E-Mail,Rolle,Mitgliedschaft,Status'],
 ['products','Produkte',1,'leaf','Dein Sortiment, Produktdetails und Verfügbarkeit.','Produkt,Größe,Preis,Bestand,Status'],
 ['packages','Pakete',1,'bag','Sets und Mitgliedschaftspakete zusammenstellen.','Name,Produkte,Preis,Status'],
 ['coupons','Gutscheine',1,'wallet','Rabatte, Gültigkeit und Einlösungen im Blick.','Code,Rabatt,Gültig bis,Einlösungen,Status'],
 ['support','Support',1,'help','Anfragen zu Produkten, Konten und Bestellungen bearbeiten.','Betreff,Kunde,Priorität,Zuständig,Status'],
 ['commission-network','Provisionsnetzwerk',2,'team','Empfehlungen und die zugehörigen Provisionen nachvollziehen.','Partner,Empfohlen von,Bestellung,Umsatz,Provision,Status'],
 ['payouts','Auszahlungen',2,'wallet','Auszahlungsanträge und Freigaben prüfen.','Partner,Betrag,Zahlungsweg,Angefragt am,Status'],
 ['grant-credits','Guthaben vergeben',2,'coins','Gutschriften mit Empfänger und nachvollziehbarer Begründung.','Empfänger,Betrag,Grund,Status'],
 ['finance','Finanzübersicht',2,'chart','Umsatz, Provisionen und Auszahlungen im Zusammenhang.','Zeitraum,Umsatz,Provisionen,Auszahlungen,Status'],
 ['net-revenue','Nettoumsatz',2,'chart','Zahlungseingänge nach Abzügen vergleichen.','Zeitraum,Brutto,Steuern,Erstattungen,Netto'],
 ['profit-breakdown','Gewinnaufteilung',2,'chart','Kosten und Margen nach Produkten aufschlüsseln.','Produkt,Umsatz,Wareneinsatz,Provisionen,Marge'],
 ['profit-forecast','Gewinnprognose',2,'chart','Szenarien für die weitere Geschäftsentwicklung planen.','Szenario,Bestellungen,Umsatz,Kosten,Ergebnis'],
 ['leaderboard','Rangliste',2,'chart','Partnerleistung und Qualifikationen vergleichen.','Platz,Partner,Umsatz,Rang,Status'],
 ['diamond-case','Diamond Case',2,'bag','Prämien, Gewinnchancen und Einlösungen verwalten.','Prämie,Typ,Gewinnchance,Bestand,Status'],
 ['crm','Lead CRM',2,'team','Leads importieren, verteilen und Gespräche nachverfolgen.','Name,Status'],
 ['diamond-club-invites','Club-Einladungen',2,'link','Kampagnen und Empfänger für Club-Einladungen verwalten.','Empfänger,Kampagne,Versandstatus'],
 ['events','Events',3,'bell','Veranstaltungen, Anmeldungen und Turnierabläufe verwalten.','Titel,Datum,Teilnehmer,Warteliste,Status'],
 ['emails','E-Mails',3,'bell','E-Mail-Inhalte und Kampagnen vorbereiten.','Betreff,Zielgruppe,Geplant am,Status'],
 ['whatsapp-notification','WhatsApp-Versand',3,'bell','Nachrichten und Empfängergruppen vorbereiten.','Nachricht,Zielgruppe,Geplant am,Status'],
 ['whatsapp-templates','WhatsApp-Vorlagen',3,'copy','Wiederverwendbare Nachrichtenvorlagen pflegen.','Name,Sprache,Nachricht,Status'],
 ['news','News',3,'copy','News als Entwurf vorbereiten, prüfen und veröffentlichen.','Titel,Status'],
 ['faq','FAQ',3,'help','Häufige Fragen und verständliche Antworten pflegen.','Frage,Antwort,Kategorie,Status'],
 ['product-feedback','Produktfeedback',3,'leaf','Rückmeldungen zur ELYSERA-Pflege auswerten.','Produkt,Kunde,Bewertung,Feedback,Status'],
 ['testimonials-reviews','Erfahrungsberichte',3,'user','Eingereichte Erfahrungen und Freigaben verwalten.','Titel,Autor,Bewertung,Status'],
 ['trustpilot-reviews','Trustpilot',3,'link','Eingereichte Bewertungsnachweise prüfen und freigeben.','Bestellung,Kunde,Nachweis,Eingereicht,Status'],
 ['ai-studio-errors','AI-Studio',4,'help','Protokollierte Werkzeugfehler nach Zeitraum und Werkzeug durchsuchen.','Werkzeug,Fehler,Zeitpunkt'],
 ['settings','Einstellungen',4,'sun','Allgemeine Einstellungen für die Administration.','Einstellung,Wert,Status'],
]
export const modules=definitions.map(([id,label,group,icon,description,fields])=>({id,label,group,icon,description,fields:(fields||'Name,Status').split(',')}))
export const samples={
 orders:[['ELY-1048','Lena Beispiel','Renewal Serum','2','118 €','Bezahlt','Offen'],['ELY-1047','Marie Muster','The Peptide Ritual Set','1','139 €','Ausstehend','Offen'],['ELY-1046','Anna Demo','Renewal Serum','1','59 €','Bezahlt','Versendet'],['ELY-1045','Sophie Beispiel','The Peptide Ritual Set','2','278 €','Bezahlt','In Bearbeitung'],['ELY-1044','Nina Muster','Renewal Serum','1','59 €','Erstattet','Storniert']],
 users:[['Lena Beispiel','lena@example.com','Partner','Partnerclub','Aktiv'],['Marie Muster','marie@example.com','Kunde','Basis','Aktiv'],['Anna Demo','anna@example.com','Partner','Partnerclub','Aktiv']],
 products:[['GHK-Cu Renewal Serum','30 ml','59 €','120','Presale'],['Balance Prepeptide Toner','100 ml','Im Set','85','Presale'],['Contour Lift Eye Cream','15 ml','Im Set','96','Presale']],
 packages:[['The Peptide Ritual Set','Serum, Toner, Eye Cream','139 €','Entwurf']],
 coupons:[['WELCOME10','10 %','31.10.2026','0','Entwurf']],
 support:[['Frage zur Auslieferung','Lena Beispiel','Hoch','Nicht zugewiesen','Offen'],['Pflege-Routine','Marie Muster','Normal','Service','In Bearbeitung']],
 'commission-network':[['Lena Beispiel','Anna Demo','ELY-1048','118 €','11,80 €','Ausstehend']],
 payouts:[['Anna Demo','125 €','Überweisung','12.09.2026','Ausstehend']],
 'grant-credits':[['Marie Muster','20 €','Kulanzgutschrift – Beispiel','Entwurf']],
 finance:[['September 2026','8.479 €','847,90 €','625 €','Beispiel']],
 'net-revenue':[['September 2026','8.479 €','1.353,79 €','59 €','7.066,21 €']],
 'profit-breakdown':[['Renewal Serum','3.540 €','900 €','354 €','2.286 €']],
 'profit-forecast':[['Basisszenario','100','10.500 €','6.300 €','4.200 €']],
 leaderboard:[['1','Anna Demo','2.780 €','Partner','Aktiv'],['2','Lena Beispiel','1.390 €','Partner','Aktiv']],
 'diamond-case':[['Pflege-Set','Produkt','5 %','10','Entwurf']],
 'diamond-club-invites':[['partner@example.com','DEMO-CLUB','31.10.2026','Entwurf']],
 events:[['ELYSERA Produkttraining','23.09.2026','Online','24','Entwurf']],
 emails:[['Entdecke deine Peptid-Routine','Alle Partner','23.09.2026','Entwurf']],
 'whatsapp-notification':[['Dein Produkttraining startet bald.','Partnerclub','23.09.2026','Entwurf']],
 'whatsapp-templates':[['Event-Erinnerung','Deutsch','Hallo {{name}}, dein Training startet am {{datum}}.','Entwurf']],
 'community-chat':[['Wie kombiniert ihr Serum und Toner?','Lena Beispiel','0','Offen']],
 faq:[['Wann startet der Presale?','Am 23. September 2026.','Bestellung','Entwurf']],
 'product-feedback':[['Renewal Serum','Lena Beispiel','5 / 5','Angenehme Textur – Beispieldaten','Offen']],
 'testimonials-reviews':[['Meine Pflege-Routine','Marie Muster','5 / 5','Entwurf']],
 'trustpilot-reviews':[['Freundlicher Service','Anna Demo','5 / 5','Noch keine Antwort','Offen']],
 'ai-studio-errors':[['Bildgenerierung #DEMO','Zeitlimit überschritten','12.09.2026, 09:42','Offen']],
 settings:[['Shopname','ELYSERA','Entwurf'],['Kontakt','service@example.com','Entwurf'],['Währung','EUR','Entwurf']]
}
