'use client'
import {useEffect,useRef,useState} from 'react'
import {orderPaymentAmount} from '../../lib/admin/order-actions-policy.mjs'
const key='elysera-bulk-paid-v1'
const money=c=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(c/100)
export const canSelectPaid=o=>['PENDING','AWAITING_BANK_TRANSFER','AWAITING_STRIPE','AWAITING_PAYPAL','AWAITING_PAY_ON_DELIVERY'].includes(o.status)&&!o.paidAt
export default function OrderBulkPaid({orders,ids,setIds,onSaved,disabled,limited}){
 const [review,setReview]=useState(null),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[results,setResults]=useState([]);const lock=useRef(false)
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved)setPending(saved)}catch{setError('Gespeicherte Sammelanfrage konnte nicht gelesen werden.')}},[])
 useEffect(()=>{setReview(null)},[ids])
 const eligible=orders.filter(canSelectPaid),all=eligible.length>0&&eligible.every(o=>ids.includes(o.id))
 function toggleAll(){setIds(all?[]:eligible.map(o=>o.id));setReview(null)}
 async function prepare(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setResults([]);setConfirmed(false);try{const rows=[];for(const id of ids){const r=await fetch('/api/admin/orders/actions?id='+encodeURIComponent(id),{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Bestellung konnte nicht geprüft werden.');if(!b.state.transitions.includes('PAID'))throw Error('Bestellung '+id+' kann nicht als bezahlt markiert werden. Auswahl bitte aktualisieren.');rows.push({state:b.state,actorId:b.actorId,cents:orderPaymentAmount(b.state)})}setReview(rows)}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 async function save(){if(lock.current)return;lock.current=true;let work=pending||review.map(({state:s,actorId,cents})=>({cents,input:{actorId,orderId:s.id,requestId:crypto.randomUUID(),expected:{xmin:s.xmin,status:s.status,version:s.version},status:'PAID',paymentReceived:true,trackingNumber:s.trackingNumber||'',trackingCarrier:s.trackingCarrier||'',note:s.note||'',reason:reason.trim()}}));
 try{sessionStorage.setItem(key,JSON.stringify(work))}catch{lock.current=false;setError('Anfragen konnten nicht sicher gespeichert werden. Es wurde nichts geändert.');return}
 setBusy(true);setPending(work);setReview(null);setError('');const done=[];
 try{while(work.length){const entry=work[0];const r=await fetch('/api/admin/orders/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(entry.input)}),b=await r.json();if(!r.ok){if([400,404].includes(r.status)||(r.status===409&&['STALE_VERSION','INVALID_TRANSITION','INVALID_PAYMENT'].includes(b.code))){work=work.slice(1);sessionStorage.setItem(key,JSON.stringify(work));setPending(work.length?work:null);setResults(v=>[...v,{id:entry.input.orderId,status:'Nicht gespeichert – erneut auswählen und prüfen'}]);setIds(v=>v.filter(id=>id!==entry.input.orderId))}throw Error(b.error||'Ergebnis noch nicht bestätigt.');}if(b.state?.id!==entry.input.orderId||!Number.isSafeInteger(b.state.version))throw Error('Antwort noch nicht bestätigt.');onSaved(b.state);done.push(entry.input.orderId);work=work.slice(1);sessionStorage.setItem(key,JSON.stringify(work));setPending(work.length?work:null);setResults(v=>[...v,{id:entry.input.orderId,status:'Gespeichert'}]);setIds(v=>v.filter(id=>id!==entry.input.orderId))}sessionStorage.removeItem(key);setConfirmed(false);setReason('')}catch(e){setError(e.message+' Die übrigen Bestellungen wurden nicht weiter verarbeitet. Dieselben gespeicherten Anfragen können erneut versucht werden.')}finally{setBusy(false);lock.current=false}}
 return <div className="ow-bulk"><div className="ow-bulk-toolbar"><label className="ow-bulk-check"><input type="checkbox" aria-label="Alle Bestellungen markieren" checked={all} disabled={disabled||busy||!!pending||!!review||!eligible.length} onChange={toggleAll}/>Alle markieren</label><span>{ids.length} ausgewählt</span><button className="ow-payment-action" disabled={disabled||busy||!!pending||!ids.length} onClick={prepare}>Auswahl als bezahlt markieren</button>{ids.length>0&&!pending&&<button disabled={busy} onClick={()=>{setIds([]);setReview(null)}}>Auswahl aufheben</button>}</div><p>Alle markieren wählt zahlungsoffene Treffer über alle Seiten aus{limited?' (innerhalb der letzten 500 Bestellungen)':''}.</p>
 {review&&<section className="ow-bulk-review" aria-label="Sammelzahlung prüfen"><h3>{review.length} Bestellungen als bezahlt markieren</h3><strong>Gesamtbetrag: {money(review.reduce((n,r)=>n+r.cents,0))}</strong><ul>{review.map(r=><li key={r.state.id}><span>{r.state.id}</span><b>{money(r.cents)}</b></li>)}</ul><label>Begründung der Sammelzahlung<textarea aria-label="Begründung der Sammelzahlung" maxLength={500} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="ow-bulk-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Ich bestätige den vollständigen Zahlungseingang für jede ausgewählte Bestellung.</label><button className="ow-payment-action" disabled={busy||!confirmed||!reason.trim()} onClick={save}>Zahlungseingänge bestätigen</button><button disabled={busy} onClick={()=>setReview(null)}>Abbrechen</button><p>Die Bestellungen werden einzeln gespeichert. Bei einem Fehler bleibt der bereits bestätigte Teil erhalten.</p></section>}
 {pending&&pending.length>0&&<div role="status"><p>{pending.length} gespeicherte Anfragen noch offen. Bitte mit demselben Administratorkonto fortsetzen.</p><button className="ow-payment-action" disabled={busy} onClick={save}>Offene Anfragen erneut versuchen</button><a href="/auth/admin">Erneut anmelden</a></div>}{busy&&<p role="status">Bestellungen werden verarbeitet …</p>}{error&&<p role="alert">{error}</p>}{results.length>0&&<p role="status">{results.filter(r=>r.status==='Gespeichert').length} Bestellungen erfolgreich gespeichert. {results.filter(r=>r.status!=='Gespeichert').map(r=>r.id+': '+r.status).join('; ')}</p>}</div>
}
