'use client'
import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {orderDetailFields,orderCategories} from '../../lib/admin/order-details-policy.mjs'
import './order-details-editor.css'
const categoryLabels={STANDARD:'Standard',URGENT:'Dringend'}
const editableKeys=['orderCategory',...Object.keys(orderDetailFields)]
const toDraft=state=>Object.fromEntries([...editableKeys.map(k=>[k,state[k]??'']),['reason','']])
export default function OrderDetailsEditor({orderId,onSaved=()=>{},actionTarget}){
 const key='elysera-order-details-request:'+orderId,initialized=useRef(false),panel=useRef(null)
 const [state,setState]=useState(null),[actor,setActor]=useState(''),[draft,setDraft]=useState(null),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[conflict,setConflict]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[authRequired,setAuthRequired]=useState(false)
 async function load(preserve=false){setBusy(true);setError('');setReview(false);try{const r=await fetch('/api/admin/orders/details?id='+encodeURIComponent(orderId),{cache:'no-store'}),body=await r.json();if(!r.ok){if(r.status===401)setAuthRequired(true);throw Error(body.error||'Stand konnte nicht geladen werden.')}setAuthRequired(false);setState(body.state);setActor(body.actorId);if(!preserve)setDraft(toDraft(body.state));setConflict(false)}catch(e){setError(e.message||'Stand konnte nicht geladen werden.')}finally{setBusy(false)}}
 useEffect(()=>{if(initialized.current)return;initialized.current=true;try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved){setPending(saved);setDraft(saved);setMessage('Eine frühere Anfrage ist noch nicht bestätigt. Nur dieselbe Anfrage wiederholen.');load(true);return}}catch{setError('Gespeicherte Anfrage nicht lesbar. Keine neue Änderung möglich.');return}load()},[])
 useEffect(()=>{const target=panel.current?.querySelector(authRequired?'.ode-auth':error?'.ode-error':review?'.ode-review':'[role="status"]'),body=panel.current?.closest('.ow-dialog-body');if(target&&body)body.scrollTo({top:body.scrollTop+target.getBoundingClientRect().top-body.getBoundingClientRect().top,behavior:'instant'})},[review,error,message,authRequired])
 function change(k,value){setDraft(d=>({...d,[k]:value}));setReview(false);setMessage('')}
 async function save(){if(busy)return;const input=pending||{actorId:actor,orderId,requestId:crypto.randomUUID(),expected:{xmin:state.xmin,status:state.status},...Object.fromEntries(editableKeys.map(k=>[k,draft[k]])),reason:draft.reason}
 try{sessionStorage.setItem(key,JSON.stringify(input))}catch{setError('Anfrage kann nicht sicher gespeichert werden. Schreiben wurde nicht gestartet.');return}
 setPending(input);setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/orders/details',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});let body;try{body=await r.json()}catch{throw Error('Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}
 if(!r.ok){if(r.status===401)setAuthRequired(true);if(r.status===409&&body.code==='STALE_VERSION'){sessionStorage.removeItem(key);setPending(null);setConflict(true);setReview(false)}else if(r.status===400||r.status===404||(r.status===409&&body.code==='INVALID_CATEGORY')){sessionStorage.removeItem(key);setPending(null);setReview(false)}throw Error(body.error||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}
 if(!body.state||body.state.id!==orderId||typeof body.state.xmin!=='string'||editableKeys.some(k=>typeof body.state[k]!=='string'))throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut versuchen.')
 sessionStorage.removeItem(key);setPending(null);setAuthRequired(false);setState(body.state);setDraft(toDraft(body.state));setReview(false);setMessage(body.replayed?'Frühere Anfrage bestätigt. Aktueller Datensatz geladen.':'Lieferdaten gespeichert und zurückgelesen.');onSaved(body.state)
 }catch(e){setError(e.message||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}finally{setBusy(false)}}
 const changes=state&&draft?editableKeys.filter(k=>draft[k].trim()!==state[k]):[]
 const controls=<div className="ode-actions">{pending?<button className="ode-primary" disabled={busy} onClick={save}>{busy?'Wird geprüft …':'Dieselbe Anfrage erneut versuchen'}</button>:conflict?<button className="ode-primary" disabled={busy} onClick={()=>load(true)}>Aktuellen Stand laden · Eingaben behalten</button>:!state?<button disabled={busy} onClick={()=>load(!!draft)}>{busy?'Stand wird geladen …':'Stand erneut laden'}</button>:<button className="ode-primary" disabled={busy||!draft?.reason?.trim()||!changes.length} onClick={()=>review?save():setReview(true)}>{busy?'Wird gespeichert …':review?'Lieferdaten jetzt speichern':'Änderung prüfen'}</button>}{review&&!pending&&!conflict&&<button disabled={busy} onClick={()=>setReview(false)}>Zurück zur Eingabe</button>}</div>
 return <section className="order-details-editor" ref={panel}><h3>Lieferdaten & interne Organisation</h3><p>Bearbeitet die Lieferadresse dieser Bestellung, ihre Priorität und den internen Administratorkommentar. Das Kundenprofil bleibt unverändert. Es werden keine Zahlungen, Bestandsänderungen oder Nachrichten ausgelöst.</p>
 {state&&<p className="ode-current">Gespeicherte Kategorie: {categoryLabels[state.orderCategory]||state.orderCategory} · Bestellstatus: {state.status}</p>}
 {draft&&<fieldset disabled={busy||!!pending||conflict}><div className="ode-fields"><label>Bestellkategorie<select aria-label="Bestellkategorie" value={draft.orderCategory} onChange={e=>change('orderCategory',e.target.value)}>{orderCategories.map(k=><option key={k} value={k}>{categoryLabels[k]}</option>)}</select></label>{Object.entries(orderDetailFields).map(([k,{label,max}])=><label className={['shippingName','shippingAddress1','shippingAddress2','adminComment'].includes(k)?'ode-wide':''} key={k}>{label}{k==='adminComment'?<textarea aria-label={label} rows={4} maxLength={max} value={draft[k]} onChange={e=>change(k,e.target.value)}/>:<input aria-label={label} maxLength={max} value={draft[k]} onChange={e=>change(k,e.target.value)}/>}</label>)}<label className="ode-wide">Begründung der Änderung<textarea aria-label="Begründung der Lieferdatenänderung" rows={2} maxLength={500} value={draft.reason} onChange={e=>change('reason',e.target.value)}/></label></div><p>Leere Felder werden als nicht erfasst gespeichert. Interne Kommentare sind nicht für Kunden bestimmt.</p></fieldset>}
 {review&&!pending&&<section className="ode-review"><h3>Änderung prüfen</h3><p>{changes.length} geänderte Felder · Bestellung {orderId}</p><dl>{changes.map(k=><div key={k}><dt>{orderDetailFields[k]?.label||'Bestellkategorie'}</dt><dd><span>Vorher: {k==='orderCategory'?categoryLabels[state[k]]:state[k]||'Nicht erfasst'}</span><strong>Neu: {k==='orderCategory'?categoryLabels[draft[k]]:draft[k].trim()||'Nicht erfasst'}</strong></dd></div>)}</dl><p><strong>Begründung:</strong> {draft.reason}</p></section>}
 {error&&<p className="ode-error" role="alert">{error}</p>}{authRequired&&<div className="ode-auth"><p>Die Anfrage bleibt gespeichert. Melde dich als ursprünglicher Administrator erneut an und öffne diese Bestellung wieder. Danach dieselbe Anfrage wiederholen.</p><a href="/auth/admin">Erneut anmelden</a></div>}{message&&<p role="status">{message}</p>}
 {actionTarget?createPortal(controls,actionTarget):controls}</section>
}
