'use client'
import {useEffect,useRef,useState} from 'react'
import './order-lookup.css'
const statusLabels={PENDING:'Ausstehend',PAID:'Bezahlt',PACKED:'Verpackt',SHIPPED:'Versendet',DELIVERED:'Zugestellt',CANCELLED:'Storniert',ISSUE:'Klärung nötig',AWAITING_BANK_TRANSFER:'Überweisung offen',AWAITING_STRIPE:'Kartenzahlung offen',AWAITING_PAY_ON_DELIVERY:'Nachnahme offen'}
export default function OrderLookup({onSelect,savedOrder}){
 const [form,setForm]=useState({q:'',status:'all',from:'',to:''}),[applied,setApplied]=useState(null),[result,setResult]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 const controller=useRef(null),attemptedPage=useRef(1)
 useEffect(()=>{if(savedOrder)setResult(current=>current?{...current,orders:current.orders.map(order=>order.id===savedOrder.id?{...order,...savedOrder}:order)}:current)},[savedOrder])
 useEffect(()=>()=>controller.current?.abort(),[])
 async function search(values=form,page=1){controller.current?.abort();const abort=new AbortController();controller.current=abort;attemptedPage.current=page;setLoading(true);setError('');setApplied({...values});try{const response=await fetch('/api/admin/orders/lookup?'+new URLSearchParams({...values,page:String(page)}),{cache:'no-store',signal:abort.signal}),body=await response.json();if(!response.ok)throw Error(body.error);setResult(body)}catch(e){if(e.name!=='AbortError')setError(e.message||'Suche fehlgeschlagen.')}finally{if(!abort.signal.aborted)setLoading(false)}}
 const changed=applied&&Object.keys(form).some(key=>form[key]!==applied[key])
 return <details className="olk-root"><summary>Gesamten Bestellbestand durchsuchen</summary><div className="olk-content"><p>Suche auch ältere ELYSERA-Bestellungen nach Nummer, Name, E-Mail, Lieferadresse oder Produkt.</p><form onSubmit={e=>{e.preventDefault();search()}}><div className="olk-query"><label>Suchbegriff<input type="search" value={form.q} maxLength={200} placeholder="Bestellnummer, Name oder E-Mail" onChange={e=>setForm({...form,q:e.target.value})}/></label><button className="olk-primary" disabled={loading}>Suchen</button></div><div className="olk-filters"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="all">Alle Status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Von (UTC)<input type="date" value={form.from} onChange={e=>setForm({...form,from:e.target.value})}/></label><label>Bis (UTC)<input type="date" value={form.to} onChange={e=>setForm({...form,to:e.target.value})}/></label></div></form>{changed&&<p className="olk-hint">Filter geändert. „Suchen“ übernimmt deine Auswahl.</p>}{loading?<p role="status">Gesamter Bestand wird durchsucht …</p>:error?<div role="alert" className="olk-error"><p>{error}</p><button onClick={()=>search(applied||form,attemptedPage.current)}>Erneut versuchen</button></div>:result&&<><div className="olk-result-title"><h2>{result.total} Treffer</h2><span>Gesamter ELYSERA-Bestand</span></div><p className="olk-applied">Angewendet: {applied.q||"Ohne Suchbegriff"} · {statusLabels[applied.status]||"Alle Status"} · {applied.from||"Offener Beginn"} bis {applied.to||"Offenes Ende"} (UTC)</p>{!result.orders.length?<p>Keine passenden Bestellungen. Passe Suchbegriff oder Filter an.</p>:<div className="olk-results">{result.orders.map(order=><button className="olk-order" key={order.id} onClick={()=>onSelect(order)}><span><strong>{[order.firstName,order.secondName].filter(Boolean).join(' ')||'Name nicht erfasst'}</strong><small>{order.id}</small><small>{new Date(order.createdAt).toLocaleDateString('de-DE',{timeZone:'UTC'})} · {statusLabels[order.status]||order.status}</small></span><span><strong>{new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(order.total)}</strong><small>Details öffnen ↗</small></span></button>)}</div>}<div className="olk-pagination"><button disabled={result.page<=1} onClick={()=>search(applied,result.page-1)}>Zurück</button><span>Seite {result.page} / {result.pages}</span><button disabled={result.page>=result.pages} onClick={()=>search(applied,result.page+1)}>Weiter</button></div></>}</div></details>
}
