'use client'
import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {orderPaymentAmount} from '../../lib/admin/order-actions-policy.mjs'
import './order-actions-editor.css'
const labels={PENDING:'Ausstehend',PAID:'Bezahlt',PACKED:'Verpackt',SHIPPED:'Versendet',DELIVERED:'Zugestellt',CANCELLED:'Storniert',ISSUE:'Klärung nötig',AWAITING_BANK_TRANSFER:'Überweisung offen',AWAITING_STRIPE:'Kartenzahlung offen',AWAITING_PAYPAL:'PayPal offen',AWAITING_PAY_ON_DELIVERY:'Nachnahme offen'}
const fields={trackingNumber:'Sendungsnummer',trackingCarrier:'Versanddienst',note:'Interne Packnotiz',reason:'Begründung der Änderung'}
export default function OrderActionsEditor({orderId,onSaved,actionTarget}){
 const key='elysera-order-request:'+orderId
 const [state,setState]=useState(null),[actor,setActor]=useState(''),[draft,setDraft]=useState(null),[pending,setPending]=useState(null),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[message,setMessage]=useState(''),[auth,setAuth]=useState(false);const initialized=useRef(false),panelRef=useRef(null)
 async function load(preserve=false){setBusy(true);setError('');setReview(false);try{const r=await fetch('/api/admin/orders/actions?id='+encodeURIComponent(orderId),{cache:'no-store'}),b=await r.json();if(!r.ok){if(r.status===401||b.code==='ACTOR_CHANGED')setAuth(true);throw Error(b.error)}setAuth(false);setState(b.state);setActor(b.actorId);if(!preserve)setDraft({status:b.state.status,trackingNumber:b.state.trackingNumber,trackingCarrier:b.state.trackingCarrier,note:b.state.note,reason:'',paymentReceived:false});setConflict(false)}catch(e){setError(e.message||'Stand konnte nicht geladen werden.')}finally{setBusy(false)}}
 useEffect(()=>{if(initialized.current)return;initialized.current=true;try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved){setPending(saved);setDraft(saved);setMessage('Eine frühere Anfrage ist noch nicht bestätigt. Nur dieselbe Anfrage wiederholen.');load(true);return}}catch{setError('Gespeicherte Anfrage nicht lesbar. Keine neue Änderung möglich.');return}load()},[])
 useEffect(()=>{const target=panelRef.current?.querySelector(error?'.ow-editor-error':review?'.ow-review':'[role="status"]');const body=panelRef.current?.closest('.ow-dialog-body');if(target&&body)body.scrollTo({top:body.scrollTop+target.getBoundingClientRect().top-body.getBoundingClientRect().top,behavior:'instant'})},[review,error,message]);
 function change(k,v){setDraft(d=>({...d,[k]:v}));setReview(false);setMessage('')}
 async function save(){if(busy)return;const input=pending||{actorId:actor,orderId,requestId:crypto.randomUUID(),expected:{xmin:state.xmin,status:state.status,version:state.version},status:draft.status,paymentReceived:draft.paymentReceived===true,...Object.fromEntries(Object.keys(fields).map(k=>[k,draft[k]]))};
 try{sessionStorage.setItem(key,JSON.stringify(input))}catch{setError('Anfrage kann nicht sicher gespeichert werden. Schreiben wurde nicht gestartet.');return}
 setPending(input);setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/orders/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});let b;try{b=await r.json()}catch{throw Error('Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}
 if(!r.ok){if(r.status===401||b.code==='ACTOR_CHANGED')setAuth(true);if(r.status===409&&b.code==='STALE_VERSION'){sessionStorage.removeItem(key);setPending(null);setConflict(true);setReview(false)}else if(r.status===400||r.status===404||(r.status===409&&['INVALID_TRANSITION','INVALID_PAYMENT'].includes(b.code))){sessionStorage.removeItem(key);setPending(null);setReview(false)}throw Error(b.error||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}
 if(!b.state||b.state.id!==orderId||!Number.isSafeInteger(b.state.version))throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut versuchen.')
 sessionStorage.removeItem(key);setPending(null);setAuth(false);setState(b.state);setDraft({status:b.state.status,trackingNumber:b.state.trackingNumber,trackingCarrier:b.state.trackingCarrier,note:b.state.note,reason:'',paymentReceived:false});setReview(false);setMessage(b.replayed?'Frühere Anfrage bestätigt. Aktueller Datensatz geladen.':'Datensatz gespeichert und zurückgelesen.');onSaved(b.state)
 }catch(e){setError(e.message||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}finally{setBusy(false)}}
 let payableCents=null;try{if(state)payableCents=orderPaymentAmount(state)}catch{}
 const amountLabel=payableCents==null?'Nicht erfasst oder nicht bestätigbar':new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(payableCents/100);
 return <section className="ow-editor" ref={panelRef}><h3>Zahlung & Versand bearbeiten</h3><p>Bestätige erhaltene Zahlungen und pflege Bestellstatus, Sendungsnummer und interne Notizen.</p>
 {state&&<p className="ow-editor-current">Aktueller Stand: {labels[state.status]||state.status} · Version {state.version}</p>}
 {state?.transitions?.includes('PAID')&&payableCents==null&&<p>Offener Zahlbetrag: {amountLabel}. Eine Zahlungsbestätigung ist erst mit gültigem Zahlbetrag möglich.</p>}
 {draft&&<>{state?.transitions?.includes('PAID')&&draft.status!=='PAID'&&<button type="button" className="ow-primary-action ow-payment-action" disabled={busy||!!pending||conflict||payableCents==null} onClick={()=>change('status','PAID')}>Als bezahlt markieren</button>}<fieldset disabled={busy||!!pending||conflict}><label>Status<select value={draft.status} onChange={e=>change('status',e.target.value)}>{[...new Set([state?.status,draft.status,...(state?.transitions||[])])].filter(Boolean).map(s=><option key={s} value={s} disabled={s==='PAID'&&state?.status!=='PAID'&&payableCents==null}>{labels[s]||s}</option>)}</select></label>{draft.status==='PAID'&&state?.status!=='PAID'&&<div className="ow-payment-confirm"><p><strong>Offener Zahlbetrag: {amountLabel}</strong></p><label className="ow-payment-checkbox"><input type="checkbox" checked={draft.paymentReceived===true} onChange={e=>change('paymentReceived',e.target.checked)}/>Ich bestätige, dass dieser Betrag vollständig eingegangen ist.</label><p>Die Zahlung wird mit dem aktuellen Zeitpunkt protokolliert. Der offene Betrag wird auf 0 € gesetzt.</p></div>}<div className="ow-editor-grid">{Object.entries(fields).map(([k,label])=><label key={k} htmlFor={"ow-edit-"+k}>{label}{['note','reason'].includes(k)?<textarea aria-label={label} id={"ow-edit-"+k} rows={k==='note'?3:2} maxLength={k==='note'?2000:500} value={draft[k]} onChange={e=>change(k,e.target.value)}/>:<input aria-label={label} id={"ow-edit-"+k} maxLength={k==='trackingNumber'?150:100} value={draft[k]} onChange={e=>change(k,e.target.value)}/>}</label>)}</div></fieldset>
 {review&&!pending&&<div className="ow-review"><strong>Änderung prüfen</strong><dl><div><dt>Status</dt><dd>{labels[state.status]} → {labels[draft.status]}</dd></div>{Object.entries(fields).map(([k,label])=><div key={k}><dt>{label}</dt><dd>{k!=='reason'&&<small>Vorher: {state[k]||'Leer'}<br/></small>}{draft[k]||'Leer'}</dd></div>)}</dl>{draft.status==='PAID'&&state.status!=='PAID'?<p><strong>Zahlungseingang: {amountLabel}</strong><br/>Zahlungsdatum: heute, {new Intl.DateTimeFormat('de-DE').format(new Date())}. Uhrzeit wird beim Speichern erfasst.</p>:<p>Speichern bestätigt diese Datensatzänderung.</p>}</div>}</>}
 {auth&&pending&&<p role="status">Deine Anfrage bleibt gespeichert. Melde dich mit demselben Administratorkonto an und wiederhole anschließend genau diese Anfrage.</p>}{error&&<p role="alert" className="ow-editor-error">{error}</p>}{message&&<p role="status">{message}</p>}
 {actionTarget&&createPortal(<div className="ow-editor-actions">{auth&&<a className="ow-primary-action" href="/auth/admin">Erneut anmelden</a>}{pending?<button className={auth?'':`ow-primary-action ${(pending?.status||draft?.status)==='PAID'?'ow-payment-action':''}`} disabled={busy} onClick={save}>{busy?'Wird geprüft …':'Dieselbe Anfrage erneut versuchen'}</button>:conflict?<button className="ow-primary-action" disabled={busy} onClick={()=>load(true)}>Aktuellen Stand laden · Eingaben behalten</button>:!state?<button disabled={busy} onClick={()=>load(!!draft)}>{busy?'Stand wird geladen …':'Stand erneut laden'}</button>:<button className={auth?'':`ow-primary-action ${(pending?.status||draft?.status)==='PAID'?'ow-payment-action':''}`} disabled={busy||auth||!draft?.reason?.trim()||(draft?.status==='PAID'&&state.status!=='PAID'&&(!draft.paymentReceived||payableCents==null))} onClick={()=>review?save():setReview(true)}>{busy?'Wird gespeichert …':review?(draft.status==='PAID'&&state.status!=='PAID'?'Zahlungseingang bestätigen':'Datensatz jetzt speichern'):'Änderung prüfen'}</button>}{review&&!pending&&!conflict&&<button disabled={busy} onClick={()=>setReview(false)}>Zurück zur Eingabe</button>}</div>,actionTarget)}</section>
}
