'use client'
import Link from 'next/link'
import {CrmLink} from '../../components/crm/CrmLink'
import LiveOverview from './live-overview'
import ShopWorkspace from './shop-workspace'
import OrdersWorkspace from './orders-workspace'
import OrderCreateWorkspace from './order-create-workspace'
import ProductMerchandisingWorkspace from './product-merchandising-workspace'
import FinanceWorkspace from './finance-workspace'
import CustomersWorkspace from './customers-workspace'
import FaqWorkspace from './faq-workspace'
import CreditsWorkspace from './credits-workspace'
import CouponsWorkspace from './coupons-workspace'
import PackagesWorkspace from './packages-workspace'
import SupportWorkspace from './support-workspace'
import ReportsWorkspace from './reports-workspace'
import PartnerWorkspace from './partner-workspace'
import EmailsWorkspace from './emails-workspace'
import FeedbackWorkspace from './feedback-workspace'
import WhatsAppWorkspace from './whatsapp-workspace'
import SettingsWorkspace from './settings-workspace'
import ProductContentWorkspace from './product-content-workspace'
import ReviewEvidenceWorkspace from '../components/review-evidence-workspace'
import ChatWorkspace from './chat-workspace'
import {useEffect,useRef,useState} from 'react'
import {DashboardIcon as Icon} from '../dashboard/design-icons'
import {modules,groups,samples} from './modules'

const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)
const financeSections=['finance','payouts','grant-credits','net-revenue','profit-breakdown','profit-forecast']
const categories=[['Übersicht','overview'],['Shop','orders'],['Partner','commission-network'],['Finanzen','finance'],['Kommunikation','emails'],['System','settings']]
function AdminNavLink(props){return String(props.href).endsWith('/crm')?<CrmLink {...props}/>:<Link {...props}/>}
function AdminLogout(){return <form action="/api/crm-auth/logout" method="post" className="ea-logout"><button type="submit">Abmelden</button></form>}
function Badge({children}){return <span className={'ea-badge '+(['Bezahlt','Aktiv','Versendet'].includes(children)?'good':['Offen','Ausstehend','Hoch'].includes(children)?'pending':'')}>{children}</span>}
function exportCSV(fields,rows,name){const escape=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\uFEFF'+[fields,...rows].map(r=>r.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='elysera-demo-'+name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function AdminPanel({section,base,initialEmailTemplateId=null,initialEmailLocale="de",initialEmailVariant="",initialProductContent=false,initialOrderCreate=false,initialProductMerchandising=false}){
 const live=base==='/admin'
 const [loadState,setLoadState]=useState('loading'),[loadError,setLoadError]=useState('')
 const module=modules.find(m=>m.id===section),[data,setData]=useState(base==='/admin'?{}:samples),[search,setSearch]=useState(''),[filter,setFilter]=useState('Alle'),[sort,setSort]=useState('new'),[page,setPage]=useState(1),[period,setPeriod]=useState('7'),[menuSearch,setMenuSearch]=useState(''),[notice,setNotice]=useState(''),[edit,setEdit]=useState(null),[ready,setReady]=useState(false)
 const menu=useRef(null),modal=useRef(null),menuTrigger=useRef(null),categoryNav=useRef(null),relatedNav=useRef(null)
 const [categoryPages,setCategoryPages]=useState([categories.slice(0,4),categories.slice(4)]),[categoryPage,setCategoryPage]=useState(0)
 useEffect(()=>{const update=()=>{const context=document.createElement('canvas').getContext('2d');context.font='12px Arial';const available=Math.min(window.innerWidth,600)-32-88;const pages=[];let page=[],used=0;for(const category of categories){const width=Math.ceil(context.measureText(category[0]).width)+14;if(page.length&&used+2+width>available){pages.push(page);page=[];used=0}used+=width+(page.length?2:0);page.push(category)}if(page.length)pages.push(page);setCategoryPages(pages)};update();window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update)},[])
 const [menuOpen,setMenuOpen]=useState(false)
 const activeCategory=section==='overview'?'overview':financeSections.includes(section)?'finance':module.group===1?'orders':module.group===2?'commission-network':module.group===3?'emails':'settings'
 useEffect(()=>{setCategoryPage(Math.max(0,categoryPages.findIndex(page=>page.some(([,id])=>id===activeCategory))))},[activeCategory,categoryPages])
 function openMenu(event){menuTrigger.current=event.currentTarget;setMenuSearch('');menu.current.showModal();setMenuOpen(true)}
 useEffect(()=>{categoryNav.current?.querySelector('[aria-current]')?.scrollIntoView({block:'nearest',inline:'nearest'});const rail=relatedNav.current,active=rail?.querySelector('[aria-current]');if(rail&&active)rail.scrollLeft=Math.max(0,active.offsetLeft-rail.offsetLeft-(rail.clientWidth-active.clientWidth)/2)},[section])
 useEffect(()=>{if(live){setReady(true);return}try{const saved=JSON.parse(localStorage.getItem('elysera-admin-ui-v1')||'null');if(saved&&typeof saved==='object')setData({...samples,...Object.fromEntries(Object.entries(saved).filter(([key,rows])=>samples[key]&&Array.isArray(rows)&&rows.every(row=>Array.isArray(row)&&row.every(v=>typeof v==='string'))))})}catch{setNotice('Gespeicherte Vorschau konnte nicht geladen werden.')}setReady(true)},[])
 useEffect(()=>{if(!ready||live)return;try{localStorage.setItem('elysera-admin-ui-v1',JSON.stringify(data))}catch{setNotice('Lokaler Speicher ist nicht verfügbar. Änderungen gelten nur bis zum Neuladen.')}},[data,ready])
 useEffect(()=>{setSearch('');setFilter('Alle');setPage(1);setEdit(null)},[section])
 useEffect(()=>{if(edit)modal.current?.showModal()},[edit])
 useEffect(()=>{if(!live||['overview','products','orders','finance','users','faq','grant-credits','coupons','packages','support','net-revenue','profit-breakdown','profit-forecast','commission-network','emails','product-feedback','whatsapp-notification','settings','trustpilot-reviews','community-chat'].includes(section))return;const controller=new AbortController();setLoadState('loading');setLoadError('');fetch('/api/admin/data/'+section,{signal:controller.signal,cache:'no-store'}).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error||'Daten konnten nicht geladen werden.');setData(prev=>({...prev,[section]:result.rows}));setLoadState('ready')}).catch(error=>{if(error.name!=='AbortError'){setLoadState('error');setLoadError(error.message)}});return()=>controller.abort()},[live,section])
 const href=id=>base+(id==='overview'?'':'/'+id)
 const rows=data[section]||[],statusIndex=module.fields.indexOf('Status'),filterIndex=statusIndex>=0?statusIndex:module.fields.indexOf('Zahlung')
 const statuses=filterIndex>=0?[...new Set(rows.map(r=>r[filterIndex]))]:[]
 let filtered=rows.map((values,index)=>({values,index})).filter(r=>r.values.join(' ').toLowerCase().includes(search.toLowerCase())&&(filter==='Alle'||r.values[filterIndex]===filter))
 if(sort==='az')filtered.sort((a,b)=>a.values[0].localeCompare(b.values[0],'de'))
 const pages=Math.max(1,Math.ceil(filtered.length/8)),current=Math.min(page,pages),visible=filtered.slice((current-1)*8,current*8)
 function openEdit(index){if(live){setNotice('Die schreibende Funktion ist noch nicht portiert.');return}setEdit({index,values:index===null?module.fields.map(f=>f==='Status'?'Entwurf':''):[...rows[index]]})}
 function save(e){e.preventDefault();setData(prev=>({...prev,[section]:edit.index===null?[edit.values,...(prev[section]||[])]:prev[section].map((r,i)=>i===edit.index?edit.values:r)}));modal.current.close();setEdit(null);setNotice('Änderung in dieser lokalen UI-Vorschau gespeichert.');setPage(1)}
 function nav(close=false){return <>{groups.map((g,i)=><div className="ea-nav-group" key={g}><span>{g}</span>{modules.filter(m=>m.group===i&&m.label.toLowerCase().includes(menuSearch.toLowerCase())).map(m=><AdminNavLink key={m.id} href={href(m.id)} aria-current={section===m.id?'page':undefined} onClick={()=>{if(close)menu.current.close()}}><Icon name={m.icon} size={19}/><span>{m.label}</span></AdminNavLink>)}</div>)}{!modules.some(m=>m.label.toLowerCase().includes(menuSearch.toLowerCase()))&&<p>Kein Bereich gefunden.</p>}</>}
 const scale=period==='30'?4:period==='90'?11:1
 return <div className="ea-app">
  <a className="ea-skip-link" href="#admin-content">Zum Inhalt springen</a>
  <div className="ea-workspace">
<header className="ea-topbar"><Link className="ea-logo" href={href('overview')}>ELYSERA<span>Luxury peptide skincare</span></Link><div className="ea-category-rail"><nav className="ea-categories" ref={categoryNav} aria-label="Kategorien">{categories.map(([label,id])=><Link key={id} href={href(id)} aria-current={activeCategory===id?(section===id?'page':'location'):undefined}>{label}</Link>)}</nav><div className="ea-category-pages"><button className="ea-category-scroll" aria-label="Vorherige Kategorien anzeigen" hidden={categoryPage===0} onClick={()=>setCategoryPage(value=>value-1)}>‹</button><nav aria-label="Mobile Kategorien">{(categoryPages[categoryPage]||categoryPages[0]).map(([label,id])=><Link key={id} href={href(id)} aria-current={activeCategory===id?(section===id?'page':'location'):undefined}>{label}</Link>)}</nav><button className="ea-category-scroll" aria-label="Weitere Kategorien anzeigen" hidden={categoryPage>=categoryPages.length-1} onClick={()=>setCategoryPage(value=>value+1)}>›</button></div></div><div className="ea-top-actions"><button className="ea-nav-search" aria-label="Alle Adminbereiche durchsuchen" aria-haspopup="dialog" aria-controls="admin-menu" aria-expanded={menuOpen} onClick={openMenu}><Icon name="menu" size={18}/><span>Bereiche suchen …</span></button><span className="ea-avatar">EA</span><span className="ea-admin-label">Team ELYSERA<small>Admin</small></span>{live&&<AdminLogout/>}</div></header>
   <main className="ea-main" id="admin-content" tabIndex={-1}>{!live&&<div className="ea-demo"><span className="ea-demo-dot"/><span>Designvorschau · Beispieldaten · Änderungen bleiben in diesem Browser.</span></div>}{section!=='overview'&&<nav className="ea-subnav" ref={relatedNav} aria-label="Verwandte Bereiche">{modules.filter(m=>m.group===module.group).map(m=><AdminNavLink key={m.id} href={href(m.id)} aria-current={section===m.id?'page':undefined}>{m.label}</AdminNavLink>)}</nav>}
    <div className="ea-page-heading" hidden={live&&['products','orders','finance','users','faq','grant-credits','coupons','packages','support','net-revenue','profit-breakdown','profit-forecast','commission-network','emails','product-feedback','whatsapp-notification','settings','trustpilot-reviews','community-chat'].includes(section)}><div><h1>{section==='overview'?'Guten Morgen, Team ELYSERA':module.label}</h1><p>{section==='overview'?'Shop, Partner und Finanzen im Überblick.':module.description}</p></div><div className="ea-heading-actions">{section==='overview'?(live?null:<label className="ea-period"><Icon name="chart" size={17}/><select aria-label="Zeitraum" value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Letzte 7 Tage</option><option value="30">Letzte 30 Tage</option><option value="90">Letzte 90 Tage</option></select></label>):<button disabled={live} className="ea-primary" onClick={()=>openEdit(null)}>+ Entwurf anlegen</button>}<button hidden={live&&section==='overview'} disabled={live&&(section==='overview'||loadState!=='ready')} onClick={()=>exportCSV(section==='overview'?['Kennzahl','Beispielwert']:module.fields,section==='overview'?[['Umsatz',String(8479*scale)],['Bestellungen',String(86*scale)],['Partner',String(24*scale)]]:filtered.map(r=>r.values),section)}>Export <Icon name="arrow" size={15}/></button></div></div>
    {notice&&<div className="ea-notice" role="status">{notice}<button aria-label="Hinweis schließen" onClick={()=>setNotice('')}>×</button></div>}
    {live&&section==='products'&&initialProductMerchandising?<ProductMerchandisingWorkspace/>:live&&section==='orders'&&initialOrderCreate?<OrderCreateWorkspace/>:live&&section==='community-chat'?<ChatWorkspace admin/>:live&&section==='trustpilot-reviews'?<ReviewEvidenceWorkspace/>:live&&section==='products'&&initialProductContent?<ProductContentWorkspace/>:live&&section==='settings'?<SettingsWorkspace/>:live&&section==='whatsapp-notification'?<WhatsAppWorkspace/>:live&&section==='product-feedback'?<FeedbackWorkspace/>:live&&section==='emails'?<EmailsWorkspace initialTemplateId={initialEmailTemplateId} initialLocale={initialEmailLocale} initialVariant={initialEmailVariant}/>:live&&section==='commission-network'?<PartnerWorkspace/>:live&&['net-revenue','profit-breakdown','profit-forecast'].includes(section)?<ReportsWorkspace section={section}/>:live&&section==='support'?<SupportWorkspace/>:live&&section==='packages'?<PackagesWorkspace/>:live&&section==='coupons'?<CouponsWorkspace/>:live&&section==='grant-credits'?<CreditsWorkspace/>:live&&section==='faq'?<FaqWorkspace/>:live&&section==='users'?<CustomersWorkspace/>:live&&section==='orders'?<OrdersWorkspace/>:live&&section==='finance'?<FinanceWorkspace/>:live&&section==='products'?<><ShopWorkspace/><Link className="ea-content-link" href="/admin/products/content">Produkttexte und Angaben bearbeiten →</Link><Link className="ea-content-link" href="/admin/products/merchandising">Kategorien und Shop-Reihenfolge bearbeiten →</Link></>:live&&section==='overview'?<LiveOverview period={period} onPeriodChange={setPeriod}/>:live&&loadState!=='ready'?<section className="ea-table-panel ea-load-panel" aria-live="polite"><Icon name={loadState==='loading'?'chart':'help'} size={30}/><h2>{loadState==='loading'?'Daten werden geladen':'Dieser Bereich wird vorbereitet'}</h2><p>{loadState==='loading'?'Deine ELYSERA-Daten werden abgerufen.':loadError}</p><Link href={href('overview')}>Zur Übersicht</Link></section>:section==='overview'?<>
     <section className="ea-kpis" aria-label="Beispielkennzahlen">{[['Umsatz',money(8479*scale),'+18,6 %','chart'],['Bestellungen',String(86*scale),'+12,4 %','bag'],['Neue Partner',String(24*scale),'+8,2 %','team'],['Offene Auszahlungen',money(625*scale),'3 Anträge','wallet']].map(([label,value,trend,icon])=><article key={label}><div><span>{label}</span><Icon name={icon} size={20}/></div><strong>{value}</strong><small className={trend.startsWith('+')?'ea-positive':''}>{trend} <span>{trend.startsWith('+')?'zum Vorzeitraum':''}</span></small></article>)}</section>
     <div className="ea-overview-grid"><section className="ea-chart-panel"><div className="ea-panel-title"><div><h2>Umsatzentwicklung</h2><p>Beispielumsatz im gewählten Zeitraum</p></div><span className="ea-legend"><i/> Umsatz</span></div><div className="ea-chart" role="img" aria-label={`Beispiel-Umsatzentwicklung über ${period} Tage, insgesamt ${money(8479*scale)}`}><div className="ea-yaxis"><span>{money(3000*scale)}</span><span>{money(2000*scale)}</span><span>{money(1000*scale)}</span><span>0 €</span></div><div className="ea-plot"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><g stroke="#e6ebf2"><path d="M0 1H700M0 73H700M0 146H700M0 219H700"/></g>{[58,83,89,119,104,132,138].map((height,i)=><rect key={i} x={18+i*99} y={220-height} width="48" height={height} rx="3" fill="#203f66"/>)}</svg><div className="ea-xaxis">{(period==='7'?['Mo','Di','Mi','Do','Fr','Sa','So']:period==='30'?['Tag 1','5','10','15','20','25','30']:['Tag 1','15','30','45','60','75','90']).map(x=><span key={x}>{x}</span>)}</div></div></div><div className="ea-chart-footer"><span>Ø Bestellwert <strong>98,59 €</strong></span><span>Erstattungen <strong>{money(59*scale)}</strong></span></div></section>
     <section className="ea-todo"><div className="ea-panel-title"><h2>Offene Aufgaben</h2><span className="ea-count">7</span></div><p>Die nächsten Schritte für dein Team.</p>{[['orders','Bestellungen prüfen','2 Zahlungen ausstehend','bag'],['payouts','Auszahlungen prüfen','3 Anträge warten auf Prüfung','wallet'],['support','Kunden unterstützen','2 offene Anfragen','help']].map(([id,title,sub,icon])=><Link key={id} href={href(id)}><span className="ea-action-icon"><Icon name={icon}/></span><span><strong>{title}</strong><small>{sub}</small></span><Icon name="arrow" size={15}/></Link>)}<div className="ea-presale"><span>Der nächste Meilenstein</span><strong>ELYSERA Presale</strong><p>23. September 2026</p><Link href={href('products')}>Sortiment vorbereiten <Icon name="arrow" size={14}/></Link></div><div className="ea-brand-card"><h2>Schönheit schafft Chancen.</h2><p>Die ELYSERA Peptid-Routine.</p><div>{["serum","toner","eye"].map(name=><img key={name} src={`/media/campaign-2026/${name}.webp`} alt=""/>)}</div><Link href={href("products")}>Zum Sortiment <Icon name="arrow" size={14}/></Link></div></section></div>
     <section className="ea-table-panel ea-recent"><div className="ea-panel-title"><div><h2>Neueste Bestellungen</h2><p>Beispielbestellungen für die UI-Vorschau</p></div><Link href={href('orders')}>Alle ansehen <Icon name="arrow" size={15}/></Link></div><div className="ea-order-cards">{data.orders.slice(0,3).map((r,i)=><Link key={i} href={href('orders')}><img src="/media/campaign-2026/serum.webp" alt=""/><div><strong>{r[0]}</strong><b>{r[1]}</b><small>{r[3]} × {r[2]}</small><Badge>{r[5]}</Badge></div><span>{r[4]}<small>{r[6]}</small></span></Link>)}</div><div className="ea-table-scroll"><table><thead><tr>{['Bestellung','Kunde / Produkt','Betrag','Zahlung','Versand',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{data.orders.slice(0,5).map((r,i)=><tr key={i}><td><strong>{r[0]}</strong><small>12. September 2026</small></td><td>{r[1]}<small>{r[3]} × {r[2]}</small></td><td>{r[4]}</td><td><Badge>{r[5]}</Badge></td><td><Badge>{r[6]}</Badge></td><td><Link aria-label={`${r[0]} in Bestellungen öffnen`} href={href('orders')}><Icon name="arrow" size={17}/></Link></td></tr>)}</tbody></table></div></section>
     <section className="ea-shortcuts"><h2>Dein Arbeitsplatz</h2><div>{[['products','Sortiment','3 Pflegeprodukte'],['commission-network','Partnernetzwerk','Empfehlungen & Provisionen'],['events','Events & Schulungen','Gemeinsam weiterentwickeln'],['finance','Finanzen','Alle Kennzahlen zusammen']].map(([id,title,sub])=><Link href={href(id)} key={id}><Icon name={modules.find(m=>m.id===id).icon}/><strong>{title}</strong><span>{sub}</span><Icon name="arrow" size={15}/></Link>)}</div></section>
    </>:<>
     {section==='products'&&!live&&<div className="ea-product-grid">{[['serum','GHK-Cu Renewal Serum','30 ml · 59 €'],['toner','Balance Prepeptide Toner','100 ml · Im Set'],['eye','Contour Lift Eye Cream','15 ml · Im Set']].map(([img,title,sub],i)=><article key={img}><img src={`/media/campaign-2026/${img}.webp`} alt={title}/><div><Badge>Presale</Badge><h2>{title}</h2><p>{sub}</p><button onClick={()=>openEdit(i)}>Produkt bearbeiten</button></div></article>)}</div>}
     <section className="ea-table-panel"><div className="ea-toolbar"><label className="ea-search"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></svg><input aria-label={`${module.label} durchsuchen`} placeholder={`${module.label} durchsuchen …`} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><div>{statuses.length>0&&<select aria-label="Status filtern" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option>Alle</option>{statuses.map(s=><option key={s}>{s}</option>)}</select>}<select aria-label="Sortierung" value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Standardreihenfolge</option><option value="az">Name A–Z</option></select></div></div>
     <div className="ea-table-scroll"><table><thead><tr>{module.fields.map(f=><th key={f}>{f}</th>)}<th>Aktion</th></tr></thead><tbody>{visible.map(({values:r,index})=><tr key={index}>{r.slice(0,module.fields.length).map((v,i)=><td key={i} data-label={module.fields[i]}>{i===filterIndex?<Badge>{v}</Badge>:v}</td>)}<td><button disabled={live} onClick={()=>openEdit(index)} aria-label={`${r[0]} bearbeiten`}>Bearbeiten</button></td></tr>)}</tbody></table></div>
     {!filtered.length&&<div className="ea-empty"><Icon name="bag" size={34}/><h2>Keine Einträge gefunden</h2><p>Passe deine Suche an oder lege einen neuen Entwurf an.</p><button onClick={()=>{setSearch('');setFilter('Alle')}}>Filter zurücksetzen</button></div>}
     <div className="ea-pagination"><span>{filtered.length} Einträge · Seite {current} von {pages}</span><div><button disabled={current<=1} onClick={()=>setPage(current-1)}>Zurück</button><button disabled={current>=pages} onClick={()=>setPage(current+1)}>Weiter</button></div></div></section><p className="ea-local-note">{live?'Echte ELYSERA-Daten. Schreibende Aktionen werden noch portiert.':'Lokale Designvorschau: Änderungen werden nur in diesem Browser gespeichert.'}</p>
    </>}
    <footer className="ea-footer"><span>ELYSERA Administration</span><span>Mit Klarheit verwalten.</span></footer>
   </main>
  </div>
  <nav className="ea-mobile-nav" aria-label="Mobile Hauptnavigation">{['overview','orders','users','finance'].map(id=><Link key={id} href={href(id)} aria-current={section===id?'page':undefined}><Icon name={modules.find(m=>m.id===id).icon} size={20}/><span>{id==='overview'?'Übersicht':id==='finance'?'Finanzen':modules.find(m=>m.id===id).label}</span></Link>)}<button onClick={openMenu} aria-label="Alle Bereiche öffnen" aria-haspopup="dialog" aria-controls="admin-menu" aria-expanded={menuOpen}><Icon name="menu" size={20}/><span>Mehr</span></button></nav>
  <dialog className="ea-menu-dialog" id="admin-menu" aria-labelledby="admin-menu-title" ref={menu} onClose={()=>{setMenuOpen(false);menuTrigger.current?.focus()}} onClick={e=>{if(e.target===e.currentTarget)menu.current.close()}}><div><div className="ea-panel-title"><h2 id="admin-menu-title">Alle Bereiche</h2><button aria-label="Menü schließen" onClick={()=>menu.current.close()}>×</button></div><input autoFocus aria-label="Bereiche suchen" placeholder="Bereich suchen …" value={menuSearch} onChange={e=>setMenuSearch(e.target.value)}/>{live&&<AdminLogout/>}<nav aria-label="Alle Adminbereiche">{nav(true)}</nav><Link href="/">Zum Shop</Link></div></dialog>
  <dialog className="ea-edit-dialog" ref={modal} onClose={()=>setEdit(null)}>{edit&&<form onSubmit={save}><div className="ea-panel-title"><h2>{edit.index===null?'Entwurf anlegen':'Eintrag bearbeiten'}</h2><button type="button" aria-label="Dialog schließen" onClick={()=>modal.current.close()}>×</button></div><p>Änderungen gelten nur für diese Designvorschau.</p><div className="ea-fields">{module.fields.map((f,i)=><label key={f}>{f}{['Nachricht','Antwort','Feedback','Beitrag','Grund'].includes(f)?<textarea required value={edit.values[i]} onChange={e=>setEdit({...edit,values:edit.values.map((v,j)=>j===i?e.target.value:v)})}/>:<input required type={f==='E-Mail'?'email':'text'} value={edit.values[i]} onChange={e=>setEdit({...edit,values:edit.values.map((v,j)=>j===i?e.target.value:v)})}/>}</label>)}</div><div className="ea-dialog-actions"><button type="button" onClick={()=>modal.current.close()}>Abbrechen</button><button className="ea-primary" type="submit">Lokal speichern</button></div></form>}</dialog>
 </div>
}
