'use client'
import {useEffect,useMemo,useRef,useState} from 'react'
import {partnerIndex,partnerView} from '@/lib/admin/partners-policy.mjs'
import './partner-workspace.css'
import CustomerImpersonation from './customer-impersonation'
const name=p=>[p.firstName,p.secondName].filter(Boolean).join(' ')||p.email||'ELYSERA-Profil'
const status={active:'Aktiv',paused:'Pausiert',unconfigured:'Nicht eingerichtet'}
const money=n=>n==null?'Unbekannt':Number(n).toLocaleString('de-DE',{style:'currency',currency:'EUR'})
const loginDate=n=>n?new Date(n).toLocaleString('de-DE',{timeZone:'Europe/Berlin',dateStyle:'medium',timeStyle:'short'})+' Uhr (Berlin)':'Noch kein Login erfasst'
const date=n=>n?new Date(n).toLocaleDateString('de-DE',{timeZone:'Europe/Berlin'}):'Datum unbekannt'
const items=rows=>(rows||[]).map(i=>`${i.quantity} × ${i.name}`).join(' · ')||'Keine Produktangaben'
async function get(url,signal){const r=await fetch(url,{cache:'no-store',signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Partnerdaten nicht verfügbar.');return d}
export default function PartnerWorkspace(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[view,setView]=useState('list'),[focus,setFocus]=useState(null),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(''),[retry,setRetry]=useState(0),[detailRetry,setDetailRetry]=useState(0);const dialog=useRef(null),opener=useRef(null)
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');get('/api/admin/partners',controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry])
 useEffect(()=>{if(!selected)return;const controller=new AbortController();setDetail(null);setDetailError('');if(!dialog.current.open)dialog.current.showModal();get(`/api/admin/partners?id=${encodeURIComponent(selected.id)}`,controller.signal).then(setDetail).catch(e=>{if(e.name!=='AbortError')setDetailError(e.message)});return()=>controller.abort()},[selected,detailRetry])
 const partners=data?.partners||[],index=useMemo(()=>partnerIndex(data?.partners||[]),[data]),{lookup,children,descendants}=index,configured=partners.filter(p=>p.partnerStatus!=='unconfigured');
 const {visible,rows,pages,current,global}=partnerView(partners,{view,focus,search,filter,page}),anchor=lookup.get(focus);
 const path=anchor&&!anchor.relationshipConflict?[...(anchor.ancestors||[])].reverse().map(id=>lookup.get(id)).filter(Boolean).concat(anchor):[];
 function branch(id){setFocus(id);setView('network');setSearch('');setFilter('all');setPage(1)}
 function change(fn){fn();setPage(1)}
 function openDetail(p,event){opener.current=event.currentTarget;setSelected(p)}

 function close(){dialog.current?.close();setSelected(null);setDetail(null);opener.current?.focus()}
 return <section className="pn-workspace" aria-label="ELYSERA Provisionsnetzwerk"><header className="pn-heading"><div><h1>Provisionsnetzwerk</h1><p>ELYSERA-Profile, eigene Zuordnungen und belegte Provisionen.</p></div><button className="pn-refresh" aria-label="Aktualisieren" title="Aktualisieren" onClick={()=>setRetry(v=>v+1)} disabled={loading}><span className="pn-refresh-label">Aktualisieren</span><span className="pn-refresh-icon" aria-hidden="true">↻</span></button></header>
 <div className="pn-metrics"><article><span>ELYSERA-Profile</span><strong>{loading||error?'—':partners.length}</strong></article><article><span>Partner eingerichtet</span><strong>{loading||error||!data?.relationshipsReady?'—':configured.length}</strong></article><article><span>Eigene Zuordnungen</span><strong>{loading||error||!data?.relationshipsReady?'—':partners.filter(p=>p.parentId&&!p.relationshipConflict).length}</strong></article><article><span>Auszahlungsbetrag</span><strong>—</strong><small>Nicht angebunden</small></article></div>
 <details className="pn-disclosure"><summary>Hinweise zu Zuordnung und Provisionen</summary><p>Eigene Zuordnungen steuern derzeit keine Provisionsberechnung. Beträge im Detail sind vorhandene Belege ausschließlich aus ELYSERA-Bestellungen; sie sind kein auszahlbarer Gesamtsaldo.</p></details>
 {!loading&&!error&&!data?.relationshipsReady&&<p className="pn-note">Partnerzuordnungen sind noch nicht eingerichtet. Die vorhandenen ELYSERA-Konten bleiben sichtbar.</p>}
 <div className="pn-toolbar"><label>Profile suchen<input type="search" placeholder="Name, E-Mail oder Profilnummer" value={search} onChange={e=>change(()=>setSearch(e.target.value))}/></label><label>Partnerstatus<select value={filter} onChange={e=>change(()=>setFilter(e.target.value))}><option value="all">Alle Profile</option>{Object.entries(status).map(([key,label])=><option key={key} value={key}>{label}</option>)}<option value="conflict">Zuordnungskonflikte</option></select></label><div className="pn-switch"><button aria-pressed={view==='list'} onClick={()=>change(()=>setView('list'))}>Liste</button><button aria-pressed={view==='network'} onClick={()=>branch(null)}>Hierarchie</button></div></div>
 {!loading&&!error&&view==='network'&&<nav className="pn-path" aria-label="Position im Referral-Baum"><button onClick={()=>branch(null)}>Alle Wurzelkonten</button>{path.map(p=><button key={p.id} aria-current={p.id===focus?'location':undefined} onClick={()=>branch(p.id)}>{name(p)}</button>)}</nav>}
 {!loading&&!error&&view==='network'&&<p className="pn-context">{global?'Such- und Filterergebnisse aus dem gesamten Netzwerk.':anchor?'Direkte Empfehlungen von '+name(anchor):'Wurzelkonten sowie Profile ohne auswertbare Zuordnung.'}</p>}
 {loading?<div className="pn-empty" role="status">Partnerdaten werden geladen …</div>:error?<div className="pn-empty" role="alert"><h3>Laden nicht möglich</h3><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>Erneut versuchen</button></div>:!visible.length?<div className="pn-empty"><h3>{view==='network'&&anchor&&!global?'Keine direkten Empfehlungen':partners.length?'Keine passenden Profile':'Noch keine ELYSERA-Profile'}</h3><p>{view==='network'&&anchor&&!global?'Über die Navigation kannst du zum übergeordneten Konto wechseln.':partners.length?'Suche oder Statusfilter anpassen.':'Neue ELYSERA-Konten erscheinen hier automatisch.'}</p></div>:<><div className="pn-list">{rows.map(p=><article className="pn-row" key={p.id}><div className="pn-identity"><h3>{name(p)}</h3><p>{p.email}</p>{<p>{p.relationshipConflict?'Zuordnungskonflikt – Hierarchie nicht verfügbar':p.parentId?`Direkt zugeordnet: ${name(lookup.get(p.parentId)||{})} · Tiefe ${p.ancestors.length}`:'Keine übergeordnete Zuordnung'}</p>}</div><span className="pn-badge">{p.relationshipConflict?'Zuordnungskonflikt':status[p.partnerStatus]||'Unbekannt'}</span><div className="pn-row-actions">{!p.relationshipConflict&&<button aria-label={'Empfehlungen von '+name(p)+' öffnen'} onClick={()=>branch(p.id)}>{(children.get(p.id)||[]).length} direkte · {descendants.get(p.id)||0} im Team</button>}<button aria-label={`Partner ${name(p)} ansehen`} onClick={e=>openDetail(p,e)}>Details ansehen</button></div></article>)}</div><footer className="pn-pagination"><span>{visible.length} Profile · Seite {current} von {pages}</span><div><button aria-label="Vorherige Partnerseite" disabled={current===1} onClick={()=>setPage(current-1)}>Zurück</button><button aria-label="Nächste Partnerseite" disabled={current===pages} onClick={()=>setPage(current+1)}>Weiter</button></div></footer></>}
 <dialog ref={dialog} className="pn-dialog" aria-labelledby="pn-detail-title" onCancel={e=>{e.preventDefault();close()}} onClose={()=>{setSelected(null);opener.current?.focus()}}>{selected&&<><header className="pn-dialoghead"><div><h2 id="pn-detail-title">{name(selected)}</h2><p>{selected.email}</p></div><button onClick={close}>Schließen</button></header><div className="pn-dialogbody">{detailError?<div role="alert"><p>{detailError}</p><button onClick={()=>setDetailRetry(v=>v+1)}>Erneut versuchen</button></div>:!detail?<p role="status">Profildetails werden geladen …</p>:<><div className="pn-profile"><h3>ELYSERA-Zuordnung</h3><p>Profilnummer: {detail.partner.id}</p><p>Erster Login: {loginDate(detail.partner.firstLoginAt)}</p><p><a href={"/admin/users?q="+encodeURIComponent(detail.partner.id)}>Kundenprofil mit Kontaktangaben öffnen</a></p><p>Status: {status[detail.partner.partnerStatus]||'Unbekannt'}</p><p>{detail.partner.relationshipConflict?'Zuordnungskonflikt: Die Hierarchie wird nicht ausgewertet.':detail.partner.parentId?`Übergeordnet: ${name(lookup.get(detail.partner.parentId)||{})}`:'Keine übergeordnete Zuordnung eingerichtet.'}</p><p>Direkte Empfehlungen: {(children.get(detail.partner.id)||[]).length} · Gesamtes Team: {descendants.get(detail.partner.id)||0}</p>{!detail.partner.relationshipConflict&&<button onClick={()=>{close();branch(detail.partner.id)}}>Partnerstruktur öffnen</button>}<small>Diese Ansicht ist schreibgeschützt. Provisionen und Rangansprüche werden daraus nicht berechnet.</small></div><CustomerImpersonation customerId={detail.partner.id}/><h3>Provisionsbelege</h3><p>Nur Belege für ELYSERA-Käuferprofile und vollständig eigene Produktbestellungen.</p>{detail.commissionsLimited&&<p>Die neuesten 100 Belege werden angezeigt.</p>}{detail.commissions.length?detail.commissions.map(c=><article className="pn-evidence" key={c.id}><header><strong>{money(c.amount)}</strong><span>{c.status} · Ebene {c.level}</span></header><p>{date(c.createdAt)} · {name(c)}</p><p>{items(c.items)}</p><p>Bestellung {c.orderId} · {money(c.orderTotal)} · {c.orderStatus}</p><small>{c.convertedToCredits?'Als Credits umgewandelt':'Nicht als Credits umgewandelt'} · Beleg {c.id}</small></article>):<p className="pn-note">Keine passenden Provisionsbelege vorhanden.</p>}<h3>Eigene Bestellungen</h3>{detail.ordersLimited&&<p>Die neuesten 100 Bestellungen werden angezeigt.</p>}{detail.orders.length?detail.orders.map(o=><article key={o.id} className="pn-evidence"><header><strong>{money(o.total)}</strong><span>{o.status}</span></header><p>{date(o.createdAt)} · {o.id}</p><p>{items(o.items)}</p></article>):<p className="pn-note">Keine vollständig eigenen ELYSERA-Bestellungen vorhanden.</p>}</>}</div></>}</dialog>
 </section>
}
