'use client'
import {useEffect,useRef,useState} from 'react'
import './partner-workspace.css'
const name=p=>[p.firstName,p.secondName].filter(Boolean).join(' ')||p.email||'ELYSERA-Profil'
const status={active:'Aktiv',paused:'Pausiert',unconfigured:'Nicht eingerichtet'}
const money=n=>n==null?'Unbekannt':Number(n).toLocaleString('de-DE',{style:'currency',currency:'EUR'})
const date=n=>n?new Date(n).toLocaleDateString('de-DE'):'Datum unbekannt'
const items=rows=>(rows||[]).map(i=>`${i.quantity} × ${i.name}`).join(' · ')||'Keine Produktangaben'
async function get(url,signal){const r=await fetch(url,{cache:'no-store',signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Partnerdaten nicht verfügbar.');return d}
export default function PartnerWorkspace(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[view,setView]=useState('list'),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(''),[retry,setRetry]=useState(0),[detailRetry,setDetailRetry]=useState(0);const dialog=useRef(null),opener=useRef(null)
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');get('/api/admin/partners',controller.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry])
 useEffect(()=>{if(!selected)return;const controller=new AbortController();setDetail(null);setDetailError('');if(!dialog.current.open)dialog.current.showModal();get(`/api/admin/partners?id=${encodeURIComponent(selected.id)}`,controller.signal).then(setDetail).catch(e=>{if(e.name!=='AbortError')setDetailError(e.message)});return()=>controller.abort()},[selected,detailRetry])
 const partners=data?.partners||[],lookup=new Map(partners.map(p=>[p.id,p])),visible=partners.filter(p=>(filter==='all'||p.partnerStatus===filter)&&`${name(p)} ${p.email} ${p.id}`.toLowerCase().includes(search.toLowerCase())),configured=partners.filter(p=>p.partnerStatus!=='unconfigured');
 function close(){dialog.current?.close();setSelected(null);setDetail(null);opener.current?.focus()}
 return <section className="pn-workspace" aria-label="ELYSERA Provisionsnetzwerk"><header className="pn-heading"><div><h2>Provisionsnetzwerk</h2><p>ELYSERA-Profile, eigene Zuordnungen und belegte Provisionen.</p></div><button className="pn-refresh" aria-label="Aktualisieren" title="Aktualisieren" onClick={()=>setRetry(v=>v+1)} disabled={loading}><span className="pn-refresh-label">Aktualisieren</span><span className="pn-refresh-icon" aria-hidden="true">↻</span></button></header>
 <div className="pn-metrics"><article><span>ELYSERA-Profile</span><strong>{loading||error?'—':partners.length}</strong></article><article><span>Partner eingerichtet</span><strong>{loading||error||!data?.relationshipsReady?'—':configured.length}</strong></article><article><span>Eigene Zuordnungen</span><strong>{loading||error||!data?.relationshipsReady?'—':partners.filter(p=>p.parentId&&!p.relationshipConflict).length}</strong></article><article><span>Auszahlungsbetrag</span><strong>—</strong><small>Nicht angebunden</small></article></div>
 <details className="pn-disclosure"><summary>Hinweise zu Zuordnung und Provisionen</summary><p>Eigene Zuordnungen steuern derzeit keine Provisionsberechnung. Beträge im Detail sind vorhandene Belege ausschließlich aus ELYSERA-Bestellungen; sie sind kein auszahlbarer Gesamtsaldo.</p></details>
 {!loading&&!error&&!data?.relationshipsReady&&<p className="pn-note">Partnerzuordnungen sind noch nicht eingerichtet. Die vorhandenen ELYSERA-Konten bleiben sichtbar.</p>}
 <div className="pn-toolbar"><label>Profile suchen<input type="search" placeholder="Name, E-Mail oder Profilnummer" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Partnerstatus<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Alle Profile</option>{Object.entries(status).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="pn-switch"><button aria-pressed={view==='list'} onClick={()=>setView('list')}>Liste</button><button aria-pressed={view==='network'} onClick={()=>setView('network')}>Hierarchie</button></div></div>
 {loading?<div className="pn-empty" role="status">Partnerdaten werden geladen …</div>:error?<div className="pn-empty" role="alert"><h3>Laden nicht möglich</h3><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>Erneut versuchen</button></div>:!visible.length?<div className="pn-empty"><h3>{partners.length?'Keine passenden Profile':'Noch keine ELYSERA-Profile'}</h3><p>{partners.length?'Suche oder Statusfilter anpassen.':'Neue ELYSERA-Konten erscheinen hier automatisch. Partnerzuordnungen benötigen eine gesonderte Einrichtung.'}</p></div>:<div className="pn-list">{visible.map(p=><article className="pn-row" key={p.id}><div className="pn-identity"><h3>{name(p)}</h3><p>{p.email}</p>{view==='network'&&<p>{p.relationshipConflict?'Zuordnungskonflikt – Hierarchie nicht verfügbar':p.parentId?`Direkt zugeordnet: ${name(lookup.get(p.parentId)||{})} · Tiefe ${p.ancestors.length}`:'Keine übergeordnete Zuordnung'}</p>}</div><span className="pn-badge">{p.relationshipConflict?'Zuordnungskonflikt':status[p.partnerStatus]||'Unbekannt'}</span><button aria-label={`Partner ${name(p)} ansehen`} onClick={e=>{opener.current=e.currentTarget;setSelected(p)}}>Details ansehen</button></article>)}</div>}
 <dialog ref={dialog} className="pn-dialog" aria-labelledby="pn-detail-title" onCancel={e=>{e.preventDefault();close()}} onClose={()=>{setSelected(null);opener.current?.focus()}}>{selected&&<><header className="pn-dialoghead"><div><h2 id="pn-detail-title">{name(selected)}</h2><p>{selected.email}</p></div><button onClick={close}>Schließen</button></header><div className="pn-dialogbody">{detailError?<div role="alert"><p>{detailError}</p><button onClick={()=>setDetailRetry(v=>v+1)}>Erneut versuchen</button></div>:!detail?<p role="status">Profildetails werden geladen …</p>:<><div className="pn-profile"><h3>ELYSERA-Zuordnung</h3><p>Status: {status[detail.partner.partnerStatus]||'Unbekannt'}</p><p>{detail.partner.relationshipConflict?'Zuordnungskonflikt: Die Hierarchie wird nicht ausgewertet.':detail.partner.parentId?`Übergeordnet: ${name(lookup.get(detail.partner.parentId)||{})}`:'Keine übergeordnete Zuordnung eingerichtet.'}</p><small>Diese Ansicht ist schreibgeschützt. Provisionen und Rangansprüche werden daraus nicht berechnet.</small></div><h3>Provisionsbelege</h3><p>Nur Belege für ELYSERA-Käuferprofile und vollständig eigene Produktbestellungen.</p>{detail.commissionsLimited&&<p>Die neuesten 100 Belege werden angezeigt.</p>}{detail.commissions.length?detail.commissions.map(c=><article className="pn-evidence" key={c.id}><header><strong>{money(c.amount)}</strong><span>{c.status} · Ebene {c.level}</span></header><p>{date(c.createdAt)} · {name(c)}</p><p>{items(c.items)}</p><p>Bestellung {c.orderId} · {money(c.orderTotal)} · {c.orderStatus}</p><small>{c.convertedToCredits?'Als Credits umgewandelt':'Nicht als Credits umgewandelt'} · Beleg {c.id}</small></article>):<p className="pn-note">Keine passenden Provisionsbelege vorhanden.</p>}<h3>Eigene Bestellungen</h3>{detail.ordersLimited&&<p>Die neuesten 100 Bestellungen werden angezeigt.</p>}{detail.orders.length?detail.orders.map(o=><article key={o.id} className="pn-evidence"><header><strong>{money(o.total)}</strong><span>{o.status}</span></header><p>{date(o.createdAt)} · {o.id}</p><p>{items(o.items)}</p></article>):<p className="pn-note">Keine vollständig eigenen ELYSERA-Bestellungen vorhanden.</p>}</>}</div></>}</dialog>
 </section>
}
