'use client'
import {useEffect,useRef,useState} from 'react'
import {productContentFields} from '../../lib/product-content.mjs'
import './product-content-workspace.css'
const draftOf=p=>({...p.content,ingredients:p.content.ingredients.join('\n'),reason:''})
const contentOf=d=>Object.fromEntries(Object.keys(productContentFields).map(k=>[k,k==='ingredients'?d[k].split('\n').map(v=>v.trim()).filter(Boolean):d[k].trim()]))
export default function ProductContentWorkspace(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null)
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/admin/product-content',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Produkttexte nicht verfügbar.');setData(b)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 function saved(product){setData(d=>({...d,products:d.products.map(p=>p.id===product.id?product:p)}));setSelected(product)}
 return <section className="product-content-workspace"><header className="pcw-heading"><div><span>Shop · Öffentliche Inhalte</span><h1>Produkttexte</h1><p>Produktnamen, Beschreibungen und Pflegehinweise der drei bestehenden Produkte.</p></div><button onClick={load} disabled={loading} aria-label="Produkttexte aktualisieren">Aktualisieren</button></header>
 <div className="pcw-summary"><span>{loading?'Wird geladen …':error?'Daten nicht verfügbar':`${data?.products.length??0} bestehende Produkte`}</span><span>Änderungen werden öffentlich sichtbar</span></div>
 {loading?<div className="pcw-state" role="status">Produkttexte werden geladen …</div>:error?<div className="pcw-state" role="alert"><h2>Laden nicht möglich</h2><p>{error}</p><button onClick={load}>Erneut versuchen</button><a href="/auth/admin">Administrator-Anmeldung</a></div>:<div className="pcw-products">{data?.products.map(product=><article key={product.id}><img src={product.image} alt=""/><div><span className="pcw-source">{product.version===0?'Originaltext · Noch nicht geändert':`Gespeichert · Version ${product.version}`}</span><h2>{product.content.name}</h2><p>{product.content.volume} · {product.content.format}</p><p className="pcw-erp">Interner Produktname: {product.erpName||'Nicht verfügbar'}</p></div><button onClick={()=>setSelected(product)} aria-label={product.content.short+' Texte bearbeiten'}>Texte bearbeiten</button></article>)}</div>}
 <p className="pcw-note">Der öffentliche Produktname ist unabhängig vom internen Produktnamen. Bilder, Produkt-URLs, Reihenfolge, Preise und Bestände werden hier nicht bearbeitet.</p>
 {selected&&<ContentDialog key={selected.id} product={selected} close={()=>setSelected(null)} onSaved={saved}/>}</section>
}
function ContentDialog({product,close,onSaved}){
 const dialog=useRef(null),bodyRef=useRef(null),initialized=useRef(false),key='elysera-product-content-request:'+product.id
 const [state,setState]=useState(null),[actor,setActor]=useState(''),[draft,setDraft]=useState(null),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[conflict,setConflict]=useState(false),[auth,setAuth]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function load(preserve=false){setBusy(true);setError('');setReview(false);try{const r=await fetch('/api/admin/product-content',{cache:'no-store'}),b=await r.json();if(!r.ok){if(r.status===401)setAuth(true);throw Error(b.error||'Stand konnte nicht geladen werden.')};const p=b.products.find(p=>p.id===product.id);if(!p)throw Error('ELYSERA-Produkt nicht gefunden.');setState(p);setActor(b.actorId);setAuth(false);if(!preserve)setDraft(draftOf(p));setConflict(false)}catch(e){setError(e.message||'Stand konnte nicht geladen werden.')}finally{setBusy(false)}}
 useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();if(!initialized.current){initialized.current=true;try{const stored=JSON.parse(sessionStorage.getItem(key)||'null');if(stored){setPending(stored);setDraft({...stored.content,ingredients:stored.content.ingredients.join('\n'),reason:stored.reason});setMessage('Eine frühere Anfrage ist noch nicht bestätigt. Nur dieselbe Anfrage wiederholen.');load(true)}else load()}catch{setError('Gespeicherte Anfrage nicht lesbar. Keine neue Änderung möglich.')}}return()=>previous?.focus()},[])
 useEffect(()=>{const body=bodyRef.current,target=body?.querySelector(auth?'.pcw-auth':error?'.pcw-error':review?'.pcw-review':'[role="status"]');if(target&&body)body.scrollTo({top:body.scrollTop+target.getBoundingClientRect().top-body.getBoundingClientRect().top,behavior:'instant'})},[review,error,message,auth])
 function change(key,value){setDraft(d=>({...d,[key]:value}));setReview(false);setMessage('')}
 async function save(){if(busy)return;const input=pending||{actorId:actor,productId:product.id,requestId:crypto.randomUUID(),expectedVersion:state.version,expectedSnapshot:state.snapshot,content:contentOf(draft),reason:draft.reason}
 try{sessionStorage.setItem(key,JSON.stringify(input))}catch{setError('Anfrage kann nicht sicher gespeichert werden. Schreiben wurde nicht gestartet.');return}
 setPending(input);setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/product-content',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});let b;try{b=await r.json()}catch{throw Error('Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}
 if(!r.ok){if(r.status===401)setAuth(true);if(r.status===409&&b.code==='STALE_VERSION'){sessionStorage.removeItem(key);setPending(null);setConflict(true);setReview(false)}else if(r.status===400||r.status===404){sessionStorage.removeItem(key);setPending(null);setReview(false)}throw Error(b.error||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}
 if(!b.product||b.product.id!==product.id||!Number.isSafeInteger(b.product.version)||typeof b.product.snapshot!=='string'||!Array.isArray(b.product.content?.ingredients))throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut versuchen.')
 sessionStorage.removeItem(key);setPending(null);setState(b.product);setDraft(draftOf(b.product));setAuth(false);setReview(false);setMessage(b.replayed?'Frühere Veröffentlichung bestätigt. Aktueller Stand geladen.':'Produkttexte gespeichert und zurückgelesen.');onSaved(b.product)
 }catch(e){setError(e.message||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}finally{setBusy(false)}}
 const changed=state&&draft?Object.keys(productContentFields).filter(k=>JSON.stringify(contentOf(draft)[k])!==JSON.stringify(state.content[k])):[]
 const valid=draft&&Object.keys(productContentFields).every(k=>k==='ingredients'?contentOf(draft).ingredients.length>0:!!draft[k].trim())
 return <dialog ref={dialog} className="pcw-dialog" aria-labelledby="pcw-title" onCancel={e=>{e.preventDefault();close()}}><header><div><span>Öffentliche Produkttexte</span><h2 id="pcw-title">{product.content.short}</h2></div><button aria-label="Produkttexte schließen" onClick={close}>×</button></header><div className="pcw-dialog-body" ref={bodyRef}>
 <p className="pcw-identity">Interner Produktname: {state?.erpName??product.erpName??'Nicht verfügbar'}</p><p>Der öffentliche Name kann kürzer sein. Der interne Produktdatensatz wird nicht umbenannt.</p>{state&&<p className="pcw-source">{state.version===0?'Unveränderte Originaltexte aus dem Katalog':`Gespeicherte Texte · Version ${state.version}`}</p>}
 {draft&&<fieldset disabled={busy||!!pending||conflict}><div className="pcw-fields">{Object.entries(productContentFields).map(([key,{label,max}])=><label key={key} className={['volume','format'].includes(key)?'':'pcw-wide'}>{label}{['description','use','texture','ingredients','delivery'].includes(key)?<textarea aria-label={label} rows={key==='ingredients'?5:key==='description'?4:3} maxLength={key==='ingredients'?4840:max} value={draft[key]} onChange={e=>change(key,e.target.value)}/>:<input aria-label={label} maxLength={max} value={draft[key]} onChange={e=>change(key,e.target.value)}/>}<small>{key==='ingredients'?'Ein Wirkstoff pro Zeile · 1–40 Einträge, je maximal 120 Zeichen':`Maximal ${max} Zeichen`}</small></label>)}<label className="pcw-wide">Begründung der Änderung<textarea aria-label="Begründung der Textänderung" rows={2} maxLength={500} value={draft.reason} onChange={e=>change('reason',e.target.value)}/></label></div></fieldset>}
 {review&&!pending&&<section className="pcw-review"><h3>Veröffentlichung prüfen</h3><p>{changed.length} geänderte Felder. Nach dem Speichern werden diese Texte öffentlich verwendet.</p><dl>{changed.map(k=><div key={k}><dt>{productContentFields[k].label}</dt><dd><span>Vorher: {Array.isArray(state.content[k])?state.content[k].join(' · '):state.content[k]}</span><strong>Neu: {Array.isArray(contentOf(draft)[k])?contentOf(draft)[k].join(' · '):contentOf(draft)[k]}</strong></dd></div>)}</dl><p><strong>Begründung:</strong> {draft.reason}</p></section>}
 {error&&<p className="pcw-error" role="alert">{error}</p>}{auth&&<div className="pcw-auth"><p>Die Anfrage bleibt gespeichert. Melde dich als ursprünglicher Administrator erneut an und öffne diese Produkttexte wieder. Danach dieselbe Anfrage wiederholen.</p></div>}{message&&<p role="status">{message}</p>}
 </div><footer><div className="pcw-actions">{auth&&<a className="pcw-primary" href="/auth/admin">Erneut anmelden</a>}{pending?<button className={auth?"":"pcw-primary"} disabled={busy} onClick={save}>{busy?'Wird geprüft …':'Dieselbe Anfrage erneut versuchen'}</button>:conflict?<button className="pcw-primary" disabled={busy} onClick={()=>load(true)}>Aktuellen Stand laden · Eingaben behalten</button>:!state?<button disabled={busy} onClick={()=>load(!!draft)}>{busy?'Stand wird geladen …':'Stand erneut laden'}</button>:<button className="pcw-primary" disabled={busy||!valid||!draft.reason.trim()||!changed.length} onClick={()=>review?save():setReview(true)}>{busy?'Wird gespeichert …':review?'Produkttexte veröffentlichen':'Änderung prüfen'}</button>}{review&&!pending&&!conflict&&<button disabled={busy} onClick={()=>setReview(false)}>Zurück zur Eingabe</button>}</div><button onClick={close}>Schließen</button></footer></dialog>
}
