'use client'
import {useEffect,useState} from 'react'
import {merchandisingCategories,merchandisingNames,merchandisingIds,validateMerchandising} from '../../lib/product-merchandising.mjs'
import './product-merchandising-workspace.css'
const storageKey='elysera-merchandising-pending'
export default function ProductMerchandisingWorkspace(){const [state,setState]=useState(null),[actor,setActor]=useState(''),[draft,setDraft]=useState(null),[reason,setReason]=useState(''),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[conflict,setConflict]=useState(false),[auth,setAuth]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 async function load(preserve=false,restored=null){setBusy(true);setError('');setReview(false);try{const r=await fetch('/api/admin/product-merchandising',{cache:'no-store'}),b=await r.json();if(!r.ok){if(r.status===401)setAuth(true);throw Error(b.error||'Stand konnte nicht geladen werden.')};validateMerchandising(b.state.products);setState(b.state);setActor(b.actorId);setAuth(!!((restored||pending)&&(restored||pending).actorId!==b.actorId));if(!preserve)setDraft(b.state.products);setConflict(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(saved){validateMerchandising(saved.products);setPending(saved);setDraft(saved.products);setReason(saved.reason);setNotice('Eine frühere Anfrage ist noch nicht bestätigt. Wiederhole genau diese Anfrage.');load(true,saved)}else load()}catch{setError('Gespeicherte Anfrage nicht lesbar. Schreiben wurde gesperrt.')}},[])
 function change(id,key,value){setDraft(rows=>{const old=rows.find(p=>p.id===id);return rows.map(p=>p.id===id?{...p,[key]:value}:key==='displayOrder'&&p.displayOrder===value?{...p,displayOrder:old.displayOrder}:p)});setReview(false);setNotice('')}
 async function save(){if(busy)return;const input=pending||{actorId:actor,requestId:crypto.randomUUID(),expectedVersion:state.version,expectedSnapshot:state.snapshot,products:validateMerchandising(draft),reason:reason.trim()};try{sessionStorage.setItem(storageKey,JSON.stringify(input))}catch{setError('Anfrage kann nicht sicher gespeichert werden. Schreiben wurde nicht gestartet.');return}setPending(input);setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/product-merchandising',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),b=await r.json();if(!r.ok){if(r.status===401||b.code==='ACTOR_CHANGED')setAuth(true);if(r.status===409&&b.code==='STALE_VERSION'){sessionStorage.removeItem(storageKey);setPending(null);setConflict(true);setReview(false)}else if(r.status===400){sessionStorage.removeItem(storageKey);setPending(null);setReview(false)}throw Error(b.error||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')};validateMerchandising(b.state?.products);if(!Number.isSafeInteger(b.state.version)||!b.state.snapshot||b.applied?.version!==input.expectedVersion+1||JSON.stringify(validateMerchandising(b.applied?.products))!==JSON.stringify(input.products))throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut versuchen.');sessionStorage.removeItem(storageKey);setPending(null);setState(b.state);setDraft(b.state.products);setReason('');setReview(false);setAuth(false);setNotice(b.replayed?'Frühere Veröffentlichung bestätigt. Aktueller Stand geladen.':'Produktdarstellung gespeichert und zurückgelesen.')}catch(e){setError(e.message||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}finally{setBusy(false)}}
 const changed=state&&draft&&JSON.stringify(state.products)!==JSON.stringify(draft),locked=busy||!!pending||conflict
 return <section className="pmw-root"><header className="pmw-heading"><div><span>Shop · Öffentliche Darstellung</span><h1>Kategorien & Darstellung</h1><p>Kategorien, Neu-Kennzeichnung und empfohlene Reihenfolge der drei Produkte.</p></div></header><div className="pmw-summary"><span>{state?`3 Produkte · Version ${state.version}`:'Stand wird geladen'}</span><span>Wirkt öffentlich im Shop</span></div>
 {draft&&<fieldset disabled={locked} className="pmw-fields">{draft.map((p,i)=><article key={p.id}><div className="pmw-product"><span>0{i+1}</span><h2>{merchandisingNames[merchandisingIds.indexOf(p.id)]}</h2></div><div className="pmw-controls"><label>Kategorie<select aria-label={`${merchandisingNames[i]} Kategorie`} value={p.category} onChange={e=>change(p.id,'category',e.target.value)}>{merchandisingCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Empfohlene Position<select aria-label={`${merchandisingNames[i]} Position`} value={p.displayOrder} onChange={e=>change(p.id,'displayOrder',Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label className="pmw-check"><input type="checkbox" aria-label={`${merchandisingNames[i]} Neu-Kennzeichnung`} checked={p.showNewBadge} onChange={e=>change(p.id,'showNewBadge',e.target.checked)}/><span>Als „NEU“ kennzeichnen</span></label></div></article>)}<p>Eine neue Position tauscht die beiden Plätze. Die Pflegereihenfolge bleibt unverändert.</p><label className="pmw-reason">Begründung<textarea aria-label="Begründung der Darstellung" rows={2} maxLength={500} value={reason} onChange={e=>{setReason(e.target.value);setReview(false)}}/></label></fieldset>}
 {review&&!pending&&<section className="pmw-review"><h2>Veröffentlichung prüfen</h2><p>Diese Darstellung erscheint nach dem Speichern öffentlich.</p>{draft.filter((p,i)=>JSON.stringify(p)!==JSON.stringify(state.products[i])).map(p=>{const old=state.products.find(r=>r.id===p.id);return <div key={p.id}><strong>{merchandisingNames[merchandisingIds.indexOf(p.id)]}</strong><p>Bisher: {old.category} · Position {old.displayOrder} · {old.showNewBadge?'NEU':'Ohne Kennzeichnung'}</p><p>Neu: {p.category} · Position {p.displayOrder} · {p.showNewBadge?'NEU':'Ohne Kennzeichnung'}</p></div>})}<p>Begründung: {reason}</p></section>}
 {error&&<p role="alert" className="pmw-error">{error}</p>}{auth&&<p className="pmw-info">Melde dich mit dem ursprünglichen Administratorkonto an und öffne diese Seite erneut. Deine genaue Anfrage bleibt gespeichert.</p>}{conflict&&<p className="pmw-info">Dein Entwurf bleibt erhalten. Lade den aktuellen Stand und prüfe die Unterschiede erneut.</p>}{notice&&<p role="status" className="pmw-info">{notice}</p>}
 <footer className="pmw-footer">{auth&&<a className="pmw-primary" href="/auth/admin">Erneut anmelden</a>}{pending?<button className={auth?'':'pmw-primary'} disabled={busy||auth} onClick={save}>Dieselbe Anfrage erneut versuchen</button>:conflict?<button className="pmw-primary" disabled={busy} onClick={()=>load(true)}>Aktuellen Stand laden · Entwurf behalten</button>:!state?<button className="pmw-primary" disabled={busy} onClick={()=>load(!!draft)}>Stand erneut laden</button>:<button className="pmw-primary" disabled={busy||!changed||!reason.trim()} onClick={()=>review?save():setReview(true)}>{busy?'Wird gespeichert …':review?'Darstellung veröffentlichen':'Änderung prüfen'}</button>}{review&&!pending&&<button disabled={busy} onClick={()=>setReview(false)}>Zurück zur Eingabe</button>}</footer></section>
}
