'use client'
import {useEffect,useRef,useState} from 'react'
import {forecast,OWN_IDS,cents} from '@/lib/admin/reports-model.mjs'
import './reports-workspace.css'
const money=n=>n===null||n===undefined?'Unbekannt':new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100)
const titles={'net-revenue':'Netto-Umsatz','profit-breakdown':'Gewinn-Aufschlüsselung','profit-forecast':'Gewinn-Prognose'}
const names=['Renewal Serum','Balance Toner','Contour Eye Cream']
export default function ReportsWorkspace({section='net-revenue'}){
 const [data,setData]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[range,setRange]=useState('month'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[query,setQuery]=useState('range=month'),[refresh,setRefresh]=useState(0),[basis,setBasis]=useState(30),[growth,setGrowth]=useState('0'),[modal,setModal]=useState(null),[draft,setDraft]=useState({}),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[page,setPage]=useState(0),[notice,setNotice]=useState(''),[conflict,setConflict]=useState(false)
 const dialog=useRef(null),opener=useRef(null),isForecast=section==='profit-forecast'
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');setData(null);setPage(0);fetch('/api/admin/reports?'+(isForecast?'range=90':query),{signal:c.signal,cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error||'Bericht nicht verfügbar.');setData(b)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[query,refresh,isForecast])
 useEffect(()=>{if(modal){dialog.current?.showModal();dialog.current?.querySelector('button')?.focus()}else if(dialog.current?.open){dialog.current.close();opener.current?.focus()}},[modal])
 function open(value,e){opener.current=e.currentTarget;setSaveError('');setConflict(false);if(value==='costs')setDraft(Object.fromEntries(OWN_IDS.map(id=>[id,data.config.costs[id]===null?'':String(data.config.costs[id]/100)])));setModal(value)}
 async function save(){let costs;try{costs=Object.fromEntries(OWN_IDS.map(id=>[id,draft[id]===''?null:cents(draft[id].replace(',','.'))]))}catch{setSaveError('Bitte Eurobeträge mit höchstens zwei Nachkommastellen eingeben.');return}setSaving(true);try{const r=await fetch('/api/admin/reports/costs',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({costs,expectedVersion:data.config.version})});const b=await r.json();if(!r.ok){if(r.status===409)setConflict(true);throw Error(b.error)}setNotice('Stückkosten gespeichert und zurückgelesen · Version '+b.config.version);setModal(null);setRefresh(v=>v+1)}catch(e){setSaveError(e.message)}finally{setSaving(false)}}
 const projection=data&&isForecast?forecast(data,basis,Number(growth)||0):null
 const basisOrders=data&&isForecast?data.orders.filter(o=>new Date(o.createdAt)>=new Date(new Date(data.range.end)-basis*86400000)&&new Date(o.createdAt)<new Date(data.range.end)):null
 const basisPaid=basisOrders?.filter(o=>['PAID','PACKED','SHIPPED','DELIVERED'].includes(o.status))
 const summary=basisOrders?{count:basisOrders.length,totalCents:basisPaid.reduce((s,o)=>s+o.totalCents,0),contributionCents:basisPaid.some(o=>o.contributionCents===null)?null:basisPaid.reduce((s,o)=>s+o.contributionCents,0)}:data?.summary
 const pendingQuery=new URLSearchParams({range,...(range==='custom'?{start,end}:{})}).toString()
 const filtersPending=!isForecast&&pendingQuery!==query
 const metrics=[['Bestellwert · bezahlt',money(summary?.totalCents),'Statusbasiert, kein Zahlungseingang'],['Bestellungen',summary?.count??'—','Nur ausschließlich ELYSERA'],['Warenbeitrag · Modell',money(summary?.contributionCents),'Bestellwert minus aktuelle Stückkosten'],['Tatsächlicher Nettogewinn','Unbekannt','Steuern, Gebühren und Erstattungen fehlen']]
 return <section className="fr-workspace" aria-busy={busy}>
 <header className="fr-heading"><div><p>Finanzen / ELYSERA</p><h1>{titles[section]}</h1><p>Verlässliche Bestellwerte. Klar getrennte Kostenschätzungen.</p></div><button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Aktualisieren</button></header>
 <form className={"fr-filters"+(isForecast?" fr-forecast-filters":"")} onSubmit={e=>{e.preventDefault();setQuery(new URLSearchParams({range,...(range==='custom'?{start,end}:{})}).toString())}}>{isForecast?<><label>Historische Basis<select value={basis} onChange={e=>setBasis(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>{n} Tage</option>)}</select></label><label>Wöchentliches Wachstum · Annahme (%)<input type="number" min="-8" max="12" step="0.5" value={growth} onChange={e=>{const n=Number(e.target.value);if(n>=-8&&n<=12)setGrowth(e.target.value)}}/></label></>:<><label>Zeitraum (UTC)<select value={range} onChange={e=>setRange(e.target.value)}>{[['month','Dieser Monat'],['previousMonth','Vormonat'],['week','Diese Woche'],['24h','Letzte 24 Stunden'],['lastMonth','Letzte 30 Tage'],['all','Gesamter Zeitraum'],['custom','Eigener Zeitraum']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>{range==='custom'&&<><label>Von<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Bis einschließlich<input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></label></>}<button type="submit" disabled={busy}>Anwenden</button></>}{data&&<button type="button" onClick={e=>open('costs',e)}>Stückkosten bearbeiten</button>}{filtersPending&&<p className="fr-unapplied" role="status">Filter geändert · angezeigter Bericht noch unverändert. Anwenden zum Laden.</p>}</form>
 {busy?<div className="fr-state" role="status">Bericht wird geladen …</div>:error?<div className="fr-state fr-error" role="alert"><h2>Bericht nicht verfügbar</h2><p>{error}</p><button onClick={()=>setRefresh(v=>v+1)}>Erneut versuchen</button></div>:data&&<>
 {notice&&<p role="status" className="fr-note">{notice}</p>}<div className="fr-metrics">{metrics.map(([title,value,note])=><article key={title}><span>{title}</span><strong>{value}</strong><small>{note}</small></article>)}</div>
 <div className="fr-layout"><div className="fr-main">
 {isForecast?<article className="fr-panel"><h2>Modellierte Entwicklung</h2><p>{basis} abgeschlossene UTC-Kalendertage · {projection.sampleDays} Tage mit bezahlten Bestellwerten · {growth||0} % angenommenes Wachstum pro Woche</p><div className="fr-chart" aria-label="Historische tägliche bezahlte Bestellwerte">{projection.days.map((d,i)=><div key={i} title={`${d.date}: ${money(d.totalCents)}`} style={{height:`${Math.max(2,d.totalCents/Math.max(1,...projection.days.map(v=>v.totalCents))*100)}%`}}/>)}</div><p>Historische Bestellwerte nach Erstellungsdatum. Tage ohne Bestellungen sind enthalten.</p><div className="fr-table"><div className="fr-row fr-table-head"><b>Horizont</b><b>Bestellwert</b><b>Warenbeitrag</b></div>{projection.projections.map(p=><div className="fr-row" key={p.horizon}><strong>{p.horizon} Tage</strong><span>{money(p.revenueCents)}</span><span>{money(p.contributionCents)}</span></div>)}</div>{projection.sampleDays===0&&<p className="fr-note">Keine bezahlte Historie: Eine Prognose ist nicht ableitbar.</p>}<p>Modell, keine Zusage. Aktuelle Stückkosten; ohne Steuern, Versandkosten, Gebühren, Erstattungen oder Provisionen. Langfristige Werte reagieren besonders stark auf Wachstumsannahmen.</p></article>:<>
 <article className="fr-panel"><h2>Bestellungen im Zeitraum</h2><p>{data.range.start.slice(0,10)} bis {new Date(new Date(data.range.end)-1).toISOString().slice(0,10)} · Erstellungsdatum in UTC</p>{!data.orders.length?<div className="fr-empty"><h3>Keine ELYSERA-Bestellungen</h3><p>Für diesen Zeitraum liegen keine ausschließlich eigenen Bestellungen vor.</p></div>:<><div className="fr-orders">{data.orders.slice(page*10,page*10+10).map(o=><button className="fr-order" key={o.id} onClick={e=>open(o,e)}><span><strong>#{o.id.slice(-8).toUpperCase()}</strong><small>{new Date(o.createdAt).toLocaleDateString('de-DE',{timeZone:'UTC'})} · {o.items.length} Positionen</small></span><span className="fr-status">{o.status}</span><b>{money(o.totalCents)}</b><span aria-hidden="true">→</span></button>)}</div><div className="fr-pagination"><button disabled={page===0} onClick={()=>setPage(v=>v-1)}>Zurück</button><span>{page+1} / {Math.ceil(data.orders.length/10)}</span><button disabled={(page+1)*10>=data.orders.length} onClick={()=>setPage(v=>v+1)}>Weiter</button></div></>}</article>
 <article className="fr-panel"><h2>Produkte · bezahlte Bestellungen</h2><p>Positionswerte vor Abgleich mit Bestellrabatten oder Versand. Nicht gleich Bestellwert.</p>{data.products.map((p,i)=><div className="fr-product" key={p.id}><div><strong>{names[i]}</strong><small>{p.quantity} Stück</small></div><div><b>{money(p.lineCents)}</b><small>Positionswert</small></div><div><b>{money(p.costCents)}</b><small>Aktuelle Kosten · Modell</small></div></div>)}</article></>}
 </div><aside className="fr-panel fr-basis"><h2>Berechnungsgrundlage</h2><dl><dt>Bestellwert</dt><dd>Gespeicherter Gesamtbetrag; Rabatte werden nicht erneut abgezogen.</dd><dt>Bezahlt</dt><dd>PAID, PACKED, SHIPPED, DELIVERED. Kein Bankabgleich.</dd><dt>Stückkosten</dt><dd>Aktuelle Konfiguration v{data.config.version}; keine historischen Einkaufskosten.</dd><dt>Zahlungseingang / Erstattungen</dt><dd>Unbekannt</dd><dt>Steuern / Versand / Provisionen</dt><dd>Unbekannt</dd></dl><p className="fr-note">Warenbeitrag ist eine Schätzung vor weiteren Kosten. Ein tatsächlicher Netto-Umsatz oder Nettogewinn ist derzeit nicht belegbar.</p></aside></div></>}
 <dialog className="fr-dialog" ref={dialog} onCancel={e=>{e.preventDefault();if(!saving)setModal(null)}}><div className="fr-dialog-head"><h2>{modal==='costs'?'Aktuelle Stückkosten':'Bestelldetails'}</h2><button aria-label="Dialog schließen" disabled={saving} onClick={()=>setModal(null)}>×</button></div>{modal==='costs'?<form onSubmit={e=>{e.preventDefault();save()}}><p>Euro je Stück. Leer bedeutet unbekannt. Änderungen gelten für heutige Modellrechnungen, nicht als historischer Kostennachweis.</p>{OWN_IDS.map((id,i)=><label key={id}>{names[i]}<input inputMode="decimal" value={draft[id]??''} onChange={e=>setDraft({...draft,[id]:e.target.value})} placeholder="Unbekannt" disabled={saving}/></label>)}{saveError&&<p role="alert" className="fr-error">{saveError}</p>}{conflict&&<button type="button" onClick={()=>{setModal(null);setRefresh(v=>v+1)}}>Aktuelle Kosten neu laden</button>}<button disabled={saving||conflict}>{saving?'Wird gespeichert …':'Kosten speichern'}</button></form>:modal&&<><p>#{modal.id} · {modal.status}</p>{modal.items.map((i,index)=><div className="fr-detail" key={index}><strong>{i.name||i.productId}</strong><span>{i.quantity} × {money(i.unitCents)} = {money(i.lineCents)}</span><small>Aktuelle Kosten: {money(i.costCents)}</small></div>)}<dl><dt>Bestellwert inkl. gespeicherter Rabatte</dt><dd>{money(modal.totalCents)}</dd><dt>Warenbeitrag · aktuelles Kostenmodell</dt><dd>{money(modal.contributionCents)}</dd><dt>Tatsächlicher Nettogewinn</dt><dd>Unbekannt</dd></dl></>}</dialog>
 </section>
}
