'use client'
import {useEffect,useRef,useState} from 'react'
import {settingsDefaults,settingsInput} from '@/lib/admin/settings-policy.mjs'
import './settings-workspace.css'
const storageKey='elysera-site-settings-pending-v1'
const labels={supportEmail:'Support-E-Mail',supportPhone:'Telefon',whatsapp:'WhatsApp',instagram:'Instagram',facebook:'Facebook',youtube:'YouTube',tiktok:'TikTok',linkedin:'LinkedIn',x:'X / Twitter'}
export default function SettingsWorkspace(){
 const [data,setData]=useState(null),[draft,setDraft]=useState({...settingsDefaults}),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(false),[conflict,setConflict]=useState(false),[review,setReview]=useState(false);const attempt=useRef(null)
 async function load(keep=false){setBusy(true);setError('');try{const r=await fetch('/api/admin/settings',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);if(!keep&&!attempt.current)setDraft(d.settings);if(keep){setConflict(false);setReview(false);setNotice('Aktueller Stand geladen. Dein Entwurf bleibt erhalten; Unterschiede unten prüfen.')}}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(storageKey));if(saved){settingsInput(saved);attempt.current=saved;setDraft(saved);setPending(true);setReview(true);setNotice('Eine frühere Speicherung ist ungeklärt. Dieselbe Anfrage erneut prüfen.')}}catch{setError('Gespeicherter Entwurf konnte nicht gelesen werden.')}load()},[])
 function edit(key,value){setDraft(d=>({...d,[key]:value}));setReview(false);setNotice('')}
 async function save(){setBusy(true);setError('');try{let input=attempt.current;if(!input){input=settingsInput({actorId:data.actorId,requestId:crypto.randomUUID(),expectedVersion:data.settings.version,...Object.fromEntries(Object.keys(settingsDefaults).map(k=>[k,draft[k]]))});sessionStorage.setItem(storageKey,JSON.stringify(input));attempt.current=input;setPending(true)}
 const r=await fetch('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),d=await r.json();if(!r.ok){if(['INVALID_INPUT','VERSION_CONFLICT'].includes(d.code)){sessionStorage.removeItem(storageKey);attempt.current=null;setPending(false)}if(r.status===409)setConflict(true);throw Error(d.error)}
 if(!d.settings||d.settings.version!==input.expectedVersion+1||Object.keys(settingsDefaults).some(k=>d.settings[k]!==input[k]))throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut prüfen.')
 sessionStorage.removeItem(storageKey);attempt.current=null;setPending(false);setData(old=>({...old,settings:d.settings}));setDraft(d.settings);setReview(false);setNotice(d.replayed?'Frühere Speicherung bestätigt.':'Gespeichert und aus der Datenbank geprüft.')
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 const differences=data?Object.keys(settingsDefaults).filter(k=>draft[k]!==data.settings[k]):[]
 return <section className="stw-root"><div className="stw-heading"><div><h1>Einstellungen</h1><p>Öffentliche Kontakte und Website-Verfügbarkeit für ELYSERA.</p></div><button disabled={busy} onClick={()=>load(true)}>Stand laden</button></div>
 <div className="stw-status"><span>Konfiguration</span><strong>{data?`Version ${data.settings.version}`:'Nicht geladen'}</strong><span>{data?(data.settings.maintenance?'Wartung aktiv':'Website freigegeben'):'Status unbekannt'}</span></div>
 {busy&&!data&&<p role="status">Einstellungen werden geladen …</p>}{error&&<div className="stw-error" role="alert">{error}</div>}{notice&&<p className="stw-notice" role="status">{notice}</p>}
 {data||pending?<><fieldset disabled={busy||pending} className="stw-panel"><legend>Öffentliche Kontaktwege</legend><p>Leere Felder werden öffentlich ausgeblendet. Telefonnummern im internationalen Format, Links als HTTPS-Profiladresse.</p><div className="stw-fields">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input value={draft[key]} onChange={e=>edit(key,e.target.value)} type={key==='supportEmail'?'email':['supportPhone','whatsapp'].includes(key)?'tel':key in labels&&['instagram','facebook','youtube','tiktok','linkedin','x'].includes(key)?'url':'text'} autoComplete="off" maxLength={500}/></label>)}</div></fieldset>
 <fieldset disabled={busy||pending} className="stw-panel"><legend>Wartungsmodus</legend><label className="stw-toggle"><input type="checkbox" checked={draft.maintenance} onChange={e=>edit('maintenance',e.target.checked)}/> Öffentliche Website vorübergehend auf Wartung setzen</label><p>Admin, Anmeldung, APIs und statische Dateien bleiben erreichbar. Öffentliche Seiten erhalten während der Wartung HTTP 503.</p><label>Öffentliche Wartungsnachricht<textarea rows={3} maxLength={500} value={draft.maintenanceMessage} onChange={e=>edit('maintenanceMessage',e.target.value)}/></label></fieldset>
 <div className="stw-panel"><h2>Änderungen prüfen</h2>{pending&&<p className="stw-notice" role="status">Speicherung ungeklärt. Die unveränderte Anfrage erneut prüfen.</p>}{error&&<p className="stw-error" role="status">{error}</p>}<p>{differences.length?`${differences.length} abweichende Felder zum geladenen Stand.`:'Keine Abweichungen zum geladenen Stand.'}</p>{(review||conflict)&&<div className="stw-changes">{differences.map(k=><div key={k}><strong>{labels[k]|| (k==='maintenance'?'Wartung':'Wartungsnachricht')}</strong><span>Aktuell: {String(data?.settings[k]??'')||'Leer'}</span><span>Entwurf: {String(draft[k])||'Leer'}</span></div>)}</div>}{conflict&&<button disabled={busy||pending} onClick={()=>load(true)}>Aktuellen Stand laden · Entwurf behalten</button>}{review?<><button className="stw-primary" disabled={busy||conflict||!data} onClick={save}>{busy?'Wird geprüft …':pending?'Dieselbe Anfrage erneut prüfen':'Verbindlich speichern'}</button><button disabled={busy||pending} onClick={()=>setReview(false)}>Weiter bearbeiten</button></>:<button className="stw-primary" disabled={busy||conflict||!data||!differences.length} onClick={()=>{try{settingsInput({actorId:data.actorId,requestId:crypto.randomUUID(),expectedVersion:data.settings.version,...Object.fromEntries(Object.keys(settingsDefaults).map(k=>[k,draft[k]]))});setError('');setReview(true)}catch(e){setError(e.message)}}}>Änderungen prüfen</button>}</div></>:!busy&&<button onClick={()=>load()}>Erneut laden</button>}
 <div className="stw-panel"><h2>Weitere Konfiguration</h2><dl className="stw-other"><div><dt>Zahlungen, Bonus und Prämien</dt><dd>Geschäftsregeln und eigene Berechtigungsgrundlagen stehen aus.</dd></div><div><dt>WhatsApp-Vorlagen und Einladungen</dt><dd>Eigener Provider, Absender und freigegebene Kampagnen sind nicht konfiguriert.</dd></div><div><dt>KI-Anbieter und Versandvorlagen</dt><dd>Keine eigene Provider-Konfiguration in diesem Modul vorhanden.</dd></div></dl></div></section>
}
