'use client'
import {useEffect,useRef,useState} from 'react'
import './shop-workspace.css'
const pendingKey='elysera-product-pending-v1'
const fields=p=>({name:p.name,price:p.price,stock:p.stock,active:p.active})
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n)
export default function ShopWorkspace({fixture}){
 const [products,setProducts]=useState(fixture?.products??null),[error,setError]=useState(''),[loading,setLoading]=useState(!fixture),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState(null),[notice,setNotice]=useState(''),[actorId,setActorId]=useState(null),[authMissing,setAuthMissing]=useState(false)
 async function reload(){setLoading(true);setError('');try{const response=await fetch('/api/admin/products/catalog',{cache:'no-store'}),body=await response.json();setAuthMissing(response.status===401);if(!response.ok)throw Error(body.error);setProducts(body.products);setActorId(body.actorId)}catch(e){setError(e.message||'Produkte konnten nicht geladen werden.')}finally{setLoading(false)}}
 useEffect(()=>{if(!fixture){try{const saved=JSON.parse(sessionStorage.getItem(pendingKey));if(saved)setEditing(saved.snapshot)}catch{}reload()}},[])
 const visible=(products||[]).filter(p=>(filter==='all'||p.active===(filter==='active'))&&p.name.toLocaleLowerCase('de').includes(query.toLocaleLowerCase('de')))
 return <section className="shop-workspace">
  <div className="sw-heading"><div><span className="sw-eyebrow">Shop · Sortiment</span><h1>Produkte</h1><p>Preise, Bestand und Sichtbarkeit für ELYSERA verwalten.</p></div><button onClick={reload} disabled={loading}>↻ Aktualisieren</button></div>
  {fixture&&<p className="sw-banner">Designvorschau · Beispieldaten · Änderungen werden nicht gespeichert</p>}
  {notice&&<p role="status" className="sw-banner">{notice}</p>}
  <div className="sw-summary"><div><span>Produkte</span><strong>{products?.length??'—'}</strong><small>ELYSERA-Sortiment</small></div><div><span>Aktiv</span><strong>{products?products.filter(p=>p.active).length:'—'}</strong><small>Freigegebene Produkte</small></div><div><span>Ohne Bestand</span><strong>{products?products.filter(p=>p.stock===0).length:'—'}</strong><small>Nachschub prüfen</small></div></div>
  <div className="sw-catalog"><div className="sw-toolbar"><label><span className="sw-sr">Produkte suchen</span><input type="search" placeholder="Produkt suchen …" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className="sw-sr">Sichtbarkeit filtern</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Alle</option><option value="active">Aktiv</option><option value="inactive">Inaktiv</option></select></label></div>
   {loading?<div className="sw-state" role="status">Sortiment wird geladen …</div>:error?<div className="sw-state" role="alert"><h2>Laden nicht möglich</h2><p>{error}</p><button onClick={reload}>Erneut versuchen</button></div>:visible.length===0?<div className="sw-state"><h2>{products?.length?'Keine Treffer':'Noch keine Produkte verfügbar'}</h2><p>{products?.length?'Passe Suche oder Filter an.':'Es wurden keine ELYSERA-Produkte gefunden.'}</p></div>:<div className="sw-grid">{visible.map(p=><article className="sw-product" key={p.id}><div className="sw-image"><img src={p.image} alt={p.name}/><span className={'sw-status '+(p.active?'is-active':'')}>{p.active?'Aktiv':'Inaktiv'}</span></div><div className="sw-product-body"><h2>{p.name}</h2><p className="sw-sku">{p.id}</p><dl><div><dt>Verkaufspreis</dt><dd>{money(p.price)}</dd></div><div><dt>Bestand</dt><dd className={p.stock===0?'sw-warning':''}>{p.stock} <small>Stück</small></dd></div></dl><button className="sw-edit" onClick={()=>{setNotice('');setEditing(p)}}>Produkt bearbeiten <span aria-hidden="true">↗</span></button></div></article>)}</div>}
  </div>
  <aside className="sw-scope"><strong>Sortimentspflege</strong><p>Änderungen betreffen den Namen, EUR-Preis, Bestand und Aktivstatus. Produktbilder stammen aus der aktuellen ELYSERA-Kampagne.</p></aside>
  {editing&&<ProductDialog authMissing={authMissing} actorId={actorId} product={editing} preview={!!fixture} close={()=>setEditing(null)} saved={(product,replayed)=>{setProducts(rows=>rows?.some(p=>p.id===product.id)?rows.map(p=>p.id===product.id?product:p):[...(rows||[]),product]);setEditing(null);setNotice((replayed?'Frühere Anfrage bestätigt; aktueller Produktstand geladen: ':'Gespeichert und aus der Datenbank zurückgelesen: ')+product.name);reload()}}/>}
 </section>
}
function ProductDialog({product,actorId,authMissing,close,saved,preview}){
 const restored=useRef(null);if(restored.current===null){try{const stored=JSON.parse(sessionStorage.getItem(pendingKey));restored.current=stored?.snapshot?.id===product.id?stored:false}catch{restored.current=false}}
 const initial=restored.current?.payload?.changes||product
 const dialog=useRef(null),attempt=useRef(restored.current||null),[baseline,setBaseline]=useState(product),[name,setName]=useState(initial.name),[price,setPrice]=useState(String(initial.price)),[stock,setStock]=useState(String(initial.stock)),[active,setActive]=useState(initial.active),[confirm,setConfirm]=useState(!!restored.current),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState(!!restored.current),[conflict,setConflict]=useState(false),[notice,setNotice]=useState(''),[authRequired,setAuthRequired]=useState(false)
 useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();dialog.current.querySelector('[name="productName"]')?.focus({preventScroll:false});return()=>requestAnimationFrame(()=>previous?.focus())},[])
 async function latest(){setBusy(true);setError('');try{const r=await fetch('/api/admin/products/catalog',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);if(d.actorId!==actorId)throw Error('Anmeldung geändert. Seite neu laden.');const row=d.products.find(p=>p.id===product.id);if(!row)throw Error('Produkt nicht mehr verfügbar.');setBaseline(row);setConflict(false);setConfirm(false);setNotice('Aktueller Stand geladen. Entwurf bleibt erhalten; Änderungen erneut prüfen.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function submit(e){e.preventDefault();setError('');if(!confirm){setConfirm(true);return}if(preview){setError('Designvorschau: Es werden keine Änderungen gespeichert.');return}setBusy(true);try{
 let entry=attempt.current;if(!entry){entry={snapshot:baseline,payload:{actorId,requestId:crypto.randomUUID(),expectedVersion:baseline.version,changes:{name:name.trim(),price:Number(price),stock:Number(stock),active},expected:fields(baseline)}};sessionStorage.setItem(pendingKey,JSON.stringify(entry));attempt.current=entry;setPending(true)}
 const response=await fetch('/api/admin/products/'+encodeURIComponent(product.id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(entry.payload)}),body=await response.json();if(!response.ok){if(response.status===401)setAuthRequired(true);if(['INVALID_INPUT','VERSION_CONFLICT'].includes(body.code)){sessionStorage.removeItem(pendingKey);attempt.current=null;setPending(false)}if(body.status===409||body.code==='VERSION_CONFLICT')setConflict(true);throw Error(body.error)}
 const applied=body.replayed?body.applied:body.product;if(!body.product||!applied||applied.version!==entry.payload.expectedVersion+1||Object.keys(entry.payload.changes).some(k=>applied[k]!==entry.payload.changes[k]))throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut prüfen.')
 sessionStorage.removeItem(pendingKey);attempt.current=null;setPending(false);saved(body.product,body.replayed)
 }catch(e){setError(e.message||'Speichern nicht bestätigt.')}finally{setBusy(false)}}
 return <dialog className="sw-dialog" ref={dialog} onKeyDown={e=>{if(e.key!=='Tab')return;const nodes=[...dialog.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}} onCancel={e=>{e.preventDefault();if(!busy&&!pending)close()}} aria-labelledby="sw-dialog-title"><form onSubmit={submit}><div className="sw-dialog-heading"><div><span className="sw-eyebrow">ELYSERA · Produktpflege</span><h2 id="sw-dialog-title">{confirm?'Änderung bestätigen':'Produkt bearbeiten'}</h2></div><button type="button" aria-label="Dialog schließen" onClick={close} disabled={busy||pending}>×</button></div><div className="sw-dialog-product"><img src={product.image} alt=""/><div><strong>{product.name}</strong><span>{product.id}</span></div></div>
 {confirm?<div className="sw-confirm"><p>Diese Werte werden nach Bestätigung im Produktdatensatz gespeichert.</p><dl><div><dt>Name</dt><dd>{baseline.name} → {name.trim()}</dd></div><div><dt>EUR-Preis</dt><dd>{money(baseline.price)} → {money(Number(price))}</dd></div><div><dt>Bestand</dt><dd>{baseline.stock} → {stock} Stück</dd></div><div><dt>Status</dt><dd>{baseline.active?'Aktiv':'Inaktiv'} → {active?'Aktiv':'Inaktiv'}</dd></div></dl></div>:<div className="sw-fields"><label>Produktname<input name="productName" required minLength={2} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><div><label>Preis in EUR<input required type="number" min="0" max="100000" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Bestand in Stück<input required type="number" min="0" max="1000000" step="1" value={stock} onChange={e=>setStock(e.target.value)}/></label></div><label className="sw-checkbox"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Katalogstatus aktiv</label><p>Der Aktivstatus wird im Produktdatensatz gespeichert.</p></div>}
 {(authMissing||authRequired)&&<div className="sw-auth-required" role="alert"><strong>Admin-Anmeldung erforderlich</strong><p>Melde dich mit demselben Admin-Konto erneut an und öffne danach die Produktverwaltung. Die unveränderte Anfrage bleibt in diesem Tab gespeichert.</p></div>}{notice&&<p role="status">{notice}</p>}{pending&&<p role="status">Speicherung ungeklärt. Die unveränderte Anfrage erneut prüfen. Du kannst die Seite neu laden; diese Anfrage bleibt erhalten.</p>}{conflict&&<p role="status">Lade den aktuellen Produktstand. Dein Entwurf bleibt erhalten und wird danach erneut geprüft.</p>}{error&&<p role="alert" className="sw-error">{error}</p>}{(authMissing||authRequired)&&pending&&<button type="button" disabled={busy} onClick={submit}>Dieselbe Anfrage erneut prüfen</button>}<footer><button type="button" disabled={busy||pending} onClick={()=>confirm?setConfirm(false):close()}>{confirm?'Zurück':'Abbrechen'}</button>{(authMissing||authRequired)?<a className="sw-primary sw-signin" href="/auth/admin">Zur Admin-Anmeldung</a>:conflict?<button className="sw-primary" type="button" disabled={busy} onClick={latest}>Aktuellen Stand laden · Entwurf behalten</button>:<button className="sw-primary" disabled={busy||!actorId&&!preview&&!pending} type="submit">{busy?'Wird gespeichert …':pending?'Dieselbe Anfrage erneut prüfen':confirm?'Verbindlich speichern':'Änderungen prüfen'}</button>}</footer></form></dialog>
}
