'use client'
import {useEffect,useRef,useState} from 'react'
import './support-workspace.css'
const labels={open:'Offen',in_progress:'In Bearbeitung',resolved:'Gelöst',closed:'Geschlossen'}
async function request(url,body){const response=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(30000),...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok){const error=Error(data.error||'Support nicht verfügbar.');error.status=response.status;error.code=data.code;throw error;}return data}
export default function SupportWorkspace({customer=false}){
 const endpoint=customer?'/api/account/support':'/api/admin/support',prefix=customer?'cs':'sp'
 const [tickets,setTickets]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[archive,setArchive]=useState(false),[detail,setDetail]=useState(null),[busy,setBusy]=useState(false),[body,setBody]=useState(''),[subject,setSubject]=useState(''),[status,setStatus]=useState('open'),[notice,setNotice]=useState(''),[pending,setPending]=useState(null)
 const dialog=useRef(null),opener=useRef(null),identity=useRef(null),storage=useRef(null)
 async function load(){setLoading(true);setError('');try{const data=await request(endpoint);setTickets(data.tickets);if(data.actorId){identity.current=data.actorId;storage.current=`elysera-${customer?'customer':'admin'}-support-${data.actorId}`;try{setPending(JSON.parse(localStorage.getItem(storage.current)||'null'))}catch{setPending(null)}}if(data.limited)setNotice('Die neuesten 1.000 Tickets werden angezeigt.')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[endpoint])
 useEffect(()=>{if(detail&&!dialog.current.open)dialog.current.showModal();else if(!detail&&dialog.current?.open)dialog.current.close()},[detail])
 async function open(ticket,event,preserveDraft=false){if(!preserveDraft)opener.current=event?.currentTarget||document.activeElement;setError('');setNotice('');setBusy(true);try{const data=await request(`${endpoint}?id=${encodeURIComponent(ticket.id)}`);setDetail(data);setStatus(data.ticket.status);if(!preserveDraft)setBody('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 function close(){if(busy)return;setDetail(null);setError('');opener.current?.focus()}
 async function mutate(action,retry){setError('');setNotice('');if(!identity.current){setError('Identität wird geladen. Bitte aktualisieren.');return}if(pending&&!retry){setError('Bitte die unbestätigte Nachricht zuerst prüfen.');return}let input=retry||{action,actorId:identity.current,ticketId:detail?.ticket.id,expectedVersion:detail?.ticket.version,status,subject,body,requestId:crypto.randomUUID()};if(['reply','create'].includes(input.action)){try{localStorage.setItem(storage.current,JSON.stringify(input));setPending(input)}catch{setError('Browser-Speicher nicht verfügbar. Nachricht wurde nicht gesendet.');return}}
 setBusy(true);try{const data=await request(endpoint,input);setDetail(data);setStatus(data.ticket.status);setBody('');setSubject('');if(['reply','create'].includes(input.action)){localStorage.removeItem(storage.current);setPending(null)}setNotice(data.replayed?'Bereits gespeicherte Nachricht bestätigt.':'Änderung gespeichert.');await load()}catch(e){if(([400,404].includes(e.status)||(e.status===409&&e.code!=='REQUEST_ID_CONFLICT'))&&['reply','create'].includes(input.action)){localStorage.removeItem(storage.current);setPending(null);setBody(input.body||'')}setError(e.message)}finally{setBusy(false)}}
 const visible=tickets.filter(t=>(customer||Boolean(t.archivedAt)===archive)&&(filter==='all'||t.status===filter)&&`${t.subject} ${t.email||''} ${t.firstName||''} ${t.id}`.toLowerCase().includes(search.toLowerCase()))
 const c=name=>`${prefix}-${name}`
 return <section className={c('workspace')} aria-label={customer?'Meine Support-Anfragen':'Support-Tickets'}>
 <header className={c('header')}><div><h2>{customer?'Meine Support-Anfragen':'Support-Tickets'}</h2><p>{customer?'Nachrichten an das ELYSERA-Team.':'Anfragen und Antworten an einem Ort.'}</p></div><button className={c('refresh')} aria-label="Aktualisieren" title="Aktualisieren" disabled={loading||busy} onClick={load}>Aktualisieren</button>{customer&&<button disabled={Boolean(pending)||busy} onClick={e=>{opener.current=e.currentTarget;setDetail({ticket:{id:null},messages:[]});setBody('');setSubject('');setError('')}}>Neue Anfrage</button>}</header>
 {pending&&!detail&&<div className={c('notice')}>Eine Nachricht wurde noch nicht bestätigt. <button disabled={busy} onClick={()=>mutate(pending.action,pending)}>Sicher erneut prüfen / senden</button></div>}
 <div className={c('filters')}><label><span>Suche</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Betreff oder Ticket"/></label><label><span>Status</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Alle Status</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{!customer&&<button aria-pressed={archive} onClick={()=>setArchive(!archive)}>{archive?'Aktive Tickets zeigen':'Archiv anzeigen'}</button>}</div>
 {!detail&&error&&<p role="alert" className={c('error')}>{error} <button onClick={load}>Erneut versuchen</button></p>}{!detail&&notice&&<p role="status">{notice}</p>}
 {loading?<p role="status" className={c('empty')}>Tickets werden geladen …</p>:!error&&!visible.length?<p className={c('empty')}>{tickets.length?'Keine Tickets für diese Auswahl.':'Noch keine Support-Anfragen.'}</p>:<div className={c('list')}>{visible.map(ticket=><article className={c('row')} key={ticket.id}><div><h3>{ticket.subject}</h3><p>{ticket.firstName||ticket.email||'ELYSERA-Anfrage'}{ticket.email&&ticket.firstName?` · ${ticket.email}`:''}</p><small>{new Date(ticket.updatedAt).toLocaleString('de-DE')}</small></div><span className={c('badge')} data-status={ticket.status}>{labels[ticket.status]}{ticket.archivedAt?' · Archiv':''}</span><button disabled={busy} onClick={e=>open(ticket,e)}>Öffnen</button></article>)}</div>}
 <dialog ref={dialog} className={c('dialog')} aria-labelledby={`${prefix}-title`} onCancel={e=>{e.preventDefault();close()}} onClose={()=>{setDetail(null);opener.current?.focus()}}>
 {detail&&<><header className={c('dialoghead')}><div><h2 id={`${prefix}-title`}>{detail.ticket.id?detail.ticket.subject:'Neue Anfrage'}</h2>{!customer&&detail.ticket.id&&<p>{detail.ticket.firstName||detail.ticket.email||'ELYSERA-Kunde'}{detail.ticket.firstName&&detail.ticket.email?` · ${detail.ticket.email}`:''}</p>}{detail.ticket.id&&<small>{labels[detail.ticket.status]} · Version {detail.ticket.version}{detail.ticket.createdAt?` · Erstellt ${new Date(detail.ticket.createdAt).toLocaleString('de-DE')}`:''}{detail.ticket.updatedAt?` · Aktualisiert ${new Date(detail.ticket.updatedAt).toLocaleString('de-DE')}`:''}</small>}</div><button aria-label="Dialog schließen" disabled={busy} onClick={close}>Schließen</button></header>
 <div className={c('dialogbody')}>
 {detail.messagesLimited&&<p>Die neuesten 2.000 Nachrichten werden angezeigt.</p>}{detail.ticket.id?<div className={c('messages')}>{detail.messages.length?detail.messages.map(message=><article className={c('message')} data-sender={message.sender} key={message.id}><header><strong>{message.sender==='staff'?'ELYSERA-Team':'Kunde'}</strong><small>{new Date(message.createdAt).toLocaleString('de-DE')}</small></header><p>{message.body}</p></article>):<p>Keine Nachrichten vorhanden.</p>}</div>:<label>Betreff<input maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)}/></label>}
 {!detail.ticket.archivedAt&&<label>{detail.ticket.id?'Antwort':'Nachricht'}<textarea rows={4} maxLength={10000} value={body} onChange={e=>setBody(e.target.value)} placeholder="Nachricht schreiben …" disabled={busy||Boolean(pending)}/><small>{body.length} / 10.000 Zeichen</small></label>}
 {!customer&&detail.ticket.id&&!detail.ticket.archivedAt&&<label>Status<select disabled={busy} value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}</div>
 <footer className={c('actions')}>{error&&<div className={c('feedback')} role="alert">{error}</div>}{notice&&<div className={c('feedback')} role="status">{notice}</div>}{pending&&<div className={c('feedback')}>Nachricht noch nicht bestätigt. Erneutes Prüfen vermeidet doppelte Nachrichten.</div>}{pending&&<button className={c('retry')} disabled={busy} onClick={()=>mutate(pending.action,pending)}>Sicher erneut prüfen / senden</button>}{error&&detail.ticket.id&&<button disabled={busy} onClick={()=>open(detail.ticket,null,true)}>Neu laden</button>}{!customer&&detail.ticket.id&&<>{!detail.ticket.archivedAt&&<button disabled={busy||Boolean(pending)||status===detail.ticket.status} onClick={()=>mutate('status')}>Status speichern</button>}{(detail.ticket.status==='resolved'||detail.ticket.archivedAt)&&<button disabled={busy||Boolean(pending)} onClick={()=>mutate(detail.ticket.archivedAt?'restore':'archive')}>{detail.ticket.archivedAt?'Wiederherstellen':'Archivieren'}</button>}</>}{!detail.ticket.archivedAt&&<button className={c('primary')} disabled={busy||!body.trim()||(!detail.ticket.id&&!subject.trim())||Boolean(pending)} onClick={()=>mutate(detail.ticket.id?'reply':'create')}>{busy?'Wird gespeichert …':detail.ticket.id?'Antwort senden':'Anfrage senden'}</button>}</footer></>}
 </dialog></section>
}
