'use client'
import {useEffect,useRef,useState} from 'react'
import {evidencePending,browserEvidenceHash} from '../../lib/review-evidence-browser.mjs'
import {evidenceMaxBytes} from '../../lib/review-evidence-policy.mjs'
import './review-evidence-workspace.css'
const labels={NONE:'Noch nicht eingereicht',PENDING:'Wird geprüft',APPROVED:'Nachweis freigegeben',REJECTED:'Erneut einreichen'}
const date=value=>value?new Date(value).toLocaleDateString('de-DE'):'—'
export function ReviewEvidenceCustomer(){return <EvidenceWorkspace admin={false}/>}
export default function ReviewEvidenceWorkspace(){return <EvidenceWorkspace admin/>}
function EvidenceWorkspace({admin}){const endpoint=admin?'/api/admin/review-evidence':'/api/account/review-evidence';const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[filter,setFilter]=useState('ALL')
 async function load(){setLoading(true);setError('');try{const r=await fetch(endpoint,{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Nachweise konnten nicht geladen werden.');setData(b)}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[])
 const rows=(data?.rows??[]).filter(r=>filter==='ALL'||r.status===filter)
 return <section className="review-evidence-workspace"><header className="rew-heading"><div><span>{admin?'Kommunikation · Private Nachweise':'Deine ELYSERA-Erfahrung'}</span><h1>Bewertungsnachweise</h1><p>{admin?'Kundennachweise prüfen, freigeben oder mit einem nachvollziehbaren Grund zurückgeben.':'Reiche einen Screenshot deiner echten, selbst verfassten Bewertung zur Prüfung ein.'}</p></div><button onClick={load} disabled={loading}>Aktualisieren</button></header><p className="rew-note">Die Prüfung bestätigt den eingereichten Nachweis. Sie veröffentlicht keine Bewertung und löst keine Vergütung oder Prämie aus.</p>
 {admin&&<label className="rew-filter">Status<select aria-label="Nachweisstatus filtern" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Alle Nachweise</option>{['PENDING','REJECTED','APPROVED'].map(s=><option value={s} key={s}>{labels[s]}</option>)}</select></label>}
 {loading?<div className="rew-state" role="status">Nachweise werden geladen …</div>:error?<div className="rew-state" role="alert"><h2>Laden nicht möglich</h2><p>{error}</p><button onClick={load}>Erneut versuchen</button><a href={admin?'/auth/admin':'/auth/signin'}>Erneut anmelden</a></div>:!rows.length?<div className="rew-state"><h2>{admin?'Keine Nachweise vorhanden':'Noch keine geeignete Bestellung'}</h2><p>{admin?'Neue Einreichungen erscheinen hier.':'Eigene versendete oder zugestellte ELYSERA-Bestellungen erscheinen hier.'}</p></div>:<div className="rew-list">{rows.map(row=><article key={row.orderId}><div><strong>{admin?[row.firstName,row.secondName].filter(Boolean).join(' ')||'Kunde':'Bestellung'}</strong><span className="rew-order">{row.orderId}</span><small>{admin?row.email:date(row.createdAt)}</small></div><div><span className={'rew-status rew-'+(row.status||'NONE')}>{labels[row.status||'NONE']}</span>{row.rejectionReason&&<p>{row.rejectionReason}</p>}<small>{row.submittedAt?'Eingereicht am '+date(row.submittedAt):'Versendet oder zugestellt'}</small></div><button onClick={()=>setSelected(row)}>{admin?'Nachweis ansehen':row.status==='REJECTED'?'Erneut einreichen':row.id?'Nachweis ansehen':'Nachweis einreichen'}</button></article>)}</div>}
 {data?.limited&&<p className="rew-note">Anzeige auf 500 Einträge begrenzt.</p>}{selected&&<EvidenceDialog admin={admin} endpoint={endpoint} actorId={data.actorId} row={selected} close={()=>setSelected(null)} saved={s=>{setData(d=>({...d,rows:d.rows.map(r=>r.orderId===s.orderId?{...r,...s}:r)}));setSelected(r=>({...r,...s}))}}/>}</section>
}
function EvidenceDialog({admin,endpoint,actorId,row,close,saved}){const dialog=useRef(null),body=useRef(null);const storageKey=(admin?'admin:':'customer:')+actorId+':'+row.orderId;const [state,setState]=useState(row),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[imageUrl,setImageUrl]=useState(''),[imageReady,setImageReady]=useState(false),[imageLoading,setImageLoading]=useState(false),[confirmed,setConfirmed]=useState(false),[action,setAction]=useState('approve'),[reason,setReason]=useState(''),[pending,setPending]=useState(null),[review,setReview]=useState(false),[busy,setBusy]=useState(true),[conflict,setConflict]=useState(false),[auth,setAuth]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function loadImage(){setImageLoading(true);setImageReady(false);setImageUrl('');try{const response=await fetch(endpoint+'?id='+encodeURIComponent(row.orderId),{cache:'no-store'}),result=await response.json();if(!response.ok){if(response.status===401)setAuth(true);throw Error(result.error||'Bild konnte nicht geladen werden.')}if(!result.evidenceUrl)throw Error(result.imageError||'Bild konnte nicht geladen werden. Bitte erneut laden.');setImageUrl(result.evidenceUrl)}catch(e){setError(e.message||'Bild konnte nicht geladen werden. Bitte erneut laden.')}finally{setImageLoading(false)}}
 async function load(){setBusy(true);setReview(false);setError('');try{const r=await fetch(endpoint,{cache:'no-store'}),b=await r.json();if(!r.ok){if(r.status===401)setAuth(true);throw Error(b.error)}const current=b.rows.find(r=>r.orderId===row.orderId);if(!current)throw Error('Bestellung nicht mehr verfügbar.');setState(current);setConflict(false);setAuth(false);if(current.id)await loadImage()}catch(e){setError(e.message||'Stand konnte nicht geladen werden.')}finally{setBusy(false)}}
 useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();(async()=>{try{const stored=admin?JSON.parse(sessionStorage.getItem(storageKey)||'null'):await evidencePending(storageKey);if(stored){setPending(stored);if(admin){setAction(stored.action);setReason(stored.reason)}else{setFile(stored.blob);setConfirmed(true)}setMessage('Eine frühere Anfrage ist noch nicht bestätigt. Dieselbe Anfrage wiederholen.')}await load()}catch(e){setError(e.message)}})();return()=>previous?.focus()},[])
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
 useEffect(()=>{const target=body.current?.querySelector(auth?'.rew-auth':error?'.rew-error':review?'.rew-review':'[role="status"]');if(target&&body.current)body.current.scrollTo({top:body.current.scrollTop+target.getBoundingClientRect().top-body.current.getBoundingClientRect().top,behavior:'instant'})},[review,error,message,auth])
 async function write(){if(busy)return;setBusy(true);setError('');setMessage('');try{let stored=pending;if(!stored){const input={actorId,orderId:row.orderId,requestId:crypto.randomUUID(),expectedVersion:state.version||0,expectedStatus:state.status||'NONE'};if(admin)stored={...input,action,reason};else stored={request:{...input,confirmedOwnWords:true,fileHash:await browserEvidenceHash(file)},blob:file}}
 if(admin)sessionStorage.setItem(storageKey,JSON.stringify(stored));else await evidencePending(storageKey,stored);setPending(stored)
 let options;if(admin)options={method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(stored)};else{const form=new FormData();form.set('request',JSON.stringify(stored.request));form.set('file',stored.blob,'evidence-image');options={method:'POST',body:form}}
 const r=await fetch(endpoint,options);let b;try{b=await r.json()}catch{throw Error('Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}
 if(!r.ok){if(r.status===401)setAuth(true);if(r.status===409&&b.code==='STALE_VERSION'){if(admin)sessionStorage.removeItem(storageKey);else await evidencePending(storageKey,undefined,true);setPending(null);setConflict(true);setReview(false)}else if([400,404,413,415].includes(r.status)||(r.status===409&&['INVALID_STATE','INELIGIBLE_ORDER','PENDING_EXISTS'].includes(b.code))){if(admin)sessionStorage.removeItem(storageKey);else await evidencePending(storageKey,undefined,true);setPending(null);setReview(false);setConflict(true)}throw Error(b.error||'Ergebnis nicht bestätigt.')}
 if(!b.submission||b.submission.orderId!==row.orderId||!Number.isSafeInteger(b.submission.version))throw Error('Antwort nicht bestätigt. Dieselbe Anfrage erneut versuchen.')
 if(admin)sessionStorage.removeItem(storageKey);else await evidencePending(storageKey,undefined,true);setPending(null);setState(s=>({...s,...b.submission}));setReview(false);setAuth(false);setFile(null);setConfirmed(false);setMessage(b.replayed?'Frühere Anfrage bestätigt. Aktueller Stand geladen.':'Nachweis gespeichert und zurückgelesen.');saved(b.submission);await loadImage()
 }catch(e){setError(e.message||'Ergebnis nicht bestätigt. Dieselbe Anfrage erneut versuchen.')}finally{setBusy(false)}}
 const maySubmit=!admin&&['SHIPPED','DELIVERED'].includes(state.orderStatus)&&(!state.status||state.status==='REJECTED');const mayReview=admin&&state.status==='PENDING';const valid=admin?(action==='approve'?imageReady:reason.trim().length>=3):!!file&&confirmed
 return <dialog className={"rew-dialog"+(!maySubmit&&!mayReview&&!pending?" rew-readonly":"")} ref={dialog} aria-busy={busy} aria-labelledby="rew-dialog-title" onCancel={e=>{e.preventDefault();close()}}><header><div><span>Privater Bewertungsnachweis</span><h2 id="rew-dialog-title">{admin?'Nachweis prüfen':maySubmit?'Nachweis einreichen':'Dein Nachweis'}</h2></div><button aria-label="Nachweis schließen" onClick={close}>×</button></header><div className="rew-dialog-body" ref={body}><p className="rew-order">Bestellung {row.orderId}</p><p className="rew-status">{labels[state.status||'NONE']} · Version {state.version||0}</p>{state.rejectionReason&&<p className="rew-rejection">Grund der Rückgabe: {state.rejectionReason}</p>}
 {state.id&&<div className="rew-image"><h3>Gespeicherter Nachweis</h3>{imageUrl?<img src={imageUrl} alt="Privater Bewertungsnachweis" onLoad={()=>setImageReady(true)} onError={()=>{setImageReady(false);setError("Bild kann nicht angezeigt werden. Bitte erneut laden.")}}/>:<p>{imageLoading?'Gespeichertes Bild wird geladen …':'Bild derzeit nicht verfügbar.'}</p>}<button disabled={busy} onClick={load}>Bild erneut laden</button>{imageUrl&&<a href={imageUrl} target="_blank" rel="noopener noreferrer">Bild in Originalgröße öffnen</a>}<small>Privater Link, fünf Minuten gültig.</small></div>}
 {(maySubmit||mayReview||pending)&&<fieldset disabled={busy||!!pending||conflict}>{admin?<><label>Entscheidung<select aria-label="Entscheidung" value={action} onChange={e=>{setAction(e.target.value);setReview(false)}}><option value="approve">Nachweis freigeben</option><option value="reject">Nachweis zurückgeben</option></select></label><label>Begründung<textarea aria-label="Begründung der Nachweisprüfung" rows={3} maxLength={500} value={reason} onChange={e=>{setReason(e.target.value);setReview(false)}}/></label><p>Bei Rückgabe sind 3–500 Zeichen erforderlich. Der Kunde sieht diesen Grund.</p></>:<><label>Screenshot auswählen<input aria-label="Screenshot auswählen" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>evidenceMaxBytes){setError('Bild darf höchstens 3 MiB groß sein.');setFile(null);return}setFile(f||null);setReview(false);setError('')}}/></label><p>JPEG, PNG oder WebP · höchstens 3 MiB. Die Datei wird sicher als WebP verarbeitet.</p>{preview&&<div className="rew-image"><h3>Dein ausgewählter Screenshot</h3><img src={preview} alt="Vorschau des ausgewählten Nachweises"/></div>}<label className="rew-check"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setReview(false)}}/>Ich bestätige, dass die Bewertung echt ist und von mir in eigenen Worten ohne KI verfasst wurde.</label></>}</fieldset>}
 {review&&!pending&&<section className="rew-review"><h3>{admin?'Entscheidung prüfen':'Einreichung prüfen'}</h3><p>Bestellung {row.orderId}</p><p>{admin?(action==='approve'?'Nachweis freigeben.':'Nachweis zurückgeben: '+reason):'Den ausgewählten Screenshot als privaten Nachweis einreichen.'}</p><p>Keine Veröffentlichung, Vergütung oder Prämie wird ausgelöst.</p></section>}
 {error&&<p className="rew-error" role="alert">{error}</p>}{auth&&<div className="rew-auth"><p>{pending?(admin?'Die genaue Anfrage bleibt gespeichert.':'Die genaue Anfrage und das Bild bleiben gespeichert.'):'Der Nachweis ist gespeichert. Für den Bildabruf ist eine erneute Anmeldung erforderlich.'} Melde dich mit demselben Konto erneut an und öffne diese Bestellung wieder.</p></div>}{message&&<p role="status">{message}</p>}
 </div><footer><div className="rew-actions">{auth&&<a className="rew-primary" href={admin?'/auth/admin':'/auth/signin'}>Erneut anmelden</a>}{pending?<button className={auth?'':'rew-primary'} disabled={busy} onClick={write}>{busy?'Wird geprüft …':'Dieselbe Anfrage erneut versuchen'}</button>:conflict?<button className="rew-primary" disabled={busy} onClick={load}>Aktuellen Stand laden · Eingaben behalten</button>:(maySubmit||mayReview)?<button className="rew-primary" disabled={busy||!valid} onClick={()=>review?write():setReview(true)}>{busy?'Wird gespeichert …':review?(admin?'Entscheidung speichern':'Nachweis jetzt einreichen'):'Änderung prüfen'}</button>:<button disabled={busy} onClick={load}>Stand aktualisieren</button>}{review&&!pending&&!conflict&&<button disabled={busy} onClick={()=>setReview(false)}>Zurück zur Eingabe</button>}</div><button onClick={close}>Schließen</button></footer></dialog>
}
