import Link from 'next/link'
import {notFound} from 'next/navigation'
import {products} from '../catalog'
import {FAQ,Checkout,Icon,RoutineQuiz,TextureFilms,RoutineSet} from '../storefront'
import {CampaignImage} from '../campaign'
const pages=['routine','science','about','faq','checkout','quiz','presale','account','contact']
export function generateStaticParams(){return pages.map(page=>({page}))}
export async function generateMetadata({params}){const {page}=await params;return {title:({quiz:'Dein Pflege-Finder',routine:'Deine Routine',science:'Peptidwissen',about:'Die Marke',faq:'Fragen & Antworten',checkout:'Deine Auswahl',presale:'Presale & Lieferung',account:'Dein Konto',contact:'Kontakt & Hilfe'})[page]}}
export default async function Content({params}){
 const {page}=await params;if(!pages.includes(page))notFound()
 if(page==='quiz')return <RoutineQuiz/>
 if(page==='checkout')return <Checkout/>
 if(page==='faq')return <section className="section editorial"><div className="page-heading"><h1>Fragen?<br/><em>Wir sind bei dir.</em></h1><p>Von der ersten Anwendung bis zum Presale: Hier findest du die wichtigsten Antworten.</p></div><FAQ/><div className="service-cta"><p>Deine Frage ist noch offen? Wir zeigen dir den passenden Kontaktweg.</p><Link className="text-link" href="/contact/">KONTAKT & HILFE <Icon/></Link></div></section>
 if(page==='contact')return <section className="section editorial"><div className="route-banner"><div><h1>Wir sind<br/><em>für dich da.</em></h1><p>Du hast eine Frage zur Kollektion, zu deinem Konto oder zu einer bestehenden Bestellung? Hier findest du den passenden Weg.</p></div><CampaignImage name="contact-portrait" alt="Pflege als persönlicher Moment" priority/></div><div className="account-destinations"><article><h2>KONTAKT</h2><p>Das bestehende PeptiKing-Kontaktformular steht dir für deine Nachricht zur Verfügung. Nenne ELYSERA im Betreff, wenn sich deine Frage auf die neue Kollektion bezieht.</p><a className="button" href="https://www.peptiking.com/contact">PEPTIKING KONTAKT ÖFFNEN <Icon/></a></article><article><h2>DEINE BESTELLUNG</h2><p>Für Fragen zu einer bestehenden Bestellung halte deine Bestellnummer bereit. Deine Bestellübersicht findest du im PeptiKing-Konto.</p><a className="text-link" href="https://www.peptiking.com/dashboard/customer/orders">BESTELLUNGEN ANSEHEN <Icon/></a></article><article><h2>PFLEGE & PRESALE</h2><p>Antworten zu Anwendung, Reihenfolge und dem bevorstehenden Presale findest du in unseren häufigen Fragen.</p><Link className="text-link" href="/faq/">ZU DEN ANTWORTEN <Icon/></Link></article></div><p className="source-note">Das Kontaktformular öffnet sich auf peptiking.com. Auf dieser lokalen ELYSERA Seite werden keine Nachrichten versendet.</p></section>
 if(page==='account')return <section className="section editorial"><div className="route-banner account-banner"><div><h1>Deine Pflege.<br/><em>Dein Konto.</em></h1><p>Nutze deinen bestehenden PeptiKing-Zugang für dein Konto und deine Bestellübersicht.</p></div><CampaignImage name="hero-mobile" alt="Die ELYSERA Kollektion" priority/></div><div className="account-destinations">{[['MEIN KONTO','Melde dich mit deinen bestehenden PeptiKing-Zugangsdaten an.','https://www.peptiking.com/auth/signin','ZUM LOGIN'],['BESTELLUNGEN','Öffne deine bestehende PeptiKing-Bestellübersicht.','https://www.peptiking.com/dashboard/customer/orders','BESTELLUNGEN ANSEHEN']].map(([title,copy,href,cta])=><article key={title}><h2>{title}</h2><p>{copy}</p><a className="text-link" href={href}>{cta} <Icon/></a></article>)}</div><div className="account-selection"><p className="source-note">Die Links öffnen PeptiKing. Deine lokale ELYSERA Presale-Auswahl wird derzeit nicht an dein Konto übertragen.</p><Link className="button outline" href="/checkout/"><span>MEINE ELYSERA AUSWAHL</span><Icon/></Link></div></section>
 if(page==='presale')return <section className="section editorial"><div className="route-banner"><div><h1>Von Anfang<br/><em>an dabei.</em></h1><p>Presale ab 23.09.2026: die komplette Routine im 3er-Set für 139 € oder das Renewal Serum einzeln für 59 €. Toner und Eye Cream sind im Presale im Set erhältlich.</p></div><CampaignImage name="hero-mobile" alt="Toner, Serum und Eye Cream" priority/></div><div className="presale-steps">{[['01','ENTDECKEN','Lerne die Produkte, ihre Texturen und ihre Aufgaben in deiner Routine kennen.'],['02','AUSWÄHLEN','Stelle deine persönliche Auswahl zusammen. Sie bleibt auf diesem Gerät gespeichert – unverbindlich und ohne Zahlung.'],['03','BESTELLSTART','Der Presale startet am 23.09.2026. Versandkosten und verbindliche Lieferinformationen erhältst du vor dem Kauf.']].map(([n,h,p])=><article key={n}><span>{n}</span><h2>{h}</h2><p>{p}</p></article>)}</div><h2>PRESALE & LIEFERUNG</h2><table className="delivery-table"><thead><tr><th>Produkt</th><th>Geplante Auslieferung</th></tr></thead><tbody>{products.map(p=><tr key={p.slug}><td>{p.short}<br/>{p.volume}</td><td>{p.delivery}</td></tr>)}</tbody></table><p className="source-note">Die genannten Planungen sind noch keine verbindliche Lieferzusage. Versand, vollständige INCI und Verkaufsbedingungen folgen vor der Bestellfreigabe.</p><div className="routine-actions"><RoutineSet/><Link className="text-link" href="/shop/">PRODUKTE ENTDECKEN <Icon/></Link></div></section>
 if(page==='routine')return <><section className="section"><div className="page-heading"><h1>Drei Schritte.<br/><em>Ganz bei dir.</em></h1><p>Leichte Schichten. Eine klare Reihenfolge. Nach der Reinigung bekommt jeder Pflegeschritt seinen Platz.</p></div>{[products[1],products[0],products[2]].map(p=><article className="routine-detail" key={p.slug}><CampaignImage name={`routine-${p.step==='01'?'toner':p.step==='02'?'serum':'eye'}`} alt={`Illustrative Anwendung: ${p.short}`}/><div><span className="routine-step">SCHRITT {p.step}</span><h2>{p.name}</h2><p>{p.use}</p><p>{p.texture}</p><Link className="text-link" href={`/products/${p.slug}/`}>PRODUKT ENTDECKEN <Icon/></Link></div></article>)}<div className="routine-actions"><RoutineSet/></div></section><TextureFilms/></>
 if(page==='science')return <><section className="section editorial"><div className="page-heading"><h1>Verstehen,<br/>was deine Haut <em>pflegt.</em></h1><p>Die ELYSERA Serie verbindet ein Peptidkonzept mit Feuchtigkeit und angenehmen Texturen.</p></div><div className="science-feature"><div className="science-image"><CampaignImage name="serum-texture" alt="Illustrative blaue Serumtextur mit Glaspipette" priority/></div><div className="feature-copy"><h2>WAS IST<br/><em>GHK-Cu?</em></h2><p>Ein Komplex aus drei Aminosäuren und einem Kupferion. In der ELYSERA Serie ist er Teil aller drei Produkte; das Serum bildet den zentralen Peptidschritt.</p><p>Seine natürliche blaue Farbe macht die Serumtextur unverwechselbar.</p><Link className="text-link" href="/products/renewal-serum/">DAS SERUM ENTDECKEN <Icon/></Link></div></div><div className="knowledge-grid">{[['Peptide','Kurze Ketten aus Aminosäuren. Ihr Aufbau und die jeweilige Formulierung bestimmen ihre kosmetische Aufgabe.'],['Feuchtigkeit','Toner, Serum und Eye Cream kombinieren unterschiedliche Wasserbinder passend zu ihrem jeweiligen Pflegeschritt.'],['Die Gesamtformel','Einzelne Inhaltsstoffe erzählen nur einen Teil der Geschichte. Textur, Formulierung und Anwendung gehören dazu.']].map(([h,p])=><article key={h}><h2>{h}</h2><p>{p}</p></article>)}</div><p className="source-note">Grundlage: ELYSERA Master Coaching, September 2026. Forschung zu einzelnen Rohstoffen ist kein Wirksamkeitsnachweis für ein fertiges Produkt. Textur- und Anwendungsmotive sind KI-generierte Inszenierungen.</p></section><TextureFilms/></>
 return <><section className="skin-story"><div className="skin-story-image"><CampaignImage name="about-portrait" alt="Pflege als persönliches Ritual – illustrative Anwendung" priority/></div><div className="skin-story-copy"><h1>Aus Erfahrung.<br/>Mit <em>Überzeugung.</em></h1><p>25 Jahre Praxis mit Haut, Pflege und kosmetischen Konzepten stehen hinter der Idee von ELYSERA.</p><p>Eine klare Wirkstofflogik. Ein angenehmes Hautgefühl. Pflege, die im Alltag ihren Platz findet.</p></div></section><section className="section about-body"><h2>Wirkstofflogik.<br/>Hautgefühl.<br/><em>Alltag.</em></h2><div><p>ELYSERA verbindet Produkte mit klaren Aufgaben zu einer nachvollziehbaren Routine. Gezielte Kombinationen, leichte Texturen und durchdachtes Layering stehen im Mittelpunkt.</p><p>Denn gute Pflege soll sich nicht nur erklären lassen. Sie soll sich auch angenehm anfühlen.</p><Link className="button" href="/shop/">ENTDECKE DIE KOLLEKTION <Icon/></Link></div></section><div className="route-banner"><div><h2>Drei Produkte.<br/><em>Eine Idee.</em></h2><p>Vorbereiten, pflegen und gezielt ergänzen. Die erste Kollektion macht aus Wirkstoffen eine verständliche Routine.</p><Link className="text-link" href="/routine/">UNSERE ROUTINE <Icon/></Link></div><CampaignImage name="hero-mobile" alt="Die erste ELYSERA Kollektion"/></div></>
}
