 'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
const modes={register:{title:'Dein Konto beginnt hier.',intro:'Erstelle dein persönliches ELYSERA Konto.',button:'KONTO ERSTELLEN'},forgot:{title:'Ein neuer Zugang.',intro:'Wir senden dir einen Link, mit dem du dein Passwort neu festlegen kannst.',button:'LINK ANFORDERN'},verify:{title:'Bestätige dein Konto.',intro:'Bestätige deine E-Mail-Adresse, um dein Konto zu aktivieren.',button:'E-MAIL BESTÄTIGEN'},reset:{title:'Dein neues Passwort.',intro:'Lege ein neues Passwort für dein bestehendes Konto fest.',button:'PASSWORT SPEICHERN'},password:{title:'Dein Konto. Gut geschützt.',intro:'Die Änderung gilt überall, wo du dein bestehendes Konto verwendest.',button:'PASSWORT ÄNDERN'},resend:{title:'Deine Bestätigungs-E-Mail.',intro:'Fordere einen neuen Bestätigungslink an.',button:'E-MAIL ANFORDERN'}}
export default function AccountForm({mode}){
 const [email,setEmail]=useState(''),[name,setName]=useState(''),[last,setLast]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[currentPassword,setCurrent]=useState(''),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const config=modes[mode],hasPassword=['register','reset','password'].includes(mode)
 useEffect(()=>{const t=new URLSearchParams(location.hash.slice(1)).get('token')||'';setToken(t);if(location.hash)history.replaceState(null,'',location.pathname)},[])
 async function submit(e){e.preventDefault();setError('');if(hasPassword&&password!==repeat){setError('Die Passwörter stimmen nicht überein.');return}setBusy(true);try{const r=await fetch('/api/auth/account/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,name,last,password,currentPassword,token})});const b=await r.json();if(!r.ok)throw Error(b.error||'Bitte erneut versuchen.');setMessage(b.message);setPassword('');setRepeat('');setCurrent('');setToken('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="es-login"><Link href="/" className="es-logo">ELYSERA<small>SKINCARE</small></Link><div className="es-login-grid"><section className="es-login-photo"><img src="/media/wavespeed-4k/hero-desktop.webp" alt="ELYSERA Peptidpflege"/><div><span>DEIN PERSÖNLICHER BEREICH</span><h2>Schönheit verbindet.<br/>Willkommen bei ELYSERA.</h2></div></section><section className="es-login-form"><span className="es-kicker">DEIN ELYSERA KONTO</span><h1>{config.title}</h1><p>{config.intro}</p>{message?<><p className="es-success" role="status">{message}</p><Link className="es-back" href="/auth/signin">Zur Anmeldung →</Link>{['register','resend','forgot'].includes(mode)&&<button className="es-back es-text-button" onClick={()=>setMessage('')}>Erneut anfordern</button>}</>:<form onSubmit={submit}>{mode==='register'&&<><label>Vorname<input autoComplete="given-name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>Nachname<input autoComplete="family-name" maxLength={80} value={last} onChange={e=>setLast(e.target.value)}/></label></>}{['register','forgot','resend'].includes(mode)&&<label>E-Mail-Adresse<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode==='password'&&<label>Aktuelles Passwort<input type="password" autoComplete="current-password" required maxLength={1024} value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label>}{hasPassword&&<><label>Neues Passwort<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} aria-describedby="password-rule"/></label><p className="es-help" id="password-rule">Mindestens 12 Zeichen. Verwende ein eigenes, langes Passwort.</p><label>Passwort wiederholen<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={repeat} onChange={e=>setRepeat(e.target.value)}/></label></>}{['verify','reset'].includes(mode)&&!token&&<p className="es-error">Öffne den Link aus deiner E-Mail. Fehlt er oder ist er abgelaufen, fordere einen neuen Link an.</p>}{error&&<p className="es-error" role="alert">{error}</p>}<button className="es-submit" disabled={busy||(['verify','reset'].includes(mode)&&!token)}>{busy?'BITTE WARTEN …':config.button}<span>→</span></button></form>}{mode==='register'&&<Link className="es-back" href="/auth/signin">Mit Google registrieren →</Link>}<nav className="es-account-links" aria-label="Kontohilfe"><Link href="/auth/signin">Anmelden</Link>{mode!=='register'&&<Link href="/auth/register">Konto erstellen</Link>}{['register','verify','resend'].includes(mode)?<Link href="/auth/resend">Bestätigung erneut senden</Link>:<Link href="/auth/forgot-password">Neuen Passwort-Link anfordern</Link>}</nav></section></div><footer>ELYSERA · SCHÖNHEIT VERBINDET</footer></main>
}
