'use client'
import PhoneField from './phone-field'
import CompactSelect from './compact-select'
import AddressSearch from './address-search'
import {countries} from '../../lib/auth/countries.mjs'
export default function PersonalFields({value,onChange,optional=false,names=false}){
 const field=(key,label,autoComplete,type='text',maxLength=100)=> <label key={key}>{label}<input type={type} autoComplete={autoComplete} required value={value[key]||''} maxLength={maxLength} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>
 return <div className="es-details-fields">{names&&<div className="es-details-row">{field('name','Vorname','given-name','text',80)}{field('last','Nachname','family-name','text',80)}</div>}<h3>Deine Adresse</h3><CompactSelect label="Land" required searchable value={value.country||''} onChange={country=>onChange({...value,country})} options={value.country&&!countries.some(country=>country.value===value.country)?[value.country,...countries]:countries} placeholder="Land auswählen"/><div className="es-details-row"><AddressSearch mode="postcode" value={value} onChange={onChange}/>{field('city','Ort','address-level2')}</div><AddressSearch value={value} onChange={onChange}/>{field('houseNumber','Hausnummer','address-line2','text',30)}{optional&&<><PhoneField value={value.phone||''} country={value.country} onChange={phone=>onChange({...value,phone})}/><div className="es-details-row"><label>Geburtsdatum<input type="date" autoComplete="bday" min="1900-01-01" max={new Date().toISOString().slice(0,10)} value={value.birthDate||''} onChange={e=>onChange({...value,birthDate:e.target.value})}/></label><CompactSelect label="Geschlecht" value={value.gender||''} onChange={gender=>onChange({...value,gender})} options={[{value:'',label:'Bitte wählen'},{value:'female',label:'Weiblich'},{value:'male',label:'Männlich'},{value:'diverse',label:'Divers'},{value:'undisclosed',label:'Keine Angabe'}]}/></div></>}</div>
}
