'use client'
import PhoneField from './phone-field'
import CompactSelect from './compact-select'
import AddressSearch from './address-search'
const regionNames=new Intl.DisplayNames(['de'],{type:'region'});
const countries='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ').map(code=>regionNames.of(code)).sort((a,b)=>a.localeCompare(b,'de'));
export default function PersonalFields({value,onChange,optional=false,names=false}){
 const field=(key,label,autoComplete,type='text',maxLength=100)=> <label key={key}>{label}<input type={type} autoComplete={autoComplete} required value={value[key]||''} maxLength={maxLength} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>
 return <div className="es-details-fields">{names&&<div className="es-details-row">{field('name','Vorname','given-name','text',80)}{field('last','Nachname','family-name','text',80)}</div>}<h3>Deine Adresse</h3><div className="es-details-row"><AddressSearch mode="postcode" value={value} onChange={onChange}/>{field('city','Ort','address-level2')}</div><AddressSearch value={value} onChange={onChange}/>{field('houseNumber','Hausnummer','address-line2','text',30)}<CompactSelect label="Land" required searchable value={value.country||''} onChange={country=>onChange({...value,country})} options={value.country&&!countries.includes(value.country)?[value.country,...countries]:countries} placeholder="Land auswählen"/>{optional&&<><h3>Weitere Angaben <small>optional</small></h3><PhoneField value={value.phone||''} country={value.country} onChange={phone=>onChange({...value,phone})}/><div className="es-details-row"><label>Geburtsdatum<input type="date" autoComplete="bday" min="1900-01-01" max={new Date().toISOString().slice(0,10)} value={value.birthDate||''} onChange={e=>onChange({...value,birthDate:e.target.value})}/></label><CompactSelect label="Geschlecht" value={value.gender||''} onChange={gender=>onChange({...value,gender})} options={[{value:'',label:'Bitte wählen'},{value:'female',label:'Weiblich'},{value:'male',label:'Männlich'},{value:'diverse',label:'Divers'},{value:'undisclosed',label:'Keine Angabe'}]}/></div></>}</div>
}
