export const presale = {start:'23.09.2026',setPrice:139,serumPrice:59}
export const presalePriceLabel = slug => slug === 'renewal-serum' ? '59 € einzeln' : 'Im 3er-Set für 139 €'
export const products = [
  {slug:'renewal-serum',short:'Renewal Serum',name:'GHK-Cu Renewal Serum',volume:'30 ml',format:'Pipette',step:'02',role:'Der zentrale Peptidschritt.',image:'/media/wavespeed-4k/serum.webp',description:'Eine leichte Textur. Ein durchdachtes Peptidkonzept. Das Renewal Serum steht im Zentrum deiner ELYSERA Routine und verbindet GHK-Cu mit ergänzenden Pflegewirkstoffen.',ingredients:['GHK-Cu','Acetyl Hexapeptide-8','Zwei-Stufen-Hyaluron','Niacinamid','Ectoin','Panthenol'],use:'Nach dem Toner dünn auftragen und sanft verteilen. Kurz einziehen lassen, bevor du die nächste Pflegeschicht oder Make-up aufträgst.',texture:'Leichtes Serum mit natürlich blauer Farbe durch den kupfergebundenen GHK-Cu-Komplex.',delivery:'Auslieferung für Mitte Oktober 2026 geplant.'},
  {slug:'balance-toner',short:'Balance Toner',name:'Balance Prepeptide Toner',volume:'100 ml',format:'Spray',step:'01',role:'Ein frischer Anfang für deine Haut.',image:'/media/wavespeed-4k/toner.webp',description:'Der erste Schritt nach der Reinigung. Eine leichte, feuchtigkeitsspendende Vorbereitung, die sich direkt aufsprühen lässt und die Haut auf dein Serum vorbereitet.',ingredients:['Polyglutaminsäure','Hyaluron','Betaine','Sodium PCA','Trehalose','Niacinamid','Ectoin'],use:'Nach der Reinigung direkt aufsprühen. Mit sauberen Händen sanft verteilen und kurz einziehen lassen. Anschließend folgt das Serum.',texture:'Feiner Sprühnebel und eine leichte, fettarme Textur. Ohne Wattepad auftragen.',delivery:'Der Liefertermin wird vor Bestellstart bekannt gegeben.'},
  {slug:'contour-eye-cream',short:'Contour Eye Cream',name:'Contour Lift Eye Cream',volume:'15 ml',format:'Tube',step:'03',role:'Besondere Pflege. Für deinen Blick.',image:'/media/wavespeed-4k/eye.webp',description:'Eine eigenständige Formulierung für die Augenpartie. Die leichte, ungetönte Pflege ergänzt deine Routine lokal mit Peptiden, Koffein und einer geschmeidigen Pflegebasis.',ingredients:['GHK-Cu','Acetyl Hexapeptide-8','Dipeptide-2','Palmitoyl Tripeptide-1','Palmitoyl Tetrapeptide-7','Koffein','Squalan'],use:'Zum Abschluss eine dünne Menge sanft an der Augenpartie einklopfen. Vor Concealer kurz einziehen lassen.',texture:'Leichte Creme ohne Tönung. Für lokale Pflege ohne eine schwere Schicht.',delivery:'Der Liefertermin wird vor Bestellstart bekannt gegeben.'},
]
export const faqs = [
 ['Welche Pflege passt zu meinen Hautbedürfnissen?','Der Toner ergänzt Feuchtigkeit bei Spannungsgefühl und feuchtigkeitsarmen Partien. Das Serum ist der zentrale Peptidschritt für Pflegeziele wie Glätte und ein gleichmäßiger wirkendes Hautbild. Die Augencreme pflegt eine trocken oder müde wirkende Augenpartie lokal. Auf jeder Produktseite findest du die Hautbedürfnisse und das Pflegegefühl im Detail.'],
 ['Was kann ich von der Routine erwarten?','Die Routine verbindet Feuchtigkeit, leichte Texturen und Peptidpflege. Festigkeit, Regeneration, Beruhigung, Glätte, Mimikfältchen und Ebenmäßigkeit beschreiben kosmetische Pflegeziele. Sichtbare Ergebnisse können variieren; Rohstoffforschung ist kein Wirksamkeitsnachweis für das fertige Produkt.'],
 ['Enthält auch der Toner Niacinamid?','Ja. Laut ELYSERA Master Coaching ergänzt Niacinamid die Feuchtigkeitsbasis des Toners. Im Renewal Serum gehört es ebenfalls zum Wirkstoffkonzept. Die Produkte haben unterschiedliche Formulierungen.'],
 ['Was bedeutet Matrixyl-3000-Logik bei der Augencreme?','Das ELYSERA Coaching fasst damit Palmitoyl Tripeptide-1 und Palmitoyl Tetrapeptide-7 zusammen. Die Produktseite nennt die beiden Peptide einzeln. Die Bezeichnung erklärt das Peptidkonzept und ersetzt keine vollständige INCI-Liste.'],
 ['In welcher Reihenfolge verwende ich die Produkte?','Nach der Reinigung beginnt die Routine mit dem Balance Prepeptide Toner. Danach folgt das Renewal Serum. Die Contour Lift Eye Cream wird zum Schluss lokal an der Augenpartie sanft eingeklopft.'],
 ['Warum ist das Serum blau?','Die blaue Farbe gehört zum kupfergebundenen GHK-Cu-Komplex, einem charakteristischen Bestandteil der ELYSERA Serie.'],
 ['Kann ich danach Make-up verwenden?','Die Routine ist auf leichte Schichten ausgelegt. Dünn auftragen und jede Schicht kurz einziehen lassen. Zu viel Produkt oder starkes Reiben kann Röllchenbildung begünstigen.'],
 ['Wie funktioniert der Presale?','Der Presale startet am 23.09.2026. Das 3er-Set kostet 139 €, das Renewal Serum einzeln 59 €. Toner und Eye Cream sind im Presale im 3er-Set erhältlich. Für das Renewal Serum ist die Auslieferung Mitte Oktober 2026 geplant. Die Liefertermine von Toner und Eye Cream werden separat bekannt gegeben.'],
 ['Kann ich mein Konto verwenden?','Dein bestehendes Konto bleibt der Zugang zu deiner Bestellübersicht. Über „Mein Konto“ gelangst du zum bestehenden Login.'],
 ['Wo finde ich die vollständigen Inhaltsstoffe?','Die Produktseiten zeigen die Wirkstoffschwerpunkte aus dem Marken-Coaching. Die vollständigen INCI-Listen werden vor der Bestellfreigabe ergänzt.'],
]
