'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {useAutoAdvance} from './auto-carousel'
import {products} from './catalog'
import {CampaignMotion} from './campaign'
const root='/media/renewal-2026/'
const slides=[{image:'hero',title:<>Deine Haut.<br/><em>Dein Ritual.</em></>,copy:'Toner, Serum & Augenpflege. Drei Schritte für deinen täglichen Pflegemoment.',href:'/shop/',cta:'Kollektion entdecken',label:'Kollektion'},...products.map(p=>({image:p.step==='01'?'toner':p.step==='02'?'serum':'eye',title:p.step==='01'?<>EIN FRISCHER<br/><em>ANFANG.</em></>:p.step==='02'?<>DEIN TÄGLICHER<br/><em>PEPTIDMOMENT.</em></>:<>PFLEGE FÜR<br/><em>DEINEN BLICK.</em></>,copy:p.role,href:`/products/${p.slug}/`,cta:p.short.toUpperCase()+' ENTDECKEN',label:p.short}))]
export function ExperienceHero(){
 const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[reduce,setReduce]=useState(true),[visible,setVisible]=useState(true),[engaged,setEngaged]=useState(false)
 const film=useRef(null),stage=useRef(null),s=slides[active]
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduce(media.matches);update();media.addEventListener('change',update);const io=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting&&!document.hidden),{threshold:.2});io.observe(stage.current);const visibility=()=>setVisible(!document.hidden&&stage.current.getBoundingClientRect().bottom>0);document.addEventListener('visibilitychange',visibility);return()=>{media.removeEventListener('change',update);io.disconnect();document.removeEventListener('visibilitychange',visibility)}},[])
 const [allPaused,setAllPaused]=useState(false)
 useEffect(()=>{const update=()=>setAllPaused(document.documentElement.dataset.motionPaused==='true');update();document.addEventListener('elysera-motion',update);return()=>document.removeEventListener('elysera-motion',update)},[])
 const running=!paused&&!reduce&&visible&&!allPaused
 const [mobile,setMobile]=useState(false)
 useEffect(()=>{const mq=matchMedia('(max-width:700px)');const update=()=>setMobile(mq.matches);update();mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update)},[])
 useEffect(()=>{const video=film.current;if(!video)return;if(running){video.play()?.catch(()=>{})}else video.pause()},[running,active,mobile])

 const select=i=>{setActive(i);setPaused(false)}
 return <section ref={stage} className={`experience-hero ${active===0?'collection-scene':'single-scene'}`} aria-label="ELYSERA Kollektion" aria-roledescription="Karussell" onMouseEnter={()=>setEngaged(true)} onMouseLeave={()=>setEngaged(false)} onFocusCapture={()=>setEngaged(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setEngaged(false)}}>
 <div key={active} className="experience-art" data-running={running}><picture>{active===0&&<source media="(max-width:700px)" srcSet="/media/renewal-2026/hero-mobile.webp"/>}<img src={active===0?"/media/renewal-2026/hero.webp":`${root}${s.image}.webp`} alt={active===0?'Die drei ELYSERA Produkte auf Glas im Wasser':s.label} fetchPriority="high"/></picture>{!reduce&&<video ref={film} key={s.image+mobile} src={`${root}${active===0?(mobile?'hero-mobile':'hero'):s.image}.mp4`} poster={`${root}${active===0?(mobile?'hero-mobile':'hero'):s.image}.webp`} autoPlay muted playsInline loop preload="auto" aria-hidden="true"/>}</div>
 <div className="experience-copy" key={`copy-${active}`}><h1>{s.title}</h1><p>{s.copy}</p><Link className="button" href={s.href}>{s.cta}<span aria-hidden="true">→</span></Link><Link className="experience-presale" href="/presale/">Alle drei im Presale · Preise folgen</Link></div>
 <div className="experience-controls"><div className="campaign-tabs" aria-label="Kampagnenmotiv auswählen">{slides.map((slide,i)=><button key={slide.label} aria-pressed={active===i} onClick={()=>select(i)}><span>{String(i+1).padStart(2,'0')}</span><span>{slide.label}</span>{active===i&&<i key={`${active}-${running}`} style={{animationPlayState:running?'running':'paused'}}/>}</button>)}</div><button className="campaign-pause" disabled={reduce} aria-label={reduce?'Animation bei reduzierter Bewegung deaktiviert':paused?'Hero-Animation abspielen':'Hero-Animation pausieren'} onClick={()=>setPaused(p=>!p)}>{reduce?'Bewegung reduziert':paused?'Abspielen':'Pause'}</button></div>
 </section>
}
export function RoutineExperience({compact=false}){const ref=useRef(null);const [step,setStep]=useState(0),[view,setView]=useState('product');useAutoAdvance(ref,()=>{setStep(i=>(i+1)%3);setView('product')},8000);const p=[products[1],products[0],products[2]][step],key=['toner','serum','eye'][step];return <section ref={ref} className="routine-experience" aria-label="Interaktive Pflegeroutine">{!compact&&<div className="routine-experience-heading"><h2>Drei Schritte.<br/><em>Dein Ritual.</em></h2><p>Wähle deinen Pflegeschritt. Entdecke Produkt und Textur.</p></div>}<div className="routine-experience-grid"><div className="routine-reveal routine-visual" key={key}><CampaignMotion key={key+view} name={view==='texture'?key+'-texture':key} alt={view==='texture'?'Illustrative Textur: '+p.short:p.name}/><div className="routine-view-tabs" role="group" aria-label="Produkt oder Textur ansehen"><button aria-pressed={view==='product'} onClick={()=>setView('product')}>DAS PRODUKT</button><button aria-pressed={view==='texture'} onClick={()=>setView('texture')}>DIE TEXTUR</button></div></div><div className="routine-experience-copy">{compact&&<h2>Deine tägliche Pflegeroutine</h2>}<div className="routine-step-tabs" aria-label="Pflegeschritt auswählen">{['Vorbereiten','Pflegen','Ergänzen'].map((label,i)=><button key={label} aria-pressed={step===i} onClick={()=>{setStep(i);setView('product')}}><span>0{i+1}</span>{label}</button>)}</div><div className="routine-step-content" key={key}><h3>{p.name}</h3><p>{compact?p.role:p.use}</p><p className="muted">{p.texture}</p><Link className="button outline" href={`/products/${p.slug}/`}>DAS PRODUKT ENTDECKEN →</Link></div>{!compact&&<p className="reveal-instruction">Entdecke das Produkt und seine Textur – wähle deine Ansicht.</p>}<Link className="text-link" href="/routine/">DER KOMPLETTE ROUTINE-GUIDE →</Link></div></div></section>}
