'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {products} from './catalog'
const root='/media/campaign-2026/'
const slides=[{image:'hero',title:<>MEHR ALS<br/><em>SKINCARE.</em></>,copy:'Drei gezielte Pflegeschritte. Ein neues Gefühl für deine Routine.',href:'/shop/',cta:'DIE KOLLEKTION ENTDECKEN',label:'Kollektion'},...products.map(p=>({image:p.step==='01'?'toner':p.step==='02'?'serum':'eye',title:p.step==='01'?<>EIN FRISCHER<br/><em>ANFANG.</em></>:p.step==='02'?<>DEIN TÄGLICHER<br/><em>PEPTIDMOMENT.</em></>:<>PFLEGE FÜR<br/><em>DEINEN BLICK.</em></>,copy:p.role,href:`/products/${p.slug}/`,cta:p.short.toUpperCase()+' ENTDECKEN',label:p.short}))]
export function ExperienceHero(){
 const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[reduce,setReduce]=useState(true),[visible,setVisible]=useState(true),[engaged,setEngaged]=useState(false)
 const film=useRef(null),stage=useRef(null),s=slides[active]
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduce(media.matches);update();media.addEventListener('change',update);const io=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting&&!document.hidden),{threshold:.2});io.observe(stage.current);const visibility=()=>setVisible(!document.hidden&&stage.current.getBoundingClientRect().bottom>0);document.addEventListener('visibilitychange',visibility);return()=>{media.removeEventListener('change',update);io.disconnect();document.removeEventListener('visibilitychange',visibility)}},[])
 const running=!paused&&!reduce&&visible
 useEffect(()=>{const video=film.current;if(!video)return;if(running){video.play()?.catch(()=>{})}else video.pause()},[running,active])

 const select=i=>{setActive(i);setPaused(false)}
 return <section ref={stage} className={`experience-hero ${active===0?'collection-scene':'single-scene'}`} aria-label="ELYSERA Kollektion" aria-roledescription="Karussell" onMouseEnter={()=>setEngaged(true)} onMouseLeave={()=>setEngaged(false)} onFocusCapture={()=>setEngaged(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setEngaged(false)}}>
 <div key={active} className="experience-art" data-running={running}><picture>{active===0&&<source media="(max-width:700px)" srcSet="/media/midnight-2026/hero-mobile.webp"/>}<img src={active===0?"/media/midnight-2026/hero.webp":`${root}${s.image}.webp`} alt={active===0?'Die drei ELYSERA Produkte auf Glas im Wasser':s.label} fetchPriority="high"/></picture>{active===0&&!reduce&&<video ref={film} src="/media/midnight-2026/hero.mp4" poster="/media/midnight-2026/hero.webp" autoPlay muted playsInline loop preload="auto" aria-hidden="true"/>}</div>
 <div className="experience-copy" key={`copy-${active}`}><h1>{s.title}</h1><p>{s.copy}</p><Link className="button" href={s.href}>{s.cta}<span aria-hidden="true">→</span></Link><Link className="experience-presale" href="/presale/">Alle drei im Presale · Preise folgen</Link></div>
 <div className="experience-controls"><div className="campaign-tabs" aria-label="Kampagnenmotiv auswählen">{slides.map((slide,i)=><button key={slide.label} aria-pressed={active===i} onClick={()=>select(i)}><span>{String(i+1).padStart(2,'0')}</span><span>{slide.label}</span>{active===i&&<i key={`${active}-${running}`} style={{animationPlayState:running?'running':'paused'}}/>}</button>)}</div><button className="campaign-pause" disabled={reduce} aria-label={reduce?'Animation bei reduzierter Bewegung deaktiviert':paused?'Hero-Animation abspielen':'Hero-Animation pausieren'} onClick={()=>setPaused(p=>!p)}>{reduce?'Bewegung reduziert':paused?'Abspielen':'Pause'}</button></div>
 </section>
}
export function RoutineExperience(){const [step,setStep]=useState(0),[reveal,setReveal]=useState(50);const p=[products[1],products[0],products[2]][step],key=['toner','serum','eye'][step];return <section className="routine-experience" aria-label="Interaktive Pflegeroutine"><div className="routine-experience-heading"><h2>DREI SCHRITTE.<br/><em>DEIN RITUAL.</em></h2><p>Wähle deinen Pflegeschritt. Entdecke Produkt und Textur.</p></div><div className="routine-experience-grid"><div className="routine-reveal" key={key}><img src={`${root}${key}.webp`} alt={p.name}/><img className="revealed-texture" src={`${root}${key}-texture.webp`} alt={`Illustrative Textur: ${p.short}`} style={{clipPath:`inset(0 0 0 ${reveal}%)`}}/><span className="reveal-label label-product">PRODUKT</span><span className="reveal-label label-texture">TEXTUR</span><div className="reveal-divider" style={{left:`${reveal}%`}}><span aria-hidden="true">↔</span></div><input type="range" min="0" max="100" value={reveal} aria-label="Produkt und Textur vergleichen" onChange={e=>setReveal(Number(e.target.value))}/></div><div className="routine-experience-copy"><div className="routine-step-tabs" aria-label="Pflegeschritt auswählen">{['Vorbereiten','Pflegen','Ergänzen'].map((label,i)=><button key={label} aria-pressed={step===i} onClick={()=>{setStep(i);setReveal(50)}}><span>0{i+1}</span>{label}</button>)}</div><div className="routine-step-content" key={key} aria-live="polite"><h3>{p.name}</h3><p>{p.use}</p><p className="muted">{p.texture}</p><Link className="button outline" href={`/products/${p.slug}/`}>DAS PRODUKT ENTDECKEN →</Link></div><p className="reveal-instruction">Schiebe den Regler im Bild und entdecke die Textur.</p><Link className="text-link" href="/routine/">DER KOMPLETTE ROUTINE-GUIDE →</Link></div></div></section>}
