'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {usePathname} from 'next/navigation'
import {products} from './catalog'
function Glyph({name}){return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name==='search'?<><circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/></>:name==='account'?<><circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></>:name==='bag'?<><path d="M5 8h14l1 13H4L5 8Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></>:<path d="M3 6h18M3 12h18M3 18h18"/>}</svg>}
const notices=['PRESALE AB 23. SEPTEMBER 2026','DREI PFLEGESCHRITTE. EIN TÄGLICHES RITUAL.','DIE ELYSERA KOLLEKTION ENTDECKEN']
export default function Navigation({count,openPanel}){
 const [menu,setMenu]=useState(null),[notice,setNotice]=useState(0),pathname=usePathname(),header=useRef(null),trigger=useRef(null)
 useEffect(()=>setMenu(null),[pathname])
 useEffect(()=>{if(!menu)return;const close=e=>{if(!header.current?.contains(e.target))setMenu(null)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[menu])
 const toggle=(name,e)=>{trigger.current=e.currentTarget;setMenu(m=>m===name?null:name)}
 const open=p=>{setMenu(null);openPanel(p)}
 const links=menu==='house'?[['/about','Die Marke'],['/science','Peptidwissen'],['/faq','Fragen & Antworten'],['/contact','Kontakt']]:menu==='experience'?[['/routine','Die drei Pflegeschritte'],['/quiz','Deine persönliche Pflege'],['/science','Wirkstoffe kennenlernen']]:[['/shop','Die gesamte Kollektion'],...products.map(p=>[`/products/${p.slug}`,p.short]),['/presale','Presale & Lieferung']]
 return <><div className="lp-announcement"><button aria-label="Vorherige Mitteilung" onClick={()=>setNotice(n=>(n+2)%3)}>‹</button><Link href={notice===0?'/presale':notice===1?'/routine':'/shop'} aria-live="polite">{notices[notice]}</Link><button aria-label="Nächste Mitteilung" onClick={()=>setNotice(n=>(n+1)%3)}>›</button></div>
 <header ref={header} className="lp-header" onKeyDown={e=>{if(e.key==='Escape'){setMenu(null);trigger.current?.focus()}}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setMenu(null)}}>
 <div className="lp-header-top"><div className="lp-locale"><span>DEUTSCHLAND | DE</span><Link href="/contact">KONTAKT</Link></div><div className="lp-mobile-tools"><button className="lp-icon" aria-label="Menü öffnen" onClick={()=>open('menu')}><Glyph name="menu"/></button><button className="lp-icon" aria-label="Produkte suchen" onClick={()=>open('search')}><Glyph name="search"/></button></div><Link href="/" className="lp-wordmark" aria-label="ELYSERA Startseite">ELYSERA<small>SKINCARE</small></Link><div className="lp-header-actions"><button className="lp-icon lp-desktop-search" aria-label="Produkte suchen" onClick={()=>open('search')}><Glyph name="search"/></button><Link className="lp-icon lp-account" href="/account" aria-label="Mein Konto"><Glyph name="account"/></Link><button className="lp-icon lp-bag" aria-label={`Warenkorb, ${count} Produkte`} onClick={()=>open('cart')}><Glyph name="bag"/>{count>0&&<span>{count}</span>}</button></div></div>
 <nav className="lp-nav" aria-label="Hauptnavigation"><button aria-expanded={menu==='shop'} aria-controls="lp-mega" onClick={e=>toggle('shop',e)}>SHOP</button><button aria-expanded={menu==='experience'} aria-controls="lp-mega" onClick={e=>toggle('experience',e)}>PFLEGERITUAL</button><Link href="/presale">PRESALE</Link><button aria-expanded={menu==='house'} aria-controls="lp-mega" onClick={e=>toggle('house',e)}>DIE MARKE</button></nav>
 {menu&&<div className="lp-mega" id="lp-mega"><nav aria-label="Untermenü"><h2>{menu==='shop'?'DIE KOLLEKTION':menu==='experience'?'DEIN PFLEGERITUAL':'DIE WELT VON ELYSERA'}</h2>{links.map(([href,label])=><Link key={href} href={href} onClick={()=>setMenu(null)}>{label}</Link>)}</nav><div className="lp-mega-products">{products.map(p=><Link key={p.slug} href={`/products/${p.slug}`} onClick={()=>setMenu(null)}><img src={`/media/atelier-2026/${p.step==='01'?'toner':p.step==='02'?'serum':'eye'}.webp`} alt={p.name}/><span>{p.short}</span></Link>)}</div><button className="lp-icon lp-mega-close" aria-label="Navigationsmenü schließen" onClick={()=>{setMenu(null);trigger.current?.focus()}}>×</button></div>}
 </header></>
}
