'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {usePathname} from 'next/navigation'
import {products} from './catalog'
const peptiking=process.env.NEXT_PUBLIC_PEPTIKING_URL||'https://www.peptiking.com'
function Glyph({name}){return <svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name==='search'?<><circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/></>:name==='account'?<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="9" r="3"/><path d="M6 18a6 6 0 0 1 12 0"/></>:name==='bag'?<><path d="m3 7 2 14h14l2-14Z"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/></>:<path d="M3 6h18M3 12h18M3 18h18"/>}</svg>}
export default function Navigation({count,openPanel}){
 const [menu,setMenu]=useState(null),pathname=usePathname(),header=useRef(null),trigger=useRef(null)
 useEffect(()=>setMenu(null),[pathname])
 useEffect(()=>{if(!menu)return;const close=e=>{if(!header.current?.contains(e.target))setMenu(null)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[menu])
 const toggle=(name,e)=>{trigger.current=e.currentTarget;setMenu(m=>m===name?null:name)}
 const open=p=>{setMenu(null);openPanel(p)}
 return <><div className="presale-announcement"><span>Die erste ELYSERA Kollektion</span><Link href="/presale/">Presale · Jetzt entdecken</Link><span>Drei Produkte. Deine Routine.</span></div><header ref={header} className={`reference-header ${pathname==='/'?'home-header':''}`} onKeyDown={e=>{if(e.key==='Escape'){setMenu(null);trigger.current?.focus()}}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setMenu(null)}}>
 <nav className="reference-links" aria-label="Hauptnavigation"><button aria-expanded={menu==='shop'} aria-controls="navigation-dropdown" onClick={e=>toggle('shop',e)}>SHOP</button><button aria-expanded={menu==='routine'} aria-controls="navigation-dropdown" onClick={e=>toggle('routine',e)}>DIE ROUTINE</button><Link href="/quiz/">QUIZ</Link><button aria-expanded={menu==='discover'} aria-controls="navigation-dropdown" onClick={e=>toggle('discover',e)}>ENTDECKEN <span aria-hidden="true">⌄</span></button></nav>
 <button className="reference-mobile icon-button" aria-label="Menü öffnen" onClick={()=>open('menu')}><Glyph name="menu"/></button><Link className="reference-wordmark" aria-label="ELYSERA Startseite" href="/"><svg className="elysera-original-logo" viewBox="670 8 196 208" aria-hidden="true" focusable="false"><defs><filter id="elysera-gold" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  4 0 0 0 -1"/></filter></defs><image href="/media/midnight-2026/logo-reference.png" width="1536" height="1024" filter="url(#elysera-gold)"/></svg></Link>
 <div className="reference-actions"><button className="icon-button" aria-label="Produkte suchen" onClick={()=>open('search')}><Glyph name="search"/></button><Link className="icon-button reference-account" href="/account/" aria-label="Mein Konto bei PeptiKing"><Glyph name="account"/></Link><button className="icon-button bag" aria-label={`Warenkorb, ${count} Produkte`} onClick={()=>open('cart')}><Glyph name="bag"/>{count>0&&<span key={count}>{count}</span>}</button></div>
 {menu&&<div id="navigation-dropdown" className="navigation-dropdown" key={menu}><div className="dropdown-links"><h2>{menu==='shop'?'DIE KOLLEKTION':menu==='routine'?'DEINE PFLEGEROUTINE':'ENTDECKE ELYSERA'}</h2>{(menu==='discover'?[['/about/','Die Marke'],['/science/','Peptidwissen'],['/faq/','Fragen & Antworten'],['/contact/','Kontakt & Hilfe'],['/account/','Mein Konto']]:menu==='routine'?[['/routine/','Die drei Pflegeschritte'],['/quiz/','Finde deine Pflege'],['/science/','Die Wirkstofflogik'],['/presale/','Presale & Lieferung']]:[['/shop/','Alle Produkte'],...products.map(p=>[`/products/${p.slug}/`,p.short]),['/presale/','Presale & Lieferung']]).map(([href,label])=><Link key={href} href={href} onClick={()=>setMenu(null)}>{label}<span aria-hidden="true">→</span></Link>)}</div><div className="dropdown-products">{products.map(p=><Link key={p.slug} href={`/products/${p.slug}/`} onClick={()=>setMenu(null)}><img src={p.image} alt={p.name}/><span>{p.short}</span><small>{p.volume} · Presale</small></Link>)}</div><button className="dropdown-close icon-button" aria-label="Navigationsmenü schließen" onClick={()=>{setMenu(null);trigger.current?.focus()}}><svg viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" fill="none" aria-hidden="true"><path d="m5 5 14 14M5 19 19 5"/></svg></button></div>}
 </header></>
}
