'use client'
import {useEffect,useRef,useState} from 'react'
export default function ProductFeedback({productId}){
 const [data,setData]=useState(null),[kind,setKind]=useState('question'),[body,setBody]=useState(''),[rating,setRating]=useState(5),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[uncertain,setUncertain]=useState(false);const attempt=useRef(null)
 async function load(){try{const r=await fetch('/api/product-feedback?productId='+encodeURIComponent(productId),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError(e.message)}}
 useEffect(()=>{setData(null);setBody('');setNotice('');attempt.current=null;setUncertain(false);try{const saved=JSON.parse(sessionStorage.getItem('elysera-feedback-public-'+productId));if(saved){attempt.current=saved;setBody(saved.payload.body);setKind(saved.payload.kind);setRating(saved.payload.rating||5);setUncertain(true);setNotice('Vorherige Übermittlung ungeklärt. Bitte dieselbe Anfrage erneut prüfen.')}}catch{}load()},[productId])
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const payload=attempt.current?.payload||{actorId:data.actorId,productId,kind,body,...kind==='review'?{rating}:{}};const key=JSON.stringify(payload);if(attempt.current?.key!==key)attempt.current={key,id:crypto.randomUUID(),payload};sessionStorage.setItem('elysera-feedback-public-'+productId,JSON.stringify(attempt.current));setUncertain(true);const r=await fetch('/api/product-feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,requestId:attempt.current.id})}),d=await r.json();if(!r.ok){if(['INVALID_INPUT','VERSION_CONFLICT'].includes(d.code)){sessionStorage.removeItem('elysera-feedback-public-'+productId);attempt.current=null;setUncertain(false)}throw Error(d.error)}sessionStorage.removeItem('elysera-feedback-public-'+productId);setUncertain(false);setBody('');attempt.current=null;setNotice(kind==='question'?'Deine Frage wurde eingereicht. Nach Beantwortung kann sie hier erscheinen.':'Deine Rezension wurde zur Prüfung eingereicht.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const control={display:'block',width:'100%',minHeight:44,padding:10,border:'1px solid #dfe9f2',borderRadius:6,font:'inherit',fontSize:16,boxSizing:'border-box',background:'#fff',color:'#183555'}
 return <section aria-label="Fragen und Rezensionen" style={{padding:'32px 16px',maxWidth:860,margin:'auto',color:'#183555'}}><h2>Fragen & Rezensionen</h2><p>Erfahrungen und Antworten zu diesem Produkt.</p>{error&&<p role="alert">{error} <button onClick={load}>Erneut laden</button></p>}{notice&&<p role="status">{notice}</p>}{!data&&!error?<p>Feedback wird geladen …</p>:data&&<><div style={{display:'grid',gap:16}}>{data.entries.length===0?<p>Noch keine veröffentlichten Beiträge.</p>:data.entries.map(row=><article key={row.id} style={{border:'1px solid #dfe9f2',padding:16,borderRadius:6,overflowWrap:'anywhere'}}><strong>{row.kind==='review'?`Rezension · ${row.rating}/5`:'Kundenfrage'}</strong>{row.verifiedPurchase&&<span> · Kauf bestätigt</span>}<p style={{whiteSpace:'pre-wrap'}}>{row.body}</p>{row.reply&&<div><strong>ELYSERA</strong><p style={{whiteSpace:'pre-wrap'}}>{row.reply}</p></div>}</article>)}</div>{data.limited&&<p>Die neuesten {data.limit} veröffentlichten Beiträge werden angezeigt.</p>}{data.actorId?<form onSubmit={submit} style={{display:'grid',gap:14,marginTop:24}}><h3>Dein Beitrag</h3><label>Beitragsart<select style={control} value={kind} disabled={busy||uncertain} onChange={e=>setKind(e.target.value)}><option value="question">Frage stellen</option><option value="review">Rezension schreiben</option></select></label>{kind==='review'&&<label>Bewertung<select style={control} value={rating} disabled={busy||uncertain} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} von 5 Sternen</option>)}</select></label>}<label>Text<textarea style={control} rows={4} minLength={5} maxLength={4000} required value={body} disabled={busy||uncertain} onChange={e=>setBody(e.target.value)}/></label><p>Dein Text kann nach Prüfung öffentlich erscheinen. Bitte keine persönlichen Daten eintragen. Ein Kaufhinweis wird nur nach nachgewiesenem Kauf vergeben.</p><button style={control} disabled={busy}>{busy?'Wird eingereicht …':uncertain?'Dieselbe Anfrage erneut prüfen':'Beitrag einreichen'}</button></form>:<p>Bitte melde dich mit deinem ELYSERA-Konto an, um einen Beitrag einzureichen.</p>}</>}</section>
}
