import {newsInput,NewsError} from './news-policy.mjs'
export async function listNews(db,page=1,admin=false){const offset=(page-1)*12;const rows=admin?await db.$queryRaw`SELECT * FROM public."ElyseraNews" ORDER BY "updatedAt" DESC,"id" LIMIT 13 OFFSET ${offset}`:await db.$queryRaw`SELECT "slug","title","excerpt","image","imageAlt","publishedAt","updatedAt" FROM public."ElyseraNews" WHERE "status"='PUBLISHED' AND "publishedAt"<=now() ORDER BY "publishedAt" DESC,"id" LIMIT 13 OFFSET ${offset}`;return {items:rows.slice(0,12).map(({lastRequest,lastRequestId,authorId,...row})=>row),more:rows.length>12}}
export async function getNews(db,slug){const [row]=await db.$queryRaw`SELECT "slug","title","excerpt","body","image","imageAlt","seoTitle","seoDescription","publishedAt","updatedAt" FROM public."ElyseraNews" WHERE "slug"=${slug} AND "status"='PUBLISHED' AND "publishedAt"<=now()`;return row||null}
export async function saveNews(db,actor,raw){const input=newsInput(raw);return db.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${input.id},0))`;const [before]=await tx.$queryRaw`SELECT * FROM public."ElyseraNews" WHERE "id"=${input.id}::uuid FOR UPDATE`;
if(before?.lastRequestId===input.requestId){if(before.authorId!==actor.id||Object.keys(input).some(key=>before.lastRequest[key]!==input[key]))throw new NewsError('Speicherkennung wurde bereits verwendet.',409);const {lastRequest,lastRequestId,authorId,...article}=before;return {article,replayed:true}}
if((before?.version||0)!==input.version)throw new NewsError('Der Beitrag wurde inzwischen geändert. Deinen Text sichern und den aktuellen Stand neu laden.',409);
if(before?.publishedAt&&before.slug!==input.slug)throw new NewsError('Die URL eines bereits veröffentlichten Beitrags bleibt unverändert.',409);
const rows=await tx.$queryRaw`INSERT INTO public."ElyseraNews" ("id","slug","title","excerpt","body","image","imageAlt","seoTitle","seoDescription","status","authorId","lastRequestId","lastRequest","publishedAt") VALUES (${input.id}::uuid,${input.slug},${input.title},${input.excerpt},${input.body},${input.image},${input.imageAlt},${input.seoTitle},${input.seoDescription},${input.status},${actor.id},${input.requestId}::uuid,${JSON.stringify(input)}::jsonb,CASE WHEN ${input.status}='PUBLISHED' THEN now() ELSE NULL END) ON CONFLICT ("id") DO UPDATE SET "slug"=EXCLUDED."slug","title"=EXCLUDED."title","excerpt"=EXCLUDED."excerpt","body"=EXCLUDED."body","image"=EXCLUDED."image","imageAlt"=EXCLUDED."imageAlt","seoTitle"=EXCLUDED."seoTitle","seoDescription"=EXCLUDED."seoDescription","status"=EXCLUDED."status","authorId"=EXCLUDED."authorId","lastRequestId"=EXCLUDED."lastRequestId","lastRequest"=EXCLUDED."lastRequest","version"="ElyseraNews"."version"+1,"updatedAt"=now(),"publishedAt"=COALESCE("ElyseraNews"."publishedAt",EXCLUDED."publishedAt") RETURNING *`;
const {lastRequest,lastRequestId,authorId,...article}=rows[0];return {article}}, {timeout:15000})}
