import {products as catalogProducts} from '../app/catalog.js'
import {ELYSERA_PRODUCTS} from './elysera-products.js'
export const productContentFields={name:{label:'Öffentlicher Produktname',max:160},short:{label:'Kurzname',max:100},volume:{label:'Inhalt / Volumen',max:60},format:{label:'Verpackungsformat',max:60},role:{label:'Rolle in der Routine',max:240},description:{label:'Beschreibung',max:4000},use:{label:'Anwendung',max:3000},texture:{label:'Textur',max:1000},ingredients:{label:'Wirkstoffschwerpunkte',max:120},delivery:{label:'Lieferhinweis',max:500}}
export const productContentIds=ELYSERA_PRODUCTS.map(p=>p.id)
export function productContentDefault(id){const identity=ELYSERA_PRODUCTS.find(p=>p.id===id);const product=identity&&catalogProducts.find(p=>p.slug===identity.slug);if(!product)throw Error('PRODUCT_OUT_OF_SCOPE');return product}
export function pickProductContent(product){return Object.fromEntries(Object.keys(productContentFields).map(k=>[k,k==='ingredients'?[...product[k]]:product[k]]))}
export function validateProductContent(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).sort().join(',')!==Object.keys(productContentFields).sort().join(','))throw Error('CONTENT_FIELDS')
 const content={};for(const [key,{max}] of Object.entries(productContentFields)){if(key==='ingredients'){if(!Array.isArray(raw[key])||!raw[key].length||raw[key].length>40||raw[key].some(v=>typeof v!=='string'||!v.trim()||v.length>max))throw Error('CONTENT_INGREDIENTS');content[key]=raw[key].map(v=>v.trim())}else{if(typeof raw[key]!=='string'||!raw[key].trim()||raw[key].length>max)throw Error('CONTENT_TEXT');content[key]=raw[key].trim()}}return content}
// Fixed slug, step and image always come from the existing catalog, never the editable row.
export function resolveProductContent(rows=[]){return ELYSERA_PRODUCTS.map(({id})=>{const base=productContentDefault(id),row=rows.find(r=>r.productId===id);return {...base,...(row?validateProductContent(row.content):{} )}})}
export async function loadPublicProductContent(db){const rows=await db.$queryRaw`SELECT "productId","content" FROM public."ElyseraProductContent" WHERE "productId"=ANY(${productContentIds}::text[])`;return resolveProductContent(rows)}
