import {NextResponse} from 'next/server'
import {cookies} from 'next/headers'
import {prisma} from '@/lib/prisma'
import {authClient,adminPrincipalFor} from '@/lib/auth/server'
import {sameOrigin} from '@/lib/auth/policy.mjs'
import {impersonationCookie,tokenHash,newImpersonationToken,impersonatedUser,eligibleImpersonationTarget} from '@/lib/auth/impersonation.mjs'
export const dynamic='force-dynamic'
const reply=(b,s=200)=>NextResponse.json(b,{status:s,headers:{'Cache-Control':'private, no-store'}})
const options={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:86400}
export async function GET(){try{const token=(await cookies()).get(impersonationCookie)?.value;if(!token)return reply({active:false});const actor=await adminPrincipalFor(await authClient()),user=await impersonatedUser(prisma,actor,token);return reply(user?{active:true,name:[user.firstName,user.secondName].filter(Boolean).join(' '),email:user.email}:{active:false,expired:true})}catch{return reply({active:false,expired:true},503)}}
export async function POST(request){if(!sameOrigin(request))return reply({error:'Nicht zulässig.'},403);try{const actor=await adminPrincipalFor(await authClient());if(!actor)return reply({error:'Administrator-Anmeldung erforderlich.'},401);const jar=await cookies();if(jar.get(impersonationCookie))return reply({error:'Bitte zuerst zum Admin zurückkehren.'},409);const raw=await request.text();if(raw.length>2048)return reply({error:'Eingabe zu lang.'},400);let body;try{body=JSON.parse(raw)}catch{return reply({error:'Ungültige Eingabe.'},400)}if(typeof body?.customerId!=='string'||!body.customerId.trim()||body.customerId.length>100)return reply({error:'Kunde erforderlich.'},400);
 const token=newImpersonationToken();await prisma.$transaction(async tx=>{const users=await tx.$queryRaw`SELECT u.id,u.role::text AS role,u.blocked,u."emailVerified",COALESCE(a.enabled,false) AS "adminAccess" FROM public."User" u JOIN public."ElyseraAccountProfile" p ON p."userId"=u.id LEFT JOIN public."ElyseraAdminAccess" a ON a."userId"=u.id WHERE u.id=${body.customerId} FOR SHARE OF u,p`;if(!eligibleImpersonationTarget(users[0])||actor.id===body.customerId)throw Error('TARGET');await tx.$executeRaw`INSERT INTO public."ElyseraImpersonationSession" ("tokenHash","actorId","targetId",reason,"expiresAt") VALUES (${tokenHash(token)},${actor.id},${body.customerId},${'Admin-Kontoansicht'},NOW()+INTERVAL '30 minutes')`},{timeout:30000,maxWait:10000});jar.set(impersonationCookie,token,options);return reply({ok:true,redirect:'/dashboard'})
 }catch(e){return reply({error:e.message==='TARGET'?'Dieses Konto kann nicht übernommen werden.':'Nutzersitzung konnte nicht gestartet werden.'},e.message==='TARGET'?403:503)}}
export async function DELETE(request){if(!sameOrigin(request))return reply({error:'Nicht zulässig.'},403);try{const jar=await cookies(),token=jar.get(impersonationCookie)?.value;if(token)await prisma.$executeRaw`UPDATE public."ElyseraImpersonationSession" SET "endedAt"=NOW() WHERE "tokenHash"=${tokenHash(token)} AND "endedAt" IS NULL`;jar.set(impersonationCookie,'',{...options,maxAge:0});return reply({ok:true,redirect:'/admin/users'})}catch{return reply({error:'Rückkehr nicht bestätigt. Bitte erneut versuchen.'},503)}}
