import {redirect} from 'next/navigation'
import Link from 'next/link'
import {currentUser} from '@/lib/auth/server'
import {pendingGoogle} from '@/lib/auth/pending-google'
import {cookies} from 'next/headers'
import {referralCookie} from '@/lib/auth/referral-policy.mjs'
import {accountProfile} from '@/lib/auth/details-store'
import ProfileDetails from '../profile-details'
import LoginGallery from '../signin/login-gallery'
import '../signin/signin.css'
export const dynamic='force-dynamic'
export default async function Page(){const user=await currentUser();const pending=user?null:await pendingGoogle();if(!user&&!pending)redirect('/auth/signin');const metadata=pending?.user_metadata||{};const full=String(metadata.full_name||metadata.name||'').trim().split(/\s+/);const profile=user?await accountProfile(user):{email:pending.email,name:metadata.given_name||full[0]||'',last:metadata.family_name||full.slice(1).join(' '),country:'Deutschland',referral:(await cookies()).get(referralCookie)?.value||''};return <main className="es-login es-signin es-register es-complete-profile"><Link href="/" className="es-logo">ELYSERA<small>SKINCARE</small></Link><div className="es-login-grid"><LoginGallery/><section className="es-login-form"><span className="es-kicker">DEIN ELYSERA KONTO</span><h1>Dein Profil vervollständigen.</h1><ProfileDetails initialProfile={profile} pendingGoogle={Boolean(pending)} complete/><Link className="es-back" href="/">← Zur ELYSERA Kollektion</Link></section></div><footer>ELYSERA · SCHÖNHEIT VERBINDET</footer></main>}
