import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import vm from 'node:vm'
import {validateCoupon,euroCents} from '../app/api/admin/coupons/policy.mjs'
const coupon={code:'ELY10',rewardType:'DISCOUNT',percentage:10,fixedCents:null,bonusProductId:null,active:true,archived:false,oneTimeOnly:false,oncePerUser:true,assignedUserId:null,startsAt:null,endsAt:null,maxRedemptions:null}
test('strict percentage/fixed/free validation rejects coercion and foreign products',()=>{assert.deepEqual(validateCoupon(coupon),coupon);for(const patch of [{percentage:0},{percentage:101},{percentage:'10'},{active:1},{archived:true},{extra:true},{startsAt:'tomorrow'},{startsAt:'2026-02-30T00:00:00.000Z'},{maxRedemptions:1.2},{rewardType:'FREE_PRODUCT',percentage:null,bonusProductId:'peptiking-product'}])assert.throws(()=>validateCoupon({...coupon,...patch}));assert.doesNotThrow(()=>validateCoupon({...coupon,rewardType:'FIXED_DISCOUNT',percentage:null,fixedCents:1299}));assert.doesNotThrow(()=>validateCoupon({...coupon,rewardType:'FREE_PRODUCT',percentage:null,bonusProductId:'elysera-renewal-serum-30ml'}))})
test('currency parses without floating point truncation',()=>{assert.equal(euroCents('12,99'),1299);assert.equal(euroCents('1.1'),110);for(const value of ['1.999','1e2','-5','0','100000.01',' 1'])assert.equal(euroCents(value),null)})
function harness({admin=true,origin=true,stale=false,missingRecipient=false,auditFailure=false,replay=false}={}){const ev={queries:[],committed:false,rolledBack:false,writes:0};const row={id:'coupon-id',data:coupon,version:1};const tx={$queryRaw:async(strings,...values)=>{const sql=strings.join('?');ev.queries.push(sql);if(sql.includes('"idempotencyKey"='))return replay?[{actorId:'admin',request:{id:'coupon-id',expectedVersion:1,idempotencyKey:'11111111-1111-1111-1111-111111111111',coupon},after:{...coupon,id:'coupon-id',version:2}}]:[];if(sql.includes('::jsonb ='))return[{equal:true}];if(sql.includes('ElyseraAccountProfile'))return missingRecipient?[]:[{userId:'customer'}];if(sql.startsWith('UPDATE')||sql.startsWith('INSERT')){ev.writes++;return[{...row,version:2}]}return[{...row,version:stale?2:1}]},$executeRaw:async(strings)=>{const sql=strings.join('?');ev.queries.push(sql);if(sql.startsWith('INSERT')&&auditFailure)throw Error('private failure');return 1}};const prisma={...tx,$transaction:async(fn,opts)=>{assert.equal(opts.timeout,30000);try{const r=await fn(tx);ev.committed=true;return r}catch(e){ev.rolledBack=true;throw e}}};const context={NextResponse:{json:(body,opts)=>({body,status:opts.status})},prisma,currentAdmin:async()=>admin?{id:'admin'}:null,sameOrigin:()=>origin,validateCoupon,URL};vm.createContext(context);vm.runInContext(readFileSync('app/api/admin/coupons/route.js','utf8').replace(/^import .*$/mg,'').replaceAll('export ','')+';this.call=PATCH',context);return {ev,call:(extra={})=>context.call({method:'PATCH',text:async()=>JSON.stringify({id:'coupon-id',expectedVersion:1,idempotencyKey:'11111111-1111-1111-1111-111111111111',coupon,...extra})})}}
test('auth and same-origin reject before data access',async()=>{for(const opts of[{admin:false},{origin:false}]){const h=harness(opts),r=await h.call();assert.ok([401,403].includes(r.status));assert.equal(h.ev.queries.length,0)}})
test('optimistic version conflict prevents mutation',async()=>{const h=harness({stale:true});const r=await h.call();assert.equal(r.status,409);assert.equal(r.body.code,'STALE_VERSION');assert.equal(h.ev.writes,0)})
test('recipient is limited to ELYSERA profiles',async()=>{const h=harness({missingRecipient:true});assert.equal((await h.call({coupon:{...coupon,assignedUserId:'foreign'}})).status,400);assert.equal(h.ev.writes,0)})
test('transaction returns persisted version and writes scoped audit',async()=>{const h=harness(),r=await h.call();assert.equal(r.status,200);assert.equal(r.body.coupon.version,2);assert.ok(h.ev.committed);assert.ok(h.ev.queries.some(q=>q.includes('INSERT INTO public."ElyseraCouponAudit"')));assert.ok(h.ev.queries.every(q=>!q.includes('public."Coupon"')))})
test('audit failure rolls transaction back without claiming success',async()=>{const h=harness({auditFailure:true}),r=await h.call();assert.equal(r.status,503);assert.ok(h.ev.rolledBack);assert.ok(!h.ev.committed);assert.doesNotMatch(JSON.stringify(r),/private failure/)})
test('idempotent replay does not repeat mutation',async()=>{const h=harness({replay:true}),r=await h.call();assert.equal(r.status,200);assert.equal(r.body.replayed,true);assert.equal(h.ev.writes,0)})

test('recipient identity lookup reads only scoped ELYSERA profile join',async()=>{const seen=[];const context={NextResponse:{json:(body,opts)=>({body,status:opts.status})},prisma:{$queryRaw:async(strings,...values)=>{seen.push({sql:strings.join('?'),values});return[{id:'known',firstName:'Anna',email:'anna@example.test'}]}},currentAdmin:async()=>({id:'admin'}),sameOrigin:()=>true,validateCoupon,URL};vm.createContext(context);vm.runInContext(readFileSync('app/api/admin/coupons/route.js','utf8').replace(/^import .*$/mg,'').replaceAll('export ','')+';this.call=GET',context);const result=await context.call({url:'http://localhost/api/admin/coupons?recipientId=known'});assert.equal(result.status,200);assert.equal(result.body.recipient.email,'anna@example.test');assert.match(seen[0].sql,/FROM public\."ElyseraAccountProfile" p JOIN public\."User" u/);assert.equal(seen[0].values[0],'known')})
