import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import vm from 'node:vm'
import {validatePackage,pricing,productIds} from '../app/api/admin/packages/policy.mjs'
const pkg={name:'Pflegeset',slug:'pflegeset',tagline:'Täglich',description:'',sortOrder:0,active:true,archived:false,items:[{productId:productIds[0],quantity:2,label:''}]}
test('strict package policy rejects foreign scope, unknown fields, coercion and duplicate items',()=>{assert.deepEqual(validatePackage(pkg),pkg);for(const patch of [{name:''},{slug:'../../x'},{active:'true'},{archived:true},{sortOrder:1.5},{extra:1},{items:[]},{items:[{...pkg.items[0],productId:'shared'}]},{items:[pkg.items[0],pkg.items[0]]},{items:[{...pkg.items[0],quantity:'1'}]}])assert.throws(()=>validatePackage({...pkg,...patch}))})
test('integer cents preserve precision and unknown prices never become zero',()=>{assert.deepEqual(pricing(pkg.items,[{id:productIds[0],price:12.99}]),{componentCents:2598,bundleCents:2338,savingsCents:260});for(const price of [null,undefined,NaN,Infinity,'12.99',1.001,-1])assert.equal(pricing(pkg.items,[{id:productIds[0],price}]).bundleCents,null);assert.equal(pricing(pkg.items,[]).componentCents,null)})
function harness({admin=true,origin=true,stale=false,auditFailure=false,replay=false,foreign=false,mismatch=false}={}){const ev={queries:[],writes:0,committed:false,rolledBack:false};let version=1;const row=()=>({id:'set-id',data:pkg,version});const tx={$queryRaw:async(strings,...values)=>{const sql=strings.join('?');ev.queries.push(sql);if(sql.includes('"idempotencyKey"='))return replay?[{actorId:'admin',request:{},after:{...pkg,id:'set-id',version:2}}]:[];if(sql.includes('::jsonb ='))return[{equal:!mismatch}];if(sql.includes('public."Products"')){assert.equal(values.length,3);assert.deepEqual(values,productIds);return foreign?[]:productIds.map(id=>({id}))}if(sql.includes('FOR UPDATE'))return[{...row(),version:stale?2:1}];if(sql.startsWith('UPDATE')||sql.startsWith('INSERT')){ev.writes++;version++;return[row()]}return[row()]},$executeRaw:async(strings)=>{const sql=strings.join('?');ev.queries.push(sql);if(sql.startsWith('INSERT')&&auditFailure)throw Error('private failure');return 1}};const prisma={...tx,$transaction:async(fn,opts)=>{assert.equal(opts.timeout,30000);try{const result=await fn(tx);ev.committed=true;return result}catch(e){ev.rolledBack=true;throw e}}};const context={NextResponse:{json:(body,opts)=>({body,status:opts.status})},prisma,currentAdmin:async()=>admin?{id:'admin'}:null,sameOrigin:()=>origin,validatePackage,pricing,productIds,URL};vm.createContext(context);vm.runInContext(readFileSync('app/api/admin/packages/route.js','utf8').replace(/^import .*$/mg,'').replaceAll('export ','')+';this.call=PATCH',context);return {ev,call:(extra={})=>context.call({method:'PATCH',text:async()=>JSON.stringify({id:'set-id',expectedVersion:1,idempotencyKey:'11111111-1111-1111-1111-111111111111',package:pkg,...extra})})}}
test('auth and same-origin precede data access',async()=>{for(const opts of [{admin:false},{origin:false}]){const h=harness(opts);assert.ok([401,403].includes((await h.call()).status));assert.equal(h.ev.queries.length,0)}})
test('foreign products and absent own product records cannot mutate',async()=>{const h=harness();assert.equal((await h.call({package:{...pkg,items:[{...pkg.items[0],productId:'foreign'}]}})).status,400);assert.equal(h.ev.writes,0);const absent=harness({foreign:true});assert.equal((await absent.call()).status,400);assert.equal(absent.ev.writes,0)})
test('version conflict rolls back before writing',async()=>{const h=harness({stale:true});assert.equal((await h.call()).status,409);assert.equal(h.ev.writes,0);assert.ok(h.ev.rolledBack)})
test('readback returns persisted version with own audit',async()=>{const h=harness(),r=await h.call();assert.equal(r.status,200);assert.equal(r.body.package.version,2);assert.ok(h.ev.committed);assert.ok(h.ev.queries.some(q=>q.includes('INSERT INTO public."ElyseraPackageAudit"')));assert.ok(!h.ev.queries.some(q=>q.includes('ProductPackage')))})
test('audit failure rolls back and never leaks database internals',async()=>{const h=harness({auditFailure:true}),r=await h.call();assert.equal(r.status,503);assert.ok(h.ev.rolledBack);assert.ok(!h.ev.committed);assert.doesNotMatch(JSON.stringify(r),/private failure/)})
test('same request replay performs no write and mismatched request cannot replay',async()=>{const h=harness({replay:true}),r=await h.call();assert.equal(r.status,200);assert.ok(r.body.replayed);assert.equal(h.ev.writes,0);const mismatch=harness({replay:true,mismatch:true});assert.equal((await mismatch.call()).status,409);assert.equal(mismatch.ev.writes,0)})
test('unfinished or invalid quantities have unknown prices',()=>{for(const quantity of ['',0,-1,1.2,101,null])assert.equal(pricing([{...pkg.items[0],quantity}],[{id:productIds[0],price:129}]).bundleCents,null);assert.equal(pricing([],[]).bundleCents,null)})
