import {test} from 'node:test'
import assert from 'node:assert/strict'
import {validateProduct} from '../app/api/admin/products/[id]/validation.mjs'
import {productSelect} from '../app/api/admin/products/[id]/validation.mjs'
import {productSave,productRequest} from '../lib/admin/product-recovery.mjs'
import {productHttp} from '../lib/admin/product-http-core.mjs'
const valid={name:'Renewal Serum',price:129.95,stock:4,active:true}
test('accept supported product fields with cent precision and trim name',()=>{assert.deepEqual(validateProduct({...valid,name:' Renewal Serum '}),valid);assert.ok(validateProduct({...valid,stock:0,active:false}))})
test('reject unknown fields and unrelated shared product configuration',()=>{for(const patch of [{id:'other'},{staffOnly:false},{marketRegions:[]},{priceUsd:20}])assert.equal(validateProduct({...valid,...patch}),null)})
test('reject coercion, invalid bounds, control characters and fractional stock',()=>{for(const patch of [{price:'129'},{price:NaN},{price:Infinity},{price:-1},{price:100001},{price:1.001},{stock:'4'},{stock:0.5},{stock:-1},{stock:1000001},{active:'false'},{name:' '},{name:'x'.repeat(161)},{name:'Name\n'}])assert.equal(validateProduct({...valid,...patch}),null)})
test('reject arrays, null and missing fields',()=>{for(const body of [null,[],{}, {name:'Test',price:1,stock:3}])assert.equal(validateProduct(body),null)})

const payload=()=>({actorId:'admin-test',requestId:'01234567-1234-1234-1234-123456789abc',expectedVersion:0,expected:valid,changes:{...valid,price:150}})
function harness(failAudit=false,badReadback=false){let row={id:'elysera-test',...valid},version=0,audits=[];return {row:()=>row,remove:()=>{row=null},version:()=>version,db:{$transaction:async(fn,options)=>{assert.equal(options.timeout,30000);const before=structuredClone({row,version,audits});try{return await fn({product:{findUnique:async()=>row?({...row}):null,update:async({data})=>{row={...row,...data};if(badReadback)row.stock++}},$executeRaw:async(parts)=>{if(parts.join('?').startsWith('UPDATE'))version++;return 1},$queryRaw:async(parts,...values)=>{const q=parts.join('?');if(q.startsWith('SELECT "payload"'))return audits.filter(a=>a.actorId===values[0]&&a.requestId===values[1]);if(q.startsWith('SELECT "id"'))return row?[{id:row.id}]:[];if(q.startsWith('SELECT "version"'))return [{version}];if(q.startsWith('INSERT')){if(failAudit)throw Error('AUDIT_FAIL');const audit={actorId:values[0],requestId:values[2],payload:JSON.parse(values[3]),after:JSON.parse(values[5])};audits.push(audit);return [{after:audit.after}]};throw Error(q)}})}catch(e){row=before.row;version=before.version;audits=before.audits;throw e}}}}}
test('request rejects unknown actor/request/version fields',()=>{for(const change of [{actorId:null},{requestId:'bad'},{expectedVersion:-1},{expectedVersion:1.5},{other:1}])assert.throws(()=>productRequest({...payload(),...change}))})
test('save exactreadback idempotent replay and request collision',async()=>{const h=harness(),p=payload();const save=v=>productSave(h.db,{id:p.actorId},'elysera-test',['elysera-test'],v);const result=await save(p);assert.equal(result.product.price,150);assert.equal(result.product.version,1);assert.equal((await save(p)).replayed,true);assert.equal(h.version(),1);await assert.rejects(save({...p,changes:{...p.changes,price:160}}),e=>e.code==='REQUEST_ID_CONFLICT')})
test('version and expected snapshot conflicts preserve product',async()=>{for(const change of [{expectedVersion:1},{expected:{...valid,stock:99}}]){const h=harness();await assert.rejects(productSave(h.db,{id:'admin-test'},'elysera-test',['elysera-test'],{...payload(),...change}),e=>e.code==='VERSION_CONFLICT');assert.equal(h.row().price,valid.price);assert.equal(h.version(),0)}})
test('audit/readback failures rollback product and revision',async()=>{for(const flags of [[true,false],[false,true]]){const h=harness(...flags);await assert.rejects(productSave(h.db,{id:'admin-test'},'elysera-test',['elysera-test'],payload()));assert.equal(h.row().price,valid.price);assert.equal(h.version(),0)}})
test('actor and outofscope identities cannot mutate',async()=>{const h=harness();await assert.rejects(productSave(h.db,{id:'other'},'elysera-test',['elysera-test'],payload()),e=>e.code==='ACTOR_CHANGED');await assert.rejects(productSave(h.db,{id:'admin-test'},'other',['elysera-test'],payload()),e=>e.status===404);assert.equal(h.version(),0)})
test('HTTP origin and auth checked before write, 503 retains unknown',async()=>{let calls=0;const deps={db:{},ids:['elysera-test'],currentAdmin:async()=>null,sameOrigin:()=>false,reply:(body,status=200)=>({body,status}),catalog:async()=>[],save:async()=>{calls++;throw Error('uncertain')}};const req={text:async()=>JSON.stringify(payload())};assert.equal((await productHttp(req,'elysera-test',true,deps)).status,403);assert.equal((await productHttp(req,'elysera-test',true,{...deps,sameOrigin:()=>true})).status,401);assert.equal(calls,0);const r=await productHttp(req,'elysera-test',true,{...deps,sameOrigin:()=>true,currentAdmin:async()=>({id:'admin-test'})});assert.equal(r.status,503);assert.equal(r.body.code,'UNCONFIRMED')})

test('replay returns historical applied snapshot plus newer current product without downgrade',async()=>{const h=harness(),p=payload();const save=v=>productSave(h.db,{id:p.actorId},'elysera-test',['elysera-test'],v);await save(p);await save({...p,requestId:'11111111-1234-1234-1234-123456789abc',expectedVersion:1,expected:p.changes,changes:{...p.changes,price:175}});const replay=await save(p);assert.equal(replay.applied.price,150);assert.equal(replay.applied.version,1);assert.equal(replay.product.price,175);assert.equal(replay.product.version,2);assert.equal(h.row().price,175)})
test('replay of deleted own product returns404 and does not resurrect',async()=>{const h=harness(),p=payload();await productSave(h.db,{id:p.actorId},'elysera-test',['elysera-test'],p);h.remove();await assert.rejects(productSave(h.db,{id:p.actorId},'elysera-test',['elysera-test'],p),e=>e.status===404&&e.code==='PRODUCT_NOT_FOUND');assert.equal(h.row(),null)})
