import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {validateContact} from '../app/api/admin/customers/policy.mjs'
const source=readFileSync(new URL('../app/api/admin/customers/route.js',import.meta.url),'utf8')
const contact={street:'Main Street',houseNumber:'1',postalCode:'10115',city:'Berlin',country:'Deutschland',phone:'+49 1234567'}
function harness({admin=true,origin=true,rows=[],auditFails=false}={}){const queries=[],writes=[];let committed=false;const tx={$queryRaw:async(strings,...values)=>{queries.push(strings.join('?'));return strings[0].startsWith('UPDATE')?[{updatedAt:new Date('2026-09-13'),details:{...contact,city:'Persisted City'}}]:rows},$executeRaw:async(strings)=>{writes.push(strings.join('?'));if(auditFails)throw Error('AUDIT_UNAVAILABLE')}};const prisma={...tx,$transaction:async fn=>{const result=await fn(tx);committed=true;return result}};const routes=Function('NextResponse','Prisma','prisma','currentAdmin','sameOrigin','ELYSERA_PRODUCTS','validateContact',source.replace(/^import .*\n/gm,'').replace(/export /g,'')+'\nreturn {GET,PATCH}')({json:(body,{status})=>({body,status})},{join:x=>x},prisma,async()=>admin?{id:'admin'}:null,()=>origin,[{id:'elysera-only'}],validateContact);return {get:id=>routes.GET({url:'https://elysera.de/api/admin/customers'+(id?'?id='+id:'')}),patch:body=>routes.PATCH({text:async()=>JSON.stringify(body)}),queries,writes,committed:()=>committed}}
test('anonymous list and edit never touch database',async()=>{const h=harness({admin:false});assert.equal((await h.get()).status,401);assert.equal((await h.patch({})).status,401);assert.equal(h.queries.length,0)})
test('cross-origin edit rejected before database access',async()=>{const h=harness({origin:false});assert.equal((await h.patch({})).status,403);assert.equal(h.queries.length,0)})
test('list requires ELYSERA profile membership and excludes sensitive shared fields',async()=>{const h=harness();assert.equal((await h.get()).status,200);assert.match(h.queries[0],/JOIN public\."ElyseraAccountProfile"/);assert.doesNotMatch(h.queries[0],/role|blocked|balance|birthDate|gender|referral/)})
test('non-member detail cannot reveal shared orders',async()=>{const h=harness();assert.equal((await h.get('outside')).status,404);assert.equal(h.queries.length,1)})
test('customer orders require customer ownership and exclude mixed and unknown product orders',async()=>{const h=harness({rows:[{id:'member'}]});assert.equal((await h.get('member')).status,200);assert.match(h.queries[1],/o\."userId"=\?/);assert.match(h.queries[1],/NOT EXISTS/);assert.match(h.queries[1],/IS NULL/);assert.match(h.queries[1],/NOT IN/);assert.match(h.queries[1],/EXISTS/)})
test('only whitelisted brand contact fields accepted',()=>{assert.deepEqual(validateContact(contact),contact);for(const key of ['name','email','role','credit','referrerId'])assert.equal(validateContact({...contact,[key]:'unsafe'}),null);assert.equal(validateContact({...contact,phone:'javascript:alert(1)'}),null)})
test('missing and stale brand profile reject with409 and never write',async()=>{for(const rows of [[],[{updatedAt:new Date('2026-09-12'),details:contact}]]){const h=harness({rows});assert.equal((await h.patch({id:'member',updatedAt:'2026-09-13T00:00:00Z',contact})).status,409);assert.equal(h.writes.length,0);assert.equal(h.queries.filter(q=>q.startsWith('UPDATE')).length,0)}})
test('successful update locks brand row, merges whitelisted details and commits audit together',async()=>{const h=harness({rows:[{updatedAt:new Date('2026-09-13'),details:{...contact,unrelated:'preserved'}}]});assert.equal((await h.patch({id:'member',updatedAt:'2026-09-13T00:00:00Z',contact})).status,200);assert.match(h.queries[0],/FOR UPDATE/);assert.match(h.queries[1],/COALESCE.*\|\|/);assert.match(h.writes[0],/public\."ElyseraCustomerAudit"/);assert.equal(h.committed(),true);assert.doesNotMatch(h.queries.join(' '),/UPDATE public\."User"/)})
test('audit failure fails entire transaction',async()=>{const h=harness({auditFails:true,rows:[{updatedAt:new Date('2026-09-13'),details:contact}]});assert.equal((await h.patch({id:'member',updatedAt:'2026-09-13T00:00:00Z',contact})).status,503);assert.equal(h.committed(),false)})

test('response uses persisted readback and unexpected envelope rejected',async()=>{const h=harness({rows:[{updatedAt:new Date('2026-09-13'),details:contact}]});const response=await h.patch({id:'member',updatedAt:'2026-09-13T00:00:00Z',contact});assert.equal(response.body.profile.details.city,'Persisted City');assert.equal((await h.patch({id:'member',updatedAt:'2026-09-13T00:00:00Z',contact,role:'ADMIN'})).status,400);assert.equal(validateContact({...contact,city:'Bad\nCity'}),null)})
