import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {cents,OWN_IDS,rangeDates,scopeOrder,reportSnapshot,forecast,validateCosts} from '../lib/admin/reports-model.mjs'
const config={version:0,costs:Object.fromEntries(OWN_IDS.map(id=>[id,null]))}
const range=rangeDates(new URLSearchParams('range=30'),new Date('2026-09-13T00:00:00Z'))
const order={id:'own',status:'PAID',createdAt:'2026-09-12T12:00:00Z',total:8,items:[{productId:OWN_IDS[0],quantity:2,price:5,name:'Serum'}]}
test('integer cents rejects precision loss and ambiguous values',()=>{assert.equal(cents('1.05'),105);for(const v of ['1.005',-1,'1e3',NaN,'9007199254740992'])assert.throws(()=>cents(v))})
test('scope excludes no lines, mixed products and null products',()=>{assert.equal(scopeOrder(order),true);for(const items of [[],[{productId:null}], [...order.items,{productId:'foreign'}]])assert.equal(scopeOrder({...order,items}),false)})
test('order totals are authoritative, unknown evidence stays null',()=>{const s=reportSnapshot([order],config,range);assert.equal(s.summary.totalCents,800);assert.equal(s.products[0].lineCents,1000);assert.equal(s.summary.costCents,null);assert.equal(s.summary.netProfitCents,null);const configured=reportSnapshot([order],{...config,costs:{...config.costs,[OWN_IDS[0]]:200}},range);assert.equal(configured.summary.contributionCents,400)})
test('UTC custom dates are inclusive calendar days with exclusive end',()=>{const r=rangeDates(new URLSearchParams('range=custom&start=2026-08-31&end=2026-09-01'),new Date('2026-09-13'));assert.equal(r.end.toISOString(),'2026-09-02T00:00:00.000Z');assert.equal(r.days,2);assert.throws(()=>rangeDates(new URLSearchParams('range=custom&start=2026-02-30&end=2026-03-01')));const previous=rangeDates(new URLSearchParams('range=previousMonth'),new Date('2026-09-13'));assert.equal(previous.end.toISOString(),'2026-09-01T00:00:00.000Z')})
test('forecast includes inactive days and refuses to invent zero-history projection',()=>{const empty=forecast(reportSnapshot([],config,range),30,0);assert.equal(empty.days.length,30);assert.equal(empty.projections[0].revenueCents,null);const f=forecast(reportSnapshot([order],config,range),30,0);assert.equal(f.projections[1].revenueCents,800);assert.equal(f.projections[1].contributionCents,null);assert.throws(()=>forecast(reportSnapshot([],config,range),30,13))})
test('cost validation rejects decimals, foreign ids, excessive amounts',()=>{assert.equal(validateCosts({costs:config.costs,expectedVersion:0}).expectedVersion,0);for(const n of [-1,.5,100000001,'5'])assert.throws(()=>validateCosts({costs:{...config.costs,[OWN_IDS[0]]:n},expectedVersion:0}))})
const source=readFileSync(new URL('../app/api/admin/reports/costs/route.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'').replace('export async function PUT','async function PUT')
function route({origin=true,admin={id:'admin'},failAudit=false}={}){let state=null,audits=[];const prisma={$transaction:async fn=>{let draft=state;const result=await fn({$executeRaw:async(strings,...values)=>{const sql=strings.join('?');if(sql.includes('INSERT INTO public."ElyseraFinanceConfig"'))draft={costs:JSON.parse(values[0]),version:(draft?.version||0)+1};if(sql.includes('INSERT INTO public."ElyseraFinanceAudit"')){if(failAudit)throw Error('DB');audits.push(values)}},$queryRaw:async()=>draft?[draft]:[]});state=draft;return result}};const fn=new Function('NextResponse','prisma','currentAdmin','sameOrigin','validateCosts',source+';return PUT')({json:(b,o)=>({body:b,status:o.status})},prisma,async()=>admin,()=>origin,validateCosts);return {fn,get:()=>state,audits}}
const req=version=>({text:async()=>JSON.stringify({costs:config.costs,expectedVersion:version})})
test('mutation requires origin and admin, atomically saves/readbacks, detects stale writes',async()=>{assert.equal((await route({origin:false}).fn(req(0))).status,403);assert.equal((await route({admin:null}).fn(req(0))).status,401);const r=route();assert.equal((await r.fn(req(0))).body.config.version,1);assert.equal(r.audits.length,1);assert.equal((await r.fn(req(0))).status,409);assert.equal(r.get().version,1)})
test('audit failure rolls back configuration',async()=>{const r=route({failAudit:true});assert.equal((await r.fn(req(0))).status,503);assert.equal(r.get(),null)})
test('forecast ends at UTC midnight and excludes the current incomplete day',()=>{const r=rangeDates(new URLSearchParams('range=90'),new Date('2026-09-13T23:59:59Z'));assert.equal(r.end.toISOString(),'2026-09-13T00:00:00.000Z');assert.equal(r.days,90);const s=reportSnapshot([{...order,createdAt:'2026-09-13T00:00:00Z'}],config,r);assert.equal(forecast(s,7).sampleDays,0)})
test('large line products and aggregate overflow fail closed; forecast overflow is unavailable',()=>{assert.throws(()=>reportSnapshot([{...order,items:[{...order.items[0],quantity:Number.MAX_SAFE_INTEGER}]}],config,range));const s=reportSnapshot([{...order,total:'90000000000000'}],config,range);assert.equal(forecast(s,7,12).projections.at(-1).revenueCents,null)})
test('SQL data reads remain qualified and enforce the full-order scope',()=>{const sql=readFileSync(new URL('../app/api/admin/reports/route.js',import.meta.url),'utf8');assert.match(sql,/public\."Order"/);assert.match(sql,/AND EXISTS/);assert.match(sql,/AND NOT EXISTS/);assert.match(sql,/"productId" IS NULL/);assert.doesNotMatch(sql,/CreditTransaction|"User"|commission\.find/)})
