import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import vm from 'node:vm'
import {parseGrant,eurosToCents,grantElyseraCredits,readElyseraCreditBalance} from '../lib/admin/credits.mjs'
const input={userId:'elysera-only',email:'recipient@example.test',amountCents:101,reason:'Service correction',idempotencyKey:'f288e50b-0d7b-423d-99b3-d6ba442aa319'},admin={id:'admin-test',email:'admin@example.test'}
function db({missing=false,auditFailure=false,email=input.email}={}){const state={rows:[],audit:[],sql:[],rolledBack:false};const prisma={$transaction:async(fn,options)=>{assert.equal(options.timeout,30000);const staged=structuredClone(state.rows),audits=structuredClone(state.audit);try{const result=await fn({$executeRaw:async(s,...v)=>{const sql=s.join('?');state.sql.push(sql);if(sql.includes('ElyseraCreditAudit')){if(auditFailure)throw Error('SECRET_DB_FAILURE');audits.push(v)}return 1},$queryRaw:async(s,...v)=>{const sql=s.join('?');state.sql.push(sql);if(sql.includes('FOR UPDATE'))return missing?[]:[{email}];if(sql.includes('SUM'))return[{balanceCents:String(staged.reduce((n,r)=>n+r.amountCents,0))}];if(sql.startsWith('SELECT *'))return staged.filter(r=>r.idempotencyKey===v[0]);if(sql.startsWith('INSERT')){const row={id:'ledger-'+staged.length,userId:v[0],amountCents:v[1],reason:v[2],actorId:v[3],actorEmail:v[4],recipientEmail:v[5],idempotencyKey:v[6]};staged.push(row);return[row]}throw Error(sql)}});state.rows=staged;state.audit=audits;return result}catch(e){state.rolledBack=true;throw e}}};return{prisma,state}}
test('positive exact integer cents only, capped and strict input shape',()=>{assert.equal(eurosToCents('0,01'),1);assert.equal(eurosToCents('1.01'),101);for(const value of ['0','-1','1.001','1e3','100000.01','Infinity'])assert.equal(eurosToCents(value),null);for(const amountCents of [0,-1,0.5,NaN,Infinity,10000001,'100'])assert.throws(()=>parseGrant({...input,amountCents}));assert.throws(()=>parseGrant({...input,extra:true}));assert.deepEqual(parseGrant(input),input)})
test('grant, audit and brand balance commit together; stable retries do not double grant',async()=>{const h=db();const a=await grantElyseraCredits(h.prisma,input,admin),b=await grantElyseraCredits(h.prisma,input,admin);assert.equal(a.balanceCents,101);assert.equal(b.balanceCents,101);assert.equal(b.replayed,true);assert.equal(h.state.rows.length,1);assert.equal(h.state.audit.length,1);assert.match(h.state.sql[0],/pg_advisory_xact_lock/);assert.match(h.state.sql[1],/public\."ElyseraAccountProfile".*FOR UPDATE/);assert.ok(h.state.sql.every(s=>!s.includes('CreditTransaction')&&!s.includes('"credits"')))})
test('same request key with changed payload or actor conflicts',async()=>{for(const change of [{amountCents:102},{reason:'Changed reason'},{email:'changed@example.test'},{userId:'other'}]){const h=db();await grantElyseraCredits(h.prisma,input,admin);await assert.rejects(grantElyseraCredits(h.prisma,{...input,...change},admin),/CONFLICT/);assert.equal(h.state.rows.length,1)}const h=db();await grantElyseraCredits(h.prisma,input,admin);await assert.rejects(grantElyseraCredits(h.prisma,input,{...admin,id:'other'}),/CONFLICT/)})
test('non ELYSERA recipient and changed identity cannot write',async()=>{for(const [settings,error] of [[{missing:true},/NOT_FOUND/],[{email:'new@example.test'},/RECIPIENT_CHANGED/]]){const h=db(settings);await assert.rejects(grantElyseraCredits(h.prisma,input,admin),error);assert.equal(h.state.rows.length,0);assert.equal(h.state.audit.length,0)}})
test('audit failure rolls back ledger insert',async()=>{const h=db({auditFailure:true});await assert.rejects(grantElyseraCredits(h.prisma,input,admin),/SECRET_DB_FAILURE/);assert.equal(h.state.rows.length,0);assert.ok(h.state.rolledBack)})
test('unknown profile balance is not zero',async()=>{await assert.rejects(readElyseraCreditBalance({$queryRaw:async()=>[]},'missing'),/NOT_FOUND/)})
function routeHarness({authorized=true,origin=true,grantError}={}){let queries=0;const ctx={NextResponse:{json:(body,{status=200}={})=>({body,status})},prisma:{$queryRaw:async()=>{queries++;return[]}},currentAdmin:async()=>authorized?admin:null,sameOrigin:()=>origin,parseGrant,grantElyseraCredits:grantError?async()=>{throw Error(grantError)}:grantElyseraCredits,readElyseraCreditBalance,URL};vm.createContext(ctx);vm.runInContext(readFileSync('app/api/admin/credits/route.js','utf8').replace(/^import .*$/mg,'').replaceAll('export ','')+';this.handlers={GET,POST}',ctx);return{...ctx.handlers,queries:()=>queries}}
test('anonymous reads and writes and cross origin writes deny before querying',async()=>{for(const opts of [{authorized:false},{origin:false}]){const h=routeHarness(opts);const r=await h.POST({text:async()=>JSON.stringify(input)});assert.ok([401,403].includes(r.status));assert.equal(h.queries(),0)}const h=routeHarness({authorized:false});assert.equal((await h.GET({url:'http://localhost/api/admin/credits?q=a'})).status,401);assert.equal(h.queries(),0)})
test('definite recipient failure is distinguishable from uncertain or conflicting prior grant',async()=>{for(const [grantError,status,code] of [['NOT_FOUND',404,'NOT_FOUND'],['RECIPIENT_CHANGED',409,'RECIPIENT_CHANGED'],['CONFLICT',409,'CONFLICT'],['PRIVATE_DATABASE_FAILURE',503,undefined]]){const response=await routeHarness({grantError}).POST({text:async()=>JSON.stringify(input)});assert.equal(response.status,status);assert.equal(response.body.code,code);assert.doesNotMatch(JSON.stringify(response),/PRIVATE_DATABASE_FAILURE/)}const invalid=await routeHarness().POST({text:async()=>JSON.stringify({...input,amountCents:0})});assert.equal(invalid.status,400);assert.equal(invalid.body.code,'INVALID')})
