import {test} from 'node:test'
import assert from 'node:assert/strict'
import {chatInput,validateName,validateMessage,canModerate,checkVersion} from '../lib/chat/policy.mjs'
import {guestFingerprint,resolveChatActor} from '../lib/chat/identity.mjs'
import {mutateChat,readChat} from '../lib/chat/service.mjs'
import {chatHttpCore} from '../lib/chat/http-core.mjs'
const guest={key:'guest:g1',id:'g1',guest:true,role:'GUEST',name:'',manageRoles:false,fingerprint:'fingerprint1'},admin={key:'user:a1',id:'a1',guest:false,role:'ADMIN',manageRoles:true,name:'Team'}
const input=(changes={})=>({actorId:guest.key,requestId:'01234567-1234-1234-1234-123456789abc',action:'SEND',body:'Meine Pflegeroutine ist sehr einfach.',displayName:'Lena',...changes})
test('message/name/domain validation rejects unsafe input and accepts own links',()=>{for(const text of ['', 'x'.repeat(501),'a\nb\nc\nd\ne\nf\ng','https://evil.test/shop','name@evil.test','mein Shop ist toll','idiot'])assert.throws(()=>validateMessage(text,'elysera.com'));assert.equal(validateMessage('Hallo https://elysera.com/routine','elysera.com'),'Hallo https://elysera.com/routine');for(const name of ['a','ELYSERA Team','Admin','<b>Hallo</b>','@profil'])assert.throws(()=>validateName(name));assert.equal(validateName('Lena'),'Lena')})
test('actions require exact actor, request, version and supported role/duration',()=>{for(const patch of [{actorId:null},{requestId:'bad'},{unknown:1},{action:'DELETE_ALL'}])assert.throws(()=>chatInput(input(patch),'elysera.com'));assert.throws(()=>chatInput(input({action:'BAN',targetId:'m',expectedVersion:0,reason:'Spam',duration:'forever'}),'elysera.com'));assert.throws(()=>checkVersion({version:1},0),e=>e.code==='VERSION_CONFLICT')})
test('rank isolation and protected accounts',()=>{assert.equal(canModerate({...admin,manageRoles:false},{actorKey:'user:x',role:'MEMBER'}),true);assert.equal(canModerate({...admin,manageRoles:false},{actorKey:'user:x',role:'ADMIN'}),false);assert.equal(canModerate(admin,{actorKey:'user:x',role:'ADMIN',protected:true}),false);assert.equal(canModerate(admin,{actorKey:admin.key,role:'MEMBER'}),false);assert.equal(canModerate({...guest,role:'MODERATOR'},{actorKey:'user:x',role:'MODERATOR'}),false)})
test('guest trusted fingerprint ignores spoofed headers unless verified hosting configured',()=>{const req={headers:new Headers({'x-forwarded-for':'203.0.113.7','x-real-ip':'203.0.113.8'})},secret='x'.repeat(64);assert.equal(guestFingerprint(req,{NODE_ENV:'production',ELYSERA_CHAT_GUEST_SECRET:secret}),null);assert.equal(guestFingerprint(req,{NODE_ENV:'production',VERCEL:'1',ELYSERA_CHAT_TRUSTED_PROXY:'vercel'}),null);const env={NODE_ENV:'production',VERCEL:'1',ELYSERA_CHAT_TRUSTED_PROXY:'vercel',ELYSERA_CHAT_GUEST_SECRET:secret};assert.equal(guestFingerprint(req,env).length,64);assert.equal(guestFingerprint({headers:new Headers({'x-forwarded-for':'203.0.113.7, 1.2.3.4'})},env),null);assert.equal(guestFingerprint(req,{...env,NODE_ENV:'development'}),guestFingerprint({headers:new Headers()},{...env,NODE_ENV:'development'}))})
function fake({auditFailure=false,banned=false,rate={},role='MEMBER'}={}){let state={messages:[],events:[],audits:[],bans:[],roles:[],version:0};const target={id:'m1',actorKey:'guest:g2',guestId:'g2',userId:null,fingerprint:'fp2',authorName:'Mia',authorRole:'GUEST',role:'GUEST',protected:false,body:'Hallo',version:0,createdAt:new Date(),deletedAt:null};state.messages.push(target)
const tx={$executeRaw:async(parts,...v)=>{const q=parts.join('?');if(q.startsWith('INSERT INTO public."ElyseraChatEvent"'))state.events.push({messageId:v[0]});return 1},$queryRaw:async(parts,...v)=>{const q=parts.join('?');if(q.startsWith('SELECT u."blocked"'))return [{blocked:false,userId:admin.id,enabled:true,role}];if(q.startsWith('SELECT "payload"'))return state.audits.filter(a=>a.actorKey===v[0]&&a.requestId===v[1]);if(q.startsWith('SELECT "id","reason"'))return banned?[{id:'ban',reason:'Spam'}]:[];if(q.startsWith('SELECT count(*) FILTER'))return [{recent:0,cooldown:false,duplicate:false,...rate}];if(q.startsWith('INSERT INTO public."ElyseraChatMessage"')){const m={id:v[0],actorKey:v[1],userId:v[2],adminId:v[3],guestId:v[4],fingerprint:v[5],authorName:v[6],authorRole:v[7],body:v[8],version:0};state.messages.push(m);return [m]};if(q.startsWith('SELECT m.*'))return state.messages.filter(m=>m.id===v[0]);if(q.startsWith('INSERT INTO public."ElyseraChatBan"')){const b={id:v[0],actorKey:v[1],displayName:v[6],reason:v[7],expiresAt:v[8],version:0};state.bans.push(b);return [b]};if(q.startsWith('UPDATE public."ElyseraChatMessage"')){const m=state.messages.find(m=>m.id===v[2]);m.deletedAt=new Date();m.version++;return [m]};if(q.startsWith('SELECT p."userId"'))return [{userId:v[0],blocked:false,protected:false,role,version:state.version}];if(q.startsWith('INSERT INTO public."ElyseraChatRole"')){state.version++;const r={userId:v[0],role:v[1],version:state.version};state.roles.push(r);return [r]};if(q.startsWith('SELECT * FROM public."ElyseraChatBan"'))return state.bans.filter(b=>b.id===v[0]);if(q.startsWith('UPDATE public."ElyseraChatBan"')){const b=state.bans.find(b=>b.id===v[1]);b.revokedAt=new Date();b.version++;return [b]};if(q.startsWith('INSERT INTO public."ElyseraChatAudit"')){if(auditFailure)throw Error('audit unavailable');const a={actorKey:v[0],requestId:v[1],payload:JSON.parse(v[2]),after:JSON.parse(v[4])};state.audits.push(a);return [a]};throw Error('Unexpected query '+q)}};
return {state:()=>state,db:{$transaction:async(fn,options)=>{assert.equal(options.timeout,30000);const before=structuredClone(state);try{return await fn(tx)}catch(e){state=before;throw e}}}}}
test('send audited once, exact replay no duplicate, altered request conflicts',async()=>{const f=fake(),p=input();const result=await mutateChat(f.db,guest,p,'elysera.com');assert.equal(result.applied.action,'SEND');assert.equal(f.state().messages.length,2);assert.equal((await mutateChat(f.db,guest,p,'elysera.com')).replayed,true);assert.equal(f.state().messages.length,2);await assert.rejects(mutateChat(f.db,guest,{...p,body:'Eine andere Nachricht.'},'elysera.com'),e=>e.code==='REQUEST_ID_CONFLICT')})
test('guest missing fingerprint, ban, rate and duplicate prevent sends',async()=>{await assert.rejects(mutateChat(fake().db,{...guest,fingerprint:null},input(),'elysera.com'),e=>e.code==='GUEST_UNAVAILABLE');for(const [config,code] of [[{banned:true},'BANNED'],[{rate:{recent:8}},'RATE_LIMITED'],[{rate:{cooldown:true}},'RATE_LIMITED'],[{rate:{duplicate:true}},'DUPLICATE']]){const f=fake(config);await assert.rejects(mutateChat(f.db,guest,input(),'elysera.com'),e=>e.code===code);assert.equal(f.state().messages.length,1)}})
test('audit failure rolls back send and event',async()=>{const f=fake({auditFailure:true});await assert.rejects(mutateChat(f.db,guest,input(),'elysera.com'));assert.equal(f.state().messages.length,1);assert.equal(f.state().events.length,0)})
test('ban+remove transaction emits tombstone, revoke own ban with version',async()=>{const f=fake();const p=input({actorId:admin.key,action:'BAN',targetId:'m1',expectedVersion:0,reason:'Werbung',duration:'24h'});await mutateChat(f.db,admin,p,'elysera.com');assert.ok(f.state().messages[0].deletedAt);assert.equal(f.state().bans.length,1);const ban=f.state().bans[0];await mutateChat(f.db,admin,input({actorId:admin.key,requestId:'11111111-1234-1234-1234-123456789abc',action:'UNBAN',targetId:ban.id,expectedVersion:0}),'elysera.com');assert.ok(f.state().bans[0].revokedAt)})
test('own role update has no general admin changes, stale version rejected',async()=>{const f=fake();await mutateChat(f.db,admin,input({actorId:admin.key,action:'ROLE',targetId:'u2',expectedVersion:0,role:'MODERATOR'}),'elysera.com');assert.equal(f.state().roles[0].role,'MODERATOR');await assert.rejects(mutateChat(f.db,admin,input({actorId:admin.key,requestId:'11111111-1234-1234-1234-123456789abc',action:'ROLE',targetId:'u2',expectedVersion:0,role:'ADMIN'}),'elysera.com'),e=>e.code==='VERSION_CONFLICT')})
test('chat moderator cannot grant roles and actor identity is bound',async()=>{const f=fake({role:'MODERATOR'});await assert.rejects(mutateChat(f.db,{...admin,manageRoles:false},input({actorId:admin.key,action:'ROLE',targetId:'u2',expectedVersion:0,role:'ADMIN'}),'elysera.com'),e=>e.code==='FORBIDDEN');await assert.rejects(mutateChat(f.db,guest,input({actorId:'guest:other'}),'elysera.com'),e=>e.code==='ACTOR_CHANGED')})
test('incremental cursor delivers100 events then tombstone without jumping',async()=>{const db={$transaction:async fn=>fn({$executeRaw:async()=>1,$queryRaw:async(parts,...values)=>{const q=parts.join('?');if(q.startsWith('SELECT "id","reason"'))return [];if(q.startsWith('SELECT e.')){const start=Number(values[0]);return Array.from({length:start===0?101:1},(_,i)=>({cursor:String(start+i+1),id:'m'+(start+i),messageId:'m'+(start+i),actorKey:'guest:other',authorName:'Gast',role:'GUEST',body:'Nachricht',version:0,createdAt:new Date(),deleted:start===100}));}throw Error(q)}})};const first=await readChat(db,guest,{cursor:'0'});assert.equal(first.messages.length,100);assert.equal(first.cursor,'100');assert.equal(first.hasMore,true);const next=await readChat(db,guest,{cursor:first.cursor});assert.equal(next.cursor,'101');assert.equal(next.messages[0].deleted,true);assert.equal(next.messages[0].body,undefined)})
test('HTTP origin/auth rejects before mutation; unconfirmed errors503',async()=>{let writes=0;const deps={db:{},resolve:async()=>guest,sameOrigin:()=>false,read:async()=>({}),mutate:async()=>{writes++;throw Error('db')},reply:(body,status=200)=>({body,status})};const r={url:'https://elysera.com/api/community-chat',text:async()=>JSON.stringify(input())};assert.equal((await chatHttpCore(r,false,true,deps)).status,403);assert.equal((await chatHttpCore(r,true,false,deps)).status,401);assert.equal(writes,0);assert.equal((await chatHttpCore(r,false,true,{...deps,sameOrigin:()=>true})).status,503)})

test('prototype duration keys and normalized expansion are rejected',()=>{for(const duration of ['__proto__','constructor','toString'])assert.throws(()=>chatInput(input({action:'BAN',targetId:'m1',expectedVersion:0,reason:'Spam',duration}),'elysera.com'));assert.throws(()=>validateMessage('ﬃ'.repeat(200),'elysera.com'));assert.throws(()=>validateName('ﬃ'.repeat(20)))})
test('admin sender without customerprofile uses ownadminFK column',async()=>{const f=fake();await mutateChat(f.db,admin,input({actorId:admin.key,displayName:''}),'elysera.com');const message=f.state().messages[1];assert.equal(message.adminId,admin.id);assert.equal(message.userId,null);assert.equal(message.guestId,null)})

test('unauthenticated admin read does not create guest identity',async()=>{const db={$queryRaw:async()=>{throw Error('Unexpected DB write/read')}};const actor=await resolveChatActor(db,{},async()=>null,async()=>{throw Error('Unexpected user lookup')},true);assert.equal(actor.manageRoles,false);assert.equal(actor.key,'anonymous')})
test('ownadmin actor does not require customer profile or guestsecret',async()=>{const actor=await resolveChatActor({}, {},async()=>({id:'a1',firstName:'Team'}),async()=>{throw Error('Unexpected memberlookup')});assert.equal(actor.key,'user:a1');assert.equal(actor.manageRoles,true);assert.equal(actor.role,'ADMIN')})

test('guest token is random, hashed in database, and cookie survives identity lookup',async()=>{const stored=new Map();const db={$queryRaw:async(parts,...values)=>{assert.equal(values[1].length,64);if(!stored.has(values[1]))stored.set(values[1],values[0]);return [{id:stored.get(values[1])}]}};const request=token=>({cookies:{get:()=>token?{value:token}:undefined},headers:new Headers()});const first=await resolveChatActor(db,request(null),async()=>null,async()=>null);assert.equal(first.cookie.length,64);assert.notEqual([...stored.keys()][0],first.cookie);const second=await resolveChatActor(db,request(first.cookie),async()=>null,async()=>null);assert.equal(first.key,second.key);assert.equal(second.cookie,null);assert.equal(stored.size,1)})

test('member/admin actor resolution receives the same trusted fingerprint as a guest',async()=>{const prior={NODE_ENV:process.env.NODE_ENV,VERCEL:process.env.VERCEL,ELYSERA_CHAT_TRUSTED_PROXY:process.env.ELYSERA_CHAT_TRUSTED_PROXY,ELYSERA_CHAT_GUEST_SECRET:process.env.ELYSERA_CHAT_GUEST_SECRET};try{Object.assign(process.env,{NODE_ENV:'production',VERCEL:'1',ELYSERA_CHAT_TRUSTED_PROXY:'vercel',ELYSERA_CHAT_GUEST_SECRET:'s'.repeat(64)});const request={headers:new Headers({'x-forwarded-for':'203.0.113.44'}),cookies:{get:()=>undefined}},db={$queryRaw:async(parts)=>parts.join('').includes('ElyseraAccountProfile')?[{userId:'u1',role:'MEMBER'}]:[{id:'guest-new'}]};const member=await resolveChatActor(db,request,async()=>null,async()=>({id:'u1',firstName:'Lena'}));const adminActor=await resolveChatActor(db,request,async()=>({id:'a1'}),async()=>null);const guestActor=await resolveChatActor(db,request,async()=>null,async()=>null);assert.equal(member.fingerprint,guestActor.fingerprint);assert.equal(adminActor.fingerprint,guestActor.fingerprint);assert.equal(member.fingerprint.length,64)}finally{for(const [key,value] of Object.entries(prior)){if(value===undefined)delete process.env[key];else process.env[key]=value}}})
test('member fingerprint ban blocks logout guest and reset-cookie guest identities',async()=>{const fingerprint='same-trusted-network-hash';const ban={actorKey:'user:member1',fingerprint,reason:'Wiederholte Werbung'};let writes=0;const db={$transaction:async(fn)=>fn({$executeRaw:async()=>1,$queryRaw:async(parts,...v)=>{const q=parts.join('?');if(q.startsWith('SELECT "payload"'))return [];if(q.startsWith('SELECT "id","reason"')){assert.equal(v[1],fingerprint);return v[0]===ban.actorKey||v[1]===ban.fingerprint?[{id:'member-ban',reason:ban.reason}]:[]}writes++;throw Error('Mutation should not be reached')}})};for(const id of ['guest-logout','guest-cookie-reset']){const actor={...guest,id,key:'guest:'+id,fingerprint};await assert.rejects(mutateChat(db,actor,input({actorId:actor.key}),'elysera.com'),e=>e.code==='BANNED')}assert.equal(writes,0)})
