import test from 'node:test'
import assert from 'node:assert/strict'
import {feedbackInput,feedbackTransition,feedbackProducts} from '../lib/admin/feedback-policy.mjs'
import {feedbackMutate} from '../lib/admin/feedback-service.mjs'
import {feedbackHttpCore} from '../lib/admin/feedback-http-core.mjs'
const raw={actorId:'u',requestId:'11111111-1111-4111-8111-111111111111',id:'f',version:1,status:'ANSWERED',reply:'A useful answer'}
const row={id:'f',productId:feedbackProducts[0],kind:'question',version:1,status:'OPEN',reply:''}
test('foreign products, unknown fields and stale versions reject',()=>{assert.throws(()=>feedbackInput({...raw,userId:'other'},true));assert.throws(()=>feedbackInput({actorId:'u',requestId:raw.requestId,productId:'foreign',kind:'review',body:'hello',rating:5},false));assert.throws(()=>feedbackTransition({...row,productId:'foreign'},raw),{status:404});assert.throws(()=>feedbackTransition({...row,version:2},raw),{code:'VERSION_CONFLICT'});assert.throws(()=>feedbackTransition(row,{...raw,reply:''}));assert.throws(()=>feedbackTransition(row,{...raw,status:'APPROVED'}))})
function mock(auditFails=false){let committed={...row};const db={$transaction:async(fn,options)=>{assert.equal(options.timeout,30000);let working={...committed};const tx={$executeRaw:async(strings,...values)=>{const sql=strings.join('?');if(sql.includes('UPDATE'))working={...working,reply:values[0],status:values[1],version:2};return 1},$queryRaw:async(strings,...values)=>{const sql=strings.join('?');if(sql.includes('SELECT "payload"'))return [];if(sql.includes('INSERT INTO public."ElyseraFeedbackAudit"')){if(auditFails)throw Error('audit storage unavailable');return [{after:JSON.parse(values[5])}]}if(sql.includes('SELECT * FROM public."ElyseraProductFeedback"'))return [{...working}];throw Error(sql)}};const result=await fn(tx);committed=working;return result}};return {db,state:()=>committed}}
test('atomic update returns actual readback and increments version',async()=>{const m=mock();const r=await feedbackMutate(m.db,{id:'u'},true,raw);assert.equal(r.entry.version,2);assert.equal(m.state().reply,raw.reply)})
test('audit failure rolls transaction back',async()=>{const m=mock(true);await assert.rejects(feedbackMutate(m.db,{id:'u'},true,raw));assert.equal(m.state().version,1);assert.equal(m.state().status,'OPEN')})
test('actor changes rejected before transaction',async()=>{await assert.rejects(feedbackMutate({$transaction:()=>assert.fail()},{id:'another'},true,raw),{status:403})})
test('same-origin and admin authentication block service access',async()=>{const deps={sameOrigin:()=>false,reply:(body,status=200)=>({body,status}),currentAdmin:async()=>null,mutate:()=>assert.fail(),read:()=>assert.fail()};const req=new Request('https://elysera.test/api/admin/product-feedback');assert.equal((await feedbackHttpCore(req,true,true,deps)).status,403);assert.equal((await feedbackHttpCore(req,true,false,deps)).status,401)})
test('idempotent retry returns audit snapshot without update',async()=>{const input=feedbackInput(raw,true);const db={$transaction:async fn=>fn({$executeRaw:async(strings)=>{assert.match(strings.join(''),/advisory/);return 1},$queryRaw:async()=>[{payload:{...input,admin:true},after:{...row,version:2}}]})};const r=await feedbackMutate(db,{id:'u'},true,raw);assert.equal(r.replayed,true);assert.equal(r.entry.version,2);await assert.rejects(feedbackMutate(db,{id:'u'},true,{...raw,reply:'different'}),{code:'REQUEST_ID_CONFLICT'})})
test('customer ingestion requires own profile and derives purchase evidence',async()=>{
 const create={actorId:'u',requestId:raw.requestId,productId:feedbackProducts[0],kind:'review',body:'A real customer review',rating:4};let inserted,queries=[]
 const db={$transaction:async fn=>fn({$executeRaw:async(strings,...values)=>{const sql=strings.join('?');queries.push(sql);if(sql.includes('INSERT INTO public."ElyseraProductFeedback"'))inserted={id:values[0],version:1,verifiedPurchase:values[7]};return 1},$queryRaw:async(strings,...values)=>{const sql=strings.join('?');queries.push(sql);if(sql.includes('ElyseraAccountProfile'))return [{userId:'u'}];if(sql.includes('SELECT "payload"'))return [];if(sql.includes('FROM public."Order"'))return [{id:'paid-own-order'}];if(sql.includes('INSERT INTO public."ElyseraFeedbackAudit"'))return [{after:JSON.parse(values[5])}];return [inserted]}})}
 const result=await feedbackMutate(db,{id:'u'},false,create);assert.equal(result.entry.verifiedPurchase,true);const purchaseQuery=queries.find(s=>s.includes('FROM public."Order"'));assert.match(purchaseQuery,/o\."userId"=/);assert.match(purchaseQuery,/NOT EXISTS/);assert.match(purchaseQuery,/PAID/)
 const denied={$transaction:async fn=>fn({$executeRaw:async()=>1,$queryRaw:async()=>[]})};await assert.rejects(feedbackMutate(denied,{id:'u'},false,create),{status:403})
})
