import test from 'node:test'
import assert from 'node:assert/strict'
import {newsInput,newsSlug} from '../lib/news-policy.mjs'
import {newsHttp} from '../lib/news-http.mjs'
import {getNews,listNews,saveNews} from '../lib/news-service.mjs'
import {jsonLd,pageMetadata,siteUrl} from '../lib/seo.mjs'
const input={id:'00000000-0000-4000-8000-000000000001',requestId:'00000000-0000-4000-8000-000000000002',version:0,title:'Neu bei ELYSERA',slug:'neu-bei-elysera',excerpt:'Ein Einblick.',body:'Erster Absatz.\n\n## Hintergrund\n\nWeiterer Text.',image:'',imageAlt:'',seoTitle:'',seoDescription:'',status:'DRAFT'}
test('publication requires content and accessible cover; drafts may be incomplete',()=>{assert.equal(newsInput({...input,body:''}).status,'DRAFT');assert.throws(()=>newsInput({...input,status:'PUBLISHED',body:''}));assert.throws(()=>newsInput({...input,status:'PUBLISHED',image:'/media/a.webp'}));assert.throws(()=>newsInput({...input,image:'https://evil.test/a.jpg'}));assert.throws(()=>newsInput({...input,image:'/media/../private.jpg'}));assert.throws(()=>newsInput({...input,slug:'../admin'}));assert.equal(newsSlug('Öl & Pflege für dich'),'oel-pflege-fuer-dich')})
test('metadata uses canonical production domain and JSON-LD cannot escape its script',()=>{const data={headline:'</script><script>alert(1)</script>'};assert.ok(!jsonLd(data).includes('<'));assert.deepEqual(JSON.parse(jsonLd(data)),data);assert.equal(pageMetadata('Titel','Text','/news/beitrag').alternates.canonical,siteUrl+'/news/beitrag');assert.equal(pageMetadata('Konto','Text','/account',undefined,true).robots.index,false)})
test('news endpoint rejects cross-origin writes and unauthenticated reads before touching storage',async()=>{let touched=false;const deps={db:{},sameOrigin:()=>false,currentAdmin:async()=>null,reply:(body,status=200)=>({body,status}),list:async()=>{touched=true},save:async()=>{touched=true}};assert.equal((await newsHttp(new Request('https://www.elysera.org/api/admin/news'),true,deps)).status,403);assert.equal((await newsHttp(new Request('https://www.elysera.org/api/admin/news'),false,deps)).status,401);assert.equal(touched,false)})
test('public queries exclude draft and archived articles in SQL, not in browser code',async()=>{const queries=[];const db={$queryRaw:async(parts)=>{queries.push(parts.join('?'));return []}};assert.equal(await getNews(db,'draft'),null);assert.deepEqual(await listNews(db),{items:[],more:false});assert.ok(queries.every(q=>q.includes("PUBLISHED")&&q.includes('"publishedAt"<=now()')))})
test('concurrent updates, retry replay and published slugs are guarded before mutation',async()=>{let row={...input,version:2,publishedAt:new Date(),lastRequestId:'another',authorId:'admin'},writes=0;const tx={$executeRaw:async()=>{},$queryRaw:async(parts)=>{if(parts.join('').includes('FOR UPDATE'))return [row];writes++;return []}};const db={$transaction:async fn=>fn(tx)};await assert.rejects(saveNews(db,{id:'admin'},input),{status:409});await assert.rejects(saveNews(db,{id:'admin'},{...input,version:2,slug:'changed'}),{status:409});row={...row,lastRequestId:input.requestId,lastRequest:Object.fromEntries(Object.entries(input).reverse())};assert.equal((await saveNews(db,{id:'admin'},input)).replayed,true);assert.equal(writes,0)})

test('admin identity and malformed payloads are rejected before saving',async()=>{let touched=false;const deps={db:{},sameOrigin:()=>true,currentAdmin:async()=>({id:'admin',role:'ADMIN'}),reply:(body,status=200)=>({body,status}),save:async()=>{touched=true}};const request=body=>new Request('https://www.elysera.org/api/admin/news',{method:'PATCH',body:JSON.stringify(body)});assert.equal((await newsHttp(request(null),true,deps)).status,400);assert.equal((await newsHttp(request({...input,actorId:'other'}),true,deps)).status,403);assert.equal(touched,false)})
