import test from 'node:test'
import assert from 'node:assert/strict'
import {orderDetailsInput,orderDetailsScope,orderDetailsVersion} from '../lib/admin/order-details-policy.mjs'
import {orderDetailsMutate} from '../lib/admin/order-details-service.mjs'
import {orderDetailsHttp} from '../lib/admin/order-details-http.mjs'
const base={id:'own-order',xmin:'123',status:'PAID',orderCategory:'STANDARD',adminComment:'',shippingName:'A Name',shippingAddress1:'Old road 1',shippingAddress2:'',shippingCity:'Berlin',shippingState:'',shippingPostalCode:'10115',shippingCountry:'DE'}
const raw=()=>({actorId:'admin',orderId:'own-order',requestId:'request-1234567890',expected:{xmin:'123',status:'PAID'},orderCategory:'URGENT',reason:'Adresse korrigiert',adminComment:'  Nur intern  ',shippingName:'A Name',shippingAddress1:'New road 2',shippingAddress2:'',shippingCity:'Berlin',shippingState:'',shippingPostalCode:'10115',shippingCountry:'DE'})
function database({items=[{productId:'own'}],auditFailure=false,readbackFailure=false}={}){const calls=[];let state={...base},audit=null;const db={calls,setItems:v=>items=v,$transaction:async(fn,options)=>{assert.equal(options.timeout,30000);return fn(db)},$executeRaw:async(strings,...values)=>{const q=strings.join('?');calls.push(q);if(q.startsWith('UPDATE public."Order"')){for(const [index,key] of ['shippingName','shippingAddress1','shippingAddress2','shippingCity','shippingState','shippingPostalCode','shippingCountry','adminComment','orderCategory'].entries())state[key]=values[index];state.xmin='124';if(readbackFailure)state.shippingCity='WRONG'}return 1},$queryRaw:async(strings,...values)=>{const q=strings.join('?');calls.push(q);if(q.includes('FROM public."Order"'))return [{...state}];if(q.includes('FROM public."OrderItem"'))return items;if(q.includes('SELECT "request","after"'))return audit?[audit]:[];if(q.includes('enum_range'))return [{category:'STANDARD'},{category:'URGENT'}];if(q.startsWith('INSERT INTO public."ElyseraOrderDetailsAudit"')){audit={request:Object.fromEntries(Object.entries(JSON.parse(values[3])).reverse()),after:Object.fromEntries(Object.entries(JSON.parse(values[5])).reverse())};return auditFailure?[]:[audit]}throw Error(q)}};return db}
test('scope rejects empty, foreign and null lines',()=>{for(const items of [[],[{productId:null}],[{productId:'own'},{productId:'foreign'}]])assert.throws(()=>orderDetailsScope(items,['own']));orderDetailsScope([{productId:'own'}],['own'])})
test('strict source categories, comment limits, string snapshot and allowed fields',()=>{assert.equal(orderDetailsInput(raw()).adminComment,'Nur intern');for(const extra of [{orderCategory:'HIGH'},{adminComment:'a'.repeat(2001)},{shippingCountry:4},{reason:''},{expected:{xmin:123,status:'PAID'}},{status:'PAID'},{userId:'foreign'},{total:0}])assert.throws(()=>orderDetailsInput({...raw(),...extra}));assert.throws(()=>orderDetailsVersion({...base,xmin:'124'},raw()),e=>e.code==='STALE_VERSION')})
test('locks scoped rows; only address/comment/category writes; readback audited; canonical retry exact',async()=>{const db=database();const result=await orderDetailsMutate(db,{id:'admin'},['own'],raw());assert.equal(result.state.shippingAddress1,'New road 2');assert.equal(result.state.adminComment,'Nur intern');assert.equal(result.state.shippingState,'');assert.equal(result.state.status,'PAID');assert(db.calls.some(q=>q.includes('OrderItem')&&q.includes('FOR SHARE')));assert(db.calls.some(q=>q.includes('FROM public."Order"')&&q.includes('FOR UPDATE')));const update=db.calls.find(q=>q.startsWith('UPDATE'));assert.doesNotMatch(update,/'status'|"status"|User|stock|total|price|paid/);const retry=await orderDetailsMutate(db,{id:'admin'},['own'],raw());assert.equal(retry.replayed,true);assert.equal(db.calls.filter(q=>q.startsWith('UPDATE')).length,1);await assert.rejects(orderDetailsMutate(db,{id:'admin'},['own'],{...raw(),adminComment:'changed'}),e=>e.code==='REQUEST_ID_CONFLICT');db.setItems([{productId:null}]);await assert.rejects(orderDetailsMutate(db,{id:'admin'},['own'],raw()),e=>e.status===404)})
test('scope/version/actor failures prevent write; audit/readback fail closed',async()=>{const db=database({items:[{productId:'foreign'}]});await assert.rejects(orderDetailsMutate(db,{id:'admin'},['own'],raw()));assert(!db.calls.some(q=>q.startsWith('UPDATE')));await assert.rejects(orderDetailsMutate(database(),{id:'other'},['own'],raw()),e=>e.code==='ACTOR_CHANGED');await assert.rejects(orderDetailsMutate(database(),{id:'admin'},['own'],{...raw(),expected:{xmin:'122',status:'PAID'}}),e=>e.code==='STALE_VERSION');await assert.rejects(orderDetailsMutate(database({auditFailure:true}),{id:'admin'},['own'],raw()),/AUDIT_FAILED/);await assert.rejects(orderDetailsMutate(database({readbackFailure:true}),{id:'admin'},['own'],raw()),/READBACK_FAILED/)})
test('HTTP sameOrigin/auth before reading or writing; redacted unknown errors',async()=>{let calls=0;const deps={db:database(),ids:['own'],reply:(body,status=200)=>({body,status}),sameOrigin:()=>false,currentAdmin:async()=>{calls++;return {id:'admin'}},read:async()=>base,mutate:async()=>{throw Error('secret database')}};const request={url:'https://example.test/api/admin/orders/details?id=own-order',text:async()=>JSON.stringify(raw())};assert.equal((await orderDetailsHttp(request,true,deps)).status,403);assert.equal(calls,0);assert.equal((await orderDetailsHttp(request,true,{...deps,sameOrigin:()=>true,currentAdmin:async()=>null})).status,401);const unknown=await orderDetailsHttp(request,true,{...deps,sameOrigin:()=>true});assert.equal(unknown.status,503);assert.equal(unknown.body.code,'UNCONFIRMED');assert.doesNotMatch(JSON.stringify(unknown),/secret/);assert.equal((await orderDetailsHttp(request,false,deps)).body.state.id,'own-order')})
