import test from 'node:test'
import assert from 'node:assert/strict'
import {orderActionInput,orderActionScope,orderActionVersion,orderPaymentAmount} from '../lib/admin/order-actions-policy.mjs'
import {orderActionMutate} from '../lib/admin/order-actions-service.mjs'
const raw=()=>({actorId:'admin',orderId:'own-order',requestId:'request-1234567890',expected:{xmin:'123',status:'PAID',version:0},status:'PACKED',trackingNumber:'ABC',trackingCarrier:'DHL',note:'Vorsichtig packen',reason:'Versand vorbereitet'})
function database({items=[{productId:'own'}],auditFailure=false,initialStatus='PAID',denied=false}={}){const calls=[];let status=initialStatus,paidAt=null,outstandingEur=129,version=0,ops=null,audit=null;const db={calls,$transaction:async(fn,options)=>{assert.equal(options.timeout,30000);return fn(db)},$executeRaw:async(strings,...values)=>{const q=strings.join('?');calls.push(q);if(q.startsWith('UPDATE public."Order"')){if(q.includes('paidAt')){status='PAID';paidAt=new Date().toISOString();outstandingEur=0}else status=values[0]};if(q.startsWith('INSERT INTO public."ElyseraOrderOperations"')){version++;ops={version,trackingNumber:values[1],trackingCarrier:values[2],note:values[3]}}return 1},$queryRaw:async(strings,...values)=>{const q=strings.join('?');calls.push(q);if(q.includes('FROM public."ElyseraAdminAccess"'))return denied?[]:[{enabled:true,emailVerified:true,email:'admin@example.invalid',supabaseUserId:'auth-id'}];if(q.includes('FROM public."Order"'))return [{id:'own-order',status,xmin:'123',total:129,discount:0,outstandingEur,paidAt}];if(q.includes('FROM public."OrderItem"'))return items;if(q.includes('FROM public."ElyseraOrderOperations"'))return ops?[ops]:[];if(q.includes('SELECT "request","after"'))return audit?[audit]:[];if(q.includes('enum_range'))return ['PAID','PACKED'].map(status=>({status}));if(q.startsWith('INSERT INTO public."ElyseraOrderAudit"')){audit={request:JSON.parse(values[3]),after:JSON.parse(values[5])};return auditFailure?[]:[audit]}throw Error(q)}};return db}
test('reject foreign, null and empty scopes',()=>{for(const items of [[],[{productId:null}],[{productId:'own'},{productId:'foreign'}]])assert.throws(()=>orderActionScope(items,['own']));orderActionScope([{productId:'own'}],['own'])})
test('strict input and explicit payment confirmation',()=>{assert.throws(()=>orderActionInput({...raw(),stock:5}));assert.throws(()=>orderActionInput({...raw(),reason:''}));assert.throws(()=>orderActionInput({...raw(),expected:{xmin:'123',status:'PENDING',version:0},status:'PAID'}));assert.throws(()=>orderActionVersion({xmin:'124',status:'PAID',version:0},raw()),e=>e.code==='STALE_VERSION')})
test('write locks scope, reads back and audits; exact retry is replayed',async()=>{const db=database();const first=await orderActionMutate(db,{id:'admin',email:'admin@example.invalid',supabaseUserId:'auth-id'},['own'],raw());assert.equal(first.state.version,1);assert.equal(first.state.status,'PACKED');assert(db.calls.find(q=>q.includes('OrderItem')&&q.includes('FOR SHARE')));assert(db.calls.find(q=>q.includes('FROM public."Order"')&&q.includes('FOR UPDATE')));const retry=await orderActionMutate(db,{id:'admin',email:'admin@example.invalid',supabaseUserId:'auth-id'},['own'],raw());assert.equal(retry.replayed,true);assert.equal(db.calls.filter(q=>q.startsWith('UPDATE public."Order"')).length,1);await assert.rejects(orderActionMutate(db,{id:'admin',email:'admin@example.invalid',supabaseUserId:'auth-id'},['own'],{...raw(),note:'Changed'}),e=>e.code==='REQUEST_ID_CONFLICT')})
test('scope and audit failure cannot return success; actor protected',async()=>{const db=database({items:[{productId:'foreign'}]});await assert.rejects(orderActionMutate(db,{id:'admin',email:'admin@example.invalid',supabaseUserId:'auth-id'},['own'],raw()),e=>e.status===404);assert(!db.calls.some(q=>q.startsWith('UPDATE')));await assert.rejects(orderActionMutate(database({auditFailure:true}),{id:'admin',email:'admin@example.invalid',supabaseUserId:'auth-id'},['own'],raw()),/AUDIT_FAILED/);await assert.rejects(orderActionMutate(database(),{id:'other'},['own'],raw()),e=>e.code==='ACTOR_CHANGED')})
test('unpaid issue and cash on delivery cannot promote to paid turnover states',()=>{for(const status of ['PENDING','ISSUE','AWAITING_PAY_ON_DELIVERY','AWAITING_BANK_TRANSFER','AWAITING_STRIPE'])for(const target of ['PACKED','SHIPPED','DELIVERED'])assert.throws(()=>orderActionVersion({xmin:'123',status,version:0},{...raw(),expected:{xmin:'123',status,version:0},status:target}),e=>e.code==='INVALID_TRANSITION')})

const actor={id:'admin',email:'admin@example.invalid',supabaseUserId:'auth-id'};
const paid=()=>({...raw(),expected:{xmin:'123',status:'PENDING',version:0},status:'PAID',paymentReceived:true});
test('manual payment is atomic, audit records amount/date, exact replay does not settle twice',async()=>{const db=database({initialStatus:'PENDING'});const first=await orderActionMutate(db,actor,['own'],paid());assert.equal(first.state.status,'PAID');assert.equal(first.state.outstandingEur,0);assert(first.state.paidAt);const replay=await orderActionMutate(db,actor,['own'],paid());assert(replay.replayed);assert.equal(db.calls.filter(q=>q.startsWith('UPDATE public."Order"')).length,1);assert(db.calls.some(q=>q.includes('ElyseraAdminAccess')&&q.includes('FOR SHARE')));assert(!db.calls.some(q=>/Commission|Products|Email/.test(q)))});
test('payment rejects settled, unknown, negative and excessive amounts',()=>{for(const extra of [{paidAt:'2026-09-13'},{outstandingEur:null},{outstandingEur:0},{outstandingEur:-1},{outstandingEur:130},{outstandingEur:1.001},{total:NaN}])assert.throws(()=>orderPaymentAmount({total:129,discount:0,outstandingEur:129,paidAt:null,...extra}),e=>e.code==='INVALID_PAYMENT');assert.equal(orderPaymentAmount({total:129,discount:0,outstandingEur:129,paidAt:null}),12900)});
test('fresh revoked administrator cannot write or replay',async()=>{const db=database({denied:true});await assert.rejects(orderActionMutate(db,actor,['own'],raw()),e=>e.status===401);assert(!db.calls.some(q=>q.startsWith('UPDATE')))});
test('cancelled and issue orders cannot be marked paid',()=>{for(const status of ['CANCELLED','ISSUE'])assert.throws(()=>orderActionVersion({xmin:'123',status,version:0},{...paid(),expected:{xmin:'123',status,version:0}}),e=>e.code==='INVALID_TRANSITION')});
