import test from 'node:test'
import assert from 'node:assert/strict'
import {createOrderInput,priceCents,customerChoice,productChoice} from '../lib/admin/order-create-policy.mjs'
import {orderCreateMutate,orderCreateChoices} from '../lib/admin/order-create-service.mjs'
import {orderCreateHttp} from '../lib/admin/order-create-http.mjs'
const ids=['own-a','own-b','own-c'],actor={id:'admin',email:'admin@example.test',supabaseUserId:'auth-admin'},customer={id:'customer',firstName:'Alexandra',secondName:'Beispiel',email:'alexandra@example.test',profileVersion:'4294967290',userVersion:'4294967291',blocked:false,role:'USER'},products=ids.map((id,i)=>({id,name:'Produkt '+id,price:i===0?19.99:2.01,stock:12,active:true,staffOnly:false,version:'4294967292'}))
const input=()=>({actorId:'admin',requestId:'request-fixture-123456',customer:customerChoice(customer),items:[{...productChoice(products[1]),quantity:3},{...productChoice(products[0]),quantity:2}],shipping:{name:'Alexandra Beispiel',address1:'Beispielstraße 12',address2:'Etage 2',postalCode:'10115',city:'Berlin',state:'',country:'Deutschland'},discountCents:101,note:'Bitte sorgfältig verpacken.'})
function fixture(){const db={state:{access:{enabled:true,blocked:false,emailVerified:true,email:actor.email,supabaseUserId:actor.supabaseUserId},customer:structuredClone(customer),products:structuredClone(products),orders:[],items:[],audits:[]},calls:[],failAudit:false,transactions:0};db.$transaction=async(fn,options)=>{assert.deepEqual(options,{timeout:30000,maxWait:10000});db.transactions++;const s=structuredClone(db.state),tx=sql(s,db);const result=await fn(tx);db.state=s;return result};Object.assign(db,sql(db.state,db));return db}
function sql(s,db){return {$queryRaw:async(strings,...v)=>{const q=strings.join('?');db.calls.push(q);if(q.includes('ElyseraPackage'))return [];if(q.includes('ElyseraAdminAccess'))return s.access?[s.access]:[];if(q.includes('ElyseraOrderCreateAudit'))return s.audits.filter(a=>a.actorId===v[0]&&a.requestId===v[1]);if(q.includes('enum_range'))return [{status:'PENDING'}];if(q.includes('FOR UPDATE OF p,u'))return s.customer?[s.customer]:[];if(q.includes('FROM public."Products"'))return q.includes('ANY')?s.products:s.products.filter(p=>p.id===v[0]);if(q.includes('FROM public."Order"'))return s.orders.filter(o=>o.id===v[0]);if(q.includes('FROM public."OrderItem"'))return s.items.filter(i=>i.orderId===v[0]).sort((a,b)=>a.id.localeCompare(b.id));if(q.includes('SELECT "userId"'))return s.customer?[{userId:s.customer.id}]:[];if(q.includes('ElyseraAccountProfile'))return s.customer?[s.customer]:[];throw Error('Unexpected query '+q)},$executeRaw:async(strings,...v)=>{const q=strings.join('?');db.calls.push(q);if(q.includes('pg_advisory'))return 1;if(q.includes('INSERT INTO public."Order"')){s.orders.push({id:v[0],userId:v[1],total:v[2],status:'PENDING',discount:v[3],outstandingEur:v[4],shippingName:v[5],shippingAddress1:v[6],shippingAddress2:v[7],shippingPostalCode:v[8],shippingCity:v[9],shippingState:v[10],shippingCountry:v[11],note:v[12],paidAt:null,paymentToken:null,createdAt:'2026-09-13T12:00:00Z'});return 1}if(q.includes('INSERT INTO public."OrderItem"')){s.items.push({orderId:v[1],id:v[2],quantity:v[3],price:v[4],name:s.products.find(p=>p.id===v[2]).name});return 1}if(q.includes('INSERT INTO public."ElyseraOrderCreateAudit"')){if(db.failAudit)throw Error('AUDIT_FAILURE');s.audits.push({actorId:v[1],requestId:v[2],orderId:v[3],customerId:v[4],request:JSON.parse(v[5]),after:JSON.parse(v[6])});return 1}throw Error('Unexpected mutation '+q)}}}
test('strict cents, explicit zero default discount, bounded quantities and no injected payment fields',()=>{assert.equal(priceCents(19.99),1999);assert.equal(priceCents(null),null);assert.equal(priceCents(1.001),null);const raw=input();delete raw.discountCents;assert.equal(createOrderInput(raw,ids).discountCents,0);assert.equal(createOrderInput(raw,ids).grossCents,4601);for(const mutate of [x=>x.items[0].quantity=1.5,x=>x.items[0].quantity=0,x=>x.items[0].id='foreign',x=>x.items.push(x.items[0]),x=>x.discountCents=4602,x=>x.shipping.address1='',x=>x.initialStatus='PAID',x=>x.items[0].priceCents=1.1]){const x=input();mutate(x);assert.throws(()=>createOrderInput(x,ids))}})
test('creates only unpaid own Order/OrderItems with deterministic product locks, integer totals and audit',async()=>{const db=fixture(),before=structuredClone(db.state.products),r=await orderCreateMutate(db,actor,ids,input());assert.equal(r.order.status,'PENDING');assert.equal(r.order.grossCents,4601);assert.equal(r.order.discountCents,101);assert.equal(r.order.outstandingCents,4500);assert.equal(r.order.paidAt,null);assert.equal(r.order.hasPaymentToken,false);assert.deepEqual(db.state.products,before);assert.equal(db.state.orders.length,1);assert.equal(db.state.audits.length,1);assert(db.calls.some(q=>q.includes('FOR UPDATE OF p,u')));assert(db.calls.filter(q=>q.includes('Products')&&q.includes('FOR UPDATE')).length===2);assert(!db.calls.some(q=>/^UPDATE|Credit|Commission|Notification/.test(q)))})
test('same key exactly replays current later order state; changed request cannot create a second order',async()=>{const db=fixture(),raw=input(),a=await orderCreateMutate(db,actor,ids,raw);db.state.orders[0].status='ISSUE';db.state.products[0].active=false;const b=await orderCreateMutate(db,actor,ids,raw);assert.equal(b.replayed,true);assert.equal(b.order.id,a.order.id);assert.equal(b.order.status,'ISSUE');assert.equal(db.state.orders.length,1);const changed=input();changed.note='Anderer Text';await assert.rejects(orderCreateMutate(db,actor,ids,changed),e=>e.code==='REQUEST_REUSED')})
test('own profile, blocked role, stale price/version/name, inactive products reject before creation',async()=>{for(const alter of [s=>s.customer=null,s=>s.customer.blocked=true,s=>s.customer.role='ADMIN',s=>s.customer.userVersion='4294967299',s=>s.products[0].price=20,s=>s.products[0].active=false,s=>s.products[0].staffOnly=true]){const db=fixture();alter(db.state);await assert.rejects(orderCreateMutate(db,actor,ids,input()));assert.equal(db.state.orders.length,0)}const db=fixture();await assert.rejects(orderCreateMutate(db,{id:'other'},ids,input()),e=>e.status===403);assert.equal(db.transactions,0)})
test('audit failure rolls back order/items; replay rejects foreign or mismatched customer scope',async()=>{const db=fixture();db.failAudit=true;await assert.rejects(orderCreateMutate(db,actor,ids,input()),/AUDIT_FAILURE/);assert.equal(db.state.orders.length,0);assert.equal(db.state.items.length,0);db.failAudit=false;await orderCreateMutate(db,actor,ids,input());db.state.items[0].id='foreign';await assert.rejects(orderCreateMutate(db,actor,ids,input()),e=>e.code==='OUT_OF_SCOPE')})
test('choices disclose cap and retain inactive own product visibility',async()=>{const db=fixture();db.state.products[0].active=false;const r=await orderCreateChoices(db,ids,'alexandra');assert.equal(r.products[0].active,false);assert.equal(r.products.length,3);assert.equal(r.limited,false);assert(db.calls.some(q=>q.includes('LIMIT 101')&&q.includes('ElyseraAccountProfile')));assert(db.calls.some(q=>q.includes('ANY')))});
test('HTTP origin/auth checks precede parsing; invalid and uncertain responses separated',async()=>{const reply=(body,status=200)=>({body,status}),base={db:{},actor:async()=>actor,sameOrigin:()=>true,ids,reply,choices:async()=>({customers:[],products:[]}),mutate:async()=>{throw Error('db timeout')}};const request=()=>new Request('http://localhost/api/admin/orders/create',{method:'POST',body:JSON.stringify(input())});assert.equal((await orderCreateHttp(request(),true,{...base,sameOrigin:()=>false})).status,403);assert.equal((await orderCreateHttp(request(),true,{...base,actor:async()=>null})).status,401);assert.equal((await orderCreateHttp(new Request('http://localhost/api',{method:'POST',body:'{'}),true,base)).status,400);assert.equal((await orderCreateHttp(request(),true,base)).status,503)})

test('revoked own admin access after lock wait cannot create or replay; stock is not reserved',async()=>{const db=fixture();db.state.access.enabled=false;await assert.rejects(orderCreateMutate(db,actor,ids,input()),e=>e.status===401);assert.equal(db.state.orders.length,0);db.state.access.enabled=true;db.state.products[0].stock=1;const raw=input();raw.items.find(p=>p.id==='own-a').stock=1;raw.items.find(p=>p.id==='own-a').quantity=20;await orderCreateMutate(db,actor,ids,raw);assert.equal(db.state.products[0].stock,1);db.state.access.enabled=false;await assert.rejects(orderCreateMutate(db,actor,ids,raw),e=>e.status===401);assert.equal(db.state.orders.length,1)})
test('multiline internal note survives exact create and replay readback',async()=>{const db=fixture(),raw=input();raw.note='Erste Zeile\nZweite Zeile mit Umlaut: sorgfältig.\nDritte Zeile';const a=await orderCreateMutate(db,actor,ids,raw);assert.equal(a.order.note,raw.note);const b=await orderCreateMutate(db,actor,ids,raw);assert.equal(b.order.note,raw.note);assert.equal(b.replayed,true);assert.equal(db.state.audits[0].after.note,raw.note)})

test('explicit complete set is captured in the immutable creation audit',async()=>{const {ritualPackage}=await import('../lib/commission-packages.mjs');const ownIds=ritualPackage.items.map(p=>p.productId),db=fixture();db.state.products=products.map((p,i)=>({...p,id:ownIds[i]}));const raw={...input(),packageId:ritualPackage.id,items:db.state.products.map(p=>({...productChoice(p),quantity:1}))};const result=await orderCreateMutate(db,actor,ownIds,raw);assert.equal(result.order.package.id,ritualPackage.id);assert.equal(db.state.audits[0].after.package.items.length,3);assert.equal(result.order.status,'PENDING');assert.equal(result.order.paidAt,null);const missing=fixture();missing.state.products=db.state.products;await assert.rejects(orderCreateMutate(missing,actor,ownIds,{...raw,items:raw.items.slice(1)}));assert.equal(missing.state.orders.length,0)})
