import test from 'node:test'
import assert from 'node:assert/strict'
import {products as catalogProducts} from '../app/catalog.js'
import {productContentIds,productContentDefault,pickProductContent,resolveProductContent,validateProductContent} from '../lib/product-content.mjs'
import {productContentState,productContentInput} from '../lib/admin/product-content-policy.mjs'
import {mutateProductContent} from '../lib/admin/product-content-service.mjs'
import {productContentHttp} from '../lib/admin/product-content-http.mjs'
const id=productContentIds[0],original=productContentState(id)
const raw=()=>({actorId:'admin',productId:id,requestId:'request-1234567890',expectedVersion:0,expectedSnapshot:original.snapshot,content:{...pickProductContent(productContentDefault(id)),name:'Test öffentlicher Name'},reason:'Test der Textpflege'})
function database({auditFailure=false,readbackFailure=false}={}){const calls=[];let row=null,audit=null;return {calls,$transaction:async function(fn,options){assert.equal(options.timeout,30000);return fn(this)},$executeRaw:async(strings,...values)=>{const q=strings.join('?');calls.push(q);if(q.startsWith('INSERT INTO public."ElyseraProductContent"')){row={productId:id,version:(row?.version??0)+1,content:JSON.parse(values[1])};if(readbackFailure)row.content.name='wrong'}return 1},$queryRaw:async(strings,...values)=>{const q=strings.join('?');calls.push(q);if(q.includes('FROM public."Products"'))return [{id,name:'ERP ELYSERA Name 30ml'}];if(q.includes('FROM public."ElyseraProductContent"'))return row?[row]:[];if(q.includes('SELECT "request","after"'))return audit?[audit]:[];if(q.startsWith('INSERT INTO public."ElyseraProductContentAudit"')){audit={request:Object.fromEntries(Object.entries(JSON.parse(values[3])).reverse()),after:JSON.parse(values[5])};return auditFailure?[]:[audit]}throw Error(q)}}}
test('missing content rows preserve exact catalog defaults; public resolver cannot override identity or other products',()=>{assert.deepEqual(resolveProductContent(),catalogProducts);assert.equal(original.version,0);const resolved=resolveProductContent([{productId:id,content:raw().content},{productId:'foreign',content:{bad:true}}]);assert.equal(resolved[0].name,'Test öffentlicher Name');for(const field of ['slug','step','image'])assert.equal(resolved[0][field],catalogProducts[0][field]);assert.deepEqual(resolved.slice(1),catalogProducts.slice(1));assert.equal('erpName' in resolved[0],false)})
test('strict own ids, exact fields, ingredient array and lengths; no price/stock/claims generation',()=>{for(const extra of [{productId:'foreign'},{expectedSnapshot:'x'},{expectedVersion:-1},{reason:''},{price:1},{content:{...raw().content,image:'/other.png'}},{content:{...raw().content,ingredients:[]}},{content:{...raw().content,ingredients:['x'.repeat(121)]}},{content:{...raw().content,name:'x'.repeat(161)}}])assert.throws(()=>productContentInput({...raw(),...extra}));assert.deepEqual(validateProductContent(pickProductContent(catalogProducts[0])),pickProductContent(catalogProducts[0]))})
test('product lock serializes version0 insert; readback and audit; exact canonical retry writes once',async()=>{const db=database();const result=await mutateProductContent(db,{id:'admin'},raw());assert.equal(result.product.version,1);assert.equal(result.product.content.name,raw().content.name);assert.equal(result.product.erpName,'ERP ELYSERA Name 30ml');assert(db.calls.some(q=>q.includes('FROM public."Products"')&&q.includes('FOR UPDATE')));assert(db.calls.some(q=>q.includes('FROM public."ElyseraProductContent"')&&q.includes('FOR UPDATE')));assert(!db.calls.some(q=>/^UPDATE public\."Products"/.test(q)));const retry=await mutateProductContent(db,{id:'admin'},raw());assert.equal(retry.replayed,true);assert.equal(db.calls.filter(q=>q.startsWith('INSERT INTO public."ElyseraProductContent"')).length,1);await assert.rejects(mutateProductContent(db,{id:'admin'},{...raw(),reason:'Different'}),e=>e.code==='REQUEST_ID_CONFLICT')})
test('actor and stale snapshot fail before writes; audit/readback fail closed',async()=>{await assert.rejects(mutateProductContent(database(),{id:'other'},raw()),e=>e.code==='ACTOR_CHANGED');for(const change of [{expectedVersion:1},{expectedSnapshot:'0'.repeat(64)}]){const db=database();await assert.rejects(mutateProductContent(db,{id:'admin'},{...raw(),...change}),e=>e.code==='STALE_VERSION');assert(!db.calls.some(q=>q.startsWith('INSERT')))}await assert.rejects(mutateProductContent(database({auditFailure:true}),{id:'admin'},raw()),/AUDIT_FAILED/);await assert.rejects(mutateProductContent(database({readbackFailure:true}),{id:'admin'},raw()),/READBACK_FAILED/)})
test('HTTP origin/auth first, JSON bounds, unavailable errors redacted',async()=>{let calls=0;const deps={db:database(),sameOrigin:()=>false,currentAdmin:async()=>{calls++;return {id:'admin'}},reply:(body,status=200)=>({body,status}),read:async()=>[original],mutate:async()=>{throw Error('secret')}};const request={text:async()=>JSON.stringify(raw())};assert.equal((await productContentHttp(request,true,deps)).status,403);assert.equal(calls,0);assert.equal((await productContentHttp(request,true,{...deps,sameOrigin:()=>true,currentAdmin:async()=>null})).status,401);const failure=await productContentHttp(request,true,{...deps,sameOrigin:()=>true});assert.equal(failure.status,503);assert.doesNotMatch(JSON.stringify(failure),/secret/);assert.equal((await productContentHttp({...request,text:async()=>'x'.repeat(30001)},true,{...deps,sameOrigin:()=>true})).status,400)})
