import test from 'node:test'
import assert from 'node:assert/strict'
import {merchandisingDefaults,validateMerchandising} from '../lib/product-merchandising.mjs'
import {merchandisingState,merchandisingInput} from '../lib/admin/product-merchandising-policy.mjs'
import {mutateMerchandising,readMerchandising} from '../lib/admin/product-merchandising-service.mjs'
import {merchandisingHttp} from '../lib/admin/product-merchandising-http.mjs'
const actor={id:'admin',email:'admin@example.test',supabaseUserId:'fixture-auth'};const input=()=>({actorId:'admin',requestId:'request-1234567890',expectedVersion:0,expectedSnapshot:merchandisingState().snapshot,products:merchandisingDefaults().map((p,i)=>({...p,showNewBadge:i!==0})),reason:'Katalogdarstellung aktualisieren'})
function fake(){let row=null,audits=[],writes=0;const db={get row(){return row},get writes(){return writes},fail:false,revoked:false,async $queryRaw(s,...v){const sql=s.join('?');if(sql.includes('FOR SHARE OF a,u'))return [{enabled:!db.revoked,blocked:false,emailVerified:true,email:actor.email,supabaseUserId:actor.supabaseUserId}];if(sql.includes('SELECT "version"'))return row?[structuredClone(row)]:[];if(sql.startsWith('SELECT "request"'))return audits.filter(a=>a.request.actorId===v[0]&&a.request.requestId===v[1]);if(sql.startsWith('INSERT INTO public."ElyseraProductMerchandisingAudit"')){if(db.fail)throw Error('audit unavailable');const audit={request:JSON.parse(v[2]),after:JSON.parse(v[4])};audits.push(audit);return [{after:audit.after}]}throw Error(sql)},async $executeRaw(s,...v){if(s.join('').startsWith('INSERT')){row={version:(row?.version??0)+1,products:JSON.parse(v[0])};writes++}},async $transaction(fn,opts){assert.equal(opts.timeout,30000);const previous=structuredClone({row,audits,writes});try{return await fn(db)}catch(e){row=previous.row;audits=previous.audits;writes=previous.writes;throw e}}};return db}
test('defaults preserve current categories, badges and catalog order',()=>{assert.deepEqual(merchandisingDefaults().map(p=>[p.category,p.showNewBadge,p.displayOrder]),[['Serum',true,1],['Toner',true,2],['Augenpflege',true,3]]);assert.equal(merchandisingState().version,0)})
test('scope, exact keys, enum, boolean and permutation validation',()=>{for(const change of [r=>r[0].id='foreign',r=>r[0].category=null,r=>r[0].category='Peptide',r=>r[0].showNewBadge='true',r=>r[0].displayOrder=2,r=>r[0].displayOrder=1.5,r=>r[0].price=1]){const rows=merchandisingDefaults();change(rows);assert.throws(()=>validateMerchandising(rows))}assert.throws(()=>merchandisingInput({...input(),extra:true}))})
test('missing row default zero, first atomic save version one with verified audit',async()=>{const db=fake();assert.equal((await readMerchandising(db)).version,0);const out=await mutateMerchandising(db,actor,input());assert.equal(out.state.version,1);assert.deepEqual(out.applied.products,input().products);assert.equal(db.writes,1)})
test('exact replay after later update returns current and original applied snapshot',async()=>{const db=fake(),a=input();const first=await mutateMerchandising(db,actor,a);const second={...input(),requestId:'request-1234567891',expectedVersion:1,expectedSnapshot:first.state.snapshot,products:merchandisingDefaults()};await mutateMerchandising(db,actor,second);const replay=await mutateMerchandising(db,actor,a);assert.equal(replay.replayed,true);assert.equal(replay.state.version,2);assert.deepEqual(replay.state.products,second.products);assert.deepEqual(replay.applied.products,a.products);assert.equal(db.writes,2)})
test('actor mismatch, key collision and stale snapshot/version reject without writes',async()=>{const db=fake();await assert.rejects(mutateMerchandising(db,{id:'other'},input()),e=>e.code==='ACTOR_CHANGED');await mutateMerchandising(db,actor,input());await assert.rejects(mutateMerchandising(db,actor,{...input(),reason:'Different'}),e=>e.code==='REQUEST_ID_CONFLICT');await assert.rejects(mutateMerchandising(db,actor,{...input(),requestId:'request-1234567899'}),e=>e.code==='STALE_VERSION');assert.equal(db.writes,1)})
test('audit failure rolls back full catalog and same key retry succeeds',async()=>{const db=fake();db.fail=true;await assert.rejects(mutateMerchandising(db,actor,input()));assert.equal(db.row,null);db.fail=false;assert.equal((await mutateMerchandising(db,actor,input())).state.version,1)})
test('HTTP enforces auth/origin before mutation and database failure is503',async()=>{let calls=0;const deps={db:{},currentAdmin:async()=>null,sameOrigin:()=>true,reply:(b,s=200)=>({b,s}),read:async()=>{throw Error('db')},mutate:async()=>{calls++}};assert.equal((await merchandisingHttp({},false,deps)).s,401);assert.equal((await merchandisingHttp({},true,{...deps,sameOrigin:()=>false})).s,403);assert.equal((await merchandisingHttp({},false,{...deps,currentAdmin:async()=>({id:'admin'})})).s,503);assert.equal(calls,0)})

test('fresh locked admin permission rejects revoked access before write',async()=>{const db=fake();db.revoked=true;await assert.rejects(mutateMerchandising(db,actor,input()),e=>e.code==='AUTH_REQUIRED');assert.equal(db.writes,0)})
