import test from 'node:test'
import assert from 'node:assert/strict'
import sharp from 'sharp'
import {normalizeEvidence} from '../lib/review-evidence-image.mjs'
import {evidenceInput,evidencePath,evidenceScope,EvidenceError} from '../lib/review-evidence-policy.mjs'
import {evidenceMutate,evidenceRead,evidenceList} from '../lib/review-evidence-service.mjs'
const hash='a'.repeat(64),sha='b'.repeat(64),image={bytes:Buffer.from('normalized-test'),fileHash:hash,sha}
const submit=(version=0,status='NONE',requestId='submit-request-123456')=>({actorId:'user',orderId:'own-order',requestId,expectedVersion:version,expectedStatus:status,confirmedOwnWords:true,fileHash:hash})
const decision=(version,action,requestId)=>({actorId:'admin',orderId:'own-order',requestId,expectedVersion:version,expectedStatus:'PENDING',action,reason:action==='reject'?'Bitte lesbaren Screenshot einreichen.':''})
function database({foreign=false,missingProfile=false,auditFailure=false,anotherPending=false}={}){let row=null;const audits=new Map(),attempts=[],calls=[];const order={id:'own-order',userId:'user',status:'SHIPPED'};return {calls,order,setRow:r=>row=r,getRow:()=>row,$transaction:async function(fn,opts){assert.equal(opts.timeout,30000);return fn(this)},$executeRaw:async(strings,...v)=>{const q=strings.join('?');calls.push(q);if(q.startsWith('INSERT INTO public."ElyseraReviewEvidence"'))row={id:v[0],userId:v[1],orderId:v[2],evidencePath:v[3],evidenceSha:v[4],evidenceBytes:v[5],confirmedOwnWords:true,version:(row?.version??0)+1,status:'PENDING',rejectionReason:null};if(q.startsWith('INSERT INTO public."ElyseraReviewEvidenceAttempt"'))attempts.push({evidencePath:v[3],evidenceSha:v[4]});if(q.startsWith('UPDATE public."ElyseraReviewEvidence"'))row={...row,status:v[0],rejectionReason:v[1],reviewedBy:v[2],version:row.version+1};return 1},$queryRaw:async(strings,...v)=>{const q=strings.join('?');calls.push(q);if(q.includes('FROM public."Order" WHERE'))return [{...order}];if(q.includes('FROM public."OrderItem" WHERE'))return [{productId:foreign?'foreign':'own'}];if(q.includes('FROM public."ElyseraAccountProfile" WHERE'))return missingProfile?[]:[{userId:'user'}];if(q.includes('SELECT "request","after","action"'))return audits.has(v[0]+v[1])?[audits.get(v[0]+v[1])]:[];if(q.includes('FROM public."ElyseraReviewEvidenceAttempt"'))return attempts;if(q.startsWith('SELECT * FROM public."ElyseraReviewEvidence"'))return row?[{...row}]:[];if(q.startsWith('SELECT "id" FROM public."ElyseraReviewEvidence"'))return anotherPending?[{id:'other'}]:[];if(q.startsWith('INSERT INTO public."ElyseraReviewEvidenceAudit"')){const record={request:Object.fromEntries(Object.entries(JSON.parse(v[4])).reverse()),after:JSON.parse(v[6]),action:v[3]};audits.set(v[1]+v[2],record);return auditFailure?[]:[record]}if(q.includes('LIMIT 501'))return [];throw Error(q)}}}
test('actual image signature/decode/size; JPEG PNG WebP normalize and reject spoofed bytes',async()=>{for(const [format,type] of [['png','image/png'],['jpeg','image/jpeg'],['webp','image/webp']]){const bytes=await sharp({create:{width:8,height:8,channels:3,background:'#183555'}})[format]().toBuffer();const result=await normalizeEvidence(bytes,type);assert.equal((await sharp(result.bytes).metadata()).format,'webp');assert.equal(result.sha.length,64);await assert.rejects(normalizeEvidence(bytes,'image/avif'),e=>e.status===415)}await assert.rejects(normalizeEvidence(Buffer.from('not an image'),'image/png'));await assert.rejects(normalizeEvidence(Buffer.alloc(3*1024*1024+1),'image/png'),e=>e.status===413)})
test('scope requires own user, nonempty all-own nonnull lines; strict action and path',()=>{for(const items of [[],[{productId:null}],[{productId:'own'},{productId:'foreign'}]])assert.throws(()=>evidenceScope({userId:'user'},items,['own'],{id:'user'}));assert.throws(()=>evidenceScope({userId:'other'},[{productId:'own'}],['own'],{id:'user'}));assert.throws(()=>evidenceInput({...submit(),confirmedOwnWords:false}));assert.throws(()=>evidenceInput({...decision(1,'reject','admin-request-123456'),reason:''},true));assert.throws(()=>evidencePath('../bad','order','request',sha));assert.equal(evidencePath('user','order','request',sha),'user/order/request-'+sha+'.webp')})
test('full submit reject resubmit approve, exact replay one upload, audited versions',async()=>{const db=database();let uploads=0;const upload=async()=>{uploads++};const first=await evidenceMutate(db,['own'],{id:'user'},false,submit(),image,upload);assert.equal(first.submission.status,'PENDING');assert.equal('evidencePath' in first.submission,false);const retry=await evidenceMutate(db,['own'],{id:'user'},false,submit(),image,upload);assert.equal(retry.replayed,true);assert.equal(uploads,1);await evidenceMutate(db,['own'],{id:'admin'},true,decision(1,'reject','reject-request-123456'),null,upload);assert.equal(db.getRow().status,'REJECTED');await evidenceMutate(db,['own'],{id:'user'},false,submit(2,'REJECTED','resubmit-request-12345'),image,upload);const approved=await evidenceMutate(db,['own'],{id:'admin'},true,decision(3,'approve','approve-request-12345'),null,upload);assert.equal(approved.submission.status,'APPROVED');assert.equal(approved.submission.version,4);assert(db.calls.some(q=>q.includes('OrderItem')&&q.includes('FOR SHARE')));assert(!db.calls.some(q=>q.startsWith('UPDATE public."Order"')));assert(!db.calls.some(q=>q.includes('CreditTransaction')));await assert.rejects(evidenceMutate(db,['own'],{id:'admin'},true,decision(3,'reject','different-request-123'),null,upload),e=>e.code==='STALE_VERSION')})
test('foreign/profile/pending eligibility blocks before upload and audits fail closed',async()=>{for(const config of [{foreign:true},{missingProfile:true},{anotherPending:true}]){let uploaded=false;await assert.rejects(evidenceMutate(database(config),['own'],{id:'user'},false,submit(),image,async()=>{uploaded=true}));assert.equal(uploaded,false)}const db=database();db.order.status='PENDING';await assert.rejects(evidenceMutate(db,['own'],{id:'user'},false,submit(),image,async()=>{}),e=>e.code==='INELIGIBLE_ORDER');await assert.rejects(evidenceMutate(database({auditFailure:true}),['own'],{id:'user'},false,submit(),image,async()=>{}),/AUDIT_FAILED/)})
test('signed read scope checks attempt ownership; signing failure retains committed record',async()=>{const db=database();await evidenceMutate(db,['own'],{id:'user'},false,submit(),image,async()=>{});const r=await evidenceRead(db,['own'],{id:'user'},false,'own-order',async()=>{throw Error('sign unavailable')});assert.equal(r.evidenceUrl,null);assert.match(r.imageError,/Bild/);assert.equal(db.getRow().status,'PENDING');await assert.rejects(evidenceRead(db,['own'],{id:'foreign'},false,'own-order',async()=>''),e=>e.status===404);db.setRow({...db.getRow(),evidencePath:'other/order/file.webp'});await assert.rejects(evidenceRead(db,['own'],{id:'admin'},true,'own-order',async()=>''),/EVIDENCE_PATH_MISMATCH/)})
test('customer/admin list queries explicitly exclude null and foreign lines',async()=>{for(const admin of [true,false]){const db=database();await evidenceList(db,['own'],{id:'user'},admin);const q=db.calls.find(q=>q.includes('LIMIT 501'));assert.match(q,/EXISTS\(SELECT 1 FROM public\."OrderItem"/);assert.match(q,/"productId" IS NULL OR NOT/);assert.match(q,/Elysera/);if(!admin)assert.match(q,/o\."userId"=\?/);}})
test('retry after later moderation returns current approved state, not historical pending',async()=>{const db=database();let uploads=0;const upload=async()=>{uploads++};await evidenceMutate(db,['own'],{id:'user'},false,submit(),image,upload);await evidenceMutate(db,['own'],{id:'admin'},true,decision(1,'approve','approve-request-later'),null,upload);const replay=await evidenceMutate(db,['own'],{id:'user'},false,submit(),image,upload);assert.equal(replay.submission.status,'APPROVED');assert.equal(replay.submission.version,2);assert.equal(replay.applied.status,'PENDING');assert.equal(uploads,1)})

test('duplicate storage key must contain identical bytes; mismatch/read failure never succeeds',async()=>{
 const {readFile}=await import('node:fs/promises'),{createHash}=await import('node:crypto')
 const source=(await readFile(new URL('../lib/review-evidence-storage.js',import.meta.url),'utf8')).replace(/^import .*$/gm,'').replace(/export /g,'')
 let existing=Buffer.from('same'),failed=false,downloads=0
 const createClient=()=>({storage:{getBucket:async()=>({data:{public:false}}),from:()=>({upload:async()=>({error:{statusCode:'409'}}),download:async()=>{downloads++;return failed?{error:{}}:{data:new Blob([existing])}}})}})
 const upload=new Function('createClient','createHash','process',source+';return uploadEvidence')(createClient,createHash,{env:{ELYSERA_SUPABASE_URL:'https://fixture.test',ELYSERA_SUPABASE_SERVICE_ROLE_KEY:'fixture'}})
 await upload('own-key',Buffer.from('same'));assert.equal(downloads,1)
 existing=Buffer.from('different');await assert.rejects(upload('own-key',Buffer.from('same')),/CONTENT_MISMATCH/)
 failed=true;await assert.rejects(upload('own-key',Buffer.from('same')),/UNCONFIRMED/)
})
