import test from 'node:test'
import assert from 'node:assert/strict'
import {settingsDefaults,settingsInput,maintenanceDecision} from '../lib/admin/settings-policy.mjs'
import {saveSiteSettings,getSiteSettings} from '../lib/admin/settings-service.mjs'
import {settingsHttpCore} from '../lib/admin/settings-http-core.mjs'
const input=()=>({...settingsDefaults,actorId:'admin-1',requestId:'01234567-1234-1234-1234-123456789abc',expectedVersion:0,supportEmail:'support@example.com'})
test('strict contacts and unknown configuration rejected',()=>{for(const change of [{instagram:'javascript:alert(1)'},{instagram:'https://instagram.com.evil.test/user'},{instagram:'https://user:pass@instagram.com/user'},{instagram:'https://instagram.com/'},{supportEmail:'hello\r\n@example.com'},{supportPhone:'0123456'},{whatsapp:'+012345678'},{maintenance:'true'},{maintenance:true},{apiKey:'secret'}])assert.throws(()=>settingsInput({...input(),...change}));assert.equal(settingsInput({...input(),instagram:'https://www.instagram.com/elysera'}).instagram,'https://www.instagram.com/elysera')})
test('maintenance bypasses admin auth previews APIs assets and own destination',()=>{for(const path of ['/admin','/admin/orders','/admin-preview/settings-check','/api/admin/settings','/_next/static/x','/auth/google/callback','/login/','/reset-password','/complete-profile','/maintenance/','/image.webp','/%61dmin'])assert.equal(maintenanceDecision(path,{maintenance:true}),false,path);assert.equal(maintenanceDecision('/contact',{maintenance:true}),true);assert.equal(maintenanceDecision('/',{maintenance:false}),false)})
function mock(failAudit=false){let row={id:'current',version:0,settings:{...settingsDefaults}},audits=[];const tx={$executeRaw:async(parts,...v)=>{const q=parts.join('?');if(q.startsWith('UPDATE'))row={...row,settings:JSON.parse(v[0]),version:row.version+1};return 1},$queryRaw:async(parts,...v)=>{const q=parts.join('?');if(q.startsWith('SELECT "payload"'))return audits.filter(a=>a.actorId===v[0]&&a.requestId===v[1]);if(q.startsWith('SELECT *'))return [structuredClone(row)];if(q.startsWith('INSERT')){if(failAudit)throw Error('audit failed');const a={actorId:v[0],requestId:v[1],payload:JSON.parse(v[2]),after:JSON.parse(v[4])};audits.push(a);return [{after:a.after}]};throw Error(q)}};return {...tx,$transaction:async(fn,options)=>{assert.equal(options.timeout,30000);const before=structuredClone(row),previous=structuredClone(audits);try{return await fn(tx)}catch(e){row=before;audits=previous;throw e}}}}
test('save readback replay collision version and actor guard',async()=>{const db=mock(),p=input();const a=await saveSiteSettings(db,{id:p.actorId},p);assert.equal(a.settings.version,1);assert.equal(a.settings.supportEmail,p.supportEmail);assert.equal((await saveSiteSettings(db,{id:p.actorId},p)).replayed,true);await assert.rejects(saveSiteSettings(db,{id:p.actorId},{...p,supportEmail:'other@example.com'}),e=>e.code==='REQUEST_ID_CONFLICT');await assert.rejects(saveSiteSettings(db,{id:p.actorId},{...p,requestId:'11111111-1234-1234-1234-123456789abc'}),e=>e.code==='VERSION_CONFLICT');await assert.rejects(saveSiteSettings(db,{id:'other'},p),e=>e.status===403)})
test('audit failure rolls back settings',async()=>{const db=mock(true);await assert.rejects(saveSiteSettings(db,{id:'admin-1'},input()));assert.equal((await getSiteSettings(db)).version,0)})
test('missing settings row reads empty v0, first save uses v0 and creates v1',async()=>{const empty={$queryRaw:async()=>[]};assert.deepEqual(await getSiteSettings(empty),{id:'current',version:0,...settingsDefaults});let inserted=false;const base=mock();const db={...base,$transaction:async(fn,options)=>base.$transaction(tx=>fn({...tx,$executeRaw:async(parts,...values)=>{if(parts.join('?').startsWith('INSERT INTO public."ElyseraSiteSettings"')){inserted=true;assert.deepEqual(JSON.parse(values[0]),settingsDefaults)}return tx.$executeRaw(parts,...values)}}),options)};assert.equal((await saveSiteSettings(db,{id:'admin-1'},input())).settings.version,1);assert.equal(inserted,true)})
test('HTTP rejects origin and unauthenticated writes before saving, public omits actor',async()=>{let writes=0;const deps={db:{},currentAdmin:async()=>null,sameOrigin:()=>false,reply:(body,status=200)=>({body,status}),read:async()=>settingsDefaults,save:async()=>{writes++}};const req={text:async()=>JSON.stringify(input())};assert.equal((await settingsHttpCore(req,true,true,deps)).status,403);assert.equal((await settingsHttpCore(req,true,true,{...deps,sameOrigin:()=>true})).status,401);assert.equal(writes,0);assert.equal('actorId' in (await settingsHttpCore(req,false,false,deps)).body,false);assert.equal((await settingsHttpCore(req,true,false,{...deps,currentAdmin:async()=>({id:'a'}),read:async()=>{throw Error('db')}})).status,503)})
