'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import './selection.css'
export const motifs=[['hero','Desktop-Hero','Kollektionsauftakt'],['hero-mobile','Mobile-Hero & Routine','Hochformat mit allen drei Produkten'],['serum','Renewal Serum','Produktkarte und Hero'],['toner','Balance Toner','Produktkarte und Hero'],['eye','Contour Eye Cream','Produktkarte und Hero'],['serum-texture','Peptidpflege','Pflege-Card, Texturbühne und Wissen'],['toner-texture','Feuchtigkeit','Pflege-Card und Texturbühne'],['eye-texture','Augenpflege','Pflege-Card, Texturbühne und Wissen'],['home-story','Die Hautpflege-Story','Porträt neben der Markenstory'],['home-finder','Der Pflege-Finder','Porträt für das Pflege-Quiz']]
const storageKey='elysera-flow-choices-v1'
const labels=['Wasser & Material','Kamerafahrt','Lichtwechsel','Fokuswechsel','Nahfahrt']
const portraits=['Atmen & Blinzeln','Leichte Kopfdrehung','Sanfte Nahfahrt','Blick & Lächeln','Luft & Licht']
const flowProject='https://flow.google.com/project/a3900712-512e-43fb-95a1-d84e7173f706'
// Only exports whose variant identity was checked are exposed in the selector.
const reviewedSources={hero:[1,2,3,4,5].map(n=>`/media/flow-options/hero-${n}.mp4`),serum:['/media/card-motion/serum.mp4'],toner:['/media/card-motion/toner.mp4'],eye:['/media/card-motion/eye.mp4']}
const remoteTitles={serum:['Serum bottle with water ripple','Serum bottle camera arc','Serum dropper bottle studio reveal','Serum bottle rack focus animation','Serum dropper pushing in'],toner:['Toner spray bottle with ripple','Toner spray bottle rotating','Toner bottle spray studio reveal','Toner spray bottle product animation','Skincare bottle camera push-in'],eye:['Eye cream tube water ripple','Navy Contour Lift Eye Cream','Navy eye cream tube animation','Navy eye cream tube animation','Navy Contour Lift Eye Cream'],'serum-texture':['Droplet releasing from glass pipette','Macro camera sliding across serum','Blue serum glass pipette animation','Serum texture focus pull']}
function Candidate({motif,index,chosen,onSelect}){
 const ref=useRef(null),pendingSeek=useRef(null),[error,setError]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(8)
 const id=`${motif}-${index+1}`,src=reviewedSources[motif]?.[index],portrait=motif==='hero-mobile'
 const remoteTitle=src?null:remoteTitles[motif]?.[index]||`${motif.toUpperCase()} · Variante ${String(index+1).padStart(2,'0')}`
 useEffect(()=>{const video=ref.current;if(!video)return;const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)video.pause()});observer.observe(video);const pauseHidden=()=>{if(document.hidden)video.pause()};document.addEventListener('visibilitychange',pauseHidden);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',pauseHidden);video.pause()}},[])
 return <article className={`film-option ${chosen?'is-selected':''}`}><div className={`film-player ${portrait?'portrait':''}`}>{remoteTitle?<img src={`/media/campaign-2026/${motif}.webp`} alt={`${motifs.find(m=>m[0]===motif)?.[1]} – Referenzbild; Video in Google Flow`}/>:<video ref={ref} key={src} src={src} poster={`/media/campaign-2026/${motif}.webp`} controls muted playsInline preload="none" aria-label={`${motifs.find(m=>m[0]===motif)?.[1]} Variante ${index+1}`} onError={()=>setError(true)} onLoadedMetadata={e=>{setDuration(e.currentTarget.duration);setError(false);if(pendingSeek.current!==null){e.currentTarget.currentTime=pendingSeek.current;pendingSeek.current=null}}} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={e=>{document.querySelectorAll('.film-player video').forEach(v=>{if(v!==e.currentTarget)v.pause()})}}/>}{chosen&&<span className="film-picked">DEINE AUSWAHL</span>}{remoteTitle&&<span className="film-location">REFERENZBILD · VIDEO IN FLOW</span>}</div><div className="film-option-body"><div className="film-title"><h2>Variante {index+1}</h2><span>{motif.startsWith('home-')?portraits[index]:labels[index]}</span></div>{remoteTitle?<div className="film-remote"><p>Video generiert. Öffne in Flow das Motiv <strong>{motif.toUpperCase()} · Variante {String(index+1).padStart(2,'0')}</strong>.<br/><span>Titel: {remoteTitle}</span></p><a className="text-link" href={flowProject} target="_blank" rel="noreferrer">IN GOOGLE FLOW ANSEHEN ↗</a></div>:<label className="film-scrub">Bewegung ansehen<input aria-label={`Variante ${index+1}: Videozeit`} type="range" min="0" max={duration||8} step=".05" value={time} onChange={e=>{const v=ref.current;if(!v)return;v.pause();const next=Number(e.target.value);if(v.readyState===0){pendingSeek.current=next;v.load()}else v.currentTime=next;setTime(next)}}/></label>}{error&&<p className="film-error" role="status">Das Video konnte nicht geladen werden. <button onClick={()=>{setError(false);ref.current?.load()}}>Erneut laden</button></p>}<button className={`button ${chosen?'':'outline'}`} aria-pressed={chosen} disabled={error} onClick={onSelect}>{chosen?'AUSWAHL AUFHEBEN':'DIESE VARIANTE AUSWÄHLEN'}</button></div></article>
}
export default function VideoSelection(){
 const [active,setActive]=useState('hero'),[choices,setChoices]=useState({}),[message,setMessage]=useState(''),[ready,setReady]=useState(false)
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem(storageKey)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))setChoices(Object.fromEntries(motifs.filter(m=>Number.isInteger(value[m[0]])&&value[m[0]]>=1&&value[m[0]]<=5).map(m=>[m[0],value[m[0]]])))}catch{}setReady(true)},[])
 const choose=index=>{const next={...choices};if(next[active]===index)delete next[active];else next[active]=index;setChoices(next);try{localStorage.setItem(storageKey,JSON.stringify(next));dispatchEvent(new Event('elysera-film-choice'));setMessage('Auswahl auf diesem Gerät gespeichert.')}catch{setMessage('Auswahl für diese Ansicht übernommen. Speichern ist im Browser gesperrt; lade deine Auswahl herunter.')}}
 const download=()=>{const blob=new Blob([JSON.stringify({project:'ELYSERA',choices},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ELYSERA-Videoauswahl.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const current=motifs.find(m=>m[0]===active)
 return <section className="film-selection"><div className="film-selection-heading"><div><Link className="text-link" href="/">← ZUR ELYSERA-SEITE</Link><h1>50 IDEEN.<br/><em>DEINE AUSWAHL.</em></h1><p>Fünf Google-Flow-Videos pro Motiv. Acht eindeutig zugeordnete Varianten sind hier abspielbar. Alle weiteren findest du im verlinkten Flow-Projekt. Vergleiche die Bewegung und wähle deine Favoriten.</p></div><div className="film-summary"><strong>{Object.keys(choices).length}<span> / 10 Motive gewählt</span></strong><button className="button outline" disabled={!ready||!Object.keys(choices).length} onClick={download}>AUSWAHL HERUNTERLADEN</button><p role="status">{message||'Deine Auswahl bleibt auf diesem Gerät gespeichert.'}</p></div></div><nav className="film-tabs" aria-label="Videomotiv auswählen">{motifs.map(([key,title])=><button key={key} aria-pressed={key===active} onClick={()=>{document.querySelectorAll('.film-player video').forEach(v=>v.pause());setActive(key);setMessage('')}}>{title}{choices[key]&&<span> · {choices[key]}</span>}</button>)}</nav><div className="film-group-heading"><div><h2>{current[1]}</h2><p>{current[2]}</p></div><span>5 Varianten · jeweils 8 Sekunden</span></div><div className="film-options" key={active}>{Array.from({length:5},(_,i)=><Candidate key={i} motif={active} index={i} chosen={choices[active]===i+1} onSelect={()=>choose(i+1)}/>)}</div><p className="film-footnote">Neun einzeln geprüfte Motive bewegen sich bereits beim Scrollen auf der Startseite. Hier kannst du weitere Varianten vormerken. Die Bildmotive sind KI-generierte Kampagneninszenierungen.</p></section>
}
