'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import Overview from './overview'
import {PartnerNetwork,ReferralPlan,WorldBonus,CareerPlan} from './partner-program'
import {DashboardIcon,sectionIcons} from './design-icons'
import {orderStatus,commissionStatus,productNames} from './live-data.mjs'
const sections=['Übersicht','Provisionen','Bestellungen','Partnernetzwerk','Marketing','Auszahlungen','Profil','Hilfe','Referral-Plan','World Bonus','Karriereplan']
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n)
const date=v=>new Date(v).toLocaleDateString('de-DE')
function Arrow(){return <span aria-hidden="true">↗</span>}
export default function Dashboard({initialProfile}){
 const [section,setSection]=useState('Übersicht'),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('Alle'),[notice,setNotice]=useState(''),[profile,setProfile]=useState(initialProfile),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[data,setData]=useState({orders:[],commissions:[]}),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/account/dashboard',{cache:'no-store'});if(r.status===401){location.assign('/auth/signin');return}const body=await r.json();if(!r.ok)throw Error(body.error);setData(body)}catch(e){setError(e.message||'Daten konnten nicht geladen werden.')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const read=()=>{const n=Number(location.hash.slice(1));if(Number.isInteger(n)&&n>=0&&n<sections.length)setSection(sections[n])};read();const escape=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('hashchange',read);window.addEventListener('keydown',escape);return()=>{window.removeEventListener('hashchange',read);window.removeEventListener('keydown',escape)}},[])
 function go(s){setSection(s);setMenu(false);setQuery('');setFilter('Alle');location.hash=sections.indexOf(s);window.scrollTo(0,0)}
 async function copy(text){try{await navigator.clipboard.writeText(text);setNotice('In die Zwischenablage kopiert.')}catch{setNotice('Bitte den Link manuell auswählen und kopieren.')}}
 async function logout(){try{const r=await fetch('/api/auth/signout',{method:'POST'});if(!r.ok)throw Error();location.assign('/auth/signin')}catch{setNotice('Abmelden gerade nicht möglich. Bitte erneut versuchen.')}}
 async function save(e){e.preventDefault();setSaving(true);try{const r=await fetch('/api/account/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:profile.name,last:profile.last,phone:profile.phone})});const body=await r.json();if(!r.ok)throw Error(body.error);setProfile(body.profile);setSaved(true);setNotice('Dein Profil wurde gespeichert.')}catch(e){setNotice(e.message||'Speichern nicht möglich.')}finally{setSaving(false)}}
 const visible=data.orders.filter(o=>(filter==='Alle'||(orderStatus[o.status]||o.status)===filter)&&[o.id,...o.items.map(i=>productNames[i.productId])].join(' ').toLowerCase().includes(query.toLowerCase()))
 function csv(){const records=[['Bestellung','Datum','Produktwert','Status'],...visible.map(o=>[o.id,date(o.createdAt),o.items.reduce((n,i)=>n+i.price*i.quantity,0),orderStatus[o.status]||o.status])];const text=records.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='elysera-bestellungen.csv';a.click();URL.revokeObjectURL(url)}
 const orders=<><div className="ed-tools"><input aria-label="Bestellungen durchsuchen" placeholder="Bestellung oder Produkt suchen" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Status filtern" value={filter} onChange={e=>setFilter(e.target.value)}>{['Alle',...new Set(Object.values(orderStatus))].map(x=><option key={x}>{x}</option>)}</select><button onClick={csv}>CSV exportieren ↓</button></div>{visible.length?<div className="ed-table-wrap"><table><thead><tr>{['Bestellung','Produkte','Produktwert','Zahlbetrag','Status'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{visible.map(o=><tr key={o.id}><td><strong>{o.id}</strong><small>{date(o.createdAt)}</small></td><td>{o.items.map(i=><small key={i.productId}>{i.quantity} × {productNames[i.productId]}</small>)}</td><td>{money(o.items.reduce((n,i)=>n+i.price*i.quantity,0))}</td><td>{money(Math.max(0,o.total-(o.discount||0)))}</td><td><span className="ed-status">{orderStatus[o.status]||o.status}</span></td></tr>)}</tbody></table></div>:<p className="ed-empty">{query||filter!=='Alle'?'Keine passenden Bestellungen gefunden.':'Du hast noch keine ELYSERA-Bestellungen.'}</p>}</>
 return <div className="ed-app ew-app"><a className="ed-skip" href="#partner-main">Zum Inhalt</a><aside className={'ed-sidebar '+(menu?'is-open':'')}><Link href="/" className="ed-logo">ELYSERA<small>BEAUTY CREATES<br/>OPPORTUNITIES</small></Link><nav aria-label="Partner Navigation">{['Übersicht','Partnernetzwerk','Referral-Plan','World Bonus','Karriereplan','Provisionen','Bestellungen','Marketing','Auszahlungen','Profil','Hilfe'].map(s=><button key={s} className={section===s?'active':''} aria-current={section===s?'page':undefined} onClick={()=>go(s)}><DashboardIcon name={sectionIcons[s]}/>{s}<span className="ed-nav-arrow">↗</span></button>)}</nav><div className="ed-sidebar-bottom"><p>SCHÖNHEIT<br/>SCHAFFT<br/>MÖGLICHKEITEN.</p><Link href="/">Zum ELYSERA Shop <Arrow/></Link><button onClick={logout} className="ew-signout">Abmelden</button></div></aside><div className="ed-body"><header className="ed-top"><button className="ed-menu" aria-label="Navigation öffnen oder schließen" aria-expanded={menu} onClick={()=>setMenu(!menu)}><DashboardIcon name="menu"/></button><span className="ew-welcome"><DashboardIcon name="sun"/>Willkommen zurück, {profile.name||'bei ELYSERA'}</span><Link href="/" className="ew-mobile-logo">ELYSERA</Link><button className="ew-notifications" aria-label="Daten aktualisieren" onClick={refresh}><DashboardIcon name="bell"/></button><button className="ed-account" onClick={()=>go('Profil')}><span className="ed-avatar">{profile.name.slice(0,1)}{profile.last.slice(0,1)}</span><span>{profile.name} {profile.last}<small>Dein ELYSERA Konto</small></span></button></header><main id="partner-main" className="ed-main"><div className={'ed-title '+(['Partnernetzwerk','Referral-Plan','World Bonus','Karriereplan'].includes(section)?'ep-hide-title':'')}><div><h1>{section==='Übersicht'?<><span className="ew-desktop-title">Dein Business im Überblick</span><span className="ew-mobile-title">Übersicht</span></>:section}</h1><p>{section==='Übersicht'?'GEMEINSAM FÜR EINE SCHÖNERE ZUKUNFT':'Alles im Blick. Raum für deinen nächsten Schritt.'}</p></div>{section==='Übersicht'&&<span className="ew-signature">More people.<br/>Brighter lives.</span>}</div>{error&&<div className="ew-data-message" role="alert">{error}<button onClick={refresh}>Erneut laden</button></div>}{loading&&<p className="ew-data-message" role="status">Deine Daten werden geladen …</p>}
 {section==='Übersicht'&&!loading&&!error&&<Overview profile={profile} go={go} copy={copy} data={data}/>}
 {section==='Bestellungen'&&!loading&&!error&&<section className="ed-panel"><h2>Deine ELYSERA-Bestellungen</h2>{orders}</section>}
 {section==='Provisionen'&&!loading&&!error&&<section className="ed-panel"><h2>Deine ELYSERA-Provisionen</h2><p>Hier siehst du die zugeordneten Provisionen deiner ELYSERA-Bestellungen.</p>{data.commissions.length?<div className="ew-ledger">{data.commissions.map(c=><article key={c.id}><div><strong>{money(c.amount)}</strong><small>{date(c.createdAt)} · {commissionStatus[c.status]||c.status}</small></div><span>Bestellung {c.orderId}</span></article>)}</div>:<p className="ed-empty">Noch keine ELYSERA-Provisionen vorhanden.</p>}</section>}
 {section==='Partnernetzwerk'&&<PartnerNetwork profile={profile}/>}
 {section==='Referral-Plan'&&<ReferralPlan/>}
 {section==='World Bonus'&&<WorldBonus/>}
 {section==='Karriereplan'&&<CareerPlan/>}
 {section==='Marketing'&&<><section className="ed-panel"><h2>Für deine nächste Empfehlung.</h2><p>Original ELYSERA Bildmaterial und Produktwissen, an einem Ort.</p><div className="ed-assets">{[['Kampagnenmotiv','/media/wavespeed-4k/hero-desktop.webp'],['Renewal Serum','/media/atelier-2026/serum.webp'],['Jessica · Markenportrait','/media/jessica/portrait-confident-1122.webp']].map(([title,src])=><article key={src}><img src={src} alt={title}/><h3>{title}</h3><a href={src} download>Bild herunterladen ↓</a></article>)}</div></section><section className="ed-panel"><h2>Die Routine kennenlernen</h2><Link href="/routine">Produktwissen öffnen <Arrow/></Link></section></>}
 {section==='Auszahlungen'&&<section className="ed-panel"><h2>Deine Auszahlungen</h2><p>Die eigene Auszahlungsfunktion wird noch eingerichtet. Es werden hier keine Auszahlungen ausgelöst.</p>{data.commissions.filter(c=>c.status==='PAID').map(c=><div className="ed-payment" key={c.id}><span>{date(c.createdAt)}<small>Ausgezahlte ELYSERA-Provision</small></span><strong>{money(c.amount)}</strong></div>)}</section>}
 {section==='Profil'&&<section className="ed-panel"><h2>Deine persönlichen Angaben</h2><p>Deine Angaben werden sicher für dein bestehendes Konto gespeichert.</p><form onSubmit={save}><div className="ed-form-grid">{[['name','Vorname'],['last','Nachname'],['email','E-Mail'],['phone','Telefon']].map(([key,label])=><label key={key}>{label}<input required={key==='name'} readOnly={key==='email'||key==='phone'} type={key==='email'?'email':key==='phone'?'tel':'text'} autoComplete={key==='name'?'given-name':key==='last'?'family-name':key==='email'?'email':'tel'} value={profile[key]} maxLength={key==='phone'?30:80} onChange={e=>{setSaved(false);setProfile({...profile,[key]:e.target.value})}}/></label>)}</div><button className="ed-primary" type="submit" disabled={saving}>{saving?'WIRD GESPEICHERT …':saved?'PROFIL GESPEICHERT':'PROFIL SPEICHERN'} <Arrow/></button></form><Link className="ew-signout" href="/auth/change-password">Passwort ändern</Link><button className="ew-signout" onClick={logout}>Abmelden</button></section>}
 {section==='Hilfe'&&<section className="ed-panel"><h2>Dein ELYSERA Konto</h2>{[['Wie melde ich mich an?','Verwende deine bestehende E-Mail-Adresse und dein Passwort. Nach der Anmeldung landest du direkt in deinem Dashboard.'],['Welche Bestellungen sehe ich hier?','Hier erscheinen ausschließlich die deinem Konto zugeordneten ELYSERA-Bestellungen.'],['Kann ich mein Profil ändern?','Ja. Änderungen an Vorname und Nachname werden für dein bestehendes Konto gespeichert.'],['Wie funktionieren Empfehlungen und Auszahlungen?','Deine Partnerstruktur findest du im Partnernetzwerk. Referral-, World-Bonus- und Karriereplan erklären die Regeln. Die eigene ELYSERA-Abrechnung wird separat eingerichtet.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<Link href="/faq">Weitere Fragen & Antworten <Arrow/></Link></section>}
 <nav className="ew-bottom-nav" aria-label="Mobile Partner Navigation">{[['Übersicht','Home'],['Partnernetzwerk','Partner'],['Referral-Plan','Plan'],['World Bonus','World'],['Profil','Profil']].map(([s,label])=><button key={s} aria-current={section===s?'page':undefined} onClick={()=>go(s)}><DashboardIcon name={sectionIcons[s]}/><span>{label}</span></button>)}</nav><footer className="ed-footer"><span>ELYSERA · PARTNER SPACE</span><Link href="/contact">Kontakt</Link><span>Mit Klarheit. Mit Vertrauen.</span></footer></main></div>{notice&&<div className="ed-toast" role="status">{notice}<button aria-label="Meldung schließen" onClick={()=>setNotice('')}>×</button></div>}</div>
}
