'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {CrmLink} from '../../components/crm/CrmLink'
import Overview from './overview'
import dynamic from 'next/dynamic'


import '../auth/signin/signin.css'
function SectionLoading(){return <p className="ew-data-message" role="status">Bereich wird geladen …</p>}
const Support=dynamic(()=>import('./support'),{loading:SectionLoading})
const ProfileDetails=dynamic(()=>import('../auth/profile-details'),{loading:SectionLoading})
const ReviewEvidenceCustomer=dynamic(()=>import('../components/review-evidence-workspace').then(m=>m.ReviewEvidenceCustomer),{loading:SectionLoading})
const PartnerNetwork=dynamic(()=>import('./partner-program').then(m=>m.PartnerNetwork),{loading:SectionLoading})
const ReferralPlan=dynamic(()=>import('./partner-program').then(m=>m.ReferralPlan),{loading:SectionLoading})
const WorldBonus=dynamic(()=>import('./partner-program').then(m=>m.WorldBonus),{loading:SectionLoading})
const CareerPlan=dynamic(()=>import('./partner-program').then(m=>m.CareerPlan),{loading:SectionLoading})
import {DashboardIcon,sectionIcons} from './design-icons'
import {orderStatus,commissionStatus,productNames} from './live-data.mjs'
const sections=['Übersicht','Provisionen','Bestellungen','Partnernetzwerk','Marketing','Auszahlungen','Profil','Hilfe','Referral-Plan','World Bonus','Karriereplan','Bewertungsnachweise']
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n)
const date=v=>new Date(v).toLocaleDateString('de-DE')
function Arrow(){return <span aria-hidden="true">↗</span>}
export default function Dashboard({initialProfile,fullNetworkAccess=false}){
 const [section,setSection]=useState('Übersicht'),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('Alle'),[notice,setNotice]=useState(''),[profile,setProfile]=useState(initialProfile),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[data,setData]=useState({orders:[],commissions:[]}),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/account/dashboard',{cache:'no-store'});if(r.status===401){location.assign('/auth/signin');return}const body=await r.json();if(!r.ok)throw Error(body.error);setData(body)}catch(e){setError(e.message||'Daten konnten nicht geladen werden.')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const read=()=>{const n=Number(location.hash.slice(1));if(Number.isInteger(n)&&n>=0&&n<sections.length)setSection(!fullNetworkAccess&&[8,9,10].includes(n)?'Übersicht':sections[n])};read();const escape=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('hashchange',read);window.addEventListener('keydown',escape);return()=>{window.removeEventListener('hashchange',read);window.removeEventListener('keydown',escape)}},[])
 function go(s){setSection(s);setMenu(false);setQuery('');setFilter('Alle');location.hash=sections.indexOf(s);window.scrollTo(0,0)}
 async function copy(text){try{await navigator.clipboard.writeText(text);setNotice('In die Zwischenablage kopiert.')}catch{setNotice('Bitte den Link manuell auswählen und kopieren.')}}
 async function logout(){try{const r=await fetch('/api/auth/signout',{method:'POST'});if(!r.ok)throw Error();const result=await r.json();location.assign(result.redirect||'/auth/signin')}catch{setNotice('Abmelden gerade nicht möglich. Bitte erneut versuchen.')}}
 async function save(e){e.preventDefault();setSaving(true);try{const r=await fetch('/api/account/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:profile.name,last:profile.last,phone:profile.phone})});const body=await r.json();if(!r.ok)throw Error(body.error);setProfile(body.profile);setSaved(true);setNotice('Dein Profil wurde gespeichert.')}catch(e){setNotice(e.message||'Speichern nicht möglich.')}finally{setSaving(false)}}
 const visible=data.orders.filter(o=>(filter==='Alle'||(orderStatus[o.status]||o.status)===filter)&&[o.id,...o.items.map(i=>productNames[i.productId])].join(' ').toLowerCase().includes(query.toLowerCase()))
 function csv(){const records=[['Bestellung','Datum','Produktwert','Status'],...visible.map(o=>[o.id,date(o.createdAt),o.items.reduce((n,i)=>n+i.price*i.quantity,0),orderStatus[o.status]||o.status])];const text=records.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='elysera-bestellungen.csv';a.click();URL.revokeObjectURL(url)}
 const orders=<><div className="ed-tools"><input aria-label="Bestellungen durchsuchen" placeholder="Bestellung oder Produkt suchen" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Status filtern" value={filter} onChange={e=>setFilter(e.target.value)}>{['Alle',...new Set(Object.values(orderStatus))].map(x=><option key={x}>{x}</option>)}</select><button onClick={csv}>CSV exportieren ↓</button></div>{visible.length?<div className="ed-table-wrap"><table><thead><tr>{['Bestellung','Produkte','Produktwert','Zahlbetrag','Status'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{visible.map(o=><tr key={o.id}><td><strong>{o.id}</strong><small>{date(o.createdAt)}</small></td><td>{o.items.map(i=><small key={i.productId}>{i.quantity} × {productNames[i.productId]}</small>)}</td><td>{money(o.items.reduce((n,i)=>n+i.price*i.quantity,0))}</td><td>{money(Math.max(0,o.total-(o.discount||0)))}</td><td><span className="ed-status">{orderStatus[o.status]||o.status}</span></td></tr>)}</tbody></table></div>:<p className="ed-empty">{query||filter!=='Alle'?'Keine passenden Bestellungen gefunden.':'Du hast noch keine ELYSERA-Bestellungen.'}</p>}</>
 return <div className="ed-app ew-app"><a className="ed-skip" href="#partner-main">Zum Inhalt</a><aside className={'ed-sidebar '+(menu?'is-open':'')}><Link href="/" className="ed-logo">ELYSERA<small>BEAUTY CREATES<br/>OPPORTUNITIES</small></Link><nav aria-label="Kontonavigation">{['Übersicht','Bestellungen','Profil','Hilfe'].map(s=><button key={s} className={section===s?'active':''} aria-current={section===s?'page':undefined} onClick={()=>go(s)}><DashboardIcon name={sectionIcons[s]}/><span className="ed-nav-label">{s}</span></button>)}<details className="ew-partner-nav" key={section} open={['Partnernetzwerk','Provisionen','Marketing','Auszahlungen','Referral-Plan','World Bonus','Karriereplan'].includes(section)||undefined}><summary>Partnerbereich<DashboardIcon name="arrow" size={16}/></summary><div>{['Partnernetzwerk','Provisionen','Marketing','Auszahlungen',...(fullNetworkAccess?['Referral-Plan','World Bonus','Karriereplan']:[])].map(s=><button key={s} className={section===s?'active':''} aria-current={section===s?'page':undefined} onClick={()=>go(s)}><DashboardIcon name={sectionIcons[s]}/><span className="ed-nav-label">{s}</span></button>)}<CrmLink href="/dashboard/crm" onClick={()=>setMenu(false)}><DashboardIcon name="leads"/><span className="ed-nav-label">Kontakte</span></CrmLink></div></details></nav><div className="ed-sidebar-bottom"><p>SCHÖNHEIT<br/>SCHAFFT<br/>MÖGLICHKEITEN.</p><Link href="/">Zur Kollektion <Arrow/></Link><button onClick={logout} className="ew-signout">Abmelden</button></div></aside><div className="ed-body"><header className="ed-top"><button className="ed-menu" aria-label="Navigation öffnen oder schließen" aria-expanded={menu} onClick={()=>setMenu(!menu)}><DashboardIcon name="menu"/></button><span className="ew-welcome"><DashboardIcon name="sun"/>Willkommen zurück, {profile.name||'bei ELYSERA'}</span><Link href="/" className="ew-mobile-logo">ELYSERA</Link><button className="ew-notifications" aria-label="Daten aktualisieren" title="Daten aktualisieren" disabled={loading} onClick={refresh}><DashboardIcon name="refresh"/></button><button className="ed-account" onClick={()=>go('Profil')}><span className="ed-avatar">{profile.name.slice(0,1)}{profile.last.slice(0,1)}</span><span>{profile.name} {profile.last}<small>Dein ELYSERA Konto</small></span></button></header><main id="partner-main" className="ed-main"><div className={'ed-title '+(['Partnernetzwerk','Bewertungsnachweise'].includes(section)?'ep-hide-title':'')}><div><h1>{section==='Übersicht'?<><span className="ew-desktop-title">Dein Konto im Überblick</span><span className="ew-mobile-title">Übersicht</span></>:section}</h1><p>{section==='Übersicht'?'Bestellungen, persönliche Angaben und Empfehlungen.':'Alles im Blick. Raum für deinen nächsten Schritt.'}</p></div></div>{error&&<div className="ew-data-message" role="alert">{error}<button onClick={refresh}>Erneut laden</button></div>}{loading&&<p className="ew-data-message" role="status">Deine Daten werden geladen …</p>}
 {section==='Übersicht'&&!loading&&!error&&<Overview profile={profile} go={go} copy={copy} data={data}/>}
 {section==='Bestellungen'&&!loading&&!error&&<section className="ed-panel"><h2>Deine ELYSERA-Bestellungen</h2>{orders}</section>}
 {section==='Provisionen'&&!loading&&!error&&<section className="ed-panel"><h2>Deine ELYSERA-Provisionen</h2><p>{data.qualification?.qualified?'Dein bezahltes ELYSERA-Set schaltet Provisionen für zukünftige Käufe deiner Empfehlungen frei.':'Für Provisionen brauchst du zuerst ein selbst gekauftes, bezahltes ELYSERA-Set.'} Vorher entgangene Provisionen bleiben verloren.</p><p>Verlorene Provision: <strong>{money(data.commissions.filter(c=>c.status==='MISSED').reduce((n,c)=>n+Number(c.amount),0))}</strong></p>{data.commissions.length?<div className="ew-ledger">{data.commissions.map(c=><article key={c.id}><div><strong>{money(c.amount)}</strong><small>{date(c.createdAt)} · {commissionStatus[c.status]||c.status}</small></div><span>Bestellung {c.orderId}</span></article>)}</div>:<p className="ed-empty">Noch keine ELYSERA-Provisionen vorhanden.</p>}</section>}
 {section==='Partnernetzwerk'&&<PartnerNetwork profile={profile} fullNetworkAccess={fullNetworkAccess}/>}
 {fullNetworkAccess&&section==='Referral-Plan'&&<ReferralPlan/>}
 {fullNetworkAccess&&section==='World Bonus'&&<WorldBonus/>}
 {fullNetworkAccess&&section==='Karriereplan'&&<CareerPlan/>}
 {section==='Marketing'&&<><section className="ed-panel"><h2>Für deine nächste Empfehlung.</h2><p>Original ELYSERA Bildmaterial und Produktwissen, an einem Ort.</p><div className="ed-assets">{[['Kampagnenmotiv','/media/wavespeed-4k/hero-desktop.webp'],['Renewal Serum','/media/atelier-2026/serum.webp']].map(([title,src])=><article key={src}><img src={src} alt={title}/><h3>{title}</h3><a href={src} download>Bild herunterladen ↓</a></article>)}</div></section><section className="ed-panel"><h2>Die Routine kennenlernen</h2><Link href="/routine">Produktwissen öffnen <Arrow/></Link></section></>}
 {section==='Auszahlungen'&&<section className="ed-panel"><h2>Deine Auszahlungen</h2><p>Die eigene Auszahlungsfunktion wird noch eingerichtet. Es werden hier keine Auszahlungen ausgelöst.</p>{data.commissions.filter(c=>c.status==='PAID').map(c=><div className="ed-payment" key={c.id}><span>{date(c.createdAt)}<small>Ausgezahlte ELYSERA-Provision</small></span><strong>{money(c.amount)}</strong></div>)}</section>}
 {section==='Profil'&&<section className="ed-panel"><h2>Deine persönlichen Angaben</h2><p>Deine Angaben werden sicher für dein bestehendes Konto gespeichert.</p><ProfileDetails initialProfile={profile}/><Link className="ew-signout" href="/auth/change-password">Passwort ändern</Link><button className="ew-signout" onClick={logout}>Abmelden</button></section>}
 {section==='Hilfe'&&<Support/>}
 {section==='Bewertungsnachweise'&&<ReviewEvidenceCustomer/>}
 {section==='Hilfe'&&<section className="ed-panel"><h2>Dein ELYSERA Konto</h2>{[['Wie melde ich mich an?','Verwende deine bestehende E-Mail-Adresse und dein Passwort. Nach der Anmeldung landest du direkt in deinem Dashboard.'],['Welche Bestellungen sehe ich hier?','Hier erscheinen ausschließlich die deinem Konto zugeordneten ELYSERA-Bestellungen.'],['Kann ich mein Profil ändern?','Ja. Änderungen an Vorname und Nachname werden für dein bestehendes Konto gespeichert.'],['Wie funktionieren Empfehlungen und Auszahlungen?','Deine direkten Empfehlungen (Level 1) findest du im Partnernetzwerk. Die eigene ELYSERA-Abrechnung wird separat eingerichtet.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<Link href="/faq">Weitere Fragen & Antworten <Arrow/></Link></section>}
 <nav className="ew-bottom-nav" aria-label="Mobile Kontonavigation">{[['Übersicht','Home'],['Hilfe','Hilfe'],['Bestellungen','Bestellungen'],['Profil','Profil']].map(([s,label])=><button key={s} aria-current={section===s?'page':undefined} onClick={()=>go(s)}><DashboardIcon name={sectionIcons[s]}/><span>{label}</span></button>)}</nav><footer className="ed-footer"><span>ELYSERA · DEIN KONTO</span><Link href="/contact">Kontakt</Link><span>Mit Klarheit. Mit Vertrauen.</span></footer></main></div>{notice&&<div className="ed-toast" role="status">{notice}<button aria-label="Meldung schließen" onClick={()=>setNotice('')}>×</button></div>}</div>
}
